---
permalink: switch-cisco-3232c/cn1610-replace-CL1.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Sie können Cisco Nexus 3232C Switches als Cluster-Switches in Ihrem AFF oder FAS Cluster verwenden. 
---
= Ersetzen Sie den Schalter CL1 des Modells CN1610 durch den Schalter C1 des Modells 3232C.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um Ihren CN1610 (CL1)-Switch durch einen Nexus 3232C (C1)-Switch zu ersetzen.

.Schritte
. Überprüfen Sie den Status des Clusters:
+
`network interface show -role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die erforderlichen Cluster-LIFs auf die entsprechenden Cluster-Ports auf dem Cluster-Switch C2 migriert wurden:

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. Schalten Sie die Knotenports ab, die auf allen Knoten mit CL1 verbunden sind:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie bestimmte Ports auf den Knoten n1 und n2 abgeschaltet werden:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. Schalten Sie die ISL-Ports 24, 31 und 32 am aktiven 3232C-Switch C2 ab.
+
Weitere Informationen zu Cisco -Befehlen finden Sie in den in der folgenden Liste aufgeführten Anleitungen: https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Serie NX-OS Befehlsreferenzen"^] Die

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die ISLs 24, 31 und 32 am aktiven 3232C-Switch C2 abgeschaltet werden:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2#
----
====
. Entfernen Sie die Kabel, die an den CN1610-Switch CL1 an allen Knoten angeschlossen sind.
+
Unter Verwendung der entsprechenden Verkabelung müssen Sie die getrennten Ports an allen Knoten wieder mit dem Nexus 3232C Switch C1 verbinden.

. Entfernen Sie die QSFP28-Kabel vom Nexus 3232C C2 Port e1/24.
+
Sie müssen die Ports e1/31 und e1/32 auf C1 mit den Ports e1/31 und e1/32 auf C2 über unterstützte Cisco QSFP28 Glasfaser- oder Direktanschlusskabel verbinden.

. Die Konfiguration auf Port 24 soll wiederhergestellt und der temporäre Portkanal 2 auf C2 entfernt werden:
+
Weitere Informationen zu Cisco -Befehlen finden Sie in den in der folgenden Liste aufgeführten Anleitungen: https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Serie NX-OS Befehlsreferenzen"^] Die

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die `running-configuration` Die Datei wird kopiert auf `startup-configuration` Datei:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *interface e1/24*
C2(config-if)# *description 100GbE/40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
Edge port type (portfast) should only be enabled on ports connected to a single
host. Connecting hubs, concentrators, switches, bridges, etc...  to this
interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet 1/24 but will only
have effect when the interface is in a non-trunking mode.

C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Aktivieren Sie die ISL-Ports 31 und 32 am aktiven Switch C2 3232C.
+
Weitere Informationen zu Cisco -Befehlen finden Sie in den in der folgenden Liste aufgeführten Anleitungen: https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Serie NX-OS Befehlsreferenzen"^] Die

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die ISLs 31 und 32 auf den Schalter C2 des 3232C aufgebracht werden:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Überprüfen Sie, ob die ISL-Verbindungen `up` am Schalter C2 des 3232C.
+
Weitere Informationen zu Cisco -Befehlen finden Sie in den in der folgenden Liste aufgeführten Anleitungen: https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Serie NX-OS Befehlsreferenzen"^] Die

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Überprüfung der ISL-Verbindungen.  Die Ports Eth1/31 und Eth1/32 zeigen an `(P)` , was bedeutet, dass beide ISL-Häfen `up` im Portkanal:

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
-----------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)

C2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Aktivieren Sie alle Cluster-Verbindungsports, die mit dem neuen 3232C-Switch C1 auf allen Knoten verbunden sind:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie alle Cluster-Verbindungsports, die mit dem neuen 3232C-Switch C1 verbunden sind, in Betrieb genommen werden:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin true*
cluster::*> *network port modify -node n1 -port e0d -up-admin true*
cluster::*> *network port modify -node n2 -port e0a -up-admin true*
cluster::*> *network port modify -node n2 -port e0d -up-admin true*
----
====
. Überprüfen Sie den Status des Clusterknotenports:
+
`network port show -role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt eine Ausgabe, die bestätigt, dass die Cluster-Verbindungsports auf den Knoten n1 und n2 des neuen 3232C-Switches C1 funktionieren. `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n2
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -

8 entries were displayed.
----
====


.Wie geht es weiter?
link:cn1610-complete-migration.html["Schließen Sie Ihre Migration ab."].
