---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Bevor Sie Cisco Nexus 3232c Switches konfigurieren, sollten Sie sich einen Überblick über den Prozess und die Nomenklatur verschaffen. 
---
= Migrationsanforderungen
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C Switches können als Cluster-Switches in Ihrem AFF oder FAS Cluster verwendet werden. Mit Cluster-Switches können Sie ONTAP Cluster mit mehr als zwei Knoten erstellen.


NOTE: Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 3000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

Falls erforderlich, finden Sie weitere Informationen in den folgenden Quellen:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 und CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== CN1610 Migrationsanforderungen

Die Cluster-Switches unterstützen folgende Knotenverbindungen:

* NetApp CN1610: Ports 0/1 bis 0/12 (10 GbE)
* Cisco Nexus 3232C: Ports e1/1-30 (40 oder 100 oder 4x10GbE)


Die Cluster-Switches verwenden die folgenden Inter-Switch-Link-Ports (ISL).

* NetApp CN1610: Ports 0/13 bis 0/16 (10 GbE)
* Cisco Nexus 3232C: Ports 1/31-32 (100GbE)


[NOTE]
====
Sie müssen 4x10G Breakout-Kabel am Cisco Nexus 3232C Cluster-Switch verwenden.

====
Die folgende Tabelle zeigt die Kabelverbindungen, die in jeder Phase des Übergangs von NetApp CN1610-Switches zu Cisco Nexus 3232C-Cluster-Switches erforderlich sind:

|===
| Bühne | Beschreibung | Erforderliche Kabel 


 a| 
Anfänglich
 a| 
CN1610 zu CN1610 (SFP+ zu SFP+)
 a| 
4 SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel



 a| 
Übergang
 a| 
CN1610 zu 3232C (QSFP zu SFP+)
 a| 
1 QSFP- und 4 SFP+-Glasfaser- oder Kupfer-Breakout-Kabel



 a| 
Finale
 a| 
3232C zu 3232C (QSFP zu QSFP)
 a| 
2 QSFP-Glasfaser- oder Kupfer-Direktanschlusskabel

|===
Sie müssen die entsprechenden Referenzkonfigurationsdateien (RCFs) heruntergeladen haben.  Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den verfügbaren RCFs definiert unterlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Die

Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen sind aufgelistet unterlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Die

Die in diesem Verfahren unterstützten ONTAP und FASTPATH-Versionen sind aufgelistet unterlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 und CN1610 Switches"^] Die

.Zu den verwendeten Beispielen
Die Beispiele im Migrationsverfahren verwenden vier Knoten:

* Zwei Knoten nutzen vier 10-GbE-Cluster-Verbindungsports: *e0a*, *e0b*, *e0c* und *e0d*.
* Die anderen beiden Knoten verwenden zwei 40-GbE-Cluster-Verbindungsglasfaserkabel: *e4a* und *e4e*.
+
Derlink:https://hwu.netapp.com/["_Hardware-Universum_"^] verfügt über Informationen zu den Cluster-Glasfaserkabeln für Ihre Plattformen.



Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Knoten sind *n1*, *n2*, *n3* und *n4*.
* Die Befehlsausgaben können je nach Version der ONTAP -Software variieren.
* Die zu ersetzenden CN1610-Schalter sind *CL1* und *CL2*.
* Die Nexus 3232C-Switches, die die CN1610-Switches ersetzen, sind *C1* und *C2*.
* *n1_clus1* ist die erste logische Clusterschnittstelle (LIF), die mit dem Cluster-Switch 1 (CL1 oder C1) für den Knoten *n1* verbunden ist.
* *n1_clus2* ist der erste Cluster-LIF, der mit dem Cluster-Switch 2 (CL2 oder C2) für den Knoten *n1* verbunden ist.
* *n1_clus3* ist die zweite LIF, die mit dem Cluster-Switch 2 (CL2 oder C2) für den Knoten *n1* verbunden ist.
* *n1_clus4* ist die zweite LIF, die mit dem Cluster-Switch 1 (CL1 oder C1) für den Knoten *n1* verbunden ist.
* Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den Referenzkonfigurationsdateien (RCFs) definiert, die unter [URL] verfügbar sind.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Die


.Wie geht es weiter?
link:cn1610-prepare-to-migrate.html["Bereiten Sie sich auf die Migration vor"].
