---
permalink: switch-cisco-3232c/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Bevor Sie Cisco Nexus 3232c Switches konfigurieren, sollten Sie sich einen Überblick über den Prozess und die Nomenklatur verschaffen. 
---
= Migrationsanforderungen
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C Switches können als Cluster-Switches in Ihrem AFF oder FAS Cluster verwendet werden. Mit Cluster-Switches können Sie ONTAP Cluster mit mehr als zwei Knoten erstellen.

[NOTE]
====
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 3000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

====
Weitere Informationen finden Sie unter:

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Cisco Nexus 5596 Anforderungen

Die Cluster-Switches verwenden die folgenden Ports für die Verbindungen zu den Knoten:

* Nexus 5596: Ports e1/1-40 (10 GbE)
* Nexus 3232C: Anschlüsse e1/1-30 (10/40/100 GbE)


Die Cluster-Switches verwenden die folgenden Inter-Switch Link (ISL)-Ports:

* Nexus 5596: Ports e1/41–48 (10 GbE)
* Nexus 3232C: Anschlüsse e1/31-32 (40/100 GbE)


Derlink:https://hwu.netapp.com/["_Hardware-Universum_"^] enthält Informationen zur unterstützten Verkabelung von Nexus 3232C-Switches:

* Knoten mit 10-GbE-Clusterverbindungen benötigen QSFP-zu-SFP+-Glasfaser-Breakout-Kabel oder QSFP-zu-SFP+-Kupfer-Breakout-Kabel.
* Knoten mit 40/100-GbE-Clusterverbindungen benötigen unterstützte QSFP/QSFP28-Optikmodule mit Glasfaserkabeln oder QSFP/QSFP28-Kupfer-Direktanschlusskabel.


Die Cluster-Switches verwenden die entsprechende ISL-Verkabelung:

* Beginn: Nexus 5596 (SFP+ zu SFP+)
+
** 8x SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel


* Interim: Nexus 5596 zu Nexus 3232C (QSFP zu 4xSFP+ Breakout)
+
** 1x QSFP-zu-SFP+-Glasfaser- oder Kupfer-Breakout-Kabel


* Endgültig: Nexus 3232C zu Nexus 3232C (QSFP28 zu QSFP28)
+
** 2x QSFP28 Glasfaser- oder Kupfer-Direktanschlusskabel


* Bei Nexus 3232C Switches können Sie QSFP/QSFP28 Ports entweder im 40/100 Gigabit Ethernet-Modus oder im 4 x10 Gigabit Ethernet-Modus betreiben.
+
Standardmäßig stehen im 40/100 Gigabit Ethernet-Modus 32 Ports zur Verfügung.  Diese 40 Gigabit-Ethernet-Ports sind nach dem 2-Tupel-Namensschema nummeriert.  Beispielsweise ist der zweite 40-Gigabit-Ethernet-Anschluss mit 1/2 nummeriert.

+
Der Vorgang der Umstellung der Konfiguration von 40-Gigabit-Ethernet auf 10-Gigabit-Ethernet wird als _breakout_ bezeichnet, und der Vorgang der Umstellung der Konfiguration von 10-Gigabit-Ethernet auf 40-Gigabit-Ethernet wird als _breakin_ bezeichnet.

+
Wenn man einen 40/100-Gigabit-Ethernet-Anschluss in 10 Gigabit-Ethernet-Anschlüsse aufteilt, werden die resultierenden Anschlüsse nach dem 3-Tupel-Namensschema nummeriert.  Beispielsweise sind die Breakout-Ports des zweiten 40/100 Gigabit Ethernet-Ports mit 1/2/1, 1/2/2, 1/2/3 und 1/2/4 nummeriert.

* Auf der linken Seite der Nexus 3232C Switches befinden sich 2 SFP+ Ports, die als 1/33 und 1/34 bezeichnet werden.
* Sie haben einige Ports an Nexus 3232C Switches so konfiguriert, dass sie mit 10 GbE oder 40/100 GbE laufen.
+
[NOTE]
====
Sie können die ersten sechs Ports in den 4x10-GbE-Modus aufteilen, indem Sie die `interface breakout module 1 port 1-6 map 10g-4x` Befehl.  Ebenso können Sie die ersten sechs QSFP+-Ports aus der Breakout-Konfiguration mithilfe der folgenden Funktion neu gruppieren: `no interface breakout module 1 port 1-6 map 10g-4x` Befehl.

====
* Sie haben die Planung und Migration durchgeführt und die erforderliche Dokumentation zur 10-GbE- und 40/100-GbE-Konnektivität von den Knoten zu den Nexus 3232C Cluster-Switches gelesen.
* Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen sind:link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Die


.Zu den verwendeten Beispielen
Die Beispiele in diesem Verfahren beschreiben den Austausch von Cisco Nexus 5596-Switches durch Cisco Nexus 3232C-Switches.  Diese Schritte können Sie (mit Anpassungen) auch für andere ältere Cisco Switches (z. B. 3132Q-V) anwenden.

Das Verfahren verwendet außerdem die folgende Schalter- und Knotennomenklatur:

* Die Befehlsausgaben können je nach ONTAP Version variieren.
* Die zu ersetzenden Nexus 5596-Schalter sind *CL1* und *CL2*.
* Die Nexus 3232C Switches, die die Nexus 5596 Switches ersetzen, sind *C1* und *C2*.
* *n1_clus1* ist die erste logische Clusterschnittstelle (LIF), die mit dem Cluster-Switch 1 (CL1 oder C1) für den Knoten *n1* verbunden ist.
* *n1_clus2* ist der erste Cluster-LIF, der mit dem Cluster-Switch 2 (CL2 oder C2) für den Knoten *n1* verbunden ist.
* *n1_clus3* ist die zweite LIF, die mit dem Cluster-Switch 2 (CL2 oder C2) für den Knoten *n1* verbunden ist.
* *n1_clus4* ist die zweite LIF, die mit dem Cluster-Switch 1 (CL1 oder C1) für den Knoten *n1* verbunden ist.
* Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den Referenzkonfigurationsdateien (RCFs) definiert, die auf dem Server verfügbar sind.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Die
* Die Knoten sind *n1*, *n2*, *n3* und *n4*.


Die Beispiele in diesem Verfahren verwenden vier Knoten:

* Zwei Knoten nutzen vier 10-GbE-Cluster-Verbindungsports: *e0a*, *e0b*, *e0c* und *e0d*.
* Die anderen beiden Knoten verwenden zwei 40-GbE-Cluster-Verbindungsports: *e4a* und *e4e*.
+
Derlink:https://hwu.netapp.com/["_Hardware-Universum_"^] listet die tatsächlichen Cluster-Ports auf Ihren Plattformen auf.



.Abgedeckte Szenarien
Dieses Verfahren umfasst die folgenden Szenarien:

* Der Cluster startet mit zwei Knoten, die über zwei Nexus 5596 Cluster-Switches verbunden sind und funktionieren.
* Der Cluster-Schalter CL2 wird durch C2 ersetzt (Schritte 1 bis 19):
+
** Der Datenverkehr auf allen Cluster-Ports und LIFs auf allen mit CL2 verbundenen Knoten wird auf die ersten Cluster-Ports und LIFs migriert, die mit CL1 verbunden sind.
** Trennen Sie die Verkabelung von allen Cluster-Ports auf allen mit CL2 verbundenen Knoten und verwenden Sie dann unterstützte Breakout-Kabel, um die Ports wieder mit dem neuen Cluster-Switch C2 zu verbinden.
** Trennen Sie die Verkabelung zwischen den ISL-Ports zwischen CL1 und CL2 und verwenden Sie dann ein unterstütztes Breakout-Kabel, um die Ports von CL1 nach C2 wieder zu verbinden.
** Der Datenverkehr auf allen Cluster-Ports und LIFs, die mit C2 auf allen Knoten verbunden sind, wird umgekehrt.


* Der Cluster-Schalter CL2 wird durch C2 ersetzt.
+
** Der gesamte Datenverkehr auf allen Cluster-Ports oder LIFs auf allen mit CL1 verbundenen Knoten wird auf die zweiten Cluster-Ports oder LIFs, die mit C2 verbunden sind, migriert.
** Trennen Sie die Verkabelung von allen Cluster-Ports auf allen mit CL1 verbundenen Knoten und stellen Sie die Verbindung mit dem neuen Cluster-Switch C1 über ein unterstütztes Breakout-Kabel wieder her.
** Trennen Sie die Verkabelung zwischen den ISL-Ports zwischen CL1 und C2 und stellen Sie die Verbindung mit einer unterstützten Verkabelung von C1 nach C2 wieder her.
** Der Datenverkehr auf allen Cluster-Ports oder LIFs, die mit C1 auf allen Knoten verbunden sind, wird umgekehrt.


* Dem Cluster wurden zwei FAS9000 Knoten hinzugefügt; Beispiele zeigen Details zum Cluster.


.Wie geht es weiter?
Nachdem Sie die Migrationsanforderungen geprüft haben, können Sielink:cn5596-prepare-to-migrate.html["Bereiten Sie sich auf die Migration Ihrer Schalter vor."] Die
