---
permalink: switch-cisco-3232c/cn5596-complete-migration.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Sie können Cisco Nexus 3232C-Switches als Cluster-Switches im AFF- oder FAS-Cluster einsetzen. 
---
= Führen Sie die Migration von 5596 Switches auf 3232C-Switches durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie wie folgt vor, um die Migration der Nexus 5596 Switches auf Nexus 3232C Switches abzuschließen.

.Schritte
. Überprüfen Sie, ob die richtigen Cluster-Switches überwacht werden:
+
`system cluster-switch show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network    10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie es erneut, indem Sie eine AutoSupport Meldung aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Was kommt als Nächstes?
link:../switch-cshm/config-overview.html["Konfigurieren Sie die Überwachung des Switch-Systemzustands"].
