---
permalink: switch-cisco-3232c/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Wenn Sie CN1610 Cluster-Switches durch Cisco Nexus 3232C Cluster-Switches ersetzen, müssen Sie bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten. 
---
= Migrieren Sie einen CN1610 Switch zu einem Cisco Nexus 3232C Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie CN1610 Cluster-Switches durch Cisco Nexus 3232C Cluster-Switches ersetzen, müssen Sie bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten.

Die Cluster-Switches unterstützen die folgenden Node-Verbindungen:

* NetApp CN1610: 0/1 bis 0/12 (10 GbE)
* Cisco Nexus 3232C – Ports e1/1-30 (40 oder 100 oder 4x10 GbE)


Bei den Cluster-Switches werden die folgenden Inter-Switch-Link-Ports (ISL) verwendet.

* NetApp CN1610: 0/13 bis 0/16 (10 GbE)
* Cisco Nexus 3232C – 31-32 Ports (100 GbE)


[NOTE]
====
Auf dem Cisco Nexus 3232C Cluster Switch müssen 4X10G-Breakout-Kabel verwendet werden.

====
Die folgende Tabelle zeigt die in der jeweiligen Phase erforderlichen Verkabelungsverbindungen beim Umstieg von NetApp CN1610-Switches auf Cisco Nexus 3232C-Cluster-Switches:

|===
| Stufe | Beschreibung | Erforderliche Kabel 


 a| 
Initial
 a| 
CN1610 bis CN1610 (SFP+ auf SFP+)
 a| 
4 SFP+-Glasfaserkabel oder Kupfer-Direct-Attached-Kabel



 a| 
Übergang
 a| 
CN1610 bis 3232C (QSFP zu SFP+)
 a| 
1 QSFP- und 4 SFP+-Glasfaserkabel oder Kupferkabel



 a| 
Endgültig
 a| 
3232C auf 3232C (QSFP zu QSFP)
 a| 
2 QSFP-Glasfaserkabel oder Kupfer-Direct-Attach-Kabel

|===
Sie müssen die entsprechenden Referenzkonfigurationsdateien (RCFs) heruntergeladen haben. Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den auf der verfügbaren RCFs definiert https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco® Cluster Network Switch Referenzkonfigurationsdatei Herunterladen"^] Seite.

Die in diesem Verfahren unterstützten ONTAP- und NX-OS-Versionen finden Sie auf der link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Seite zu Cisco Ethernet Switches"^].

Die in diesem Verfahren unterstützten ONTAP- und FASTPATH-Versionen werden auf der aufgeführt link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html["Seite zu den NetApp CN1601 und CN1610 Switches"^].
