---
permalink: switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3232c, storage switches 
summary: Beim Austausch von Cisco Nexus 3232C Storage-Switches müssen bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen bekannt sein. 
---
= Einen Cisco Nexus 3232C Storage-Switch austauschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Austausch von Cisco Nexus 3232C Storage-Switches müssen bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen bekannt sein.

Vor der Installation der NX-OS Software und der RCFs auf einem Cisco Nexus Storage-Switch müssen Sie die folgenden Bedingungen überprüfen:

* Ihr System kann Cisco Nexus 3232C Storage-Switches unterstützen.
* Sie müssen die Switch-Kompatibilitätstabelle auf der Seite Cisco Ethernet Switch für die unterstützten ONTAP-, NX-OS- und RCF-Versionen verwenden.
+
[NOTE]
====
Sie sollten beachten, dass es Abhängigkeiten zwischen der Befehlssyntax für in den RCF- und NX-OS-Versionen geben kann.

====
* Sie müssen die entsprechenden Software- und Upgrade-Leitfäden auf der Cisco Website für vollständige Dokumentation zum Upgrade und Downgrade von Cisco Switches unter abrufen link:http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Switches Der Cisco Nexus 3000-Serie"^].
* Sie müssen die entsprechenden RCFs heruntergeladen haben.

