---
permalink: switch-cisco-3232c/index.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Sie können Cisco Nexus 3232C-Switches als Cluster-Switches im AFF- oder FAS-Cluster einsetzen. 
---
= Überblick über die Cisco Nexus 3232C-Switches und ihre Anforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung von Cisco Nexus 3232C Switches müssen alle Anforderungen und eine empfohlene Dokumentation geprüft werden.



== Aufgabenübersicht

Sie können Cisco Nexus 3232C-Switches als Cluster-Switches im AFF- oder FAS-Cluster einsetzen. Zu den Installations- und Wartungsaufgaben zählen:

* Installieren des Cisco Nexus 3232C-Switch (X190100) in einem NetApp Systemschrank mit angepassten Halterungen, die im Lieferumfang des Switches enthalten sind, oder Installieren eines Racks mit den Standardhalterungen, die auch im Lieferumfang des Switches enthalten sind.
* Installieren der NX-OS-Software und der Referenzkonfigurationsdateien (RCF's) auf dem Cisco Nexus 3232C-Cluster Switch
* Migration von einem 2-Node-Cluster ohne Switches zu einem Cluster mit Cisco Nexus 3232C-Cluster-Switches
* Austausch eines Cisco Nexus 3232C-Cluster-Switch
* Austausch eines Cisco Nexus 3232C Storage-Switches:




== Konfigurationsanforderungen

Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Switches. Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen. Außerdem müssen Sie spezifische Netzwerkinformationen bereitstellen.



== Netzwerkanforderungen

Sie benötigen die folgenden Netzwerkinformationen für alle Switch-Konfigurationen:

* IP-Subnetz für den Management-Netzwerkdatenverkehr
* Host-Namen und IP-Adressen für jeden Storage-System-Controller und alle entsprechenden Switches
* Die meisten Storage-System-Controller werden über die Schnittstelle E0M verwaltet durch eine Verbindung zum Ethernet-Service-Port (Symbol Schraubenschlüssel). Auf AFF A800 und AFF A700 Systemen verwendet die E0M Schnittstelle einen dedizierten Ethernet-Port.


Siehe https://hwu.netapp.com["Hardware Universe"^] Aktuelle Informationen.



== Anforderungen für Smart Call Home

Smart Call Home überwacht die Hardware- und Softwarekomponenten in Ihrem Netzwerk, um eine E-Mail-basierte Benachrichtigung über wichtige Systembedingungen zu generieren. Wenn ein Ereignis auf Ihrem Gerät auftritt, wird Smart Call Home an alle Empfänger, die im Zielprofil konfiguriert sind, eine Warnmeldung ausgegeben.

Sie müssen einen Cluster-Netzwerk-Switch konfigurieren, um per E-Mail mit dem Smart Call Home-System kommunizieren zu können. Sie können optional Ihren Cluster-Netzwerk-Switch einrichten, um die integrierte Smart Call Home-Support-Funktion von Cisco zu nutzen.

Bevor Sie die Smart Call Home-Funktion verwenden können, müssen Sie die folgenden Überlegungen beachten:

* Es muss ein E-Mail-Server vorhanden sein.
* Der Switch muss über eine IP-Verbindung zum E-Mail-Server verfügen.
* Der Name des Kontakts (SNMP-Serverkontakt), die Telefonnummer und die Adresse der Straße müssen konfiguriert werden. Dies ist erforderlich, um den Ursprung der empfangenen Nachrichten zu bestimmen.
* Eine CCO-ID muss mit einem entsprechenden Cisco SMARTnet-Servicevertrag für Ihr Unternehmen verknüpft sein.
* Cisco SMARTnet Service muss vorhanden sein, damit das Gerät registriert werden kann.


Der http://www.cisco.com/c/en/us/products/switches/index.html["Cisco Support-Website"^] Enthält Informationen zu den Befehlen zum Konfigurieren von Smart Call Home.



== Dokumentationsanforderungen

Zum Einrichten der Cisco Nexus 3232C-Switches und des ONTAP-Clusters benötigen Sie spezifische Switch- und Controller-Dokumentation.



=== Switch-Dokumentation

Zum Einrichten der Cisco Nexus 3232C-Switches wird die folgende Dokumentation von benötigt https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Switches Der Cisco Nexus 3000-Serie Unterstützen"^] Seite.

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 3000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 3000 Series Switch Software Configuration Guides_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 3000 Series NX-OS Software Upgrade and Downgrade Guide_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Enthält Informationen zum Downgrade des Switch auf ONTAP unterstützte Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 3000 Series NX-OS Command Reference Master Index_
 a| 
Enthält Links zu den verschiedenen von Cisco bereitgestellten Befehlsreferenzen.



 a| 
_Cisco Nexus 3000 MIBs Referenz_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 3000-Switches.



 a| 
_Nexus 3000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 3000 Serie, Informationen und andere, die bei der Diagnose von Problemen mit Links, interner Hardware oder der Systemsoftware helfen können.



 a| 
_Versionshinweise zur Cisco Nexus 3000-Serie NX-OS (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Bugs und Einschränkungen der Cisco Nexus 3000 Serie.



 a| 
Gesetzliche Vorschriften, Compliance und Sicherheitsinformationen für die Cisco Nexus 6000, Cisco Nexus 5000 Serie, Cisco Nexus 3000 Serie und Cisco Nexus 2000 Serie
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 3000.

|===


=== Dokumentation der ONTAP Systeme

Um ein ONTAP-System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Betriebssystemversion über das https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 Dokumentationszentrum"^].

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP-Dokumentation
 a| 
Dieser Service bietet detaillierte Informationen zu allen Aspekten der ONTAP Versionen.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Liefert Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===


=== Schienensatz und Rack-Dokumentation

Informationen zur Installation eines Cisco Switch der 3232C-Serie in einem NetApp Rack finden Sie in der folgenden Hardware-Dokumentation.

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42-HE-System-Cabinet, Deep Guide"^]
 a| 
Beschreibt die FRUs, die dem 42U-Systemschrank zugeordnet sind, und bietet Anweisungen für Wartung und FRU-Austausch.



 a| 
link:task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html["Installieren Sie einen Cisco Nexus 3232C Switch in einem NetApp Rack"^]
 a| 
Beschreibt die Installation eines Cisco Nexus 3232C-Switch in einem NetApp Rack mit vier Pfosten.

|===