---
permalink: switch-cisco-3232c/install-switch-3232c.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 3232c 
summary: Befolgen Sie dieses Verfahren, um den Cisco Nexus 3232C-Switch zu installieren. 
---
= Installieren Sie den 3232C-Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie wie folgt vor, um den Cisco Nexus 3232C Switch einzurichten und zu konfigurieren.

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Zugriff auf einen HTTP-, FTP- oder TFTP-Server am Installationsort, um die entsprechenden NX-OS- und Referenzkonfigurationsdatei-(RCF)-Versionen herunterzuladen.
* Anwendbare NX-OS-Version, heruntergeladen von https://software.cisco.com/download/home["Cisco -Software-Download"^] Seite.
* Anwendbare Lizenzen, Netzwerk- und Konfigurationsinformationen sowie Kabel.
* Vollendetlink:setup_worksheet_3232c.html["Verkabelungs-Arbeitsblätter"] Die
* Anwendbare NetApp -Clusternetzwerk- und Managementnetzwerk-RCFs, die von der NetApp -Support-Website heruntergeladen wurden unter http://mysupport.netapp.com/["mysupport.netapp.com"^] Die  Alle Cisco Cluster-Netzwerk- und Management-Netzwerk-Switches werden mit der standardmäßigen Cisco -Werkskonfiguration ausgeliefert. Diese Switches verfügen ebenfalls über die aktuelle Version der NX-OS-Software, haben jedoch die RCFs nicht geladen.
* link:required-documentation-3232c.html["Erforderliche Switch- und ONTAP Dokumentation"].


.Schritte
. Installieren Sie die Cluster-Netzwerk- und Management-Netzwerk-Switches und -Controller.
+
[cols="1,2"]
|===
| Wenn Sie die... installieren | Dann... 


 a| 
Cisco Nexus 3232C in einem NetApp -Systemschrank
 a| 
Anweisungen zum Einbau des Switches in einen NetApp -Schrank finden Sie im Leitfaden _Installing a Cisco Nexus 3232C cluster switch and pass-through panel in a NetApp cabinet_.



 a| 
Ausrüstung in einem Telekommunikationsrack
 a| 
Beachten Sie die in den Hardware-Installationshandbüchern für Switches und den Installations- und Einrichtungsanweisungen von NetApp beschriebenen Vorgehensweisen.

|===
. Verbinden Sie die Cluster-Netzwerk- und Management-Netzwerk-Switches mithilfe der ausgefüllten Verkabelungsarbeitsblätter mit den Controllern.
. Schalten Sie die Cluster-Netzwerk- und Management-Netzwerk-Switches und -Controller ein.


.Wie geht es weiter?
Optional können Sie link:install-cisco-nexus-3232c.html["Installieren Sie einen Cisco Nexus 3223C-Switch in einem NetApp -Schrank"]Die Ansonsten gehen Sie zu link:cabling-considerations-3232c.html["Verkabelung und Konfiguration überprüfen"]Die
