---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Bevor Sie Cisco Nexus 3232c Switches konfigurieren, sollten Sie sich einen Überblick über den Prozess und die Nomenklatur verschaffen. 
---
= Migrationsanforderungen
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Zwei-Knoten-Cluster ohne Switches haben, können Sie zu einem Zwei-Knoten-Cluster mit Switches migrieren, der Cisco Nexus 3232C Cluster-Netzwerk-Switches enthält. Dies ist ein unterbrechungsfreies Verfahren.

.Bevor Sie beginnen
Überprüfen Sie die folgenden Installationen und Verbindungen:

* Für Knotenverbindungen stehen Ports zur Verfügung.  Die Cluster-Switches verwenden die Inter-Switch Link (ISL)-Ports e1/31-32.
* Sie verfügen über die passenden Kabel für die Clusterverbindungen:
+
** Die Knoten mit 10-GbE-Clusterverbindungen benötigen QSFP-Lichtwellenleitermodule mit Breakout-Glasfaserkabeln oder QSFP-zu-SFP+-Kupfer-Breakout-Kabel.
** Die Knoten mit 40/100 GbE Cluster-Verbindungen benötigen unterstützte QSFP/QSFP28 optische Module mit Glasfaserkabeln oder QSFP/QSFP28 Kupfer-Direktanschlusskabel.
** Die Cluster-Switches benötigen die entsprechende ISL-Verkabelung:
+
*** 2x QSFP28 Glasfaser- oder Kupfer-Direktanschlusskabel.




* Die Konfigurationen sind ordnungsgemäß eingerichtet und funktionieren.
+
Die beiden Knoten müssen in einer Zwei-Knoten-Clusterumgebung ohne Schalter verbunden und funktionsfähig sein.

* Alle Cluster-Ports befinden sich im Status *up*.
* Der Cisco Nexus 3232C Cluster-Switch wird unterstützt.
* Die bestehende Cluster-Netzwerkkonfiguration weist folgende Merkmale auf:
+
** Eine redundante und voll funktionsfähige Nexus 3232C Cluster-Infrastruktur auf beiden Switches
** Die neuesten RCF- und NX-OS-Versionen auf Ihren Switches
** Management-Konnektivität auf beiden Switches
** Konsolenzugriff auf beide Schalter
** Alle logischen Schnittstellen (LIFs) des Clusters im Status *up*, die noch nicht migriert wurden
** Erste Anpassung des Schalters
** Alle ISL-Ports sind aktiviert und verkabelt.




.Zu den verwendeten Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Nexus 3232C Cluster-Switches, *C1* und *C2*.
* Die Knoten sind *n1* und *n2*.


Die Beispiele in diesem Verfahren verwenden zwei Knoten, die jeweils zwei 40-GbE-Cluster-Verbindungsports *e4a* und *e4e* verwenden.  Derlink:https://hwu.netapp.com/["_Hardware-Universum_"^] enthält Details zu den Cluster-Ports auf Ihren Plattformen.

* *n1_clus1* ist die erste logische Clusterschnittstelle (LIF), die für den Knoten *n1* mit dem Cluster-Switch *C1* verbunden wird.
* *n1_clus2* ist der erste Cluster-LIF, der mit dem Cluster-Switch *C2* für den Knoten *n1* verbunden ist.
* *n2_clus1* ist der erste Cluster-LIF, der mit dem Cluster-Switch *C1* für den Knoten *n2* verbunden ist.
* *n2_clus2* ist der zweite Cluster-LIF, der mit dem Cluster-Switch *C2* für den Knoten *n2* verbunden werden soll.
* Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den Referenzkonfigurationsdateien (RCFs) definiert, die auf dem Server verfügbar sind. https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Seite.


[NOTE]
====
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 3000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

====
.Wie geht es weiter?
Nachdem Sie die Migrationsanforderungen geprüft haben, können Sielink:migrate-from-switchless-prepare-to-migrate.html["Bereiten Sie sich auf die Migration Ihrer Schalter vor."] Die
