---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Wenn Sie CN1610 Cluster-Switches durch Cisco Nexus 3232C Cluster-Switches ersetzen, müssen Sie bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten. 
---
= Migrationsanforderungen für Cisco Nexus 3232C Cluster Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Migration zu Cisco Nexus 3232C Cluster-Switches. Überprüfen Sie die Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen.



== Migrationsanforderungen für CN1610

Die Cluster-Switches unterstützen die folgenden Node-Verbindungen:

* NetApp CN1610: 0/1 bis 0/12 (10 GbE)
* Cisco Nexus 3232C – Ports e1/1-30 (40 oder 100 oder 4x10 GbE)


Bei den Cluster-Switches werden die folgenden Inter-Switch-Link-Ports (ISL) verwendet.

* NetApp CN1610: 0/13 bis 0/16 (10 GbE)
* Cisco Nexus 3232C – 31-32 Ports (100 GbE)


[NOTE]
====
Auf dem Cisco Nexus 3232C Cluster Switch müssen 4X10G-Breakout-Kabel verwendet werden.

====
Die folgende Tabelle zeigt die in der jeweiligen Phase erforderlichen Verkabelungsverbindungen beim Umstieg von NetApp CN1610-Switches auf Cisco Nexus 3232C-Cluster-Switches:

|===
| Stufe | Beschreibung | Erforderliche Kabel 


 a| 
Initial
 a| 
CN1610 bis CN1610 (SFP+ auf SFP+)
 a| 
4 SFP+-Glasfaserkabel oder Kupfer-Direct-Attached-Kabel



 a| 
Übergang
 a| 
CN1610 bis 3232C (QSFP zu SFP+)
 a| 
1 QSFP- und 4 SFP+-Glasfaserkabel oder Kupferkabel



 a| 
Endgültig
 a| 
3232C auf 3232C (QSFP zu QSFP)
 a| 
2 QSFP-Glasfaserkabel oder Kupfer-Direct-Attach-Kabel

|===
Sie müssen die entsprechenden Referenzkonfigurationsdateien (RCFs) heruntergeladen haben. Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den auf der verfügbaren RCFs definiert https://["Cisco® Cluster Network Switch Referenzkonfigurationsdatei Herunterladen"^] Seite.

Die in diesem Verfahren unterstützten ONTAP- und NX-OS-Versionen finden Sie auf der link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Seite zu Cisco Ethernet Switches"^].

Die in diesem Verfahren unterstützten ONTAP- und FASTPATH-Versionen werden auf der aufgeführt link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html["Seite zu den NetApp CN1601 und CN1610 Switches"^].



== CN5596 Anforderungen

Die Cluster-Switches verwenden die folgenden Ports für Verbindungen zu den Nodes:

* Ports e1/1-40 (10 GbE): Nexus 5596
* Ports e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** Bei den Cluster-Switches werden die folgenden Inter-Switch Link (ISL)-Ports verwendet:


* Ports e1/41-48 (10 GbE): Nexus 5596
* Ports e1/31-32 (40/100 GbE): Nexus 3232C
+
** Der link:https://hwu.netapp.com/["_Hardware Universe_"^] Hier finden Sie Informationen zur unterstützten Verkabelung zu Nexus 3232C-Switches:


* Nodes mit 10 GbE-Cluster-Verbindungen erfordern QSFP zu SFP+-Breakout-Kabel oder QSFP zu SFP+-Kupfer-Breakout-Kabel.
* Nodes mit 40/100 GbE-Cluster-Verbindungen erfordern unterstützte QSFP/QSFP28 optische Module mit Glasfaserkabeln oder QSFP/QSFP28 Kupfer-Direct-Attach-Kabeln.
+
** Die Cluster-Switches verwenden die entsprechende ISL-Verkabelung:


* Anfang Nexus 5596 (SFP+ auf SFP+)
+
** 8 x SFP+-Glasfaserkabel oder Kupfer-Direct-Attached-Kabel


* Interim: Nexus 5596 auf Nexus 3232C (QSFP zu 4xSFP+ Breakout-out)
+
** 1x Kabel für QSFP zu SFP+-Ausbruchkabel oder Kupferausbruch


* Final: Nexus 3232C auf Nexus 3232C (QSFP28 zu QSFP28)
+
** 2 QSFP28 Glasfaserkabel oder Kupfer-Direct-Attach-Kabel
+
*** Bei Nexus 3232C Switches können QSFP/QSFP28-Ports entweder im 40/100-Gigabit-Ethernet- oder im 4 x 10-Gigabit-Ethernet-Modus betrieben werden.
+
Standardmäßig sind im 40/100-Gigabit-Ethernet-Modus 32 Ports vorhanden. Diese 40-Gigabit-Ethernet-Ports werden in einer 2-tupel-Namenskonvention nummeriert. So wird beispielsweise der zweite 40-Gigabit-Ethernet-Port mit der Nummer 1/2 nummeriert. Der Prozess der Änderung der Konfiguration von 40 Gigabit Ethernet zu 10 Gigabit Ethernet wird _Breakout_ genannt und der Prozess der Änderung der Konfiguration von 10 Gigabit Ethernet zu 40 Gigabit Ethernet wird _break_ genannt. Wenn Sie einen 40/100-Gigabit-Ethernet-Port in 10 Gigabit-Ethernet-Ports untergliedern, werden die resultierenden Ports mit einer 3-tupel-Namenskonvention nummeriert. Beispielsweise werden die Ausbruchanschlüsse des zweiten 40/100-Gigabit-Ethernet-Ports mit den Nummern 1/2/1, 1/2/2/2, 1/2/3 und 1/2/4 nummeriert.

*** Auf der linken Seite der Nexus 3232C-Switches sind 2 SFP+-Ports, genannt 1/33 und 1/34.
*** Sie haben einige der Ports auf Nexus 3232C-Switches für 10-GbE- oder 40/100-GbE-Ausführung konfiguriert.
+
[NOTE]
====
Sie können die ersten sechs Ports mit dem in den 4x10 GbE-Modus versetzen `interface breakout module 1 port 1-6 map 10g-4x` Befehl. Auf ähnliche Weise können Sie die ersten sechs QSFP+-Ports aus Breakout-Konfiguration mit dem neu gruppieren `no interface breakout module 1 port 1-6 map 10g-4x` Befehl.

====
*** Sie haben die Planung, Migration und die erforderliche Dokumentation auf 10-GbE- und 40/100-GbE-Konnektivität zwischen den Nodes zu Nexus 3232C-Cluster-Switches gelesen.
*** Die in diesem Verfahren unterstützten ONTAP- und NX-OS-Versionen befinden sich auf dem link:http://support.netapp.com/NOW/download/software/cm_switches/.html["Seite zu Cisco Ethernet Switches"^].





