---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Beim Austausch von CN1610-Cluster-Switches durch Cisco Nexus 3232C-Cluster-Switches müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten. 
---
= Migrationsanforderungen für Cisco Nexus 3232C Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie auf Cisco Nexus 3232C Cluster-Switches migrieren, überprüfen Sie die Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen.



== CN1610 Migrationsanforderungen

Die Cluster-Switches unterstützen folgende Knotenverbindungen:

* NetApp CN1610: Ports 0/1 bis 0/12 (10 GbE)
* Cisco Nexus 3232C: Ports e1/1-30 (40 oder 100 oder 4x10GbE)


Die Cluster-Switches verwenden die folgenden Inter-Switch-Link-Ports (ISL).

* NetApp CN1610: Ports 0/13 bis 0/16 (10 GbE)
* Cisco Nexus 3232C: Ports 1/31-32 (100GbE)


[NOTE]
====
Sie müssen 4x10G Breakout-Kabel am Cisco Nexus 3232C Cluster-Switch verwenden.

====
Die folgende Tabelle zeigt die Kabelverbindungen, die in jeder Phase des Übergangs von NetApp CN1610-Switches zu Cisco Nexus 3232C-Cluster-Switches erforderlich sind:

|===
| Bühne | Beschreibung | Erforderliche Kabel 


 a| 
Anfänglich
 a| 
CN1610 zu CN1610 (SFP+ zu SFP+)
 a| 
4 SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel



 a| 
Übergang
 a| 
CN1610 zu 3232C (QSFP zu SFP+)
 a| 
1 QSFP- und 4 SFP+-Glasfaser- oder Kupfer-Breakout-Kabel



 a| 
Finale
 a| 
3232C zu 3232C (QSFP zu QSFP)
 a| 
2 QSFP-Glasfaser- oder Kupfer-Direktanschlusskabel

|===
Sie müssen die entsprechenden Referenzkonfigurationsdateien (RCFs) heruntergeladen haben.  Die Anzahl der 10-GbE- und 40/100-GbE-Ports ist in den verfügbaren RCFs definiert.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Die

Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen sind aufgelistet unterlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Die

Die in diesem Verfahren unterstützten ONTAP und FASTPATH-Versionen sind aufgelistet unterlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 und CN1610 Switches"^] Die



== CN5596-Anforderungen

Die Cluster-Switches verwenden die folgenden Ports für die Verbindungen zu den Knoten:

* Ports e1/1-40 (10 GbE): Nexus 5596
* Anschlüsse e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** Die Cluster-Switches verwenden die folgenden Inter-Switch Link (ISL)-Ports:


* Ports e1/41–48 (10 GbE): Nexus 5596
* Anschlüsse e1/31-32 (40/100 GbE): Nexus 3232C
+
** Derlink:https://hwu.netapp.com/["_Hardware-Universum_"^] enthält Informationen zur unterstützten Verkabelung von Nexus 3232C-Switches:


* Knoten mit 10-GbE-Clusterverbindungen benötigen QSFP-zu-SFP+-Glasfaser-Breakout-Kabel oder QSFP-zu-SFP+-Kupfer-Breakout-Kabel.
* Knoten mit 40/100-GbE-Clusterverbindungen benötigen unterstützte QSFP/QSFP28-Optikmodule mit Glasfaserkabeln oder QSFP/QSFP28-Kupfer-Direktanschlusskabel.
+
** Die Cluster-Switches verwenden die entsprechende ISL-Verkabelung:


* Beginn: Nexus 5596 (SFP+ zu SFP+)
+
** 8x SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel


* Interim: Nexus 5596 zu Nexus 3232C (QSFP zu 4xSFP+ Breakout)
+
** 1x QSFP-zu-SFP+-Glasfaser- oder Kupfer-Breakout-Kabel


* Endgültig: Nexus 3232C zu Nexus 3232C (QSFP28 zu QSFP28)
+
** 2x QSFP28 Glasfaser- oder Kupfer-Direktanschlusskabel
+
*** Bei Nexus 3232C Switches können Sie QSFP/QSFP28 Ports entweder im 40/100 Gigabit Ethernet-Modus oder im 4 x10 Gigabit Ethernet-Modus betreiben.
+
Standardmäßig stehen im 40/100 Gigabit Ethernet-Modus 32 Ports zur Verfügung.  Diese 40 Gigabit-Ethernet-Ports sind nach dem 2-Tupel-Namensschema nummeriert.  Beispielsweise ist der zweite 40-Gigabit-Ethernet-Anschluss mit 1/2 nummeriert.  Der Vorgang der Umstellung der Konfiguration von 40-Gigabit-Ethernet auf 10-Gigabit-Ethernet wird als _breakout_ bezeichnet, und der Vorgang der Umstellung der Konfiguration von 10-Gigabit-Ethernet auf 40-Gigabit-Ethernet wird als _breakin_ bezeichnet.  Wenn man einen 40/100-Gigabit-Ethernet-Anschluss in 10 Gigabit-Ethernet-Anschlüsse aufteilt, werden die resultierenden Anschlüsse nach dem 3-Tupel-Namensschema nummeriert.  Beispielsweise sind die Breakout-Ports des zweiten 40/100 Gigabit Ethernet-Ports mit 1/2/1, 1/2/2, 1/2/3 und 1/2/4 nummeriert.

*** Auf der linken Seite der Nexus 3232C Switches befinden sich 2 SFP+ Ports, die als 1/33 und 1/34 bezeichnet werden.
*** Sie haben einige Ports an Nexus 3232C Switches so konfiguriert, dass sie mit 10 GbE oder 40/100 GbE laufen.
+
[NOTE]
====
Sie können die ersten sechs Ports in den 4x10-GbE-Modus aufteilen, indem Sie die `interface breakout module 1 port 1-6 map 10g-4x` Befehl.  Ebenso können Sie die ersten sechs QSFP+-Ports aus der Breakout-Konfiguration mithilfe der folgenden Funktion neu gruppieren: `no interface breakout module 1 port 1-6 map 10g-4x` Befehl.

====
*** Sie haben die Planung und Migration durchgeführt und die erforderliche Dokumentation zur 10-GbE- und 40/100-GbE-Konnektivität von den Knoten zu den Nexus 3232C Cluster-Switches gelesen.
*** Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen sind:link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Die





