---
permalink: switch-cisco-3232c/required-documentation-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Lesen Sie bei der Installation und Wartung von Cisco Nexus 3232C Switches alle empfohlenen Dokumente. 
---
= Dokumentationsanforderungen für Cisco Nexus 3232C-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lesen Sie bei der Installation und Wartung von Cisco Nexus 3232C Switches alle empfohlenen Dokumente.



== Switch-Dokumentation

Zum Einrichten der Cisco Nexus 3232C-Switches wird die folgende Dokumentation von benötigt https://["Switches Der Cisco Nexus 3000-Serie Unterstützen"^] Seite.

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 3000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 3000 Series Switch Software Configuration Guides_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 3000 Series NX-OS Software Upgrade and Downgrade Guide_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Enthält Informationen zum Downgrade des Switch auf ONTAP unterstützte Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 3000 Series NX-OS Command Reference Master Index_
 a| 
Enthält Links zu den verschiedenen von Cisco bereitgestellten Befehlsreferenzen.



 a| 
_Cisco Nexus 3000 MIBs Referenz_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 3000-Switches.



 a| 
_Nexus 3000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 3000 Serie, Informationen und andere, die bei der Diagnose von Problemen mit Links, interner Hardware oder der Systemsoftware helfen können.



 a| 
_Versionshinweise zur Cisco Nexus 3000-Serie NX-OS (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Bugs und Einschränkungen der Cisco Nexus 3000 Serie.



 a| 
Gesetzliche Vorschriften, Compliance und Sicherheitsinformationen für die Cisco Nexus 6000, Cisco Nexus 5000 Serie, Cisco Nexus 3000 Serie und Cisco Nexus 2000 Serie
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 3000.

|===


== Dokumentation der ONTAP Systeme

Um ein ONTAP-System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Betriebssystemversion über das https://["ONTAP 9 Dokumentationszentrum"^].

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP-Dokumentation
 a| 
Dieser Service bietet detaillierte Informationen zu allen Aspekten der ONTAP Versionen.



 a| 
https://["Hardware Universe"^]
 a| 
Liefert Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===


== Schienensatz und Rack-Dokumentation

Informationen zur Installation eines Cisco Switch der 3232C-Serie in einem NetApp Rack finden Sie in der folgenden Hardware-Dokumentation.

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://["42-HE-System-Cabinet, Deep Guide"^]
 a| 
Beschreibt die FRUs, die dem 42U-Systemschrank zugeordnet sind, und bietet Anweisungen für Wartung und FRU-Austausch.



 a| 
link:install-cisco-nexus-3232c.html["Installieren Sie einen Cisco Nexus 3232C Switch in einem NetApp Rack"^]
 a| 
Beschreibt die Installation eines Cisco Nexus 3232C-Switch in einem NetApp Rack mit vier Pfosten.

|===