---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: Wenn Sie die unterstützten Plattformen dokumentieren möchten, müssen Sie das leere Verkabelungsarbeitsblatt ausfüllen, indem Sie das ausgefüllte Beispiel-Verkabelungsarbeitsblatt als Anleitung verwenden. Jeder Switch kann als einzelner 100-GbE-, 40-GbE-Port oder 4-x-GbE-Ports konfiguriert werden. 
---
= Füllen Sie das Cisco Nexus 3232C-Verkabelungsarbeitsblatt aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die unterstützten Plattformen dokumentieren möchten, laden Sie eine PDF-Datei dieser Seite herunter, und füllen Sie das Verkabelungsarbeitsblatt aus.

Das Verkabelungsarbeitsblatt enthält Beispiele für empfohlene Port-Zuweisungen von den Switches zu den Controllern. Das leere Arbeitsblatt bietet eine Vorlage, die Sie beim Einrichten des Clusters verwenden können.

Jeder Switch kann als einzelner 100-GbE-, 40-GbE-Port oder 4-x-GbE-Ports konfiguriert werden.



== Beispiel für eine Verkabelung

Die Beispielanschlussdefinition für jedes Switch-Paar lautet wie folgt:

[cols="1, 1, 1, 1"]
|===
2+| Cluster-Switch A 2+| Cluster-Switch B 


| Switch-Port | Verwendung von Nodes und Ports | Switch-Port | Verwendung von Nodes und Ports 


 a| 
1
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
1
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
2
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
2
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
3
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
3
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
4
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
4
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
5
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
5
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
6
 a| 
4 x 10 Gbit/40 Gbit/100 GNode
 a| 
6
 a| 
4 x 10 Gbit/40 Gbit/100 GNode



 a| 
7
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
7
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
8
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
8
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
9
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
9
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
10
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
10
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
11
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
11
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
12
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
12
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
13
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
13
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
14
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
14
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
15
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
15
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
16
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
16
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
17
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
17
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
18
 a| 
4 x 10 GB/40 GB/100 GB Node
 a| 
18
 a| 
4 x 10 GB/40 GB/100 GB Node



 a| 
19
 a| 
40 Gbit/100 G Node 19
 a| 
19
 a| 
40 Gbit/100 G Node 19



 a| 
20
 a| 
40 Gbit/100 G Node 20
 a| 
20
 a| 
40 Gbit/100 G Node 20



 a| 
21
 a| 
40 Gbit/100 G Node 21
 a| 
21
 a| 
40 Gbit/100 G Node 21



 a| 
22
 a| 
40 Gbit/100 G Node 22
 a| 
22
 a| 
40 Gbit/100 G Node 22



 a| 
23
 a| 
40 Gbit/100 G Node 23
 a| 
23
 a| 
40 Gbit/100 G Node 23



 a| 
24
 a| 
40 Gbit/100 G Node 24
 a| 
24
 a| 
40 Gbit/100 G Node 24



 a| 
25 bis 30
 a| 
Reserviert
 a| 
25 bis 30
 a| 
Reserviert



 a| 
31
 a| 
100-GB-ISL zu Switch B-Port 31
 a| 
31
 a| 
100-GB-ISL für Switch A-Port 31



 a| 
32
 a| 
100-GB-ISL zu Switch B-Port 32
 a| 
32
 a| 
100-GB-ISL für Switch A-Port 32

|===


== Leeres Verkabelungsarbeitsblatt

Sie können das leere Verkabelungsarbeitsblatt verwenden, um die Plattformen zu dokumentieren, die als Nodes in einem Cluster unterstützt werden. Der Abschnitt „_supported Cluster Connections_“ des https://["Hardware Universe"^] Definiert die von der Plattform verwendeten Cluster-Ports.

[cols="1, 1, 1, 1"]
|===
2+| Cluster-Switch A 2+| Cluster-Switch B 


| Switch-Port | Node-/Port-Verwendung | Switch-Port | Node-/Port-Verwendung 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 bis 30
 a| 
Reserviert
 a| 
25 bis 30
 a| 
Reserviert



 a| 
31
 a| 
100-GB-ISL zu Switch B-Port 31
 a| 
31
 a| 
100-GB-ISL für Switch A-Port 31



 a| 
32
 a| 
100-GB-ISL zu Switch B-Port 32
 a| 
32
 a| 
100-GB-ISL für Switch A-Port 32

|===