---
permalink: switch-cisco-3232c/task-steps-to-replace-a-cisco-nexus-3232c-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: Es besteht die Möglichkeit, einen defekten Cisco Nexus 3232C-Storage-Switch durch Ausführen einer bestimmten Aufgabenfolge unterbrechungsfrei zu ersetzen. 
---
= Schritte zum Austausch eines Cisco Nexus 3232C Storage-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es besteht die Möglichkeit, einen defekten Cisco Nexus 3232C-Storage-Switch durch Ausführen einer bestimmten Aufgabenfolge unterbrechungsfrei zu ersetzen.

Die vorhandene Netzwerkkonfiguration muss die folgenden Merkmale aufweisen:

* Auf der Seite Cisco Ethernet Switches befinden sich die neuesten RCF- und NX-OS-Versionen auf Ihren Switches.
* Management-Konnektivität muss auf beiden Switches vorhanden sein.
+
[NOTE]
====
Stellen Sie sicher, dass alle Fehlerbehebungsschritte durchgeführt wurden, um zu bestätigen, dass Ihr Switch ausgetauscht werden muss.

====


Der Cisco Nexus 3232C Switch muss folgende Merkmale aufweisen:

* Die Konnektivität des Managementnetzwerks muss funktionsfähig sein.
* Der Konsolenzugriff auf den Ersatzschalter muss vorhanden sein.
* Das entsprechende RCF- und NX-OS-Betriebssystemabbild muss auf den Switch geladen werden.
* Die anfängliche Anpassung des Schalters muss abgeschlossen sein.


*Verfahrensübersicht:*

* *Bestätigen Sie, dass der zu ersetzende Schalter S2 ist (Schritte ,1-,5)*
* *Trennen Sie die Kabel vom Schalter S2 ,(Schritt 6)*
* *Schließen Sie die Kabel wieder an den Schalter NS2 an (Schritt ,7)*
* *Überprüfung aller Gerätekonfigurationen auf Switch NS2 (Schritte ,8-,10)*
* Dieses Verfahren ersetzt den zweiten Nexus 3232C Storage Switch S2 durch den neuen 3232C Switch NS2.
* Die beiden Knoten sind node1 und node2.


.Schritte
. [[One]]]Wenn AutoSupport für diesen Cluster aktiviert ist, die automatische Case-Erstellung durch Aufrufen einer AutoSupport Meldung unterdrücken:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_X_ ist die Dauer des Wartungsfensters in Stunden.

+
[NOTE]
====
Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

====
. Überprüfen Sie den Integritätsstatus der Storage-Node-Ports, um sicherzustellen, dass eine Verbindung zum Storage-Switch S1 besteht:
`storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
. Stellen Sie sicher, dass der Speicherschalter S1 verfügbar ist:
`network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
. Führen Sie die aus
`show lldp neighbors` Mit dem Befehl auf dem Arbeitsschalter bestätigen Sie, dass Sie beide Nodes und alle Shelfs sehen können:
`show lldp neighbors`
+
[listing]
----
S1# show lldp neighbors
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
. [[fünf]]]Überprüfen Sie die Shelf-Ports im Storage-System:
`storage shelf port show -fields remote-device,remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
. [[sechs]]Entfernen Sie alle Kabel, die am Speicherschalter S2 angeschlossen sind.
. [[sieben]]Alle Kabel wieder an den Ersatz-Schalter NS2 anschließen.
. [[acht]]Integritätsstatus der Speicher-Node-Ports erneut prüfen:
`storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. Vergewissern Sie sich, dass beide Switches verfügbar sind:
`network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
. [[ten]]Überprüfung der Shelf-Ports im Speichersystem:
`storage shelf port show -fields remote-device,remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
. Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie es erneut, indem Sie eine AutoSupport Meldung aufrufen:
`system node autosupport invoke -node * -type all -message MAINT=END`

