---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_migrate_from_a_switchless_cluster_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= Migrieren Sie von einem Cluster ohne Switches mit DAT Storage durch Ergänzung von zwei neuen Shared-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




==== Migrieren Sie von einem Cluster ohne Switches mit DAT Storage

Wenn Sie ein unterbrechungsfrei 2-Node-Cluster ohne Switches zu einem Cluster mit Cisco Nexus 9336C-FX2 Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben. Der dokumentierte Prozess funktioniert für alle Nodes mit optischen oder Twinax-Ports, wird auf diesem Switch jedoch nicht unterstützt, wenn die Nodes integrierte 10-Gbit-BASE-T RJ45-Ports für die Cluster-Netzwerk-Ports verwenden.

Die meisten Systeme benötigen an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports. Siehe  https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"] Finden Sie weitere Informationen.

Falls Sie eine bestehende Cluster-Umgebung mit zwei Nodes ohne Switches nutzen, können Sie mit Cisco Nexus 9336C-FX2 Switches zu einer Switch-basierten Cluster-Umgebung mit zwei Nodes migrieren. So können Sie auf mehr als zwei Nodes im Cluster skalieren.

.Bevor Sie beginnen
* Konfiguration mit zwei Nodes ohne Switches:
+
** Die Konfiguration mit zwei Nodes ohne Switches muss ordnungsgemäß eingerichtet und funktionsfähig sein.
** Die Knoten müssen ONTAP 9.8 und höher ausführen.
** Alle Cluster-Ports müssen den Status *up* aufweisen.
** Alle logischen Cluster-Schnittstellen (LIFs) müssen sich im *up*-Zustand und auf ihren *Home*-Ports befinden.


* Konfiguration des Cisco Nexus 9336C-FX2 Switches:
+
** Beide Switches müssen über Management-Netzwerk-Konnektivität verfügen.
** Konsolenzugriff auf die Cluster-Switches muss vorhanden sein.
** Nexus 9336C-FX2 Node-zu-Node-Switch und Switch-to-Switch-Verbindungen müssen Twinax- oder Glasfaserkabel verwenden.
** Das NetApp https://hwu.netapp.com["Hardware Universe"] Enthält weitere Informationen zur Verkabelung.
** Inter-Switch Link (ISL)-Kabel müssen an den Anschlüssen 1/35 und 1/36 an beiden 9336C-FX2-Switches angeschlossen sein.


* Die Erstanpassung der Schalter 9336C-FX2 muss abgeschlossen sein. So werden die:
+
** 9336C-FX2-Switches führen die neueste Version der Software aus
** Auf die Switches wurden Referenzkonfigurationsdateien (RCFs) angewendet
** Auf den neuen Switches müssen alle Site-Anpassungen wie SMTP, SNMP und SSH konfiguriert werden.




.Über diese Aufgabe
In den Beispielen dieses Verfahrens wird die folgende Terminologie für Cluster-Switch und Node verwendet:

* Die Namen der Schalter 9336C-FX2 lauten _cs1_ und _cs2_.
* Die Namen der Cluster SVMs sind _node1_ und _node2_.
* Die Namen der LIFs sind_node1_clus1_ und _node1_clus2_ auf Knoten 1, und _node2_clus1_ und _node2_clus2_ auf Knoten 2.
* Die Eingabeaufforderung des Cluster1::*> gibt den Namen des Clusters an.
* Die in diesem Verfahren verwendeten Cluster-Ports lauten _e3a_ und _e3b_ gemäß AFF A400-Controller. Der https://hwu.netapp.com["Hardware Universe"] Enthält die neuesten Informationen über die tatsächlichen Cluster-Ports für Ihre Plattformen.


.Schritte
. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:  `system node autosupport invoke -node * -type all -message MAINT=xh`.
+
Wobei x die Dauer des Wartungsfensters in Stunden ist.




NOTE: Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

. [[Schritt2]]Ändern Sie die Berechtigungsebene in Erweitert, geben Sie y ein, wenn Sie dazu aufgefordert werden, fortzufahren:
`set -privilege advanced`
+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Deaktivieren Sie alle Node-Ports (keine ISL-Ports) auf den neuen Cluster-Switches cs1 und cs2. Sie dürfen die ISL-Ports nicht deaktivieren.
+
Das folgende Beispiel zeigt, dass die Node-Ports 1 bis 34 auf Switch cs1 deaktiviert sind:



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e/1-34
cs1(config-if-range)# shutdown
----
. [[Schritt4]]Überprüfen Sie, ob die ISL und die physischen Ports auf der ISL zwischen den beiden 9336C-FX2-Switches cs1 und cs2 auf den Ports 1/35 und 1/36 stehen:
`show port-channel summary`
+
Das folgende Beispiel zeigt, dass die ISL-Ports auf Switch cs1 aktiv sind:



[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
Das folgende Beispiel zeigt, dass die ISL-Ports auf Switch cs2 aktiv sind:

[listing]
----
       cs2# show port-channel summary
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
. [[schritt5]]Liste der benachbarten Geräte anzeigen:
`show cdp neighbors`.
+
Dieser Befehl enthält Informationen zu den Geräten, die mit dem System verbunden sind. Im folgenden Beispiel sind die benachbarten Geräte auf Switch cs1 aufgeführt:



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
Im folgenden Beispiel sind die benachbarten Geräte auf Switch cs2 aufgeführt:

[listing]
----
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
. [[ste6]]] Überprüfen Sie, ob alle Cluster-Ports aktiv sind:
`network port show - ipspace Cluster`
+
Jeder Port sollte für „Link“ und „OK“ für den Integritätsstatus angezeigt werden:



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
. [[step7]]Überprüfung, ob alle Cluster-LIFs betriebsbereit sind:
`network interface show - vserver Cluster`
+
Jede LIF im Cluster sollte für „true“ anzeigen `Is Home` Und haben einen Status Admin/Oper von up/up.



[listing]
----
cluster1::*> network interface show -vserver Cluster
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
. [[Schritt8]]Überprüfung, ob die automatische Umrüstung auf allen Cluster-LIFs aktiviert ist:
`network interface show - vserver Cluster -fields auto-revert`


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
. [[Schritt9]]Trennen Sie das Kabel vom Cluster-Port e3a auf node1, und verbinden sie dann e3a mit Port 1 am Cluster-Switch cs1. Verwenden Sie dabei die geeignete Verkabelung, die von den Switches 9336C-FX2 unterstützt wird.
+
Das NetApp https://hwu.netapp.com["Hardware Universe"] Enthält weitere Informationen zur Verkabelung.

. Trennen Sie das Kabel vom Cluster-Port e3a auf node2, und verbinden sie dann e3a mit Port 2 am Cluster-Switch cs1. Verwenden Sie dazu die geeignete Verkabelung, die von den Switches 9336C-FX2 unterstützt wird.
. Aktivieren Sie alle Ports für Knoten auf Cluster-Switch cs1.
+
Das folgende Beispiel zeigt, dass die Ports 1/1 bis 1/34 auf Switch cs1 aktiviert sind:



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1-34
cs1(config-if-range)# no shutdown
----
. [[step 12]]Überprüfen Sie, ob alle Cluster-LIFs *up*, betriebsbereit und als wahr angezeigt werden `Is Home`:
`network interface show - vserver Cluster`
+
Das folgende Beispiel zeigt, dass alle LIFs *up* auf node1 und node2 sind und dass `Is Home` Die Ergebnisse sind *wahr*:



[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
. [[steep13]]Informationen zum Status der Knoten im Cluster anzeigen:
`cluster show`
+
Im folgenden Beispiel werden Informationen über den Systemzustand und die Berechtigung der Nodes im Cluster angezeigt:



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. [[STep14]]Trennen Sie das Kabel vom Cluster-Port e3b auf node1, und verbinden sie dann e3b mit Port 1 am Cluster-Switch cs2. Verwenden Sie dazu die entsprechende Verkabelung, die von den Switches 9336C-FX2 unterstützt wird.
. Trennen Sie das Kabel vom Cluster-Port e3b auf node2, und verbinden sie dann e3b mit Port 2 am Cluster-Switch cs2. Verwenden Sie dazu die geeignete Verkabelung, die von den Switches 9336C-FX2 unterstützt wird.
. Aktivieren Sie alle Ports für Knoten auf Cluster-Switch cs2.
+
Das folgende Beispiel zeigt, dass die Ports 1/1 bis 1/34 auf Switch cs2 aktiviert sind:



[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1-34
cs2(config-if-range)# no shutdown
----
. [[step17]]Überprüfen Sie, ob alle Cluster-Ports aktiv sind:
`network port show - ipspace Cluster`
+
Im folgenden Beispiel werden alle Cluster-Ports auf node1 und node2 angezeigt:



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
. [[Schritt18]]Überprüfen Sie, ob alle Schnittstellen für wahr angezeigt werden `Is Home`:
`network interface show - vserver Cluster`



NOTE: Dies kann einige Minuten dauern.

Das folgende Beispiel zeigt, dass alle LIFs *up* auf node1 und node2 sind und dass `Is Home` Die Ergebnisse sind wahr:

[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
. [[Schritt19]]Überprüfen Sie, ob beide Knoten jeweils eine Verbindung zu jedem Switch haben:
`show cdp neighbors`
+
Das folgende Beispiel zeigt die entsprechenden Ergebnisse für beide Switches:



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
. [[steep20]]Informationen über die erkannten Netzwerkgeräte in Ihrem Cluster anzeigen:
`network device-discovery show -protocol cdp`


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
. [[step21]]Überprüfen Sie, ob die Speicherkonfiguration von HA-Paar 1 (und HA-Paar 2) korrekt und fehlerfrei ist:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[steep22]]Überprüfen Sie, ob die Einstellungen deaktiviert sind:
`network options switchless-cluster show`



NOTE: Es kann einige Minuten dauern, bis der Befehl abgeschlossen ist. Warten Sie, bis die Ankündigung „3-Minuten-Lebensdauer abläuft“ abläuft.

Der `false` Die Ausgabe im folgenden Beispiel zeigt, dass die Konfigurationseinstellungen deaktiviert sind:

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
. [[steep23]]Überprüfen Sie den Status der Knotenmitglieder im Cluster:
`cluster show`
+
Das folgende Beispiel zeigt Informationen über den Systemzustand und die Berechtigung der Nodes im Cluster:



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. [[steep24]] Stellen Sie sicher, dass das Clusternetzwerk über vollständige Konnektivität verfügt:
`cluster ping-cluster -node node-name`


[listing]
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
...
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
...
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[steep25]]Ändern Sie die Berechtigungsebene zurück in admin:
`set -privilege admin`
. Aktivieren Sie die Protokollerfassungsfunktion für die Ethernet Switch-Systemzustandsüberwachung mithilfe der Befehle, um Switch-bezogene Protokolldateien zu erfassen:
+
** `system switch ethernet log setup-password`
** `system switch ethernet log enable-collection`




[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.

Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----


==== Stellen Sie den gemeinsamen Schalter ein

Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die Namen der beiden gemeinsamen Schalter sind _sh1_ und _sh2_.
* Die Knoten sind _node1_ und _node2_.



NOTE: Das Verfahren erfordert die Verwendung von ONTAP Befehlen und Switches der Cisco Nexus 9000 Serie. ONTAP Befehle werden verwendet, sofern nicht anders angegeben.

.Schritte
. Überprüfen Sie, ob die Storage-Konfiguration von HA-Paar 1 (und HA-Paar 2) richtig und fehlerfrei ist:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[Schritt2]]Überprüfung, ob die Storage-Node-Ports ordnungsgemäß und betriebsbereit sind:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
. [[Schritt3]]Bewegen Sie das HA-Paar 1, den Pfad A des NSM224-Pfads in den Bereich der sh1-Ports 11-22.
. Installieren Sie ein Kabel von HA-Paar 1, node1, Pfad A zu sh1-Port-Bereich 11-22. Beispiel: Der Pfad Ein Speicherport an einer AFF A400 ist e0c.
. Installieren Sie ein Kabel von HA-Paar 1, node2, Pfad A zu sh1-Port-Bereich 11-22.
. Vergewissern Sie sich, dass die Node-Ports ordnungsgemäß und betriebsbereit sind:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step7]]Prüfen Sie, ob es keine Storage Switch- oder Verkabelungsprobleme beim Cluster gibt:
`system health alert show -instance`


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[Schritt8]]Bewegen Sie die Anschlüsse für HA-Paar 1, NSM224 Pfad B in den bereich der sh2-Ports 11-22.
. Installieren Sie ein Kabel von HA-Paar 1, node1, Pfad B bis sh2-Port-Bereich 11-22. Beispiel: Der Speicherport Pfad B auf einer AFF A400 ist e5b.
. Installieren Sie ein Kabel zwischen HA-Paar 1, node2, Pfad B und sh2-Port-Bereich 11-22.
. Vergewissern Sie sich, dass die Node-Ports ordnungsgemäß und betriebsbereit sind:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[Schritt12]]Überprüfung, ob die Speicherkonfiguration von HA-Paar 1 korrekt und fehlerfrei ist:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[Schritt13]]Konfigurieren Sie die nicht verwendeten sekundären Storage-Ports (Controller) auf HA-Paar 1 vom Storage zum Netzwerk neu. Wenn mehr als eine NS224 direkt angeschlossen war, gibt es Ports, die neu konfiguriert werden sollten.


[listing]
----
storage port modify –node [node name] –port [port name] –mode network
----
So platzieren Sie Storage-Ports in einer Broadcast-Domäne:

* `network port broadcast-domain create` (Um bei Bedarf eine neue Domäne zu erstellen)
* `network port broadcast-domain add-ports` (Zum Hinzufügen von Ports zu einer vorhandenen Domäne)


. [[Schritt14]]Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie sie erneut, indem Sie eine AutoSupport-Meldung aufrufen:
`system node autosupport invoke -node * -type all -message MAINT=END`

