---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Erfahren Sie mehr über die neuen Schalter für FAS und AFF Systeme. 
---
= Was ist neu bei Schaltern?
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die neuen Schalter für FAS und AFF Systeme.  Weitere Informationen zum Schalter finden Sie unter https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^] Die



== Neue Switch-Unterstützung

[cols="25h,~,~"]
|===
| Schalter | Beschreibung | Verfügbar ab 


 a| 
32-Port 400GbE-Ports Cisco Switch (X190300-CS-PI und X190300-PE)
 a| 
Unterstützung für Cisco 9332D-GX2B Intra-Cluster/HA/Storage-Switch.
 a| 
ONTAP 9.17.1



 a| 
64-Port 400GbE-Ports Cisco -Switch (X190310-CS-PI)
 a| 
Unterstützung für Cisco 9364D-GX2A Intra-Cluster/HA/Storage-Switch.
 a| 
ONTAP 9.17.1



 a| 
Cisco Nexus 9336C-FX2-T Cluster- und Speicherswitch mit 12 Ports für 10/25/40/100GbE-Anschlüsse (X190212-CS-PE und X190212-CS-PI)
 a| 
Unterstützt 10/25/40/100GbE-Clusterkonfigurationen und 100GbE-Speicherkonfigurationen (Switch-Attached Storage).
 a| 
ONTAP 9.10.1



 a| 
Cisco Nexus 9336C-FX2-T Cluster- und Speicherswitch mit 12 Ports für 10/25/40/100GbE-Anschlüsse (X190212-CS-PE und X190212-CS-PI)
 a| 
Unterstützt 10/25/40/100GbE-Clusterkonfigurationen und 100GbE-Speicherkonfigurationen (Switch-Attached Storage).
 a| 
ONTAP 9.10.1



 a| 
NVIDIA Switch mit 16 Ports und 100-GbE-Anbindung (X190006-PE und X190006-PI)
 a| 
Unterstützung für NVIDIA SN2100 Cluster-Interconnect-Switches und Storage-Switches, einschließlich Unterstützung für MetroCluster IP-Konfigurationen.
 a| 
ONTAP 9.10.1



 a| 
Cisco Switch mit 36 ​​Ports und 100-GbE-Geschwindigkeit (X190200-CS-PE und X190200-CS-PI)
 a| 
Unterstützt eine gemeinsam genutzte Infrastruktur (Cluster, HA und Switch-gebundener Speicher) auf demselben Paar Cisco Nexus 9336C-FX2 Switches, einschließlich der Unterstützung für MetroCluster IP-Konfigurationen.
 a| 
ONTAP 9.9.1



 a| 
Cisco Switch mit 36 ​​Ports und 100-GbE-Anschlüssen (X190200-CS-PE und X190200-CS-PI), (X190210-FE-PE und X190210-FE-PI)
 a| 
Cisco Nexus 9336C-FX2 Cluster-Interconnect-Switch und Storage-Switch-Unterstützung für AFF und ASA -Speichersysteme sowie für Front-End-Datenkonnektivität.
 a| 
ONTAP 9,8



 a| 
Broadcom BES-53248 Switch (X190005 und X190005R)
 a| 
Broadcom BES-53248 Cluster-Interconnect-Switch-Unterstützung für AFF/ FAS -Controller mit 10/25GbE- und 40/100GbE-Ports.
 a| 
ONTAP 9,8



 a| 
Cisco Switch mit 36 ​​Ports und 100-GbE-Ethernet (X190200) sowie Cisco Switch mit 32 Ports und 100-GbE-Ethernet (X190100 und X190100R)
 a| 
Cisco Nexus 3232C Storage-Switch-Unterstützung zum Anschluss von NS224 NVMe-Laufwerksgehäusen an AFF und ASA Speichersysteme:

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9,8

|===