---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Erfahren Sie mehr über die neuen Switches für FAS und AFF Systeme. 
---
= Was ist neu für Schalter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen Switches für FAS und AFF Systeme. Weitere Informationen zu den Schaltern finden Sie im https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^].



== Unterstützung für neue Switches

[cols="25h,~,~"]
|===
| Schalter | Beschreibung | Verfügbar ab 


 a| 
12-Port 10/25/40/100GbE Cisco Nexus 9336C-FX2-T Cluster- und Speicher-Switch (X190212-CS-PE und X190212-CS-PI)
 a| 
Unterstützt 10/25/40/100GbE-Clusterkonfigurationen und 100GbE-Speicherkonfigurationen (Switch-Attached Storage).
 a| 
ONTAP 9.10.1



 a| 
16-Port 100-GbE-NVIDIA-Switch (X190006-PE und X190006-PI)
 a| 
NVIDIA SN2100 Cluster Interconnect Switch und Storage Switch Unterstützung, einschließlich Unterstützung für MetroCluster IP-Konfigurationen.
 a| 
ONTAP 9.10.1



 a| 
36-Port 100 GbE Cisco Switch (X190200-CS-PE und X190200-CS-PI)
 a| 
Unterstützung einer Shared IT-Infrastruktur (Cluster, HA und Switch-Attached Storage) auf demselben Paar Cisco Nexus 9336C-FX2 Switches, einschließlich Unterstützung für MetroCluster IP-Konfigurationen.
 a| 
ONTAP 9.9.1



 a| 
36-Port 100 GbE Cisco Switch (X190200-CS-PE und X190200-CS-PI), (X190210-FE-PE und X190210-FE-PI)
 a| 
Cisco Nexus 9336C-FX2 Cluster-Interconnect-Switch und Storage-Switch-Unterstützung für AFF- und ASA-Storage-Systeme sowie für Front-End-Datenkonnektivität.
 a| 
ONTAP 9.8



 a| 
Broadcom BES-53248 Switch (X190005 und X190005R)
 a| 
Unterstützung der Broadcom BES-53248 Cluster Interconnect Switches für AFF/FAS Controller mit 10/25-GbE- und 40/100-GbE-Ports.
 a| 
ONTAP 9.8



 a| 
36-Port 100-GbE-Cisco-Switch (X190200) und 32-Port 100-GbE-Cisco-Switch (X190100 und X190100R)
 a| 
Unterstützung für Storage-Switches der Cisco Nexus 3232C-Serie zur Verbindung der NS224 NVMe Laufwerk-Shelfs AFF und ASA Storage-Systeme:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===