---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: Bevor Sie Ihren NVIDIA SN2100 Switch konfigurieren, lesen Sie bitte die folgenden Informationen. 
---
= Überprüfung der Verkabelung und Konfigurationsüberlegungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Ihren NVIDIA SN2100 Switch konfigurieren, beachten Sie bitte die folgenden Hinweise.



== NVIDIA -Portdetails

|===


| *Switch-Ports* | *Portnutzung* 


 a| 
swp1s0-3
 a| 
4x10GbE Breakout-Cluster-Portknoten



 a| 
swp2s0-3
 a| 
4x25GbE Breakout-Cluster-Portknoten



 a| 
swp3-14
 a| 
40/100GbE-Cluster-Portknoten



 a| 
swp15-16
 a| 
100GbE Inter-Switch Link (ISL)-Ports

|===
Siehe die https://hwu.netapp.com/Switch/Index["Hardware Universe"^] Weitere Informationen zu Switch-Ports finden Sie hier.



== Verbindungsverzögerungen bei optischen Verbindungen

Falls Sie Verbindungsverzögerungen von mehr als fünf Sekunden feststellen, bietet Cumulus Linux 5.4 und spätere Versionen Unterstützung für schnelles Verbindungsaufbauen.  Sie können die Links mithilfe der folgenden Funktion konfigurieren: `nv set` Befehl wie folgt:

[listing, subs="+quotes"]
----
*nv set interface <interface-id> link fast-linkup on*
*nv config apply*
*reload the switchd*
----
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus-cs13:mgmt:~$ *nv set interface swp5 link fast-linkup on*
cumulus@cumulus-cs13:mgmt:~$ *nv config apply*
*switchd need to reload on this config change*

Are you sure? [y/N] *y*
applied [rev_id: 22]

Only switchd reload required
----
====


== Unterstützung für Kupferverbindungen

Um dieses Problem zu beheben, sind folgende Konfigurationsänderungen erforderlich.

[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Ermitteln Sie die Bezeichnung für jede Schnittstelle, die 40GbE/100GbE-Kupferkabel verwendet:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface pluggables*

Interface  Identifier     Vendor Name     Vendor PN    Vendor SN      Vendor Rev
---------  -------------  --------------  -----------  -------------  ----------
swp3       0x11 (QSFP28)  Molex           112-00576    93A2229911111  B0
swp4       0x11 (QSFP28)  Molex           112-00576    93A2229922222  B0
----
. Fügen Sie die folgenden zwei Zeilen hinzu: `/etc/cumulus/switchd.conf` Datei für jeden Port (swp<n>), der 40GbE/100GbE-Kupferkabel verwendet:
+
** `interface.swp<n>.enable_media_depended_linkup_flow=TRUE`
** `interface.swp<n>.enable_short_tuning=TRUE`
+
Beispiel:

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo nano /etc/cumulus/switchd.conf*
.
.
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
interface.swp4.enable_media_depended_linkup_flow=TRUE
interface.swp4.enable_short_tuning=TRUE
----


. Starten Sie das Gerät neu. `switchd` Service:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo systemctl restart switchd.service*
----
. Vergewissern Sie sich, dass die Ports aktiv sind:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP              Summary
-----  --------- ----  -----  ---------- ----------------- --------
UP     swp3      100G  9216   Trunk/L2                     Master: bridge(UP)
UP     swp4      100G  9216   Trunk/L2                     Master: bridge(UP)
----


--
.Cumulus Linux 5.x
--
. Ermitteln Sie die Bezeichnung für jede Schnittstelle, die 40GbE/100GbE-Kupferkabel verwendet:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show interface --view=pluggables*

Interface  Identifier     Vendor Name     Vendor PN    Vendor SN      Vendor Rev
---------  -------------  --------------  -----------  -------------  ----------
swp3       0x11 (QSFP28)  Molex           112-00576    93A2229911111  B0
swp4       0x11 (QSFP28)  Molex           112-00576    93A2229922222  B0
----
. Konfigurieren Sie die Links mithilfe der `nv set` Befehl wie folgt:
+
** `nv set interface <interface-id> link fast-linkup on`
** `nv config apply`
** Laden Sie die `switchd` Service
+
Beispiel:

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set interface swp5 link fast-linkup on*
cumulus@cumulus:mgmt:~$ *nv config apply*
switchd need to reload on this config change

Are you sure? [y/N] *y*
applied [rev_id: 22]

Only switchd reload required
----


. Vergewissern Sie sich, dass die Ports aktiv sind:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP              Summary
-----  --------- ----  -----  ---------- ----------------- --------
UP     swp3      100G  9216   Trunk/L2                     Master: bridge(UP)
UP     swp4      100G  9216   Trunk/L2                     Master: bridge(UP)
----


--
====
Siehe den Artikel in der Wissensdatenbank. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric_Interconnect_and_Management_Switches/NVIDIA_SN2100_switch_fails_to_connect_using_40_100GbE_copper_cable["Der SN2100-Switch kann keine Verbindung über 40/100GbE-Kupferkabel herstellen."^] für weitere Einzelheiten.

Unter Cumulus Linux 4.4.2 werden Kupferverbindungen auf SN2100-Switches mit X1151A NIC, X1146A NIC oder integrierten 100GbE-Ports nicht unterstützt. Beispiel:

* AFF A800 an den Ports e0a und e0b
* AFF A320 an den Ports e0g und e0h




== QSA-Adapter

Wenn ein QSA-Adapter verwendet wird, um eine Verbindung zu den 10GbE/25GbE-Cluster-Ports einer Plattform herzustellen, kann es vorkommen, dass die Verbindung nicht zustande kommt.

Um dieses Problem zu beheben, gehen Sie wie folgt vor:

* Für 10GbE stellen Sie die Verbindungsgeschwindigkeit von swp1s0-3 manuell auf 10000 ein und deaktivieren Sie die automatische Aushandlung.
* Für 25GbE stellen Sie die Verbindungsgeschwindigkeit swp2s0-3 manuell auf 25000 ein und deaktivieren Sie die automatische Aushandlung.



NOTE: Bei Verwendung von 10GbE/25GbE QSA-Adaptern stecken Sie diese in nicht-breakout 40GbE/100GbE-Ports (swp3-swp14).  Stecken Sie den QSA-Adapter nicht in einen Port, der für Breakout konfiguriert ist.



== Einstellen der Schnittstellengeschwindigkeit an Breakout-Ports

Je nach Transceiver im Switch-Port müssen Sie möglicherweise die Geschwindigkeit an der Switch-Schnittstelle auf eine feste Geschwindigkeit einstellen.  Bei Verwendung von 10GbE- und 25GbE-Breakout-Ports überprüfen Sie, ob die automatische Aushandlung deaktiviert ist, und stellen Sie die Schnittstellengeschwindigkeit am Switch ein.

[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
Beispiel:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add int swp1s3 link autoneg off && net com*
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
Überprüfen Sie den Schnittstellen- und Portstatus, um sicherzustellen, dass die Einstellungen angewendet wurden:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface*

State  Name      Spd    MTU    Mode        LLDP             Summary
-----  --------  -----  -----  ----------  ---------------  --------------------------------------
.
.
UP     swp1s0     10G   9216   Trunk/L2    cs07 (e4c)       Master: br_default(UP)
UP     swp1s1     10G   9216   Trunk/L2    cs07 (e4d)       Master: br_default(UP)
UP     swp1s2     10G   9216   Trunk/L2    cs08 (e4c)       Master: br_default(UP)
UP     swp1s3     10G   9216   Trunk/L2    cs08 (e4d)       Master: br_default(UP)
.
.
UP     swp3       40G   9216   Trunk/L2    cs03 (e4e)       Master: br_default(UP)
UP     swp4       40G   9216   Trunk/L2    cs04 (e4e)       Master: br_default(UP)
DN     swp5       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp6       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp7       N/A   9216   Trunk/L2                     Master: br_default(UP)
.
.
UP     swp15      100G  9216   BondMember  cs01 (swp15)     Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  cs01 (swp16)     Master: cluster_isl(UP)
.
.
----
--
.Cumulus Linux 5.x
--
Beispiel:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set interface swp1s3 link auto-negotiate off*
cumulus@cumulus:mgmt:~$ *nv set interface swp1s3 link speed 10G*
cumulus@cumulus:mgmt:~$ *nv show interface swp1s3*

link                                                                                            
  auto-negotiate        off                     off                     off                   
  duplex                full                    full                    full                  
  speed                 10G                     10G                     10G                   
  fec                   auto                    auto                    auto                  
  mtu                   9216                    9216                    9216                  
[breakout]                                                                                    
  state                 up                      up                      up
----
Überprüfen Sie den Schnittstellen- und Portstatus, um sicherzustellen, dass die Einstellungen angewendet wurden:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show interface*

State  Name      Spd    MTU    Mode        LLDP             Summary
-----  --------  -----  -----  ----------  ---------------  --------------------------------------
.
.
UP     swp1s0     10G   9216   Trunk/L2    cs07 (e4c)       Master: br_default(UP)
UP     swp1s1     10G   9216   Trunk/L2    cs07 (e4d)       Master: br_default(UP)
UP     swp1s2     10G   9216   Trunk/L2    cs08 (e4c)       Master: br_default(UP)
UP     swp1s3     10G   9216   Trunk/L2    cs08 (e4d)       Master: br_default(UP)
.
.
UP     swp3       40G   9216   Trunk/L2    cs03 (e4e)       Master: br_default(UP)
UP     swp4       40G   9216   Trunk/L2    cs04 (e4e)       Master: br_default(UP)
DN     swp5       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp6       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp7       N/A   9216   Trunk/L2                     Master: br_default(UP)
.
.
UP     swp15      100G  9216   BondMember  cs01 (swp15)     Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  cs01 (swp16)     Master: cluster_isl(UP)
.
.
----
--
====
.Wie geht es weiter?
Nachdem Sie Ihre Verkabelungs- und Konfigurationsanforderungen überprüft haben, können Sielink:install-cable-shelves-sn2100-cluster.html["Verkabeln Sie die NS224-Regale als schaltergebundene Aufbewahrung."] Die
