---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Wenn Sie ONTAP Cluster mit mehr als zwei Nodes erstellen möchten, sind zwei unterstützte Cluster-Netzwerk-Switches erforderlich. Sie können zusätzliche, optionale Management Switches verwenden. 
---
= Komponenten und Teilenummern für NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lesen Sie bei der Installation und Wartung von NVIDIA SN2100-Switches die Liste der Komponenten und Teilenummern für Schrank und Schienensatz.



== Rack-Details

Sie installieren den NVIDIA SN2100-Switch (X190006) in einem NVIDIA Dual/Single-Switch-Schrank mit den Standardhalterungen, die im Lieferumfang des Switches enthalten sind.



== Einzelheiten zum Schienensatz

In der folgenden Tabelle sind die Teilenummer und Beschreibung der SN2100-Switches und Schienen-Kits aufgeführt:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
X190006-PE
 a| 
Cluster-Switch, NVIDIA SN2100, 16 PT 100 GbE, PTSX



 a| 
X190006-PI
 a| 
Cluster Switch, NVIDIA SN2100, 16 PT 100 GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Rail Kit, NVIDIA Dual Switch Seite an Seite



 a| 
X-MTEF-KIT-E
 a| 
Rail Kit, NVIDIA Single Switch, kurze Tiefe

|===

NOTE: Weitere Informationen finden Sie in der NVIDIA-Dokumentation auf https://docs.nvidia.com/networking/display/sn2000pub/Installation["Installieren Sie den SN2100-Switch und den Schienen-Kit"^].

.Was kommt als Nächstes?
Nachdem Sie Ihre Komponenten und Teilenummern bestätigt haben, können Sie die folgenden überprüfen: link:required-documentation-sn2100-cluster.html["erforderliche Dokumentation"]Die
