---
permalink: switch-nvidia-sn2100/configure-overview-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Der NVIDIA SN2100 Switch ist ein 10/25/40/100 GbE Ethernet-Switch mit Cumulus Linux. Der SN2100 Switch unterstützt Cluster- und Storage-Anwendungen in ONTAP 9.10.1 über verschiedene Switch-Paare. 
---
= Überblick über Installation und Konfiguration von NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NVIDIA SN2100 ist ein Cluster-Switch, mit dem Sie ONTAP Cluster mit mehr als zwei Knoten erstellen können.



== Überblick über die Erstkonfiguration

Gehen Sie wie folgt vor, um einen NVIDIA SN2100-Switch auf Systemen mit ONTAP zu konfigurieren:

. link:install-hardware-sn2100-cluster.html["Installieren Sie die Hardware für den NVIDIA SN2100 Switch"].
+
Anweisungen hierzu finden Sie im _NVIDIA Switch Installation Guide_.

. link:configure-sn2100-cluster.html["Konfigurieren Sie den Switch"].
+
Anweisungen hierzu finden Sie in der Dokumentation von NVIDIA.

. link:cabling-considerations-sn2100-cluster.html["Prüfen Sie die Verkabelung und Konfigurationsüberlegungen"].
+
Prüfen Sie die Anforderungen für optische Verbindungen, den QSA-Adapter und die Switch-Port-Geschwindigkeit.

. link:install-cable-shelves-sn2100-cluster.html["Verbinden Sie die NS224-Shelfs als Switch-Attached Storage"].
+
Befolgen Sie die Verkabelungsverfahren, wenn Sie über ein System verfügen, in dem die NS224-Laufwerk-Shelfs als Switch-Attached Storage (kein Direct-Attached Storage) verkabelt werden müssen.

. link:install-cumulus-mode-sn2100-cluster.html["Installieren Sie Cumulus Linux im Cumulus-Modus"] Oder link:install-onie-mode-sn2100-cluster.html["Installieren Sie Cumulus Linux im ONIE-Modus"].
+
Sie können Cumulus Linux (CL) OS installieren, wenn der Switch Cumulus Linux oder ONIE ausführt.

. link:install-rcf-sn2100-cluster.html["Installieren Sie das RCF-Skript (Reference Configuration File)"].
+
Für Clustering- und Speicheranwendungen stehen zwei RCF-Skripte zur Verfügung. Das Verfahren für jedes ist gleich.

. link:CSHM_log_collection.html["Aktivieren Sie die Protokollerfassung"].
+
Verwenden Sie diese Funktion, um Switch-bezogene Protokolldateien in ONTAP zu sammeln.

. link:CSHM_snmpv3.html["Konfigurieren Sie SNMPv3 für die Überwachung"].
+
Diese Version umfasst Unterstützung für SNMPv3 für die Erfassung von Switch-Protokollen und für Switch Health Monitoring (SHM).



Die Verfahren verwenden Network Command Line Utility (NCLU), eine Befehlszeilenoberfläche, die sicherstellt, dass Cumulus Linux für alle zugänglich ist. Der NET-Befehl ist das Wrapper-Dienstprogramm, mit dem Sie Aktionen von einem Terminal aus ausführen.



== Weitere Informationen

Bevor Sie mit der Installation oder Wartung beginnen, überprüfen Sie bitte die folgenden Punkte:

* link:configure-reqs-sn2100-cluster.html["Konfigurationsanforderungen"]
* link:components-sn2100-cluster.html["Komponenten und Teilenummern"]
* link:required-documentation-sn2100-cluster.html["Erforderliche Dokumentation"]
* https://hwu.netapp.com["Hardware Universe"^] Für alle unterstützten ONTAP-Versionen.

