---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt alle Anforderungen und die empfohlene Dokumentation beachten. 
---
= Konfigurationsanforderungen für NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt alle Konfigurationsanforderungen beachten.



== Installationsvoraussetzungen

Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Cluster-Netzwerk-Switches.  Sie können zusätzliche Management-Schalter verwenden, die optional sind.

Sie installieren den NVIDIA SN2100 Switch (X190006) im NVIDIA Dual/Single Switch Schrank mit den Standardhalterungen, die im Lieferumfang des Switches enthalten sind.

Hinweise zur Verkabelung finden Sie unter link:cabling-considerations-sn2100-cluster.html["Überprüfung der Verkabelung und Konfigurationsüberlegungen"].



== ONTAP und Linux-Unterstützung

Der NVIDIA SN2100 Switch ist ein 10/25/40/100GbE Switch, auf dem Cumulus Linux läuft.  Der Schalter unterstützt Folgendes:

* ONTAP 9.10.1P3 und höher
+
Der SN2100-Switch dient Cluster- und Speicheranwendungen in ONTAP 9.10.1P3 und späteren Versionen über verschiedene Switch-Paare.

* Cumulus Linux (CL) Betriebssystemversionen
+
** Bestimmte CL-Versionen sind qualifiziert und werden von NetApp unterstützt. Aktuelle Kompatibilitätsinformationen finden Sie unter link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Informationen zu NVIDIA Ethernet-Switches"^] oder dem link:https://hwu.netapp.com["Hardware Universe"^].
** Um die SN2100 Cumulus Software von NVIDIA herunterzuladen, benötigen Sie Anmeldedaten, um auf das NVIDIA Enterprise Support Portal zuzugreifen. Siehe den Knowledge Base Artikel link:https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["So registrieren Sie sich bei NVIDIA für den Zugriff auf das Enterprise-Supportportal"^].


* Sie können Cumulus Linux installieren, wenn auf dem Switch Cumulus Linux oder ONIE läuft.


.Wie geht es weiter?
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie Ihre link:components-sn2100-cluster.html["Komponenten und Teilenummern"]Die
