---
permalink: switch-nvidia-sn2100/install_setup_sn2100_switches_overview.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Der NVIDIA SN2100 Switch ist ein 10/25/40/100 GbE Ethernet-Switch mit Cumulus Linux. Der SN2100 Switch unterstützt Cluster- und Storage-Anwendungen in ONTAP 9.10.1 über verschiedene Switch-Paare. 
---
= Einrichten und Konfigurieren der NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der NVIDIA SN2100 Switch ist ein 10/25/40/100 GB Ethernet-Switch mit Cumulus Linux. Der SN2100 Switch dient Cluster- und Speicheranwendungen in ONTAP 9.10.1P3 über verschiedene Switch-Paare.

Cumulus Linux (CL) kann entweder installiert werden, wenn der Switch Cumulus Linux oder ONIE ausführt. Für diese Version wird Cumulus Linux Version 4.4.2 unterstützt.


NOTE: Die Verfahren hier verwenden Network Command Line Utility (NCLU), eine Befehlszeilenoberfläche, die sicherstellt, dass Cumulus Linux für alle zugänglich ist. Der NET-Befehl ist das Wrapper-Dienstprogramm, mit dem Sie Aktionen von einem Terminal aus ausführen.


IMPORTANT: Stellen Sie bei der Verwendung von Breakout-Kabeln für 10G und 25G sicher, dass die automatische Aushandlung nicht erfolgt und die Port-Geschwindigkeit auf dem Switch fest eingestellt ist. Siehe link:install_cabling_config_considerations_sn2100.html["Überlegungen zur Verkabelung und Konfiguration"^] Entnehmen.
