---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt die gesamte empfohlene Dokumentation lesen. 
---
= Dokumentationsanforderungen für NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation des NVIDIA SN2100 Switches sollten Sie unbedingt die gesamte empfohlene Dokumentation durchlesen.

[cols="1,2"]
|===
| Titel | Beschreibung 


 a| 
link:https://docs.nvidia.com/networking/display/sn2000pub/Installation["NVIDIA Switch Installationsanleitung"^]
 a| 
Beschreibt die Installation Ihrer NVIDIA SN2100 Switches.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["NS224 NVMe-Laufwerksgehäuse-Verkabelungsleitfaden"^]
 a| 
Übersicht und Abbildungen zur Konfiguration der Verkabelung von Laufwerksschächten.

|===


== ONTAP-Systemdokumentation

Um ein ONTAP-System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Version des Betriebssystems.

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controllerspezifische _Installations- und Einrichtungsanweisungen_
 a| 
Beschreibt die Installation von NetApp -Hardware.



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Bietet detaillierte Informationen zu allen Aspekten der ONTAP Releases.



 a| 
link:https://hwu.netapp.com/["Hardware Universe"^]
 a| 
Ermöglicht Ihnen, unterstützte Hardware wie Cluster-Switches und Kabel für Ihr Plattformmodell zu bestätigen.

|===