---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/components-9336c-storage.html 
keywords: shared storage cluster switch 
summary: Ab ONTAP 9.9.1 können Sie Cisco Nexus 9336C-FX2 Switches verwenden, um Speicher- und Clusterfunktionen in einem gemeinsam genutzten Switch-Szenario zu kombinieren. 
---
= Komponenten und Teilenummern für Cisco Nexus 9336C-FX2 und 9336C-FX2-T Speicherswitches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung der Cisco Nexus 9336C-FX2 und 9336C-FX2-T Storage-Switches sollten Sie unbedingt die Liste der Komponenten und Teilenummern überprüfen.

Die folgende Tabelle listet die Teilenummer und Beschreibung für die Speicherschalter, Lüfter und Netzteile 9336C-FX2 und 9336C-FX2-T auf:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
X190200-CS-PE
 a| 
Cluster-Schalter, N9336C 36Pt PTSX 10/25/40/100G



 a| 
X190200-CS-PI
 a| 
Cluster-Schalter, N9336C 36Pt PSIN 10/25/40/100G



 a| 
X190212-CS-PE
 a| 
Cluster-Schalter, N9336C 12Pt (9336C-FX2-T) PTSX 10/25/40/100G



 a| 
X190212-CS-PI
 a| 
Clusterschalter, N9336C 12Pt (9336C-FX2-T) PSIN 10/25/40/100G



 a| 
SW-N9K-FX2-24P-UPG
 a| 
SW, Cisco 9336CFX2 24-Port POD-Lizenz



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT 10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT 10/25/40/100GQSFP28



 a| 
X190002
 a| 
Zubehörset X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C AC 1100W Netzteil - Abluftführung an der linken Seite



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C AC 1100W Netzteil - Lufteinlass an der linken Seite



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65 CFM, Abluftstrom an der Backbordseite



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65 CFM, Einlassluftstrom auf der Backbordseite

|===


== Cisco Smart-Lizenzen nur für 9336C-FX2-T-Ports

Um mehr als 12 Ports an Ihrem Cisco Nexus 9336C-FX-T Storage-Switch zu aktivieren, müssen Sie eine Cisco Smart-Lizenz erwerben.  Cisco Smart-Lizenzen werden über Cisco Smart-Konten verwaltet.

. Erstellen Sie bei Bedarf ein neues Smart-Konto. Sehen https://id.cisco.com/signin/register["Erstellen Sie ein neues Smart-Konto"^] für Details.
. Zugriff auf ein bestehendes Smart-Konto anfordern. Sehen https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30["Zugriff auf ein bestehendes Smart-Konto anfordern"^] für Details.



NOTE: Sobald Sie Ihre Smart-Lizenz erworben haben, installieren Sie die entsprechende RCF-Datei, um alle 36 verfügbaren Ports zu aktivieren und zu konfigurieren.

.Was kommt als nächstes
Nachdem Sie Ihre Komponenten und Teilenummern bestätigt haben, können Sie die folgenden überprüfen: link:required-documentation-9336c-storage.html["erforderliche Dokumentation"]Die
