---
permalink: switch-cisco-9336c-fx2-storage/configure-software-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Überblick über die Software-Konfiguration für Cisco Nexus 9336C-FX2 Storage-Switches 
---
= Workflow zur Softwareinstallation für Cisco Nexus 9336C-FX2 Storage-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
So installieren und konfigurieren Sie Software für einen Cisco Nexus 9336C-FX2-Speicher-Switch:

. link:install-nxos-overview-9336c-storage.html["Bereiten Sie die Installation oder das Upgrade von NX-OS und RCF vor"].
+
Die Cisco NX-OS-Software und die Referenzkonfigurationsdateien (RCFs) müssen auf Cisco Nexus 9336C-FX2-Speicherswitches installiert sein.

. link:install-nxos-software-9336c-storage.html["Installieren oder aktualisieren Sie die NX-OS-Software"].
+
Laden Sie die NX-OS-Software auf dem Cisco Nexus 9336C-FX2-Speicherschalter herunter, und installieren Sie sie oder aktualisieren Sie sie.

. link:install-rcf-software-9336c-storage.html["Installieren oder aktualisieren Sie die RCF-Konfigurationsdatei"].
+
Installieren oder aktualisieren Sie den RCF, nachdem Sie den Cisco Nexus 9336C-FX2-Speicherschalter zum ersten Mal eingerichtet haben. Sie können dieses Verfahren auch verwenden, um Ihre RCF-Version zu aktualisieren.


