---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: Sie können die RCF-Datei installieren, nachdem Sie den Switch Nexus 9336C-FX2 zum ersten Mal eingerichtet haben. Sie können dieses Verfahren auch verwenden, um Ihre RCF-Version zu aktualisieren. 
---
= Übersicht zur Installation oder Aktualisierung der Referenzkonfigurationsdatei (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Referenzkonfigurationsdatei (RCF) wird nach der erstmaligen Einrichtung des Speicherswitches Nexus 9336C-FX2 installiert. Sie aktualisieren Ihre RCF-Version, wenn auf Ihrem Switch eine vorhandene Version der RCF-Datei installiert ist.

Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Wie man die Konfiguration eines Cisco Interconnect-Switches löscht und gleichzeitig die Remote-Konnektivität beibehält"^] Weitere Informationen zur Installation oder Aufrüstung Ihres RCF erhalten Sie bei Bedarf.

.Verfügbare RCF-Konfigurationen
Die folgende Tabelle beschreibt die für verschiedene Konfigurationen verfügbaren RCFs.  Wählen Sie den für Ihre Konfiguration passenden RCF aus.

Für spezifische Details zur Port- und VLAN-Nutzung verweisen wir auf den Abschnitt „Banner und wichtige Hinweise“ in Ihrem RCF.

[cols="1,2"]
|===
| RCF-Name | Beschreibung 


 a| 
2-Cluster-HA-Ausbruch
 a| 
Unterstützt zwei ONTAP -Cluster mit mindestens acht Knoten, einschließlich Knoten, die gemeinsam genutzte Cluster+HA-Ports verwenden.



 a| 
4-Cluster-HA-Ausbruch
 a| 
Unterstützt vier ONTAP -Cluster mit mindestens vier Knoten, einschließlich Knoten, die gemeinsam genutzte Cluster+HA-Ports verwenden.



 a| 
1-Cluster-HA
 a| 
Alle Ports sind für 40/100GbE konfiguriert.  Unterstützt gemeinsam genutzten Cluster-/HA-Datenverkehr auf Ports.  Erforderlich für die Systeme AFF A320, AFF A250 und FAS500f .  Darüber hinaus können alle Ports als dedizierte Cluster-Ports verwendet werden.



 a| 
1-Cluster-HA-Ausbruch
 a| 
Die Ports sind für 4x10GbE Breakout, 4x25GbE Breakout (RCF 1.6+ auf 100GbE Switches) und 40/100GbE konfiguriert.  Unterstützt gemeinsam genutzten Cluster-/HA-Datenverkehr auf Ports für Knoten, die gemeinsam genutzte Cluster-/HA-Ports verwenden: AFF A320, AFF A250 und FAS500f Systeme.  Darüber hinaus können alle Ports als dedizierte Cluster-Ports verwendet werden.



 a| 
Cluster-HA-Speicher
 a| 
Die Ports sind für 40/100GbE für Cluster+HA, 4x10GbE Breakout für Cluster und 4x25GbE Breakout für Cluster+HA sowie 100GbE für jedes Storage-HA-Paar konfiguriert.



 a| 
Cluster
 a| 
Zwei Varianten von RCF mit unterschiedlicher Belegung von 4x10GbE-Ports (Breakout) und 40/100GbE-Ports. Alle FAS und AFF Knoten werden unterstützt, mit Ausnahme der Systeme AFF A320, AFF A250 und FAS500f .



 a| 
Storage
 a| 
Alle Ports sind für 100GbE NVMe-Speicherverbindungen konfiguriert.

|===
.Empfohlene Dokumentation
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^]
+
Auf der NetApp Support-Website finden Sie die Tabelle zur Switch-Kompatibilität, in der die unterstützten ONTAP und RCF-Versionen aufgeführt sind.  Beachten Sie, dass zwischen der Befehlssyntax in der RCF und der Syntax in bestimmten Versionen von NX-OS Befehlsabhängigkeiten bestehen können.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 Series Switches"^]
+
Die vollständige Dokumentation zu den Upgrade- und Downgrade-Verfahren für Cisco -Switches finden Sie in den entsprechenden Software- und Upgrade-Leitfäden auf der Cisco -Website.



.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Namen der beiden Cisco Switches lauten cs1 und cs2.
* Die Knotennamen sind node1-01, node1-02, node1-03 und node1-04.
* Die Cluster-LIF-Namen sind node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 und node1-04_clus2.
* Der `cluster1::*>` Die Eingabeaufforderung zeigt den Namen des Clusters an.


Siehe die https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] um die korrekten Ports auf Ihrer Plattform zu überprüfen.


NOTE: Die Befehlsausgaben können je nach ONTAP Version variieren.

.verwendete Befehle
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 9000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

.Wie geht es weiter?
Nachdem Sie die Installations- oder Aktualisierungsprozedur für RCF durchgelesen haben, können Sielink:install-rcf-software-9336c-storage.html["Installieren Sie den RCF"] oderlink:upgrade-rcf-software-9336c-storage.html["Aktualisieren Sie Ihren RCF"] nach Bedarf.
