---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Falls Sie die erforderlichen Konfigurationsinformationen und Dokumentationen noch nicht besitzen, müssen Sie diese Informationen sammeln, bevor Sie Ihren Cluster und die Management-Netzwerk-Switches einrichten. 
---
= Installieren Sie die Speicher-Switches 9336C-FX2 und 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie dieses Verfahren, um die Speicher-Switches Cisco Nexus 9336C-FX2 und 9336C-FX2-T zu installieren.

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Zugriff auf einen HTTP-, FTP- oder TFTP-Server am Installationsort, um die entsprechenden NX-OS- und Referenzkonfigurationsdatei-(RCF)-Versionen herunterzuladen.
* Anwendbare NX-OS-Version, heruntergeladen von https://software.cisco.com/download/home["Cisco -Software-Download"^] Seite.
* Anwendbare Lizenzen, Netzwerk- und Konfigurationsinformationen sowie Kabel.
* Vollendetlink:setup-worksheet-9336c-storage.html["Verkabelungs-Arbeitsblätter"] Die
* Anwendbare NetApp -Clusternetzwerk- und Managementnetzwerk-RCFs, die von der NetApp -Support-Website heruntergeladen wurden unter http://mysupport.netapp.com/["mysupport.netapp.com"^] Die  Alle Cisco Cluster-Netzwerk- und Management-Netzwerk-Switches werden mit der standardmäßigen Cisco -Werkskonfiguration ausgeliefert. Diese Switches verfügen ebenfalls über die aktuelle Version der NX-OS-Software, haben jedoch die RCFs nicht geladen.
* Erforderliche Schalterdokumentation. Sehenlink:required-documentation-9336c-storage.html["Erforderliche Dokumentation"] für weitere Informationen.


.Schritte
. Installieren Sie die Cluster-Netzwerk- und Management-Netzwerk-Switches und -Controller.
+
[cols="1,2"]
|===
| Wenn Sie Ihr... installieren | Dann... 


 a| 
Cisco Nexus 9336C-FX2 in einem NetApp -Systemschrank
 a| 
Sehenlink:install-switch-and-passthrough-panel-9336c-storage.html["Switch im NetApp Schrank installieren"] Anweisungen zur Installation des Switches in einem NetApp -Schrank finden Sie hier.



 a| 
Ausrüstung in einem Telekommunikationsrack
 a| 
Beachten Sie die in den Hardware-Installationshandbüchern für Switches und den Installations- und Einrichtungsanweisungen von NetApp beschriebenen Vorgehensweisen.

|===
. Verbinden Sie die Cluster-Netzwerk- und Management-Netzwerk-Switches mithilfe der ausgefüllten Verkabelungsarbeitsblätter mit den Controllern.
. Schalten Sie die Cluster-Netzwerk- und Management-Netzwerk-Switches und -Controller ein.


.Wie geht es weiter?
Optional können Sie link:install-switch-and-passthrough-panel-9336c-storage.html["Installieren Sie einen Cisco Nexus 9336C-FX2 Switch in einem NetApp Schrank"]Die Ansonsten gehen Sie zu link:setup-switch-9336c-storage.html["Konfigurieren Sie den Switch"]Die
