---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: Sie können die RCF-Datei installieren, nachdem Sie den Switch Nexus 9336C-FX2 zum ersten Mal eingerichtet haben. Sie können dieses Verfahren auch verwenden, um Ihre RCF-Version zu aktualisieren. 
---
= Übersicht zur Installation oder Aktualisierung der Referenzkonfigurationsdatei (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Referenzkonfigurationsdatei (RCF) wird nach der erstmaligen Einrichtung des Speicherswitches Nexus 9336C-FX2 installiert. Sie aktualisieren Ihre RCF-Version, wenn auf Ihrem Switch eine vorhandene Version der RCF-Datei installiert ist.

Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Wie man die Konfiguration eines Cisco Interconnect-Switches löscht und gleichzeitig die Remote-Konnektivität beibehält"^] Weitere Informationen zur Installation oder Aufrüstung Ihres RCF erhalten Sie bei Bedarf.

.Verfügbare RCF-Konfiguration
Storage - (Storage RCF 1._xx_) ist die verfügbare RCF-Konfiguration, bei der alle Ports für 100GbE NVMe storage connections konfiguriert sind.

.Empfohlene Dokumentation
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^]
+
Auf der NetApp Support-Website finden Sie die Tabelle zur Switch-Kompatibilität, in der die unterstützten ONTAP und RCF-Versionen aufgeführt sind.  Beachten Sie, dass zwischen der Befehlssyntax in der RCF und der Syntax in bestimmten Versionen von NX-OS Befehlsabhängigkeiten bestehen können.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 Series Switches"^]
+
Die vollständige Dokumentation zu den Upgrade- und Downgrade-Verfahren für Cisco -Switches finden Sie in den entsprechenden Software- und Upgrade-Leitfäden auf der Cisco -Website.



.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Namen der beiden Cisco Switches sind s1 und s2.
* Die Knotennamen lauten cluster1-01 und cluster1-02.


Siehe die https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] um die korrekten Ports auf Ihrer Plattform zu überprüfen.


NOTE: Die Befehlsausgaben können je nach ONTAP Version variieren.

.verwendete Befehle
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 9000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

.Wie geht es weiter?
Nachdem Sie die Installations- oder Aktualisierungsprozedur für RCF durchgelesen haben, können Sielink:install-rcf-software-9336c-storage.html["Installieren Sie den RCF"] oderlink:upgrade-rcf-software-9336c-storage.html["Aktualisieren Sie Ihren RCF"] nach Bedarf.
