---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: 'Die Cisco NX-OS Software und die Referenzkonfigurationsdateien (RCFs) müssen auf den Cisco Nexus 9336C-FX2 Cluster-Switches installiert sein.' 
---
= Bereiten Sie die Installation oder Aktualisierung der NX-OS-Software und RCF vor.
:allow-uri-read: 


[role="lead"]
Bevor Sie die NX-OS-Software und die Referenzkonfigurationsdatei (RCF) installieren, befolgen Sie bitte diese Schritte.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Namen der beiden Cisco Switches sind s1 und s2.
* Die Knotennamen lauten cluster1-01 und cluster1-02.


.Informationen zu diesem Vorgang
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 9000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Fallerstellung, indem Sie eine AutoSupport-Nachricht auslösen: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
wobei x die Dauer des Wartungsfensters in Stunden ist.

+

NOTE: Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie *y* eingeben, wenn Sie zur Fortsetzung aufgefordert werden:
+
[source, cli]
----
set -privilege advanced
----
+
Die erweiterte Aufforderung(`*>` ) erscheint.

. Zeigen Sie an, wie viele Schnittstellen in jedem Node für jeden Netzwerk-Switch konfiguriert sind:
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e5a    s1                        Eth1/2            N9K-C9336C
            e3b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e5a    s1                        Eth1/1            N9K-C9336C
            e3b    s2                        Eth1/1            N9K-C9336C
.
.
----
====
. Prüfen Sie den administrativen oder betrieblichen Status jedes Node-Speicherports und Speicherregalports.
+
.. Zeigen Sie die Attribute des Knotenspeicherports an:
+
[source, cli]
----
storage port show
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -

.
.
----
====
.. Zeigen Sie die Attribute der Storage-Shelf-Ports an:
+
[source, cli]
----
storage shelf port show
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Vergewissern Sie sich, dass die Switch-Zustandsüberwachung (CSHM) für den Switch aktiviert ist, damit die Switches überwacht werden:
+
[source, cli]
----
system switch ethernet show
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.Wie geht es weiter?
Nachdem Sie die Installation der NX-OS-Software und von RCF vorbereitet haben, können Sie link:install-nxos-software-9336c-storage.html["Installieren oder aktualisieren Sie die NX-OS-Software"]Die
