---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'Der Austausch eines defekten Nexus 9336C-FX2 Switches in einem Cluster-Netzwerk ist ein unterbrechungsfreies Verfahren \ (NDU\).' 
---
= Ersetzen Sie einen Cisco Nexus 9336C-FX2 Storage-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen defekten Nexus 9336C-FX2-Switch in einem Cluster-Netzwerk ersetzen. Hierbei handelt es sich um ein unterbrechungsfreies Verfahren.

.Bevor Sie beginnen
Stellen Sie vor der Installation der NX-OS-Software und der RCFs auf einem Cisco Nexus 9336C-FX2-Storage-Switch sicher, dass:

* Ihr System kann Cisco Nexus 9336C-FX2 Storage Switches unterstützen.
* Sie haben sich auf der Seite Cisco Ethernet Switch die Switch-Kompatibilitätstabelle für die unterstützten ONTAP-, NX-OS- und RCF-Versionen angehört.
* Sie haben die entsprechenden Leitfäden zu Software und Upgrades auf der Cisco Website zur Verfügung gestellt.


Switches Der Cisco Nexus 3000-Serie:

* Sie haben die entsprechenden RCFs heruntergeladen.
* Die vorhandene Netzwerkkonfiguration weist folgende Merkmale auf:
+
** Auf der Seite Cisco Ethernet Switches befinden sich die neuesten RCF- und NX-OS-Versionen auf Ihren Switches.
** Management-Konnektivität muss auf beiden Switches vorhanden sein.


* Der Cisco Nexus 9336C-FX2-Ersatzschalter weist folgende Merkmale auf:
+
** Die Management-Netzwerk-Konnektivität ist funktionsfähig.
** Der Konsolenzugriff auf den Ersatz-Switch erfolgt.
** Das entsprechende RCF- und NX-OS-Betriebssystemabbild wird auf den Switch geladen.
** Die anfängliche Konfiguration des Schalters ist abgeschlossen.




.Über diese Aufgabe
Dieses Verfahren ersetzt den zweiten Nexus 9336C-FX2 Storage Switch S2 durch den neuen 9336C-FX Switch NS2. Die beiden Knoten sind node1 und node2.

Schritte zur Fertigstellung:

* Vergewissern Sie sich, dass der zu ersetzende Schalter S2 ist.
* Trennen Sie die Kabel vom Schalter S2.
* Schließen Sie die Kabel wieder an den Schalter NS2 an.
* Überprüfen Sie alle Gerätekonfigurationen auf Switch NS2.
+

NOTE: Es können Abhängigkeiten zwischen der Befehlssyntax für in der RCF- und NX-OS-Version bestehen.



.Schritte
. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_X_ ist die Dauer des Wartungsfensters in Stunden.

. Überprüfen Sie den Integritätsstatus der Storage-Node-Ports, um sicherzustellen, dass eine Verbindung zum Storage-Switch S1 besteht:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. Stellen Sie sicher, dass der Speicherschalter S1 verfügbar ist:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. Führen Sie die Show aus `lldp neighbors` Mit dem Befehl auf dem Arbeitsschalter bestätigen Sie, dass Sie beide Nodes und alle Shelfs sehen können:
+
`show lldp neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Überprüfen Sie die Shelf-Ports im Storage-System:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. Entfernen Sie alle Kabel, die am Lagerschalter S2 angeschlossen sind.
. Schließen Sie alle Kabel wieder an den Ersatzschalter NS2 an.
. Überprüfen Sie den Integritätsstatus der Speicher-Node-Ports erneut:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. Vergewissern Sie sich, dass beide Switches verfügbar sind:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. Überprüfen Sie die Shelf-Ports im Storage-System:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie es erneut, indem Sie eine AutoSupport Meldung aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Was kommt als Nächstes?
link:../switch-cshm/config-overview.html["Konfigurieren Sie die Überwachung des Switch-Systemzustands"].
