---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'Der Austausch eines defekten Nexus 9336C-FX2-Switches in einem Clusternetzwerk ist ein nicht-unterbrechendes Verfahren (NDU).' 
---
= Ersetzen Sie die Speicher-Switches Cisco Nexus 9336C-FX2 und 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können defekte Nexus 9336C-FX2- und 9336C-FX2-T-Switches in einem Clusternetzwerk ersetzen. Dies ist ein unterbrechungsfreies Verfahren.

.Bevor Sie beginnen
Stellen Sie vor der Installation der NX-OS-Software und RCFs auf den Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Speicher-Switches Folgendes sicher:

* Ihr System kann die Speicher-Switches Cisco Nexus 9336C-FX2 und 9336C-FX2-T unterstützen.
* Sie haben die Switch-Kompatibilitätstabelle auf der Cisco Ethernet Switch-Seite konsultiert, um die unterstützten ONTAP, NX-OS- und RCF-Versionen zu ermitteln.
* Sie haben die entsprechenden Software- und Upgrade-Anleitungen auf der Cisco -Website konsultiert.
* Sie haben die entsprechenden RCFs heruntergeladen.
* Die bestehende Netzwerkkonfiguration weist folgende Merkmale auf:
+
** Auf der Cisco Ethernet Switches-Seite finden Sie die neuesten RCF- und NX-OS-Versionen für Ihre Switches.
** Die Management-Konnektivität muss auf beiden Switches vorhanden sein.


* Der Ersatz-Switch Cisco Nexus 9336C-FX2 weist folgende Merkmale auf:
+
** Die Managementnetzwerkanbindung ist funktionsfähig.
** Der Konsolenzugriff auf den Ersatzschalter ist eingerichtet.
** Das entsprechende RCF- und NX-OS-Betriebssystemabbild wird auf den Switch geladen.
** Die Erstkonfiguration des Switch ist abgeschlossen.




.Informationen zu diesem Vorgang
Bei diesem Verfahren wird der zweite Nexus 9336C-FX2 Speicherswitch s2 durch den neuen 9336C-FX Switch ns2 ersetzt. Die beiden Knoten sind cluster1-01 und cluster1-02.

Zu erledigende Schritte:

* Bestätigen Sie, dass der auszutauschende Switch S2 ist.
* Trennen Sie die Kabel vom Switch s2.
* Schließen Sie die Kabel wieder an den Switch ns2 an.
* Überprüfen Sie alle Gerätekonfigurationen auf Switch ns2.
+

NOTE: Zwischen der Befehlssyntax in den RCF- und NX-OS-Versionen können Abhängigkeiten bestehen.



.Schritte
. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ ist die Dauer des Wartungsfensters in Stunden.

. Überprüfen Sie den Gesundheitszustand der Speicherknoten-Ports, um sicherzustellen, dass eine Verbindung zum Storage Switch s1 besteht:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Überprüfen Sie, ob der Storage-Switch s1 verfügbar ist:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. Leite die Show `lldp neighbors` Führen Sie einen Befehl auf dem funktionierenden Switch aus, um zu bestätigen, dass Sie beide Knoten und alle Regale sehen können:
+
`show lldp neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Überprüfen Sie die Storage-Shelf-Ports im Storage-System:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. Entfernen Sie alle an den Storage Switch s2 angeschlossenen Kabel.
. Schließen Sie alle Kabel wieder an den Ersatz-Netzwerk-Switch ns2 an.
. Überprüfen Sie erneut den Gesundheitszustand der Speicherknotenports:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Vergewissern Sie sich, dass beide Schalter verfügbar sind:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. Überprüfen Sie die Regalanschlüsse im Lagersystem:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Wie geht es weiter?
Nachdem Sie Ihre Schalter ausgetauscht haben, können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
