---
permalink: switch-cisco-9336c-fx2-storage/upgrade-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Mit diesem Verfahren können Sie Ihre RCF-Version aktualisieren. 
---
= Aktualisieren Sie Ihre Referenzkonfigurationsdatei (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie aktualisieren Ihre RCF-Version, wenn auf Ihren betriebsbereiten Switches bereits eine Version der RCF-Datei installiert ist.

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Eine aktuelle Sicherungskopie der Switch-Konfiguration.
* Ein voll funktionsfähiger Cluster (keine Fehler in den Protokollen oder ähnliche Probleme).
* Der aktuelle RCF.
* Wenn Sie Ihre RCF-Version aktualisieren, benötigen Sie eine Boot-Konfiguration in der RCF, die die gewünschten Boot-Images widerspiegelt.
+
Wenn Sie die Bootkonfiguration ändern müssen, um die aktuellen Boot-Images widerzuspiegeln, müssen Sie dies tun, bevor Sie die RCF erneut anwenden, damit bei zukünftigen Neustarts die richtige Version instanziiert wird.




NOTE: Während dieses Vorgangs ist kein betriebsbereiter Inter-Switch-Link (ISL) erforderlich. Dies ist beabsichtigt, da RCF-Versionsänderungen die ISL-Konnektivität vorübergehend beeinträchtigen können. Um einen unterbrechungsfreien Clusterbetrieb zu gewährleisten, migriert das folgende Verfahren alle Cluster-LIFs zum operativen Partner-Switch, während die Schritte auf dem Ziel-Switch ausgeführt werden.


CAUTION: Vor der Installation einer neuen Switch-Softwareversion und neuer RCFs müssen Sie die Switch-Einstellungen löschen und eine Basiskonfiguration durchführen.  Sie müssen über die serielle Konsole mit dem Switch verbunden sein oder grundlegende Konfigurationsinformationen gesichert haben, bevor Sie die Switch-Einstellungen löschen.



== Schritt 1: Vorbereitung auf das Upgrade

. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Wobei _x_ die Dauer des Wartungsfensters in Stunden angibt.

. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie *y* eingeben, wenn Sie zur Fortsetzung aufgefordert werden:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Zeigen Sie die Ports auf jedem Knoten an, die mit den Switches verbunden sind:
+
[source, cli]
----
network device-discovery show
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
node1-01/cdp
            e3a    cs1                       Ethernet1/7     N9K-C9336C
            e3b    cs2                       Ethernet1/7     N9K-C9336C
node1-02/cdp
            e3a    cs1                       Ethernet1/8     N9K-C9336C
            e3b    cs2                       Ethernet1/8     N9K-C9336C
.
.
.
----
====
. Überprüfen Sie, ob alle Speicherports aktiv sind und einen fehlerfreien Status aufweisen:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
node1-02
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
.
.
.
----
====
. Automatische Wiederherstellung der Cluster-LIFs deaktivieren.
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





== Schritt 2: Ports konfigurieren

. Fahren Sie auf Switch CS1 die Ports herunter, die mit allen Ports der Knoten verbunden sind.
+
[listing, subs="+quotes"]
----
cs1> *enable*
cs1# *configure*
cs1(config)# *interface eth1/1/1-2,eth1/7-8*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: Stellen Sie sicher, dass Sie *alle* verbundenen Ports herunterfahren, um Probleme mit der Netzwerkverbindung zu vermeiden. Siehe den Artikel in der Wissensdatenbank. https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Knoten außerhalb des Quorums bei Migration des Cluster-LIF während des Switch-OS-Upgrades"^] für weitere Einzelheiten.

. Überprüfen Sie, ob für die Cluster-LIFs ein Failover auf die auf Switch cs1 gehosteten Ports durchgeführt wurde. Dies kann einige Sekunden dauern.
+
[source, cli]
----
network interface show -role cluster
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e7b     true

8 entries were displayed.
----
====
. Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false

4 entries were displayed.
----
====
. Falls Sie dies noch nicht getan haben, speichern Sie eine Kopie der aktuellen Switch-Konfiguration, indem Sie die Ausgabe des folgenden Befehls in eine Textdatei kopieren:
+
`show running-config`

+
.. Alle benutzerdefinierten Ergänzungen zwischen dem aktuellen `running-config` und die verwendete RCF-Datei (z. B. eine SNMP-Konfiguration für Ihre Organisation).
.. Für NX-OS 10.2 und höher verwenden Sie die `show diff running-config` Befehl zum Vergleich mit der gespeicherten RCF-Datei im Bootflash. Alternativ können Sie ein Vergleichstool eines Drittanbieters verwenden.


. Speichern Sie die grundlegenden Konfigurationsdetails in der `write_erase.cfg` Datei auf dem Bootflash.
+
[NOTE]
====
Stellen Sie sicher, dass Sie Folgendes konfigurieren:

** Benutzername und Passwort
** Verwaltungs-IP-Adresse
** Standardgateway
** Schaltername


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

. Beim Upgrade auf RCF Version 1.12 und höher führen Sie die folgenden Befehle aus:
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1280 >> bootflash:write_erase.cfg`

+
Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Wie man die Konfiguration eines Cisco Interconnect-Switches löscht und gleichzeitig die Remote-Konnektivität beibehält"^] für weitere Einzelheiten.

. Überprüfen Sie, ob die `write_erase.cfg` Die Datei ist wie erwartet gefüllt:
+
`*show file bootflash:write_erase.cfg*`

. Stellen Sie die `write erase` Befehl zum Löschen der aktuell gespeicherten Konfiguration:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Kopieren Sie die zuvor gespeicherte Basiskonfiguration in die Startkonfiguration.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Starten Sie den Switch neu:
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Sobald die Management-IP-Adresse wieder erreichbar ist, melden Sie sich über SSH am Switch an.
+
Möglicherweise müssen Sie die Einträge in der Host-Datei aktualisieren, die mit den SSH-Schlüsseln zusammenhängen.

. Kopieren Sie die RCF mit einem der folgenden Übertragungsprotokolle in den Bootflash des Switches cs1: FTP, TFTP, SFTP oder SCP.
+
Weitere Informationen zu Cisco -Befehlen finden Sie im entsprechenden Handbuch im https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 Serie NX-OS Befehlsreferenz"^] Führer.

+
.Beispiel anzeigen
[%collapsible]
====
Dieses Beispiel zeigt, wie TFTP verwendet wird, um eine RCF-Datei in den Bootflash des Switches cs1 zu kopieren:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_9336C_RCF_v1.6-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Wenden Sie die zuvor heruntergeladene RCF-Datei auf den Bootflash an.
+
Weitere Informationen zu Cisco -Befehlen finden Sie im entsprechenden Handbuch im https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 Serie NX-OS Befehlsreferenz"^] Führer.

+
Dieses Beispiel zeigt die RCF-Datei. `NX9336C-FX2-RCF-v1.13-1-Storage.txt` wird auf Switch CS1 installiert:

+
[listing, subs="+quotes"]
----
cs1# *copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
Lesen Sie die Abschnitte *Installationshinweise*, *Wichtige Hinweise* und *Banner* Ihres RCF gründlich durch. Sie müssen diese Anweisungen lesen und befolgen, um die ordnungsgemäße Konfiguration und den ordnungsgemäßen Betrieb des Switches sicherzustellen.

====
. Überprüfen Sie, ob es sich bei der RCF-Datei um die korrekte, neuere Version handelt:
+
`show running-config`

+
Wenn Sie die Ausgabe überprüfen, um sicherzustellen, dass Sie die richtige RCF-Datei haben, achten Sie darauf, dass die folgenden Informationen korrekt sind:

+
** Das RCF-Banner
** Die Knoten- und Porteinstellungen
** Anpassungen
+
Das Ergebnis variiert je nach Ihrer Website-Konfiguration.  Prüfen Sie die Port-Einstellungen und beachten Sie die Versionshinweise, um sich über etwaige Änderungen zu informieren, die speziell für die von Ihnen installierte RCF-Version gelten.



. Wenden Sie alle zuvor vorgenommenen Anpassungen auf die Switch-Konfiguration erneut an.
. Nachdem Sie überprüft haben, ob die RCF-Versionen, die benutzerdefinierten Erweiterungen und die Schaltereinstellungen korrekt sind, kopieren Sie die `running-config` Datei an die `startup-config` Datei.
+
Weitere Informationen zu Cisco -Befehlen finden Sie im entsprechenden Handbuch im https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 Serie NX-OS Befehlsreferenz"^] Führer.

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Neustart des Switches cs1.  Sie können die Warnungen „`cluster switch health monitor`“ und die Ereignisse „`cluster ports down`“, die auf den Knoten während des Neustarts des Switches gemeldet werden, ignorieren.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Überprüfen Sie, ob alle Speicherports aktiv sind und einen fehlerfreien Status aufweisen:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
node1-02
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
.
.
.
----
====
. Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. Wiederholen Sie die Schritte 4 bis 19 auf Switch cs2.
. Automatische Wiederherstellung der Cluster-LIFs aktivieren.
+
`network interface modify -vserver Cluster -lif * -auto-revert true`





== Schritt 3: Überprüfen Sie die Clusternetzwerkkonfiguration und den Clusterzustand.

. Überprüfen Sie, ob die mit den Cluster-Ports verbundenen Switch-Ports *aktiv* sind.
+
[source, cli]
----
show interface brief
----
. Überprüfen Sie, ob die erwarteten Knoten noch verbunden sind:
+
[source, cli]
----
show cdp neighbors
----
. Überprüfen Sie mithilfe der folgenden Befehle, ob sich die Clusterknoten in den richtigen Cluster-VLANs befinden:
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
. Überprüfen Sie, ob die Cluster-LIFs wieder auf ihren Heimatport zurückgekehrt sind:
+
[source, cli]
----
network interface show -role cluster
----
+
Falls Cluster-LIFs nicht zu ihren Heimatports zurückgekehrt sind, setzen Sie sie manuell vom lokalen Knoten aus zurück:

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
[source, cli]
----
cluster show
----
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:
+
.. Sie können die `network interface check cluster-connectivity show` Befehl zum Anzeigen der Details einer Zugriffsprüfung für die Clusterkonnektivität:
+
[source, cli]
----
network interface check cluster-connectivity show
----
.. Alternativ können Sie die `cluster ping-cluster -node <node-name>` Befehl zum Überprüfen der Verbindung:
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----




.Wie geht es weiter?
Nach dem Upgrade Ihres RCF können Sielink:configure-ssh-keys.html["Überprüfen Sie die SSH-Konfiguration"] Die
