---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/components-9336c-shared.html 
keywords: shared storage cluster switch 
summary: Ab ONTAP 9.9.1 können Sie Cisco Nexus 9336C-FX2 Switches verwenden, um Speicher- und Clusterfunktionen in einem gemeinsam genutzten Switch-Szenario zu kombinieren. 
---
= Komponenten und Teilenummern für Cisco Nexus 9336C-FX2 Shared Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung des Cisco Nexus 9336C-FX2 Switches sollten Sie unbedingt die Liste der Komponenten und Teilenummern überprüfen.

Die folgende Tabelle listet die Teilenummer und Beschreibung für den Schalter 9336C-FX2, die Lüfter und die Netzteile auf:

|===
| Teilenummer | Beschreibung 


| X190200-CS-PE | N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28 


| X190200-CS-PI | N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28 


| X190002 | Zubehörset X190001/X190003 


| X-NXA-PAC-1100W-PE2 | N9K-9336C AC 1100W Netzteil - Abluftführung an der linken Seite 


| X-NXA-PAC-1100W-PI2 | N9K-9336C AC 1100W Netzteil - Lufteinlass an der linken Seite 


| X-NXA-FAN-65CFM-PE | N9K-9336C 65 CFM, Abluftstrom an der Backbordseite 


| X-NXA-FAN-65CFM-PI | N9K-9336C 65 CFM, Einlassluftstrom auf der Backbordseite 
|===
.Was kommt als nächstes
Nachdem Sie Ihre Komponenten und Teilenummern bestätigt haben, können Sie die folgenden überprüfen: link:required-documentation-9336c-shared.html["erforderliche Dokumentation"]Die
