---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/configure-reqs-9336c-shared.html 
keywords: shared storage cluster switch 
summary: Ab ONTAP 9.9.1 können Sie Cisco Nexus 9336C-FX2 Switches verwenden, um Speicher- und Clusterfunktionen in einem gemeinsam genutzten Switch-Szenario zu kombinieren. 
---
= Konfigurationsanforderungen für Cisco Nexus 9336C-FX2 Shared Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei der Installation und Wartung des Cisco Nexus 9336C-FX2 Switches sollten Sie unbedingt die Konfigurations- und Netzwerkanforderungen überprüfen.



== ONTAP-Unterstützung

Ab ONTAP 9.9.1 können Sie Cisco Nexus 9336C-FX2 Switches verwenden, um Speicher- und Clusterfunktionen in einer gemeinsamen Switch-Konfiguration zu kombinieren.

Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Netzwerk-Switches.



== Konfigurationsanforderungen

Für die Konfiguration benötigen Sie die entsprechende Anzahl und Art von Kabeln und Kabelverbindern für Ihre Switches.

Je nach Art des Switches, den Sie initial konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Konsolenport des Switches herstellen; außerdem müssen Sie spezifische Netzwerkinformationen angeben.



== Netzwerkanforderungen

Für alle Switch-Konfigurationen benötigen Sie folgende Netzwerkinformationen.

* IP-Subnetz für den Verwaltungsnetzwerkverkehr
* Hostnamen und IP-Adressen für jeden Speichersystem-Controller und alle entsprechenden Switches
* Die meisten Speichersystem-Controller werden über die e0M-Schnittstelle verwaltet, indem eine Verbindung zum Ethernet-Service-Port (Schraubenschlüsselsymbol) hergestellt wird. Bei den Systemen AFF A800 und AFF A700s verwendet die e0M-Schnittstelle einen dedizierten Ethernet-Anschluss.
* Siehe die https://hwu.netapp.com["Hardware Universe"] für die aktuellsten Informationen.


Weitere Informationen zur Erstkonfiguration Ihres Switches finden Sie in der folgenden Anleitung: https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2 Installations- und Upgrade-Leitfaden"] Die

.Was kommt als nächstes
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie Ihre link:components-9336c-shared.html["Komponenten und Teilenummern"]Die
