---
permalink: switch-cisco-9336c-fx2-shared/configure-switch-overview-9336c-shared.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Überblick über Installation und Konfiguration für gemeinsame Cisco Nexus 9336C-FX2-Switches 
---
= Überblick über Installation und Konfiguration für gemeinsame Cisco Nexus 9336C-FX2-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der gemeinsame Switch der Cisco Nexus 9336C-FX2 ist Teil der Cisco Nexus 9000 Plattform und kann in einem NetApp Systemschrank installiert werden. Gemeinsam genutzte Switches ermöglichen es Ihnen, Cluster- und Storage-Funktionen in einer gemeinsamen Switch-Konfiguration zu kombinieren, indem Sie gemeinsam genutzte Cluster- und Speicherreferenzkonfigurationsdateien unterstützen.



== Überblick über die Erstkonfiguration

Gehen Sie wie folgt vor, um einen Cisco Nexus 9336C-FX2 Switch auf Systemen mit ONTAP zu konfigurieren:

. link:cable-9336c-shared.html["Füllen Sie das Verkabelungsarbeitsblatt aus"].
+
Verwenden Sie die Verkabelungsabbilder, um die Verkabelung zwischen den Controllern und den Switches abzuschließen.

. link:install-9336c-shared.html["Den Schalter einbauen"].
. link:setup-and-configure-9336c-shared.html["Konfigurieren Sie den Switch"].
. link:install-switch-and-passthrough-panel-9336c-shared.html["Switch in NetApp-Schrank einbauen"].
+
Je nach Konfiguration können Sie den Cisco Nexus 9336C-FX2 Switch und die Pass-Through-Panel in einem NetApp Rack mit den im Lieferumfang des Switches enthaltenen Standardhalterungen installieren.

. link:prepare-nxos-rcf-9336c-shared.html["Bereiten Sie sich auf die Installation von NX-OS und RCF vor"].
. link:install-nxos-software-9336c-shared.html["Installieren Sie die NX-OS-Software"].
. link:install-nxos-rcf-9336c-shared.html["Installieren Sie die RCF-Konfigurationsdatei"].
+
Installieren Sie den RCF, nachdem Sie den Nexus 9336C-FX2-Schalter zum ersten Mal eingerichtet haben. Sie können dieses Verfahren auch verwenden, um Ihre RCF-Version zu aktualisieren.





== Weitere Informationen

Bevor Sie mit der Installation oder Wartung beginnen, überprüfen Sie bitte die folgenden Punkte:

* link:configure-reqs-9336c-shared.html["Konfigurationsanforderungen"]
* link:components-9336c-shared.html["Komponenten und Teilenummern"]
* link:required-documentation-9336c-shared.html["Erforderliche Dokumentation"]

