---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Installieren Sie gemeinsam genutzte Cisco Nexus 9336C-FX2 Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Anweisungen, um gemeinsam genutzte Cisco Nexus 9336C-FX2-Switches zu konfigurieren.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie Folgendes haben:

* Erforderliche Dokumentation für gemeinsamen Switch, Controller-Dokumentation und ONTAP-Dokumentation Siehe link:required-documentation-9336c-shared.html["Dokumentationsanforderungen für Cisco Nexus 9336C-FX2 Shared-Switches"] Und https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP-Dokumentation"^].
* Anwendbare Lizenzen, Netzwerk- und Konfigurationsinformationen und Kabel
* Abgeschlossene Verkabelungsarbeitsblätter. Siehe link:cable-9336c-shared.html["Füllen Sie das Cisco Nexus 9336C-FX2-Verkabelungsarbeitsblatt aus"]. Weitere Informationen zur Verkabelung finden Sie im https://hwu.netapp.com["Hardware Universe"].


.Schritte
. Racks für Switches, Controller und NS224 NVMe Storage-Shelfs
+
Im link:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Anweisungen zum Rack"]erfahren Sie, wie Sie den Switch in einem NetApp-Schrank einmontieren.

. Schalten Sie die Switches, Controller und NS224 NVMe Storage-Shelfs ein.


.Was kommt als Nächstes?
Optional können Sielink:install-switch-and-passthrough-panel-9336c-shared.html["Installation eines Cisco Nexus 9336C-FX2 Switch in einem NetApp Rack"] .  Andernfalls gehen Sie zulink:setup-and-configure-9336c-shared.html["Konfigurieren Sie den Switch"] .
