---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Installieren Sie gemeinsam genutzte Cisco Nexus 9336C-FX2-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Anweisungen, um Cisco Nexus 9336C-FX2 Shared Switches zu konfigurieren.

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Erforderliche Dokumentation für gemeinsam genutzte Switches, Controller und ONTAP .  Sehenlink:required-documentation-9336c-shared.html["Dokumentationsanforderungen für Cisco Nexus 9336C-FX2 Shared Switches"] Und https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP-Dokumentation"^] Die
* Anwendbare Lizenzen, Netzwerk- und Konfigurationsinformationen sowie Kabel.
* Ausgefüllte Verkabelungs-Arbeitsblätter. Sehenlink:cable-9336c-shared.html["Füllen Sie das Verkabelungsarbeitsblatt für den Cisco Nexus 9336C-FX2 aus."] .  Weitere Informationen zur Verkabelung finden Sie unter https://hwu.netapp.com["Hardware Universe"] Die


.Schritte
. Die Switches, Controller und NS224 NVMe-Speichergehäuse werden in ein Rack eingebaut.
+
Siehe dielink:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Regaleinbauanleitung"] um zu lernen, wie man den Switch in einem NetApp -Schrank montiert.

. Schalten Sie die Switches, Controller und NS224 NVMe-Speichergehäuse ein.


.Wie geht es weiter?
Optional können Sie link:install-switch-and-passthrough-panel-9336c-shared.html["Installieren Sie einen Cisco Nexus 9336C-FX2 Switch in einem NetApp Schrank"]Die Ansonsten gehen Sie zu link:setup-and-configure-9336c-shared.html["Konfigurieren Sie den Schalter"]Die
