---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= Migration von einem schalterlosen Cluster mit direkt angeschlossenem Speicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können von einem switchlosen Cluster mit direkt angeschlossenem Speicher migrieren, indem Sie zwei neue gemeinsam genutzte Switches hinzufügen.

Die Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerkanschlüsse oder an jedem Controller einen einzelnen Clusteranschluss haben.  Der dokumentierte Prozess funktioniert für alle Knoten, die optische oder Twinax-Anschlüsse verwenden, wird jedoch auf diesem Switch nicht unterstützt, wenn die Knoten Onboard-10Gb BASE-T RJ45-Anschlüsse für die Cluster-Netzwerkanschlüsse verwenden.

Die meisten Systeme benötigen zwei dedizierte Cluster-Netzwerkanschlüsse an jedem Controller. Sehen https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"] für weitere Informationen.

Wenn Sie bereits eine switchlose Clusterumgebung mit zwei Knoten besitzen, können Sie mithilfe von Cisco Nexus 9336C-FX2 Switches zu einer switchierten Clusterumgebung mit zwei Knoten migrieren, um die Anzahl der Knoten im Cluster auf über zwei zu erhöhen.



== Überprüfungsanforderungen

Stellen Sie sicher, dass:

* Für die schalterlose Zwei-Knoten-Konfiguration:
+
** Die Zwei-Knoten-Konfiguration ohne Schalter ist ordnungsgemäß eingerichtet und funktioniert.
** Auf den Knoten läuft ONTAP 9.8 oder höher.
** Alle Cluster-Ports befinden sich im Status *up*.
** Alle logischen Schnittstellen (LIFs) des Clusters befinden sich im Zustand *up* und sind an ihren *home*-Ports angeschlossen.


* Für die Konfiguration des Cisco Nexus 9336C-FX2 Switches:
+
** Beide Switches verfügen über eine Management-Netzwerkanbindung.
** Es besteht Konsolenzugriff auf die Cluster-Switches.
** Knoten-zu-Knoten-Switch- und Switch-zu-Switch-Verbindungen des Nexus 9336C-FX2 verwenden Twinax- oder Glasfaserkabel.
** NetApp https://hwu.netapp.com["Hardware Universe"] enthält weitere Informationen zur Verkabelung.
** Inter-Switch Link (ISL)-Kabel sind an die Ports 1/35 und 1/36 beider 9336C-FX2-Switches angeschlossen.


* Die erste Anpassung der 9336C-FX2-Schalter ist abgeschlossen.  Damit die:
+
** Die Switches vom Typ 9336C-FX2 verwenden die neueste Softwareversion.
** Referenzkonfigurationsdateien (RCFs) wurden auf die Schalter angewendet.
** Sämtliche Standortanpassungen, wie z. B. SMTP, SNMP und SSH, werden auf den neuen Switches konfiguriert.






== Migrieren Sie die Schalter

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Cluster-Switch- und Knotennomenklatur:

* Die Namen der 9336C-FX2-Schalter lauten _cs1_ und _cs2_.
* Die Namen der Cluster-SVMs lauten _node1_ und _node2_.
* Die Namen der LIFs lauten _node1_clus1_ und _node1_clus2_ auf Knoten 1 bzw. _node2_clus1_ und _node2_clus2_ auf Knoten 2.
* Die Eingabeaufforderung cluster1::*> zeigt den Namen des Clusters an.
* Die in diesem Verfahren verwendeten Cluster-Ports sind _e3a_ und _e3b_, gemäß dem AFF A400 -Controller.  Der https://hwu.netapp.com["Hardware Universe"] Enthält die aktuellsten Informationen zu den tatsächlichen Cluster-Ports für Ihre Plattformen.




=== Schritt 1: Migration von einem schalterlosen Cluster mit direkt angeschlossenen

. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht: `system node autosupport invoke -node * -type all -message MAINT=xh` Die
+
wobei x die Dauer des Wartungsfensters in Stunden ist.




NOTE: Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

. [[step2]]Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie bei Aufforderung „y“ eingeben:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Deaktivieren Sie alle zum Knoten führenden Ports (nicht die ISL-Ports) an den beiden neuen Cluster-Switches cs1 und cs2.  Die ISL-Ports dürfen nicht deaktiviert werden.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die dem Knoten zugewandten Ports 1 bis 34 am Switch cs1 deaktiviert sind:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]]Überprüfen Sie, ob die ISL und die physischen Ports der ISL zwischen den beiden 9336C-FX2 Switches cs1 und cs2 an den Ports 1/35 und 1/36 aktiv sind:
+
`show port-channel summary`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die ISL-Ports am Switch cs1 aktiv sind:

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
Das folgende Beispiel zeigt, dass die ISL-Ports am Switch cs2 aktiv sind:

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]]Zeige die Liste der benachbarten Geräte an:
+
`show cdp neighbors`

+
Dieser Befehl liefert Informationen über die mit dem System verbundenen Geräte.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel listet die benachbarten Geräte am Switch cs1 auf:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
Das folgende Beispiel listet die benachbarten Geräte am Switch cs2 auf:

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[Schritt 6]]Überprüfen Sie, ob alle Cluster-Ports aktiv sind:
+
`network port show - ipspace Cluster`

+
Jeder Port sollte bei „Verbindung“ als aktiv und bei „Gesundheitsstatus“ als fehlerfrei angezeigt werden.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[Schritt 7]]Überprüfen Sie, ob alle Cluster-LIFs aktiv und betriebsbereit sind:
+
`network interface show - vserver Cluster`

+
Jeder Cluster-LIF sollte „true“ anzeigen für `Is Home` und den Status Admin/Oper von up/up haben.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[Schritt 8]]Überprüfen Sie, ob die automatische Rücksetzung auf allen Cluster-LIFs aktiviert ist:
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]Trennen Sie das Kabel vom Cluster-Port e3a auf Knoten 1 und verbinden Sie dann e3a mit Port 1 auf dem Cluster-Switch cs1. Verwenden Sie dazu die von den 9336C-FX2-Switches unterstützten geeigneten Kabel.
+
NetApp https://hwu.netapp.com["Hardware Universe"] enthält weitere Informationen zur Verkabelung. Sehen link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Welche zusätzlichen Informationen benötige ich für die Installation meiner Geräte, die nicht in HWU enthalten sind?"^] Für weitere Informationen zu den Installationsanforderungen des Schalters.

. Trennen Sie das Kabel vom Cluster-Port e3a auf Knoten 2 und verbinden Sie dann e3a mit Port 2 des Cluster-Switches cs1 unter Verwendung der von den 9336C-FX2-Switches unterstützten geeigneten Verkabelung.
. Aktivieren Sie alle zum Knoten hin ausgerichteten Ports am Cluster-Switch cs1.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die Ports 1/1 bis 1/34 am Switch cs1 aktiviert sind:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]Überprüfen Sie, ob alle Cluster-LIFs *aktiv* und betriebsbereit sind und als „true“ angezeigt werden für `Is Home` :
+
`network interface show - vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass alle LIFs auf Knoten 1 und Knoten 2 *aktiv* sind und dass `Is Home` Die Ergebnisse sind *wahr*:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]Informationen über den Status der Knoten im Cluster anzeigen:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt Informationen über den Zustand und die Eignung der Knoten im Cluster an:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]Trennen Sie das Kabel vom Cluster-Port e3b auf Knoten 1 und verbinden Sie dann e3b mit Port 1 auf Cluster-Switch cs2. Verwenden Sie dazu die von den 9336C-FX2-Switches unterstützten Kabel.
. Trennen Sie das Kabel vom Cluster-Port e3b auf Knoten 2 und verbinden Sie dann e3b mit Port 2 des Cluster-Switches cs2 unter Verwendung der von den 9336C-FX2-Switches unterstützten geeigneten Verkabelung.
. Aktivieren Sie alle zum Knoten hin ausgerichteten Ports am Cluster-Switch cs2.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die Ports 1/1 bis 1/34 am Switch cs2 aktiviert sind:

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]Überprüfen Sie, ob alle Cluster-Ports aktiv sind:
+
`network port show - ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass alle Cluster-Ports auf Knoten 1 und Knoten 2 aktiv sind:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]Überprüfen Sie, ob alle Schnittstellen „true“ anzeigen für `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: Dieser Vorgang kann mehrere Minuten dauern.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass alle LIFs auf Knoten 1 und Knoten 2 *aktiv* sind und dass `Is Home` Die Ergebnisse sind korrekt:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]Überprüfen Sie, ob beide Knoten jeweils eine Verbindung zu jedem Switch haben:
+
`show cdp neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die entsprechenden Ergebnisse für beide Schalter:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]Informationen zu den in Ihrem Cluster gefundenen Netzwerkgeräten anzeigen:
+
`network device-discovery show -protocol cdp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]Überprüfen Sie, ob die Speicherkonfiguration von HA-Paar 1 (und HA-Paar 2) korrekt und fehlerfrei ist:
+
`system switch ethernet show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]Überprüfen Sie, ob die Einstellungen deaktiviert sind:
+
`network options switchless-cluster show`

+

NOTE: Die Ausführung des Befehls kann mehrere Minuten dauern.  Warten Sie auf die Ansage „3 Minuten bis zum Ablauf der Gültigkeitsdauer“.

+
Der `false` Die Ausgabe im folgenden Beispiel zeigt, dass die Konfigurationseinstellungen deaktiviert sind:

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]Überprüfen Sie den Status der Knoten im Cluster:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt Informationen über den Zustand und die Eignung der Knoten im Cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können die `network interface check cluster-connectivity` Befehl zum Starten einer Zugriffsprüfung für die Clusterkonnektivität und anschließenden Anzeigen der Details:

`network interface check cluster-connectivity start`Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Vorgang ausführen. `show` Befehl zum Anzeigen der Details.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Alle ONTAP Versionen
--
Für alle ONTAP Versionen können Sie auch die `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Verbindung:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step25]] Ändern Sie die Berechtigungsstufe wieder auf Administrator:
+
`set -privilege admin`





=== Schritt 2: Gemeinsamen Schalter einrichten

Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Namen der beiden gemeinsam genutzten Switches lauten _sh1_ und _sh2_.
* Die Knoten heißen _node1_ und _node2_.



NOTE: Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 9000 Series Switches-Befehle benötigt. Es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

. Überprüfen Sie, ob die Speicherkonfiguration von HA-Paar 1 (und HA-Paar 2) korrekt und fehlerfrei ist:
+
`system switch ethernet show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Überprüfen Sie, ob die Ports des Speicherknotens intakt und betriebsbereit sind:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]Verschieben Sie die HA-Paar-1-, NSM224-Pfad-A-Ports in den sh1-Portbereich 11-22.
. Installieren Sie ein Kabel von HA-Paar 1, Knoten 1, Pfad A zum sh1-Portbereich 11-22.  Beispielsweise ist der Pfad A Speicherport auf einem AFF A400 e0c.
. Installieren Sie ein Kabel von HA-Paar 1, Knoten 2, Pfad A zum sh1-Portbereich 11-22.
. Überprüfen Sie, ob die Knotenports intakt und betriebsbereit sind:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Prüfen Sie, ob es Probleme mit dem Speicherschalter oder der Verkabelung des Clusters gibt:
+
`system health alert show -instance`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Verschieben Sie die HA-Paar-1-, NSM224-Pfad-B-Ports in den sh2-Portbereich 11-22.
. Installieren Sie ein Kabel von HA-Paar 1, Knoten 1, Pfad B zum sh2-Portbereich 11-22.  Beispielsweise ist der Speicherport Pfad B auf einem AFF A400 e5b.
. Installieren Sie ein Kabel von HA-Paar 1, Knoten 2, Pfad B zum sh2-Portbereich 11-22.
. Überprüfen Sie, ob die Knotenports intakt und betriebsbereit sind:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Überprüfen Sie, ob die Speicherkonfiguration des HA-Paares 1 korrekt und fehlerfrei ist:
+
`system switch ethernet show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Konfigurieren Sie die ungenutzten (Controller-)Sekundärspeicheranschlüsse des HA-Paares 1 von Speicher auf Netzwerk um.  Wenn mehr als ein NS224 direkt angeschlossen wurde, müssen einige Ports neu konfiguriert werden.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
So platzieren Sie Speicherports in einer Broadcast-Domäne:

+
** `network port broadcast-domain create`(um bei Bedarf eine neue Domain zu erstellen)
** `network port broadcast-domain add-ports`(um einer bestehenden Domäne Ports hinzuzufügen)


. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Wie geht es weiter?
Nach der Migration Ihrer Switches können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
