---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migration von einer Switched-Konfiguration mit Direct-Attached Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können von einer Switched-Konfiguration mit Direct-Attached Storage durch Hinzufügen von zwei neuen Shared-Switches migrieren.

.Unterstützte Switches
Folgende Switches werden unterstützt:

* Nexus 9336C-FX2
* Nexus 3232C


Die in diesem Verfahren unterstützten ONTAP- und NX-OS-Versionen finden sich auf der Seite Cisco Ethernet Switches. Siehe https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet Switches"].

.Verbindungs-Ports
Die Switches verwenden die folgenden Ports, um eine Verbindung zu den Nodes herzustellen:

* Nexus 9336C-FX2:
+
** Ports 1 - 3: Breakout-Modus (4X10G) Intra-Cluster-Ports, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Ports 4- 6: Breakout-Modus (4X25G) Intra-Cluster/HA-Ports, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Ports 7–34: 40 GbE Intra-Cluster/HA-Ports, int e1/7-34


* Nexus 3232C:
+
** 1–30 Ports: 10/40/100 GbE


* Bei den Switches werden die folgenden Inter-Switch Link (ISL)-Ports verwendet:
+
** Anschlüsse in e1/35-36: Nexus 9336C-FX2
** Ports e1/31-32: Nexus 3232C




Der https://hwu.netapp.com["Hardware Universe"] Die enthält Informationen über die unterstützte Verkabelung aller Cluster Switches.

.Was Sie benötigen
* Stellen Sie sicher, dass Sie die folgenden Aufgaben ausgeführt haben:
+
** Konfiguration einiger Ports auf Nexus 9336C-FX2-Switches für 100 GbE.
** Geplante, migrierte und dokumentierte 100-GbE-Konnektivität von Nodes zu Nexus 9336C-FX2 Switches.
** Unterbrechungsfreie Migration anderer Cisco Cluster Switches von einem ONTAP Cluster zu Cisco Nexus 9336C-FX2 Netzwerk-Switches


* Das vorhandene Switch-Netzwerk ist ordnungsgemäß eingerichtet und funktioniert.
* Alle Ports befinden sich im Status *up*, um einen unterbrechungsfreien Betrieb zu gewährleisten.
* Die Nexus 9336C-FX2 Switches sind unter der entsprechenden Version des installierten NX-OS und angewendete Referenzkonfigurationsdatei (RCF) konfiguriert und betrieben.
* Die vorhandene Netzwerkkonfiguration verfügt über folgende Merkmale:
+
** Ein redundantes und voll funktionsfähiges NetApp Cluster unter Verwendung beider älteren Cisco Switches.
** Management-Konnektivität und Konsolenzugriff auf die älteren Cisco Switches und die neuen Switches.
** Alle Cluster-LIFs im Status *up* mit den Cluster-LIFs befinden sich auf ihren Home-Ports.
** ISL-Ports aktiviert und zwischen den anderen Cisco Switches und zwischen den neuen Switches verkabelt.




.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die vorhandenen Cisco Nexus 3232C Cluster-Switches sind _c1_ und _c2_.
* Die neuen Nexus 9336C-FX2 Switches sind _sh1_ und _sh2_.
* Die Knoten sind _node1_ und _node2_.
* Die Cluster-LIFs sind auf Node 1_clus1_ und _node1_clus2_ und _node2_clus1_ bzw. _node2_clus2_ auf Knoten 2.
* Schalter c2 wird zuerst durch Schalter sh2 ersetzt und dann wird der Schalter c1 durch den Schalter sh1 ersetzt.


.Schritte
. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Wobei x die Dauer des Wartungsfensters in Stunden ist.

. Überprüfen Sie den Administrations- und Betriebsstatus der einzelnen Cluster-Ports.
. Vergewissern Sie sich, dass alle Cluster-Ports einen ordnungsgemäßen Status aufweisen:
+
`network port show –role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[Schritt4]]Stellen Sie sicher, dass sich alle Cluster-Schnittstellen (LIFs) auf dem Home-Port befinden:
+
`network interface show -role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[schritt5]]Überprüfen Sie, ob auf dem Cluster Informationen für beide Cluster-Switches angezeigt werden:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[Schritt6]]Automatische Wiederherstellung auf den Cluster-LIFs deaktiviert.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]Schalten Sie den c2-Schalter aus.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[Schritt8]]Überprüfen Sie, ob die Cluster-LIFs zu den Ports migriert haben, die auf dem Cluster-Switch sh1 gehostet werden:
+
`network interface show -role cluster`

+
Dies kann einige Sekunden dauern.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[Schritt9]]Schalter c2 durch den neuen Schalter sh2 ersetzen und den neuen Schalter neu verkabeln.
. Vergewissern Sie sich, dass die Anschlüsse auf sh2 gesichert sind. *Hinweis* dass die LIFs noch auf Switch c1 sind.
. Schalten Sie den c1-Schalter aus.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[steep12]]Überprüfen Sie, ob die Cluster-LIFs zu den Ports migriert wurden, die auf Cluster-Switch sh2 gehostet wurden. Dies kann einige Sekunden dauern.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[STep13]]Schalter c1 durch den neuen Schalter sh1 ersetzen und den neuen Schalter neu verkabeln.
. Überprüfen Sie, ob die Anschlüsse auf sh1 gesichert sind. *Hinweis* dass sich die LIFs noch auf Schalter c2 befinden.
. Aktivieren Sie die automatische Zurücksetzung auf den Cluster-LIFs:
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[steep16]]Stellen Sie sicher, dass sich das Cluster in einem ordnungsgemäßen Zustand befindet:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====

