---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migration von einer Switched-Konfiguration mit direkt angeschlossenem Speicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können von einer Switched-Konfiguration mit direkt angeschlossenem Speicher migrieren, indem Sie zwei neue Shared Switches hinzufügen.

.Unterstützte Schalter
Folgende Schalter werden unterstützt:

* Nexus 9336C-FX2
* Nexus 3232C


Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen finden Sie auf der Cisco Ethernet Switches-Seite. Sehen https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"] .

.Anschlussports
Die Switches verwenden die folgenden Ports, um eine Verbindung zu den Knoten herzustellen:

* Nexus 9336C-FX2:
+
** Ports 1-3: Breakout-Modus (4x10G) Intra-Cluster-Ports, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Ports 4–6: Breakout-Modus (4x25G) Intra-Cluster/HA-Ports, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Ports 7-34: 40/100GbE Intra-Cluster/HA-Ports, int e1/7-34


* Nexus 3232C:
+
** Ports 1-30: 10/40/100 GbE


* Die Switches verwenden die folgenden Inter-Switch Link (ISL)-Ports:
+
** Anschlüsse int e1/35-36: Nexus 9336C-FX2
** Anschlüsse e1/31-32: Nexus 3232C




Der https://hwu.netapp.com["Hardware Universe"] enthält Informationen zur unterstützten Verkabelung für alle Cluster-Switches.

.Was du brauchst
* Bitte stellen Sie sicher, dass Sie die folgenden Aufgaben erledigt haben:
+
** Einige Ports an Nexus 9336C-FX2 Switches wurden für den Betrieb mit 100 GbE konfiguriert.
** Planung, Migration und Dokumentation der 100-GbE-Konnektivität von Knoten zu Nexus 9336C-FX2-Switches.
** Andere Cisco -Cluster-Switches wurden unterbrechungsfrei von einem ONTAP Cluster auf Cisco Nexus 9336C-FX2-Netzwerk-Switches migriert.


* Das bestehende Vermittlungsnetzwerk ist ordnungsgemäß eingerichtet und funktioniert.
* Alle Ports befinden sich im *aktiven* Zustand, um einen unterbrechungsfreien Betrieb zu gewährleisten.
* Die Nexus 9336C-FX2 Switches sind konfiguriert und in Betrieb, wobei die richtige Version von NX-OS installiert und die Referenzkonfigurationsdatei (RCF) angewendet wurde.
* Die bestehende Netzwerkkonfiguration weist folgende Merkmale auf:
+
** Ein redundanter und voll funktionsfähiger NetApp Cluster, der beide ältere Cisco Switches nutzt.
** Management-Konnektivität und Konsolenzugriff sowohl auf die älteren Cisco Switches als auch auf die neuen Switches.
** Alle Cluster-LIFs befinden sich im Status *up* und sind an ihren jeweiligen Heimatports angeschlossen.
** ISL-Ports wurden aktiviert und zwischen den anderen Cisco -Switches sowie zwischen den neuen Switches verkabelt.




.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die vorhandenen Cisco Nexus 3232C Cluster-Switches sind _c1_ und _c2_.
* Die neuen Nexus 9336C-FX2-Switches sind _sh1_ und _sh2_.
* Die Knoten heißen _node1_ und _node2_.
* Die Cluster-LIFs sind _node1_clus1_ und _node1_clus2_ auf Knoten 1 bzw. _node2_clus1_ und _node2_clus2_ auf Knoten 2.
* Zuerst wird der Schalter c2 durch den Schalter sh2 ersetzt, dann wird der Schalter c1 durch den Schalter sh1 ersetzt.


.Schritte
. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Wobei x die Dauer des Wartungsfensters in Stunden angibt.

. Überprüfen Sie den administrativen und operativen Status jedes Cluster-Ports.
. Überprüfen Sie, ob alle Cluster-Ports aktiv und fehlerfrei sind:
+
`network port show –role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[Schritt 4]]Überprüfen Sie, ob sich alle Cluster-Schnittstellen (LIFs) am Home-Port befinden:
+
`network interface show -role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]Überprüfen Sie, ob der Cluster Informationen für beide Cluster-Switches anzeigt:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]Automatische Rücksetzung der Cluster-LIFs deaktivieren.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]Schalten Sie den Schalter c2 aus.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]Überprüfen Sie, ob die Cluster-LIFs auf die Ports migriert wurden, die auf dem Cluster-Switch sh1 gehostet werden:
+
`network interface show -role cluster`

+
Dies kann einige Sekunden dauern.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]Ersetzen Sie den Schalter c2 durch den neuen Schalter sh2 und verkabeln Sie den neuen Schalter neu.
. Überprüfen Sie, ob die Ports auf sh2 wieder funktionieren.  *Hinweis*: Die LIFs sind noch an Schalter c1 angeschlossen.
. Schalten Sie den Schalter c1 aus.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]Überprüfen Sie, ob die Cluster-LIFs auf die Ports migriert wurden, die auf dem Cluster-Switch sh2 gehostet werden. Dies kann einige Sekunden dauern.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]Ersetzen Sie den Schalter c1 durch den neuen Schalter sh1 und verkabeln Sie den neuen Schalter neu.
. Überprüfen Sie, ob die Ports auf sh1 wieder funktionieren.  *Hinweis*: Die LIFs sind noch auf Schalter c2.
. Automatische Wiederherstellung der Cluster-LIFs aktivieren:
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.Wie geht es weiter?
Nach der Migration Ihrer Switches können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
