---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Konfigurieren Sie gemeinsam genutzte Cisco Nexus 9336C-FX2-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Anweisungen, um Cisco Nexus 9336C-FX2 Shared Switches zu konfigurieren.

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Erforderliche Dokumentation für gemeinsam genutzte Switches, Controller und ONTAP .  Sehenlink:required-documentation-9336c-shared.html["Dokumentationsanforderungen für Cisco Nexus 9336C-FX2 Shared Switches"] Und https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP-Dokumentation"^] Die
* Anwendbare Lizenzen, Netzwerk- und Konfigurationsinformationen sowie Kabel.
* Ausgefüllte Verkabelungs-Arbeitsblätter. Sehenlink:cable-9336c-shared.html["Füllen Sie das Verkabelungsarbeitsblatt für den Cisco Nexus 9336C-FX2 aus."] .  Weitere Informationen zur Verkabelung finden Sie unter https://hwu.netapp.com["Hardware Universe"] Die


.Schritte
. [[step3]]Führen Sie eine Erstkonfiguration der Schalter durch.
+
Für die Konfiguration benötigen Sie die entsprechende Anzahl und Art von Kabeln und Kabelverbindern für Ihre Switches.

+
Je nach Art des Switches, den Sie initial konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Konsolenport des Switches herstellen; außerdem müssen Sie spezifische Netzwerkinformationen angeben.

. Schalten Sie den Switch ein.
+
Beantworten Sie die folgenden Fragen zur Ersteinrichtung, wenn Sie den Switch zum ersten Mal einschalten.

+
Die Sicherheitsrichtlinie Ihrer Website definiert die zu aktivierenden Antworten und Dienste.

+
.. Automatische Bereitstellung abbrechen und mit normaler Einrichtung fortfahren?  (ja/nein)
+
Antworten Sie mit *ja*.  Die Standardeinstellung ist Nein.

.. Wollen Sie einen sicheren Passwortstandard erzwingen?  (ja/nein)
+
Antworten Sie mit *ja*.  Die Standardeinstellung ist Ja.

.. Geben Sie das Passwort für den Administrator ein.
+
Das Standardpasswort lautet admin; Sie müssen ein neues, sicheres Passwort erstellen.

+
Ein schwaches Passwort kann abgelehnt werden.

.. Möchten Sie den Dialog zur Basiskonfiguration aufrufen?  (ja/nein)
+
Antworten Sie bei der Erstkonfiguration des Switches mit *ja*.

.. Ein weiteres Benutzerkonto erstellen?  (ja/nein)
+
Die Antwort hängt von den Richtlinien Ihrer Website bezüglich alternativer Administratoren ab.  Die Standardeinstellung ist Nein.

.. SNMP-Community-String schreibgeschützt konfigurieren?  (ja/nein)
+
Antworten Sie mit *nein*.  Die Standardeinstellung ist Nein.

.. SNMP-Community-Zeichenfolge für Lese- und Schreibzugriffe konfigurieren?  (ja/nein)
+
Antworten Sie mit *nein*.  Die Standardeinstellung ist Nein.

.. Geben Sie den Namen des Schalters ein.
+
Der Name des Schalters ist auf 63 alphanumerische Zeichen beschränkt.

.. Mit der Out-of-Band-Managementkonfiguration (mgmt0) fortfahren?  (ja/nein)
+
Antworten Sie bei dieser Eingabeaufforderung mit *ja* (Standardeinstellung).  Geben Sie an der Eingabeaufforderung „mgmt0 IPv4-Adresse:“ Ihre IP-Adresse ein: ip_address

.. Standardgateway konfigurieren?  (ja/nein)
+
Antworten Sie mit *ja*.  Geben Sie an der IPv4-Adresse des Standardgateways Ihre Standardgateway-Adresse ein.

.. Erweiterte IP-Optionen konfigurieren?  (ja/nein)
+
Antworten Sie mit *nein*.  Die Standardeinstellung ist Nein.

.. Den Telnet-Dienst aktivieren?  (ja/nein)
+
Antworten Sie mit *nein*.  Die Standardeinstellung ist Nein.

.. SSH-Dienst aktivieren?  (ja/nein)
+
Antworten Sie mit *ja*.  Die Standardeinstellung ist Ja.

+

NOTE: Bei der Verwendung von Ethernet Switch Health Monitor (CSHM) wird SSH aufgrund seiner Protokollierungsfunktionen empfohlen.  Für erhöhte Sicherheit wird auch SSHv2 empfohlen.

.. [[step14]]Geben Sie den Typ des SSH-Schlüssels ein, den Sie generieren möchten (dsa/rsa/rsa1).  Standardmäßig wird RSA verwendet.
.. Geben Sie die Anzahl der Schlüsselbits ein (1024-2048).
.. Den NTP-Server konfigurieren?  (ja/nein)
+
Antworten Sie mit *nein*.  Die Standardeinstellung ist Nein.

.. Standard-Schnittstellenschicht (L3/L2) konfigurieren:
+
Antworte mit *L2*.  Standardmäßig ist L2 eingestellt.

.. Standardmäßigen Schnittstellenstatus des Switch-Ports konfigurieren (ausgeschaltet/nicht ausgeschaltet):
+
Antworte mit *noshut*.  Die Standardeinstellung ist noshut.

.. CoPP-Systemprofil konfigurieren (streng/moderat/tolerant/dicht):
+
Mit *streng* antworten.  Die Standardeinstellung ist strikt.

.. Möchten Sie die Konfiguration bearbeiten?  (ja/nein)
+
An dieser Stelle sollten Sie die neue Konfiguration sehen.  Überprüfen Sie die soeben eingegebene Konfiguration und nehmen Sie gegebenenfalls die erforderlichen Änderungen vor.  Antworten Sie mit „Nein“, wenn Sie mit der Konfiguration zufrieden sind.  Antworten Sie mit *ja*, wenn Sie Ihre Konfigurationseinstellungen bearbeiten möchten.

.. Diese Konfiguration verwenden und speichern?  (ja/nein)
+
Antworten Sie mit *ja*, um die Konfiguration zu speichern.  Dadurch werden die Kickstart- und Systemabbilder automatisch aktualisiert.



. Überprüfen Sie die von Ihnen getroffenen Konfigurationseinstellungen in der Anzeige, die am Ende des Setups erscheint, und stellen Sie sicher, dass Sie die Konfiguration speichern.
+

NOTE: Wenn Sie die Konfiguration in diesem Schritt nicht speichern, werden beim nächsten Neustart des Switches keine der Änderungen wirksam.

. Überprüfen Sie die Version auf den Cluster-Netzwerk-Switches und laden Sie gegebenenfalls die von NetApp unterstützte Softwareversion auf die Switches herunter. https://software.cisco.com/download/home["Cisco -Software-Download"^] Seite.


.Wie geht es weiter?
Nachdem Sie Ihre Schalter konfiguriert haben, können Sie link:prepare-nxos-rcf-9336c-shared.html["Bereiten Sie die Installation von NX-OS und RCF vor"]Die
