---
sidebar: sidebar 
permalink: switch-cisco-9364d-gx2a/configure-reqs-9364d-cluster.html 
keywords: shared storage cluster switch 
summary: Ab ONTAP 9.9.1 können Sie Cisco Nexus 9364d-gx2a-Switches verwenden, um Speicher- und Clusterfunktionen in einem Shared-Switch-Szenario zu kombinieren. 
---
= Netzwerkanforderungen für Cisco Nexus 9364D-GX2A-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie bei der Installation und Wartung des Cisco Nexus 9364D-GX2A-Switches unbedingt die Verkabelungs- und Netzwerkanforderungen.



== Netzwerkanforderungen

Für alle Switch-Konfigurationen benötigen Sie folgende Netzwerkinformationen.

* IP-Subnetz für den Verwaltungsnetzwerkverkehr
* Hostnamen und IP-Adressen für jeden Speichersystem-Controller und alle entsprechenden Switches
* Die meisten Speichersystem-Controller werden über die e0M-Schnittstelle verwaltet, indem eine Verbindung zum Ethernet-Service-Port (Schraubenschlüsselsymbol) hergestellt wird.
* Siehe die https://hwu.netapp.com["Hardware Universe"^] für die aktuellsten Informationen.




== Verkabelungsanforderungen

* Sie verfügen über die passende Anzahl und Art an Kabeln und Kabelsteckern für Ihre Switches. Siehe die https://hwu.netapp.com["Hardware Universe"^] Die
* Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolenport herstellen.

