---
sidebar: sidebar 
permalink: switch-cisco-9364d-gx2a/required-documentation-9364d-cluster.html 
keywords: shared storage cluster switch 
summary: Lesen Sie zur Installation und Wartung des Cisco Nexus 9364d-gx2a-Switches unbedingt die spezifische Switch- und Controller-Dokumentation, um Ihre Cisco 9364d-gx2a-Switches und ONTAP Cluster einzurichten. 
---
= Dokumentationsanforderungen für Cisco Nexus 9364D-GX2A-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lesen Sie zur Installation und Wartung des Cisco Nexus 9364D-GX2A-Switches unbedingt die spezifische Switch- und Controller-Dokumentation, um Ihre Cisco 9364D-GX2A-Switches und den ONTAP Cluster einzurichten.



== Switch-Dokumentation

Für die Einrichtung der Cisco Nexus 9364D-GX2A Switches benötigen Sie die folgende Dokumentation von https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 Series Switches Unterstützung"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9364d-gx2a/cisco-nexus-9364d-gx2a-nx-os-mode-switch-hardware-installation-guide/m_installing_chassis_2ru_duvel.html["Cisco Nexus 9364D-GX2A NX-OS-Modusschalter – Hardwareinstallationshandbuch"^]
 a| 
Bietet detaillierte Informationen zu Standortanforderungen, Hardware-Details der Schalter und Installationsoptionen.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Softwarekonfigurationshandbücher für Cisco Nexus 9000 Series Switches"^](Wählen Sie die Anleitung für die auf Ihren Switches installierte NX-OS-Version aus)
 a| 
Liefert die grundlegenden Switch-Konfigurationsinformationen, die Sie benötigen, bevor Sie den Switch für den ONTAP -Betrieb konfigurieren können.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Leitfaden für Software-Upgrades und -Downgrades der Cisco Nexus 9000-Serie mit NX-OS"^](Wählen Sie die Anleitung für die auf Ihren Switches installierte NX-OS-Version aus)
 a| 
Bietet Informationen darüber, wie der Switch gegebenenfalls auf eine von ONTAP unterstützte Switch-Software heruntergestuft werden kann.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Cisco Nexus 9000 Serie NX-OS Befehlsreferenz"^]
 a| 
Bietet Links zu den verschiedenen Befehlsreferenzen von Cisco.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Cisco Nexus 9000 Series NX-OS-Systemnachrichtenreferenz"^]
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 9000-Serie, sowohl die informativen als auch die, die bei der Diagnose von Problemen mit Verbindungen, interner Hardware oder der Systemsoftware hilfreich sein können.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Cisco Nexus 9000 Serie NX-OS Versionshinweise"^](Wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)
 a| 
Beschreibt die Funktionen, Fehler und Einschränkungen der Cisco Nexus 9000-Serie.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Informationen zur Einhaltung gesetzlicher Bestimmungen und zur Sicherheit für die Cisco Nexus 9000-Serie"^]
 a| 
Bietet Informationen zur Einhaltung internationaler behördlicher Vorschriften, zur Sicherheit und zu gesetzlichen Bestimmungen für die Switches der Serie Nexus 9000.

|===


== ONTAP-Systemdokumentation

Um ein ONTAP -System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Betriebssystemversion von https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 Dokumentationscenter"^] Die

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://docs.netapp.com/us-en/ontap-afx/index.html["AFX-Systemdokumentation"^]
 a| 
Beschreibt die Installation von NetApp -Hardware.



 a| 
https://docs.netapp.com/us-en/ontap-family/["ONTAP-Dokumentation"^]
 a| 
Bietet detaillierte Informationen zu allen Aspekten der ONTAP Releases.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Bietet Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===