---
sidebar: sidebar 
permalink: switch-cisco-9364d-gx2a/reset-switch-9364d.html 
keywords: reset switch factory defaults 
summary: Setzen Sie den 9364D-GX2A-Switch auf die Werkseinstellungen zurück. 
---
= Setzen Sie den 9364D-GX2A-Switch auf die Werkseinstellungen zurück
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um den 9364D-GX2A-Switch auf die Werkseinstellungen zurückzusetzen, müssen Sie die 9364D-GX2A-Switch-Einstellungen löschen.

.Informationen zu diesem Vorgang
* Sie müssen über die serielle Konsole mit dem Switch verbunden sein.
* Diese Aufgabe setzt die Konfiguration des Managementnetzwerks zurück.


.Schritte
. Löschen Sie die vorhandene Konfiguration:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Laden Sie die Switch-Software neu:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Das System wird neu gestartet und der Konfigurationsassistent wird aufgerufen. Wenn Sie während des Startvorgangs die Aufforderung „Auto Provisioning abbrechen und mit der normalen Einrichtung fortfahren?“ erhalten, (ja/nein)[n]“, sollten Sie mit *ja* antworten, um fortzufahren.


