= Bevor Sie beginnen
:allow-uri-read: 


Der Ethernet Switch Health Monitor (CSHM) ist dafür zuständig, den Betriebszustand der Cluster- und Speichernetzwerk-Switches sicherzustellen und Switch-Protokolle zu Debugging-Zwecken zu sammeln.  Dieses Verfahren führt Sie durch den Prozess der Einrichtung der Datenerfassung, der Anforderung detaillierter *Support*-Protokolle und der Aktivierung einer stündlichen Erfassung von *periodischen* Daten, die von AutoSupport erfasst werden.

*HINWEIS:* Wenn Sie den FIPS-Modus aktivieren, müssen Sie Folgendes durchführen:

[NOTE]
====
. Generieren Sie die SSH-Schlüssel auf dem Switch gemäß den Anweisungen des Herstellers neu.
. SSH-Schlüssel in ONTAP neu generieren mit `debug system regenerate-systemshell-key-pair`
. Führen Sie die Routine zur Einrichtung der Protokollsammlung erneut aus. `system switch ethernet log setup-password` Befehl


====


== Bevor Sie beginnen

* Der Benutzer muss Zugriff auf den Schalter haben. `show` Befehle.  Falls diese nicht verfügbar sind, erstellen Sie einen neuen Benutzer und erteilen Sie diesem die erforderlichen Berechtigungen.
* Die Zustandsüberwachung des Switches muss aktiviert sein.  Überprüfen Sie dies, indem Sie sicherstellen, dass `Is Monitored:` Das Feld wird in der Ausgabe auf *true* gesetzt. `system switch ethernet show` Befehl.
* Für die Protokollerfassung mit Broadcom- und Cisco -Switches:
+
** Der lokale Benutzer muss über Netzwerkadministratorrechte verfügen.
** Für jede Clusterkonfiguration, bei der die Protokollerfassung aktiviert ist, sollte ein neuer Benutzer auf dem Switch angelegt werden.  Diese Switches unterstützen keine mehreren SSH-Schlüssel für denselben Benutzer.  Jede zusätzliche Konfiguration der Protokollerfassung überschreibt alle bereits vorhandenen SSH-Schlüssel des Benutzers.


* Für die Protokollerfassung mit NVIDIA -Switches muss dem Benutzer, der für die Protokollerfassung zuständig ist, die Berechtigung zum Ausführen des Programms erteilt werden. `cl-support` Befehle ausführen, ohne ein Passwort angeben zu müssen.  Um diese Verwendung zu ermöglichen, führen Sie folgenden Befehl aus:
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`





== Schritte

[role="tabbed-block"]
====
.ONTAP 9.15.1 und höher
--
. Um die Protokollerfassung einzurichten, führen Sie für jeden Switch den folgenden Befehl aus.  Sie werden aufgefordert, den Switch-Namen, den Benutzernamen und das Passwort für die Protokollerfassung einzugeben.
+
*HINWEIS:* Wenn Sie die Benutzerspezifikationsabfrage mit *j* beantworten, stellen Sie sicher, dass der Benutzer über die erforderlichen Berechtigungen verfügt, wie in der Dokumentation beschrieben.<<Bevor Sie beginnen>> Die

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Für CL 5.11.1 erstellen Sie den Benutzer *cumulus* und antworten Sie mit *y* auf die folgende Eingabeaufforderung: Möchten Sie einen anderen Benutzer als admin für die Protokollerfassung angeben?  {y|n}: *y*

. [[step2]]Aktivieren Sie die regelmäßige Protokollerfassung:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. Anforderung von Support-Protokollsammlung:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. Um alle Details der Protokollerfassung anzuzeigen, einschließlich Aktivierung, Statusmeldung, vorherigem Zeitstempel und Dateinamen der periodischen Erfassung, Anforderungsstatus, Statusmeldung, vorherigem Zeitstempel und Dateinamen der Support-Erfassung, verwenden Sie Folgendes:
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 und früher
--
. Um die Protokollerfassung einzurichten, führen Sie für jeden Switch den folgenden Befehl aus.  Sie werden aufgefordert, den Switch-Namen, den Benutzernamen und das Passwort für die Protokollerfassung einzugeben.
+
*HINWEIS:* Wenn Sie antworten `y` Stellen Sie bei der Eingabeaufforderung für die Benutzerspezifikation sicher, dass der Benutzer über die erforderlichen Berechtigungen verfügt, wie in der folgenden Beschreibung aufgeführt:<<Bevor Sie beginnen>> Die

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Für CL 5.11.1 erstellen Sie den Benutzer *cumulus* und antworten Sie mit *y* auf die folgende Eingabeaufforderung: Möchten Sie einen anderen Benutzer als admin für die Protokollerfassung angeben?  {y|n}: *y*

. [[step2]] Um die Erfassung von Support-Protokollen anzufordern und die regelmäßige Erfassung zu aktivieren, führen Sie den folgenden Befehl aus.  Damit werden beide Arten der Protokollerfassung gestartet: die detaillierte `Support` Protokolle und eine stündliche Erfassung von `Periodic` Daten.
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Warten Sie 10 Minuten und überprüfen Sie dann, ob die Protokollerfassung abgeschlossen ist:

+
[source, cli]
----
system switch ethernet log show
----


--
====