= 
:allow-uri-read: 


Um die Integritätsüberwachung von Ethernet-Switches auf NVIDIA-Ethernet-Switches zu konfigurieren, befolgen Sie dieses Verfahren.

Diese Anweisungen gelten, wenn NVIDIA X190006-PE und X190006-PI Switches nicht richtig erkannt werden. Dies kann durch Ausführen von  `system switch ethernet show` und prüfen Sie, ob *OTHER* für Ihr Modell angezeigt wird. Um Ihr NVIDIA-Switch-Modell zu identifizieren, suchen Sie die Teilenummer mit dem Befehl  `nv show platform hardware` für NVIDIA CL 5.8 und früher oder  `nv show platform` für spätere Versionen.

[NOTE]
====
Diese Schritte werden auch empfohlen, wenn Sie möchten, dass die Integritätsüberwachung und Protokollerfassung bei Verwendung von NVIDIA CL 5.11.x mit den folgenden ONTAP-Versionen wie vorgesehen funktioniert. Auch ohne diese Schritte funktionieren Integritätsüberwachung und Protokollerfassung möglicherweise weiterhin, aber durch deren Befolgung wird sichergestellt, dass alles ordnungsgemäß funktioniert.

* 9.10.1P20, 9.11.1P18, 9.12.1P16, 9.13.1P8, 9.14.1, 9.15.1 und spätere Patch-Versionen


====
.Bevor Sie beginnen
* Stellen Sie sicher, dass das ONTAP Cluster betriebsbereit ist und ausgeführt wird.
* Aktivieren Sie SSH auf dem Switch, um alle in CSHM verfügbaren Funktionen zu nutzen.
* Löschen Sie das `/mroot/etc/cshm_nod/nod_sign/` Verzeichnis auf allen Knoten:
+
.. Betreten Sie die Nodeshell:
+
`system node run -node <name>`

.. Zu erweiterten Berechtigungen wechseln:
+
`priv set advanced`

.. Listen Sie die Konfigurationsdateien im `/etc/cshm_nod/nod_sign` Verzeichnis auf. Wenn das Verzeichnis existiert und Konfigurationsdateien enthält, werden die Dateinamen aufgelistet.
+
`ls /etc/cshm_nod/nod_sign`

.. Löschen Sie alle Konfigurationsdateien, die Ihren angeschlossenen Switch-Modellen entsprechen.
+
Wenn Sie sich nicht sicher sind, entfernen Sie alle Konfigurationsdateien für die oben aufgeführten unterstützten Modelle, laden Sie die neuesten Konfigurationsdateien für dieselben Modelle herunter, und installieren Sie sie.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Vergewissern Sie sich, dass die gelöschten Konfigurationsdateien nicht mehr im Verzeichnis sind:
+
`ls /etc/cshm_nod/nod_sign`





.Schritte
. Laden Sie die ZIP-Datei für die Konfiguration der Ethernet-Switch-Systemzustandsüberwachung basierend auf der entsprechenden ONTAP-Version herunter. Diese Datei ist auf der Seite verfügbar https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA Ethernet-Switches"^] .
+
.. Wählen Sie auf der Download-Seite der NVIDIA SN2100-Software *Nvidia CSHM-Datei* aus.
.. Aktivieren Sie auf der Seite Achtung/muss gelesen werden das Kontrollkästchen, um zuzustimmen.
.. Aktivieren Sie auf der Seite Endbenutzer-Lizenzvereinbarung das Kontrollkästchen, um zuzustimmen, und klicken Sie auf *Akzeptieren und Fortfahren*.
.. Wählen Sie auf der Seite Nvidia CSHM File - Download die entsprechende Konfigurationsdatei aus. Folgende Dateien sind verfügbar:




[role="tabbed-block"]
====
.ONTAP 9.15.1 und höher
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 bis 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]Laden Sie die entsprechende ZIP-Datei auf Ihren internen Webserver hoch.
. Greifen Sie von einem der ONTAP-Systeme im Cluster aus auf den erweiterten Modus zu.
+
`set -privilege advanced`

. Führen Sie den Befehl Switch Health Monitor configure aus.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet*
----
. Überprüfen Sie, ob die Befehlsausgabe mit dem folgenden Text für Ihre ONTAP-Version endet:


[role="tabbed-block"]
====
.ONTAP 9.15.1 und höher
--
Die Konfigurationsdatei wurde von der Statusüberwachung des Ethernet-Switches installiert.

--
.ONTAP 9.11.1 bis 9.14.1
--
SHM hat die Konfigurationsdatei installiert.

--
.ONTAP 9.10.1
--
Das heruntergeladene CSHM-Paket wurde erfolgreich verarbeitet.

--
====
Sollte ein Fehler auftreten, wenden Sie sich an den NetApp Support.

. [[step6]]Warten Sie bis zu zweimal das Abfrageintervall der Ethernet-Switch-Integritätsüberwachung, das durch Ausführen gefunden `system switch ethernet polling-interval show`wird, bevor Sie den nächsten Schritt abschließen.
. Führen Sie den Befehl auf dem ONTAP-System aus `system switch ethernet show` , und stellen Sie sicher, dass die Cluster-Switches erkannt werden, wobei das überwachte Feld auf *true* und das Seriennummernfeld nicht *Unknown* anzeigt.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
----



NOTE: Wenn Ihr Modell nach der Anwendung der Konfigurationsdatei immer noch *ANDERE* anzeigt, wenden Sie sich an den NetApp-Support.
