---
permalink: switch-cisco-9332d-gx2b/replace-9332d-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9332d-gx2b cluster switch - cisco nexus 9332d-gx2b 
summary: 'Der Austausch eines defekten Nexus 9332D-GX2B-Switches in einem Clusternetzwerk ist ein unterbrechungsfreier Vorgang \(NDU\).' 
---
= Ersetzen Sie einen Cisco Nexus 9332D-GX2B-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um einen defekten Nexus 9332D-GX2B-Switch in einem gemeinsam genutzten Netzwerk zu ersetzen. Dies ist ein unterbrechungsfreies Verfahren (NDU).



== Überprüfungsanforderungen

Bevor Sie den Schalter austauschen, stellen Sie sicher, dass Folgendes passiert:

* Sie haben die Seriennummer des Schalters überprüft, um sicherzustellen, dass der richtige Schalter ausgetauscht wird.
* Zur bestehenden Cluster- und Netzwerkinfrastruktur:
+
** Der bestehende Cluster wurde als voll funktionsfähig verifiziert, wobei mindestens ein Cluster-Switch vollständig angeschlossen ist.
** Alle Cluster-Ports sind aktiv.
** Alle logischen Schnittstellen (LIFs) des Clusters sind aktiv und an ihren jeweiligen Ports angeschlossen.
** Das ONTAP `cluster ping-cluster -node <node-name>` Der Befehl muss anzeigen, dass die grundlegende Konnektivität und die Kommunikation über eine PMTU hinaus auf allen Pfaden erfolgreich sind.


* Zum Nexus 9332D-GX2B-Ersatzschalter:
+
** Die Management-Netzwerkanbindung des Ersatz-Switches ist funktionsfähig.
** Der Konsolenzugriff auf den Ersatzschalter ist eingerichtet.
** Die Knotenverbindungen sind die Ports 1/1 bis 1/30.
** Alle Inter-Switch Link (ISL)-Ports sind an den Ports 1/31 und 1/32 deaktiviert.
** Die gewünschte Referenzkonfigurationsdatei (RCF) und das NX-OS-Betriebssystem-Image werden auf den Switch geladen.
** Die erste Anpassung des Schalters ist abgeschlossen, wie in folgendem Abschnitt detailliert beschrieben:link:setup-switch-9332d-cluster.html["Konfigurieren des Cluster-Switches 9332D-GX2B"] Die
+
Alle zuvor vorgenommenen Anpassungen am Standort, wie z. B. STP, SNMP und SSH, werden auf den neuen Switch kopiert.



* Sie haben den Befehl zum Migrieren eines Cluster-LIF von dem Knoten ausgeführt, auf dem der Cluster-LIF gehostet wird.




== Konsolenprotokollierung aktivieren

NetApp empfiehlt dringend, die Konsolenprotokollierung auf den verwendeten Geräten zu aktivieren und beim Austausch Ihres Switches die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während der Wartungsarbeiten aktiviert.
* Lösen Sie vor und nach der Wartung einen Wartungs AutoSupport aus, um die Fallerstellung für die Dauer der Wartung zu deaktivieren.  Siehe diesen Wissensdatenbankartikel https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Wie man die automatische Fallerstellung während geplanter Wartungsfenster unterdrückt"^] für weitere Einzelheiten.
* Aktivieren Sie die Sitzungsprotokollierung für alle CLI-Sitzungen.  Anweisungen zum Aktivieren der Sitzungsprotokollierung finden Sie im Abschnitt „Protokollierung der Sitzungsausgabe“ in diesem Wissensdatenbankartikel. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP -Systemen?"^] Die




== Tauschen Sie den Schalter aus.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Namen der vorhandenen Nexus 9332D-GX2B-Switches sind cs1 und cs2.
* Der Name des neuen Nexus 9332D-GX2B-Switches lautet newcs2.
* Die Knotennamen sind node1-01, node1-02, node1-03 und node1-04.
* Die Cluster-LIF-Namen lauten node1-01_clus1 und node1-01_clus2 für node1-01, node1-02_clus1 und node1-02_clus2 für node1-02, node1-03_clus1 und node1-03_clus2 für node1-03 sowie node1-04_clus1 und node1-04_clus2 für node1-04.
* Die Aufforderung zum Ändern aller Clusterknoten lautet cluster1::*>


.Informationen zu diesem Vorgang
Das folgende Verfahren basiert auf der folgenden Cluster-Netzwerktopologie:

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current     Current   Is
Vserver     Interface  Admin/Oper Address/Mask       Node        Port      Home
----------- ---------- ---------- ------------------ ----------- --------- ----
Cluster
            node1-01_clus1 up/up  169.254.36.44/16    node1-01    e7a      true
            node1-01_clus2 up/up  169.254.7.5/16      node1-01    e7b      true
            node1-02_clus1 up/up  169.254.197.206/16  node1-02    e7a      true
            node1-02_clus2 up/up  169.254.195.186/16  node1-02    e7b      true
            node1-03_clus1 up/up  169.254.192.49/16   node1-03    e7a      true
            node1-03_clus2 up/up  169.254.182.76/16   node1-03    e7b      true
            node1-04_clus1 up/up  169.254.59.49/16    node1-04    e7a      true
            node1-04_clus2 up/up  169.254.62.244/16   node1-04    e7b      true

8 entries were displayed.

cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID          Local Intrfce  Hldtme Capability  Platform         Port ID
cs2(FDOXXXXXXXX)    Eth1/31        179    R S I s   N9K-C9364D-GX2A   Eth1/63
cs2(FDOXXXXXXXX)    Eth1/32        179    R S I s   N9K-C9364D-GX2A   Eth1/64
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18

cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID          Local Intrfce  Hldtme Capability  Platform         Port ID
cs1(FLMXXXXXXXX)    Eth1/31        179    R S I s   N9K-C9364D-GX2A   Eth1/63
cs1(FLMXXXXXXXX)    Eth1/32        179    R S I s   N9K-C9364D-GX2A   Eth1/64
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18
----
====


=== Schritt 1: Vorbereitung auf den Austausch

. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
wobei x die Dauer des Wartungsfensters in Stunden ist.

+

NOTE: Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

. Installieren Sie die entsprechende RCF-Datei und das Image auf dem Switch newcs2 und treffen Sie alle notwendigen Vorbereitungen vor Ort.
+
Prüfen, laden und installieren Sie gegebenenfalls die entsprechenden Versionen der RCF- und NX-OS-Software für den neuen Switch.  Wenn Sie überprüft haben, dass der neue Switch korrekt eingerichtet ist und keine Aktualisierungen der RCF- und NX-OS-Software erforderlich sind, fahren Sie mit Schritt 2 fort.

+
.. Gehen Sie auf der NetApp Support-Website zur Seite „NetApp Cluster and Management Network Switches Reference Configuration File Description Page“.
.. Klicken Sie auf den Link zur _Kompatibilitätsmatrix für Cluster- und Managementnetzwerke_ und notieren Sie sich anschließend die erforderliche Switch-Softwareversion.
.. Klicken Sie auf den Zurück-Pfeil Ihres Browsers, um zur Beschreibungsseite zurückzukehren, klicken Sie auf *WEITER*, akzeptieren Sie die Lizenzvereinbarung und gehen Sie dann zur Downloadseite.
.. Folgen Sie den Anweisungen auf der Downloadseite, um die korrekten RCF- und NX-OS-Dateien für die Version der ONTAP -Software herunterzuladen, die Sie installieren.


. Melden Sie sich auf dem neuen Switch als Administrator an und fahren Sie alle Ports herunter, die mit den Knotenclusterschnittstellen verbunden werden (Ports 1/1 bis 1/30).
+
Wenn der zu ersetzende Schalter nicht funktionsfähig und ausgeschaltet ist, fahren Sie mit Schritt 4 fort.  Die LIFs auf den Clusterknoten sollten bereits für jeden Knoten auf den anderen Clusterport umgeschaltet haben.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
newcs2# *config*
newcs2(config)# *interface e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7/1-4,e1/8/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/9/1-4,e1/10/1-4,e1/11/1-4,e1/12/1-4,e1/13/1-4,e1/14/1-4,e1/15/1-4,e1/16/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/17/1-4,e1/18/1-4,e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-44,e1/23/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/24/1-,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-44*
newcs2(config-if-range)# *shutdown*
newcs2(config-if-range)# exit
newcs2(config)# exit
----
====
. Überprüfen Sie, ob für alle Cluster-LIFs die automatische Rücksetzung aktiviert ist:
+
[source, cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

             Logical
Vserver      Interface        Auto-revert
------------ ---------------- -------------
Cluster      node1-01_clus1   true
Cluster      node1-02_clus2   true
Cluster      node1-03_clus1   true
Cluster      node1-04_clus2   true

4 entries were displayed.
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:
+
.. Sie können die `network interface check cluster-connectivity show` Befehl zum Anzeigen der Details einer Zugriffsprüfung für die Clusterkonnektivität:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. Alternativ können Sie auch die `cluster ping-cluster -node <node-name>` Befehl zum Überprüfen der Verbindung:
+
`cluster ping-cluster -node <node-name>`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== Schritt 2: Kabel und Anschlüsse konfigurieren

. Fahren Sie die ISL-Ports Eth1/31 und Eth1/32 auf dem Nexus 9332D-GX2B-Switch cs1 herunter.
+
[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/31-32*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# exit
cs1(config)# exit
----
. Entfernen Sie alle Kabel vom Nexus 9332D-GX2B cs2-Switch und schließen Sie sie dann an dieselben Ports am 9332D-GX2B newcs2-Switch an.
. Aktivieren Sie die ISL-Ports Eth1/31 und Eth1/32 zwischen den Switches cs1 und newcs2 und überprüfen Sie dann den Betriebsstatus des Portkanals.
+
Port-Channel sollte Po1(SU) und Member Ports sollten Eth1/31(P) und Eth1/32(P) anzeigen.

+
.Beispiel anzeigen
[%collapsible]
====
Dieses Beispiel aktiviert die ISL-Ports Eth1/31 und Eth1/32 und zeigt die Port-Kanal-Zusammenfassung auf Switch cs1 an:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *int e1/31-32*
cs1(config-if-range)# *no shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
cs1#
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
----
====
. Überprüfen Sie, ob Port e7b auf allen Knoten aktiv ist:
+
[source, cli]
----
network port show ipspace Cluster
----
+
.Beispiel anzeigen
[%collapsible]
====
Die Ausgabe sollte in etwa wie folgt aussehen:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.
----
====
. Auf demselben Knoten, den Sie im vorherigen Schritt verwendet haben, stellen Sie die Cluster-LIF, die dem Port im vorherigen Schritt zugeordnet ist, mit dem Befehl network interface revert wieder her.
+
.Beispiel anzeigen
[%collapsible]
====
In diesem Beispiel wird LIF node1-01_clus2 auf node1-01 erfolgreich zurückgesetzt, wenn der Home-Wert „true“ und der Port „e7b“ ist.

Die folgenden Befehle geben LIF zurück. `node1-01_clus2` An `node1-01` zum Heimathafen `e7a` und zeigt Informationen über die LIFs auf beiden Knoten an.  Das Hochfahren des ersten Knotens ist erfolgreich, wenn die Spalte „Is Home“ für beide Cluster-Schnittstellen den Wert „true“ aufweist und die korrekten Portzuweisungen angezeigt werden. `e7a` Und `e7b` auf Knoten1-01.

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical        Status     Network            Current    Current Is
Vserver   Interface      Admin/Oper Address/Mask       Node       Port    Home
--------- -------------- ---------- ------------------ ---------- ------- -----
Cluster
          node1-01_clus1  up/up     169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up     169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up     169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up     169.254.19.183/16  node1-02   e7a     false
          .
          .
          .
----
====
. Informationen über die Knoten in einem Cluster anzeigen:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Dieses Beispiel zeigt, dass der Knotenstatus für Knoten 1 und Knoten 2 in diesem Cluster „true“ ist:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node           Health  Eligibility
-------------- ------- ------------
node1-01       false   true
node1-02       true    true
node1-03       true    true
node1-04       true    true
----
====
. Überprüfen Sie, ob alle physischen Cluster-Ports aktiv sind:
+
[source, cli]
----
network port show ipspace Cluster
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
.
.
.
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:
+
.. Sie können die `network interface check cluster-connectivity` Befehl zum Anzeigen der Details einer Zugriffsprüfung für die Clusterkonnektivität:
+
[source, cli]
----
network interface check cluster-connectivity start
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. Alternativ können Sie auch die `cluster ping-cluster -node <node-name>` Befehl zum Überprüfen der Verbindung:
+
`cluster ping-cluster -node <node-name>`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== Schritt 3: Konfiguration überprüfen

. Überprüfen Sie den Zustand aller Ports im Cluster.
+
.. *Cluster-Ports*
+
... Überprüfen Sie, ob die Cluster-Ports auf allen Knoten im Cluster aktiv und fehlerfrei sind:
+
[source, cli]
----
network port show ipspace Cluster
----
+
[source, cli]
----
network interface show -vserver Cluster
----
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
show cdp neighbors
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*
Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.

cluster1::*> *network interface show -vserver Cluster*

          Logical       Status     Network            Current    Current Is
Vserver   Interface     Admin/Oper Address/Mask       Node       Port    Home
--------- ------------- ---------- ------------------ ---------- ------- ----
Cluster
          node1-01_clus1  up/up    169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up    169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up    169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up    169.254.19.183/16  node1-02   e7a     true
          node1-03_clus1  up/up    169.254.209.69/16  node1-03   e7a     true
          node1-03_clus2  up/up    169.254.49.125/16  node1-03   e7b     true
          node1-04_clus1  up/up    169.254.47.194/16  node1-04   e7b     true
          node1-04_clus2  up/up    169.254.19.183/16  node1-04   e7a     false

8 entries were displayed.

cluster1::> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
.
.
.

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce  Hldtme Capability  Platform          Port ID
newcs2(FDOXXXXXXXX)   Eth1/31        179    R S I s     N9K-C9364D-GX2A   Eth1/63
newcs2(FDOXXXXXXXX)   Eth1/32        179    R S I s     N9K-C9364D-GX2A   Eth1/64
node1-01              Eth1/4/1       123    H           AFX-1K            e1a
node1-01              Eth1/4/2       123    H           AFX-1K            e7a
node1-01              Eth1/4/3       123    H           AFX-1K            e10a
node1-01              Eth1/4/4       123    H           AFX-1K            e11a
node1-02              Eth1/9/1       138    H           AFX-1K            e1a
node1-02              Eth1/9/2       138    H           AFX-1K            e7a
node1-02              Eth1/9/3       138    H           AFX-1K            e10a
node1-02              Eth1/9/4       138    H           AFX-1K            e11a
node1-03              Eth1/15/1      138    H           AFX-1K            e1a
node1-03              Eth1/15/2      138    H           AFX-1K            e7a
node1-03              Eth1/15/3      138    H           AFX-1K            e10a
node1-03              Eth1/15/4      138    H           AFX-1K            e11a
node1-04              Eth1/16/1      173    H           AFX-1K            e1a
node1-04              Eth1/16/2      173    H           AFX-1K            e7a
node1-04              Eth1/16/3      173    H           AFX-1K            e10a
node1-04              Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18


newcs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform          Port ID
cs1(FDOXXXXXXXX)   Eth1/31        179    R S I s     N9K-C9364D-GX2A   Eth1/63
cs1(FDOXXXXXXXX)   Eth1/32        179    R S I s     N9K-C9364D-GX2A   Eth1/64
node1-01           Eth1/4/1       123    H           AFX-1K            e1a
node1-01           Eth1/4/2       123    H           AFX-1K            e7a
node1-01           Eth1/4/3       123    H           AFX-1K            e10a
node1-01           Eth1/4/4       123    H           AFX-1K            e11a
node1-02           Eth1/9/1       138    H           AFX-1K            e1a
node1-02           Eth1/9/2       138    H           AFX-1K            e7a
node1-02           Eth1/9/3       138    H           AFX-1K            e10a
node1-02           Eth1/9/4       138    H           AFX-1K            e11a
node1-03           Eth1/15/1      138    H           AFX-1K            e1a
node1-03           Eth1/15/2      138    H           AFX-1K            e7a
node1-03           Eth1/15/3      138    H           AFX-1K            e10a
node1-03           Eth1/15/4      138    H           AFX-1K            e11a
node1-04           Eth1/16/1      173    H           AFX-1K            e1a
node1-04           Eth1/16/2      173    H           AFX-1K            e7a
node1-04           Eth1/16/3      173    H           AFX-1K            e10a
node1-04           Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18
----
====


.. *HA-Ports*
+
... Überprüfen Sie, ob alle HA-Ports aktiv sind und einen fehlerfreien Status aufweisen:
+
`ha interconnect status show -node <node-name>`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *Speicheranschlüsse*
+
... Überprüfen Sie, ob alle Speicherports aktiv sind und einen fehlerfreien Status aufweisen:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *Lagerregalanschlüsse*
+
... Überprüfen Sie, ob alle Ports des Speicherregals aktiv sind und einen fehlerfreien Status aufweisen:
+
[source, cli]
----
storage shelf port show
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... Überprüfen Sie den Verbindungsstatus aller Speicherregal-Ports:
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Wie geht es weiter?
Nachdem Sie Ihre Schalter ausgetauscht haben,link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"] Die
