---
permalink: switch-cisco-9332d-gx2b/smart-call-9332d-cluster.html 
sidebar: sidebar 
keywords: cisco smart call,small call home 
summary: Smart Call Home überwacht die Hardware- und Softwarekomponenten Ihres Netzwerks und generiert eine E-Mail-basierte Benachrichtigung über kritische Systemzustände.  Wenn auf Ihrem Gerät ein Ereignis eintritt, sendet Smart Call Home eine Benachrichtigung an alle Empfänger, die in Ihrem Zielprofil konfiguriert sind. 
---
= Anforderungen für Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Smart Call Home zu verwenden, müssen Sie einen Cluster-Netzwerk-Switch für die Kommunikation per E-Mail mit dem Smart Call Home-System konfigurieren. Darüber hinaus können Sie Ihren Cluster-Netzwerk-Switch optional so einrichten, dass er die integrierte Smart Call Home-Supportfunktion von Cisco nutzt.

Smart Call Home überwacht die Hardware- und Softwarekomponenten in Ihrem Netzwerk. Wenn eine kritische Systemkonfiguration auftritt, wird eine E-Mail-Benachrichtigung generiert und ein Alarm an alle Empfänger gesendet, die in Ihrem Zielprofil konfiguriert sind.

Smart Call Home überwacht die Hardware- und Softwarekomponenten in Ihrem Netzwerk. Wenn eine kritische Systemkonfiguration auftritt, wird eine E-Mail-Benachrichtigung generiert und ein Alarm an alle Empfänger gesendet, die in Ihrem Zielprofil konfiguriert sind.

Bevor Sie Smart Call Home verwenden können, beachten Sie die folgenden Anforderungen:

* Ein E-Mail-Server muss vorhanden sein.
* Der Switch muss über eine IP-Verbindung zum E-Mail-Server verfügen.
* Der Kontaktname (SNMP-Server-Kontakt), die Telefonnummer und die Straßenadresse müssen konfiguriert werden.  Dies ist erforderlich, um den Ursprung der empfangenen Nachrichten zu ermitteln.
* Eine CCO-ID muss mit einem passenden Cisco SMARTnet Servicevertrag für Ihr Unternehmen verknüpft sein.
* Für die Registrierung des Geräts muss der Cisco SMARTnet-Dienst eingerichtet sein.


Der http://www.cisco.com/c/en/us/products/switches/index.html["Cisco Supportseite"^] enthält Informationen zu den Befehlen zur Konfiguration von Smart Call Home.
