---
permalink: switch-cisco-9336c-fx2/9336-overview.html 
sidebar: sidebar 
keywords: cisco nexus 9336c-fx2 
summary: Wenn Sie ONTAP Cluster mit mehr als zwei Nodes erstellen möchten, sind zwei unterstützte Cluster-Netzwerk-Switches erforderlich. Sie können zusätzliche, optionale Management Switches verwenden. 
---
= Cisco 9336C-FX2 Switch – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP Cluster mit mehr als zwei Nodes erstellen möchten, sind zwei unterstützte Cluster-Netzwerk-Switches erforderlich. Sie können zusätzliche, optionale Management Switches verwenden.

Sie können den Cisco Nexus 9336C-FX2 Switch (X190200/X190210) in einem NetApp Systemschrank oder Schrank eines Drittanbieters mit Standardhalterungen in einem Gehäuse von NetApp installieren, die im Lieferumfang des Switches enthalten sind.

In der folgenden Tabelle sind die Teilenummer und Beschreibung für den Switch 9336C-FX2, die Lüfter und die Netzteile aufgeführt:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
Zubehörkit X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C AC 1100 W Netzteil – Luftstrom am Port Side



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C AC 1100 W Netzteil – Luftstrom für den seitlichen Ansauganschluss



 a| 
X-NXA-LÜFTER-65CFM-PE
 a| 
N9K-9336C 65 CFM, Luftstrom nach Anschlussseite



 a| 
X-NXA-LÜFTER-65CFM-PI
 a| 
N9K-9336C 65 CFM, Luftstrom zur Ansaugöffnung an der Seite des Ports

|===


== Weitere unterstützte Switches

* Nexus 3232C
+
Sie können den Cisco Nexus 3232C Switch (X190100) NetApp Systemschrank mit angepassten Halterungen installieren, die mit dem Switch geliefert werden. Alternativ können Sie ihn in einem Rack mit den Standardhalterungen installieren, die auch im Lieferumfang des Switches enthalten sind.

* Nexus 3132Q-V
+
Sie können den Cisco Nexus 3132Q-V Switch (X190001) in einem NetApp Systemschrank oder Schrank eines Drittanbieters mit den im Lieferumfang des Switches enthaltenen Standardhalterungen installieren.



Folgende Cluster-Switches sind bei NetApp nicht mehr verfügbar; werden jedoch für begrenzte Zeit von Cisco unterstützt:

* Nexus 5596UP/5596T
+
Sie können den Cisco Nexus 5596UP Switch (X1967-R6) oder 5596T (X1989-R6) in einem NetApp Systemschrank mit angepassten Halterungen installieren, die im Lieferumfang des Switches enthalten sind. Alternativ können Sie den Switch in einem Rack mit den Standardhalterungen installieren, die auch im Lieferumfang des Switches enthalten sind.

+
Der Nexus 5596UP Switch unterstützt außerdem ein oder zwei Erweiterungsmodule mit 16 Ports (X1988-R6).

+
Der Nexus 5596T Switch wird nur als Cluster Interconnect Switch für die FAS2520 unterstützt und ist für unterbrechungsfreie Hardware Upgrades geeignet.

+
http://support.netapp.com/info/communications/ECMP12454150.html["Ende der Verfügbarkeit"^] Details:


