---
permalink: switch-cisco-9336c-fx2/cabling-considerations-9336c-fx2.html 
sidebar: sidebar 
keywords: 9336c-fx2 cabling setup, 9336c-fx2 switches configuration, nx-os 
summary: Lesen Sie die folgenden Informationen, bevor Sie den Cisco 9336C-FX2-Switch konfigurieren. 
---
= Prüfen Sie die Verkabelung und Konfigurationsüberlegungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Ihre 9336C-FX2- und 9336C-FX2-T-Switches konfigurieren, beachten Sie die folgenden Hinweise.



== Unterstützung für NVIDIA CX6-, CX6-DX- und CX7-Ethernet-Ports

Wenn Sie einen Switch-Port mit einem ONTAP-Controller über NVIDIA ConnectX-6 (CX6), ConnectX-6 DX (CX6-DX) oder ConnectX-7 (CX7) NIC-Ports verbinden, müssen Sie die Switch-Port-Geschwindigkeit fest kodieren.

[listing, subs="+quotes"]
----
(cs1)(config)# interface Ethernet1/19
*For 100GbE speed:*
(cs1)(config-if)# *speed 100000*
*For 40GbE speed:*
(cs1)(config-if)# *speed 40000*
(cs1)(config-if)# no negotiate auto
(cs1)(config-if)# exit
(cs1)(config)# exit
*Save the changes:*
(cs1)# *copy running-config startup-config*
----
Siehe https://hwu.netapp.com/Switch/Index["Hardware Universe"^] Weitere Informationen zu Switch-Ports.



== Anforderungen für 25 GbE FEC



=== FAS2820 e0a/e0b-Ports

Für die FAS2820 e0a- und e0b-Ports sind Änderungen an der FEC-Konfiguration erforderlich, um eine Verbindung mit den Switch-Ports 9336C-FX2 und 9336C-FX2-T herzustellen. Für die Switch-Ports e0a und e0b ist die FEC-Einstellung auf `rs-cons16` .

[listing, subs="+quotes"]
----
(cs1)(config)# interface Ethernet1/8-9
(cs1)(config-if-range)# *fec rs-cons16*
(cs1)(config-if-range)# exit
(cs1)(config)# exit
*Save the changes:*
(cs1)# *copy running-config startup-config*
----


== Ports werden aufgrund von TCAM-Ressourcen nicht verbunden

Auf den Switches 9336C-FX2 und 9336C-FX2-T sind die in der vom Switch verwendeten Konfiguration konfigurierten TCAM-Ressourcen (Ternary Content Addressable Memory) erschöpft.

Weitere Informationen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/on-prem/Switches/Cisco-KBs/Ports_do_not_link_up_on_Cisco_Nexus_9336C-FX2_due_to_TCAM_resources["Aufgrund von TCAM-Ressourcen sind die Ports auf dem Cisco Nexus 9336C-FX2 nicht verbunden"^] Für Details zur Lösung dieses Problems.
