---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/components-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: In ONTAP 9.9 können Unternehmen mithilfe von Cisco Nexus 9336C-FX2 Switches Storage- und Cluster-Funktionen in einem gemeinsamen Switch-Szenario kombinieren. 
---
= Komponenten und Teilenummern für Cisco Nexus 9336C-FX2 Cluster Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informationen zur Installation und Wartung von Cisco Nexus 9336C-FX2 Switches finden Sie in der Liste der Komponenten und Teilenummern.

In der folgenden Tabelle sind die Teilenummer und Beschreibung für den Switch 9336C-FX2, die Lüfter und die Netzteile aufgeführt:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
Zubehörkit X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C AC 1100 W Netzteil – Luftstrom am Port Side



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C AC 1100 W Netzteil – Luftstrom für den seitlichen Ansauganschluss



 a| 
X-NXA-LÜFTER-65CFM-PE
 a| 
N9K-9336C 65 CFM, Luftstrom nach Anschlussseite



 a| 
X-NXA-LÜFTER-65CFM-PI
 a| 
N9K-9336C 65 CFM, Luftstrom zur Ansaugöffnung an der Seite des Ports

|===