---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Überblick über die Softwarekonfiguration von Cisco Nexus 9336C-FX2 Cluster-Switches 
---
= Workflow zur Softwareinstallation für Cisco Nexus 9336C-FX2 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
So installieren und konfigurieren Sie die Software für einen Cisco Nexus 9336C-FX2 Switch:

. link:install-nxos-overview-9336c-cluster.html["Bereiten Sie sich auf die Installation der NX-OS-Software und der RCF vor"].
. link:install-nxos-software-9336c-cluster.html["Installieren Sie die NX-OS-Software"].
. link:install-nxos-rcf-9336c-cluster.html["Installieren Sie die Referenzkonfigurationsdatei (RCF)."].
+
Installieren Sie den RCF, nachdem Sie den Nexus 9336C-FX2-Schalter zum ersten Mal eingerichtet haben. Sie können dieses Verfahren auch verwenden, um Ihre RCF-Version zu aktualisieren.

+
.Verfügbare RCF-Konfigurationen
In der folgenden Tabelle werden die für verschiedene Konfigurationen verfügbaren RCFs beschrieben. Wählen Sie den RCF aus, der für Ihre Konfiguration geeignet ist.

+
Einzelheiten zur Port- und VLAN-Nutzung finden Sie im Abschnitt Banner und wichtige Hinweise in Ihrem RCF.

+
[cols="1,2"]
|===
| RCF-Name | Beschreibung 


 a| 
2-Cluster-HA-Breakout an
 a| 
Unterstützt zwei ONTAP-Cluster mit mindestens acht Nodes, einschließlich Nodes, die gemeinsam genutzte Cluster + HA-Ports verwenden.



 a| 
4-Cluster-HA-Breakout an
 a| 
Unterstützt vier ONTAP-Cluster mit mindestens vier Knoten, einschließlich Knoten, die gemeinsam genutzte Cluster+HA-Ports verwenden.



 a| 
1-Cluster-HA
 a| 
Alle Ports sind für 40/100-GbE konfiguriert. Unterstützt Shared Cluster/HA-Datenverkehr auf Ports. Erforderlich für Systeme AFF A320, AFF A250 und FAS500f Darüber hinaus können alle Ports als dedizierte Cluster-Ports verwendet werden.



 a| 
1-Cluster-HA-Breakout an
 a| 
Die Ports sind für 4x10-GbE-Breakout, 4x25-GbE-Breakout (RCF 1.6+ auf 100-GbE-Switches) und 40/100-GbE-Breakout konfiguriert. Unterstützt Shared-Cluster-/HA-Traffic auf Ports für Nodes, die Shared-Cluster/HA-Ports verwenden: AFF A320, AFF A250 und FAS500f Systeme. Darüber hinaus können alle Ports als dedizierte Cluster-Ports verwendet werden.



 a| 
Cluster-HA-Storage
 a| 
Die Ports sind für 40/100 GbE für Cluster+HA, 4 x 10 GbE Breakout für Cluster und 4 x 25 GbE Breakout für Cluster+HA und 100 GbE für jedes Storage HA-Paar konfiguriert.



 a| 
Cluster
 a| 
Zwei RCF-Varianten mit unterschiedlichen Zuweisungen von 4x10GbE-Ports (Breakout) und 40/100-GbE-Ports. Alle FAS/AFF Nodes werden unterstützt, außer AFF A320, AFF A250 und FAS500f Systeme.



 a| 
Storage
 a| 
Alle Ports sind für 100-GbE-NVMe-Storage-Verbindungen konfiguriert.

|===

