---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/configure-reqs-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: Ab ONTAP 9.9.1 können Sie Cisco Nexus 9336C-FX2 Switches verwenden, um Speicher- und Clusterfunktionen in einem gemeinsam genutzten Switch-Szenario zu kombinieren. 
---
= Konfigurationsanforderungen für Cisco Nexus 9336C-FX2 und 9336C-FX2-T Cluster-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie bei der Installation und Wartung der Switches Cisco Nexus 9336C-FX2 und 9336C-FX2-T unbedingt die Konfigurations- und Netzwerkanforderungen.



== ONTAP-Unterstützung

[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Ab ONTAP 9.9.1 können Sie Cisco Nexus 9336C-FX2 Switches verwenden, um Speicher- und Clusterfunktionen in einer gemeinsamen Switch-Konfiguration zu kombinieren.

Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Netzwerk-Switches.


NOTE: Der Ethernet-Switch-Health-Monitor unterstützt weder ONTAP 9.13.1P8 und ältere Versionen noch 9.14.1P3 und ältere Versionen oder NX-OS Version 10.3(4a)(M).

--
.ONTAP 9.10.1 und höher
--
Darüber hinaus können Sie ab ONTAP 9.10.1 Cisco Nexus 9336C-FX2-T-Switches verwenden, um Speicher- und Clusterfunktionen in einer gemeinsam genutzten Switch-Konfiguration zu kombinieren.

Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Netzwerk-Switches.

--
====


== Konfigurationsanforderungen

Stellen Sie sicher, dass:

* Sie verfügen über die passende Anzahl und Art an Kabeln und Kabelsteckern für Ihre Switches. Siehe die https://hwu.netapp.com["Hardware Universe"^] Die
* Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolenport herstellen.




== Netzwerkanforderungen

Für alle Switch-Konfigurationen benötigen Sie folgende Netzwerkinformationen.

* IP-Subnetz für den Verwaltungsnetzwerkverkehr
* Hostnamen und IP-Adressen für jeden Speichersystem-Controller und alle entsprechenden Switches
* Die meisten Speichersystem-Controller werden über die e0M-Schnittstelle verwaltet, indem eine Verbindung zum Ethernet-Service-Port (Schraubenschlüsselsymbol) hergestellt wird. Bei den Systemen AFF A800 und AFF A700s verwendet die e0M-Schnittstelle einen dedizierten Ethernet-Anschluss.
* Siehe die https://hwu.netapp.com["Hardware Universe"^] für die aktuellsten Informationen.


Weitere Informationen zur Erstkonfiguration Ihres Switches finden Sie in der folgenden Anleitung: https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2 Installations- und Upgrade-Leitfaden"^] Die

.Was kommt als nächstes
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie Ihre link:components-9336c-cluster.html["Komponenten und Teilenummern"]Die
