---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Überblick über die Softwarekonfiguration von Cisco Nexus 9336C-FX2 Cluster-Switches 
---
= Workflow zur Softwareinstallation für Cisco Nexus 9336C-FX2 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie wie folgt vor, um die Software für einen Cisco Nexus 9336C-FX2-Switch zu installieren und zu konfigurieren und die Referenzkonfigurationsdatei (RCF) zu installieren oder zu aktualisieren:

. link:install-nxos-overview-9336c-cluster.html["Bereiten Sie die Installation der NX-OS-Software und der RCF vor"].
+
Die Cisco NX-OS-Software und die Referenzkonfigurationsdateien (RCFs) müssen auf Cisco Nexus 9336C-FX2-Cluster-Switches installiert sein.

. link:install-nxos-software-9336c-cluster.html["Installieren oder aktualisieren Sie die NX-OS-Software"].
+
Laden Sie die NX-OS-Software auf dem Cisco Nexus 9336C-FX2 Cluster-Switch herunter, und installieren Sie sie, oder aktualisieren Sie sie.

. link:install-nxos-rcf-9336c-cluster.html["Installieren oder aktualisieren Sie den RCF"].
+
Installieren oder aktualisieren Sie den RCF, nachdem Sie den Cisco Nexus 9336C-FX2-Switch zum ersten Mal eingerichtet haben. Sie können dieses Verfahren auch verwenden, um Ihre RCF-Version zu aktualisieren.

. link:configure-ssh-keys.html["Überprüfen Sie die SSH-Konfiguration auf den Nexus 9336C-FX2 Cluster-Switches"].
+
Wenn Sie den Ethernet Switch Health Monitor (CSHM) und die Protokollerfassungsfunktionen verwenden, überprüfen Sie, ob SSH auf den Switches aktiviert ist.


