---
permalink: switch-cisco-9336c-fx2/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: 'SSH ist eine Voraussetzung für die Verwendung des Cluster Switch Health Monitor (CSHM) und der Protokollerfassungsfunktionen. Um SSH auf Cisco 9336c-fx2-Cluster-Switches zu aktivieren, generieren Sie zuerst die SSH-Schlüssel und aktivieren dann SSH.' 
---
= Übersicht zur Installation oder Aktualisierung der Referenzkonfigurationsdatei (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie installieren die Referenzkonfigurationsdatei (RCF), nachdem Sie die Nexus-Switches 9336C-FX2 und 9336C-FX2-T zum ersten Mal eingerichtet haben. Sie aktualisieren Ihre RCF-Version, wenn auf Ihrem Switch eine vorhandene Version der RCF-Datei installiert ist.

Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Wie man die Konfiguration eines Cisco Interconnect-Switches löscht und gleichzeitig die Remote-Konnektivität beibehält"^] Weitere Informationen zur Installation oder Aufrüstung Ihres RCF erhalten Sie bei Bedarf.

.Verfügbare RCF-Konfigurationen
Die folgende Tabelle beschreibt die für verschiedene Konfigurationen verfügbaren RCFs. Wählen Sie den für Ihre Konfiguration passenden RCF aus. Sehenlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] für weitere Informationen.

Für spezifische Details zur Port- und VLAN-Nutzung verweisen wir auf den Abschnitt „Banner und wichtige Hinweise“ in Ihrem RCF.

[cols="1,2"]
|===
| RCF-Konfiguration | Beschreibung 


 a| 
2-Cluster-HA-Ausbruch
 a| 
Unterstützt zwei ONTAP -Cluster mit mindestens acht Knoten, einschließlich Knoten, die gemeinsam genutzte Cluster+HA-Ports verwenden.



 a| 
4-Cluster-HA-Ausbruch
 a| 
Unterstützt vier ONTAP -Cluster mit mindestens vier Knoten, einschließlich Knoten, die gemeinsam genutzte Cluster+HA-Ports verwenden.



 a| 
1-Cluster-HA
 a| 
Alle Ports sind für 40/100GbE konfiguriert.  Unterstützt gemeinsam genutzten Cluster-/HA-Datenverkehr auf Ports.  Erforderlich für die Systeme AFF A320, AFF A250 und FAS500f .  Darüber hinaus können alle Ports als dedizierte Cluster-Ports verwendet werden.



 a| 
1-Cluster-HA-Ausbruch
 a| 
Die Ports sind für 4x10GbE Breakout, 4x25GbE Breakout (RCF 1.6+ auf 100GbE Switches) und 40/100GbE konfiguriert.  Unterstützt gemeinsam genutzten Cluster-/HA-Datenverkehr auf Ports für Knoten, die gemeinsam genutzte Cluster-/HA-Ports verwenden: AFF A320, AFF A250 und FAS500f Systeme.  Darüber hinaus können alle Ports als dedizierte Cluster-Ports verwendet werden.



 a| 
Cluster-HA-Speicher
 a| 
Die Ports sind für 40/100GbE für Cluster+HA, 4x10GbE Breakout für Cluster und 4x25GbE Breakout für Cluster+HA sowie 100GbE für jedes Storage HA-Paar konfiguriert.



 a| 
Cluster
 a| 
Zwei Varianten von RCF mit unterschiedlicher Belegung von 4x10GbE-Ports (Breakout) und 40/100GbE-Ports. Alle FAS/ AFF -Knoten werden unterstützt, mit Ausnahme der Systeme AFF A320, AFF A250 und FAS500f .



 a| 
Storage
 a| 
Alle Ports sind für 100GbE NVMe-Speicherverbindungen konfiguriert.

|===
.Verfügbare RCFs
Die folgende Tabelle listet die verfügbaren RCFs für die Switches 9336C-FX2 und 9336C-FX2-T auf.  Wählen Sie die für Ihre Konfiguration passende RCF-Version aus. Sehenlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] für weitere Informationen.

[cols="1"]
|===
| RCF-Name 


 a| 
Cluster-HA-Breakout RCF 1._xx_



 a| 
Cluster-HA-Storage RCF 1._xx_



 a| 
Speicher RCF 1._xx_



 a| 
MultiCluster-HA RCF 1._xx_

|===
.Empfohlene Dokumentation
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches (NSS)"^]
+
Auf der NetApp Support-Website finden Sie die Tabelle zur Switch-Kompatibilität, in der die unterstützten ONTAP und RCF-Versionen aufgeführt sind.  Beachten Sie, dass zwischen der Befehlssyntax in der RCF und der Syntax in bestimmten Versionen von NX-OS Befehlsabhängigkeiten bestehen können.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Cisco Nexus 9000 Series Switches"^]
+
Die vollständige Dokumentation zu den Upgrade- und Downgrade-Verfahren für Cisco -Switches finden Sie in den entsprechenden Software- und Upgrade-Leitfäden auf der Cisco -Website.



.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Namen der beiden Cisco Switches lauten *cs1* und *cs2*.
* Die Knotennamen lauten *cluster1-01*, *cluster1-02*, *cluster1-03* und *cluster1-04*.
* Die Cluster-LIF-Namen lauten *cluster1-01_clus1*, *cluster1-01_clus2*, *cluster1-02_clus1*, *cluster1-02_clus2*, *cluster1-03_clus1*, *cluster1-03_clus2*, *cluster1-04_clus1* und *cluster1-04_clus2*.
* Der `cluster1::*>` Die Eingabeaufforderung zeigt den Namen des Clusters an.


Die Beispiele in diesem Verfahren verwenden vier Knoten.  Diese Knoten verwenden zwei 10GbE-Cluster-Verbindungsports *e0a* und *e0b*.  Siehe die https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] um die korrekten Cluster-Ports auf Ihren Plattformen zu überprüfen.


NOTE: Die Befehlsausgaben können je nach ONTAP Version variieren.

Einzelheiten zu den verfügbaren RCF-Konfigurationen finden Sie unterlink:configure-software-overview-9336c-cluster.html["Softwareinstallations-Workflow"] .

.verwendete Befehle
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 9000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

.Wie geht es weiter?
Nachdem Sie die Installations- oder Aktualisierungsprozedur für RCF durchgelesen haben, können Sielink:install-rcf-software-9336c-cluster.html["Installieren Sie den RCF"] oderlink:upgrade-rcf-software-9336c-cluster.html["Aktualisieren Sie Ihren RCF"] wie erforderlich.
