---
permalink: switch-cisco-9336c-fx2/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: two-node switchless cluster,migrating to a Cisco 9336C-FX2 switch,tnsc 
summary: Wenn Sie ein unterbrechungsfrei 2-Node-Cluster ohne Switches zu einem Cluster mit Cisco Nexus 9336C-FX2 Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben. Der dokumentierte Prozess funktioniert für alle Nodes mit optischen oder Twinax-Ports, wird auf diesem Switch jedoch nicht unterstützt, wenn die Nodes integrierte 10-Gbit-BASE-T RJ45-Ports für die Cluster-Netzwerk-Ports verwenden. 
---
= Migration zu einem Switch-basierten 2-Node-Cluster mit Cisco Nexus 9336C-FX2 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein unterbrechungsfrei 2-Node-Cluster ohne Switches zu einem Cluster mit Cisco Nexus 9336C-FX2 Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben. Der dokumentierte Prozess funktioniert für alle Nodes mit optischen oder Twinax-Ports, wird auf diesem Switch jedoch nicht unterstützt, wenn die Nodes integrierte 10-Gbit-BASE-T RJ45-Ports für die Cluster-Netzwerk-Ports verwenden.

Die meisten Systeme benötigen an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports. Siehe https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet Switches"^]
