---
permalink: switch-cisco-9336c-fx2/replace-install-initial.html 
sidebar: sidebar 
keywords: initial setup steps, cisco cluster switch install 
summary: Mit diesem Verfahren können Sie die Erstinstallation des Cisco Nexus 9336C-FX2-Switches durchführen. 
---
= Erstinstallation des Nexus 9336C-FX2 Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Verfahren können Sie die Erstinstallation des Cisco Nexus 9336C-FX2-Switches durchführen.

Sie können die entsprechende NetApp Cisco NX-OS Software für ihre Switches auf der NetApp Support Site unter herunterladen http://mysupport.netapp.com/["mysupport.netapp.com"^].

Bei NX-OS handelt es sich um ein Netzwerkbetriebssystem für die Ethernet Switches der Nexus Serie und die MDS Serie mit Fibre Channel (FC) Storage Area Network Switches von Cisco Systems.

Dieses Verfahren enthält eine Zusammenfassung des Verfahrens zur Installation Ihrer Switches und deren Ausführung.

.Schritte
. Schließen Sie den seriellen Port an den Host oder den seriellen Port Ihrer Wahl an.
. Verbinden Sie den Verwaltungsport (auf der Seite des Switches ohne Port) mit dem gleichen Netzwerk, in dem sich der SFTP-Server befindet.
. Legen Sie an der Konsole die seriellen Einstellungen der Host-Seite fest:
+
** 9600 Baud
** 8 Datenbits
** 1 Stoppbit
** Parität: Keine
** Flusskontrolle: Keine


. Der Nexus 9336C-FX2 Switch wird zum ersten Mal gebootet oder kann nach dem Löschen der laufenden Konfiguration neu gebootet werden. Unterbrechen Sie diesen Zyklus, indem Sie *yes* eingeben, um das Einschalten der automatischen Provisionierung abzubrechen. Sie werden dann mit dem System Admin Account Setup dargestellt:
+
[listing]
----
$ VDC-1 %$ %POAP-2-POAP_INFO:   - Abort Power On Auto Provisioning [yes - continue with normal setup, skip - bypass password and basic configuration, no - continue with Power On Auto Provisioning] (yes/skip/no)[no]: yes
Disabling POAP.......Disabling POAP
2019 Apr 10 00:36:17 switch %$ VDC-1 %$ poap: Rolling back, please wait... (This may take 5-15 minutes)

---- System Admin Account Setup ----
----
. Geben Sie * y* ein, um den sicheren Kennwortstandard durchzusetzen:
+
[listing]
----
Do you want to enforce secure password standard (yes/no) [y]: y
----
. Geben Sie das Passwort für den Benutzer admin ein und bestätigen Sie es:
+
[listing]
----
Enter the password for "admin":
Confirm the password for "admin":
----
. Rufen Sie das Dialogfeld grundlegende Systemkonfiguration auf:
+
[listing]
----
This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus9000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus9000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.

Would you like to enter the basic configuration dialog (yes/no):
----
. Ein weiteres Anmeldekonto erstellen:
+
[listing]
----
Create another login account (yes/no) [n]:
----
. Konfigurieren Sie die SNMP-Community-Strings Read-Only und read-write:
+
[listing]
----
Configure read-only SNMP community string (yes/no) [n]:

Configure read-write SNMP community string (yes/no) [n]:
----
. Konfigurieren Sie den Namen des Cluster-Switches:
+
[listing]
----
Enter the switch name : cs2
----
. Konfigurieren Sie die Out-of-Band-Managementoberfläche:
+
[listing]
----

Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]: y

Mgmt0 IPv4 address : 172.22.133.216

Mgmt0 IPv4 netmask : 255.255.224.0

Configure the default gateway? (yes/no) [y]: y

IPv4 address of the default gateway : 172.22.128.1
----
. Erweiterte IP-Optionen konfigurieren:
+
[listing]
----
Configure advanced IP options? (yes/no) [n]: n
----
. Telnet-Dienste konfigurieren:
+
[listing]
----
Enable the telnet service? (yes/no) [n]: n
----
. Konfigurieren von SSH-Diensten und SSH-Schlüsseln:
+
[listing]
----
Enable the ssh service? (yes/no) [y]: y

Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa

Number of rsa key bits <1024-2048> [1024]: 2048
----
. Weitere Einstellungen konfigurieren:
+
[listing]
----
Configure the ntp server? (yes/no) [n]: n

  Configure default interface layer (L3/L2) [L2]: L2

  Configure default switchport interface state (shut/noshut) [noshut]: noshut

  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]: strict
----
. Bestätigen Sie die Switch-Informationen und speichern Sie die Konfiguration:
+
[listing]
----
Would you like to edit the configuration? (yes/no) [n]: n

Use this configuration and save it? (yes/no) [y]: y

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. Aktivieren Sie für ONTAP 9.8 und höher die Protokollerfassungsfunktion für die Ethernet Switch-Systemzustandsüberwachung, um Switch-bezogene Protokolldateien zu erfassen. Verwenden Sie dazu die folgenden Befehle: `system switch ethernet log setup-password` Und `system switch ethernet log enable-collection`
+
[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system  switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: Wenn einer dieser Befehle einen Fehler sendet, wenden Sie sich an den NetApp Support.

. Aktivieren Sie bei Patch-Releases von ONTAP Releases 9.5P16, 9.6P12 und 9.7P10 sowie höher die Protokollerfassung der Ethernet Switch-Systemzustandsüberwachung mit den Befehlen zum Erfassen von Switch-bezogenen Protokolldateien: `system cluster-switch log setup-password` Und `system cluster-switch log enable-collection`
+
[listing]
----
cluster1::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: Wenn einer dieser Befehle einen Fehler sendet, wenden Sie sich an den NetApp Support.


