---
permalink: switch-cisco-9336c-fx2/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: Nexus 9336C-FX2 switches initial installation, configure cisco cluster switch 
summary: Sie können einen neuen Nexus 9336C-FX2-Switch konfigurieren, indem Sie die in diesem Kapitel beschriebenen Schritte ausführen. 
---
= Konfigurieren Sie einen Cisco Nexus 9336C-FX2 Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen neuen Nexus 9336C-FX2-Switch konfigurieren, indem Sie die in diesem Kapitel beschriebenen Schritte ausführen.

Die Installation des Nexus 9336C-FX2 Switch auf Systemen mit ONTAP 9.8 und höher beginnt mit der Einrichtung einer IP-Adresse und -Konfiguration, damit der Switch über die Managementoberfläche kommunizieren kann. Anschließend können Sie die NX-OS-Software und die Referenzkonfigurationsdatei (RCF) installieren. Dieses Verfahren dient zur Vorbereitung des Nexus 9336C-FX2-Schalters, bevor Controller hinzugefügt werden.

Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die Switch-Namen des Nexus 9336C-FX2 sind cs1 und cs2.
* Das in diesem Verfahren verwendete Beispiel startet das Upgrade auf dem zweiten Schalter _*cs2*._
* Die Cluster-LIF-Namen sind node1_clug1 und node1_clus2 für node1, und node2_clus1 und node2_clus2 für node2.
* Der IPspace Name ist der Cluster.
* Der `cluster1::*>` Eine Eingabeaufforderung gibt den Namen des Clusters an.
* Die Cluster-Ports auf jedem Node lauten e0a und e0b.
+
Siehe https://hwu.netapp.com["Hardware Universe"^] Für die tatsächlichen Cluster-Ports, die auf Ihrer Plattform unterstützt werden.

* Die für Nexus 9336C-FX2-Switches unterstützten Node-Verbindungen sind Ports 1/1 bis 1/34.
* Die Inter-Switch Links (ISLs) werden für Nexus 9336C-FX2 Switches von den Ports 1/35 und 1/36 unterstützt.
* Die Beispiele in diesem Verfahren verwenden zwei Nodes, Sie können jedoch bis zu 24 Nodes in einem Cluster haben.

