---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/required-documentation-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: Überprüfen Sie bei der Installation und Wartung des Cisco Nexus 9336C-FX2 Switches spezielle Switch- und Controller-Dokumentation, um Ihre Cisco 9336-FX2-Switches und das ONTAP-Cluster einzurichten. 
---
= Dokumentationsanforderungen für Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lesen Sie zur Installation und Wartung der Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Switches unbedingt die spezifische Switch- und Controller-Dokumentation, um Ihre Cisco 9336-FX2-Switches und den ONTAP Cluster einzurichten.



== Switch-Dokumentation

Zur Einrichtung der Cisco Nexus 9336C-FX2 und 9336C-FX2-T Switches benötigen Sie folgende Dokumentation aus dem https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Der Cisco Nexus 9000-Serie Unterstützen"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 9000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 9000 Series Switch Software Configuration Guides_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Enthält Informationen zum Downgrade des Switch auf ONTAP unterstützte Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 9000 Series NX-OS Command Reference Master Index_
 a| 
Enthält Links zu den verschiedenen von Cisco bereitgestellten Befehlsreferenzen.



 a| 
_Cisco Nexus 9000 MIBs Referenz_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 9000-Switches.



 a| 
_Nexus 9000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 9000 Serie, Informationen und andere, die bei der Diagnose von Problemen mit Links, interner Hardware oder der Systemsoftware helfen können.



 a| 
_Versionshinweise zur Cisco Nexus 9000-Serie NX-OS (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Bugs und Einschränkungen der Cisco Nexus 9000 Serie.



 a| 
Compliance- und Sicherheitsinformationen für die Cisco Nexus 9000-Serie
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 9000.

|===


== Dokumentation der ONTAP Systeme

Um ein ONTAP-System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Version des Betriebssystems von  https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP-Dokumentation
 a| 
Dieser Service bietet detaillierte Informationen zu allen Aspekten der ONTAP Versionen.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Liefert Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===


== Schienensatz und Rack-Dokumentation

Informationen zur Installation eines Cisco 9336-FX2 Switch in einem NetApp Rack finden Sie in der folgenden Hardware-Dokumentation.

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42-HE-System-Cabinet, Deep Guide"^]
 a| 
Beschreibt die FRUs, die dem 42U-Systemschrank zugeordnet sind, und bietet Anweisungen für Wartung und FRU-Austausch.



 a| 
link:install-switch-and-passthrough-panel-9336c-cluster.html["Installation eines Cisco 9336-FX2 Switch in einem NetApp Rack"^]
 a| 
Beschreibt, wie Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Switches in einem NetApp Schrank mit vier Pfosten installiert werden.

|===