---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/required-documentation-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: Für die Installation und Wartung von Cisco Nexus 9336C-FX2 Switches sollten Sie unbedingt die spezifische Switch- und Controller-Dokumentation lesen, um Ihre Cisco 9336-FX2 Switches und ONTAP Cluster einzurichten. 
---
= Dokumentationsanforderungen für Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lesen Sie zur Installation und Wartung der Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Switches unbedingt die spezifische Switch- und Controller-Dokumentation, um Ihre Cisco 9336-FX2-Switches und den ONTAP Cluster einzurichten.



== Switch-Dokumentation

Für die Einrichtung der Cisco Nexus Switches 9336C-FX2 und 9336C-FX2-T benötigen Sie die folgende Dokumentation von https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 Series Switches Unterstützung"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
_Hardware-Installationsanleitung für die Nexus 9000-Serie_
 a| 
Bietet detaillierte Informationen zu Standortanforderungen, Hardware-Details der Schalter und Installationsoptionen.



 a| 
_Softwarekonfigurationshandbücher für Cisco Nexus 9000 Series Switches_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version aus)
 a| 
Liefert die grundlegenden Switch-Konfigurationsinformationen, die Sie benötigen, bevor Sie den Switch für den ONTAP -Betrieb konfigurieren können.



 a| 
_Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide_ (Wählen Sie den Leitfaden für die auf Ihren Switches installierte NX-OS-Version aus)
 a| 
Bietet Informationen darüber, wie der Switch gegebenenfalls auf eine von ONTAP unterstützte Switch-Software heruntergestuft werden kann.



 a| 
Cisco Nexus 9000 Serie NX-OS Befehlsreferenz – Masterindex
 a| 
Bietet Links zu den verschiedenen Befehlsreferenzen von Cisco.



 a| 
Cisco Nexus 9000 MIBs-Referenz
 a| 
Beschreibt die Management Information Base (MIB)-Dateien für die Nexus 9000 Switches.



 a| 
_Referenz der NX-OS-Systemmeldungen der Nexus 9000-Serie_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 9000-Serie, sowohl die informativen als auch die, die bei der Diagnose von Problemen mit Verbindungen, interner Hardware oder der Systemsoftware hilfreich sein können.



 a| 
_Cisco Nexus 9000 Series NX-OS Versionshinweise (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Fehler und Einschränkungen der Cisco Nexus 9000-Serie.



 a| 
Informationen zur Einhaltung gesetzlicher Bestimmungen und zur Sicherheit für die Cisco Nexus 9000-Serie
 a| 
Bietet Informationen zur Einhaltung internationaler behördlicher Vorschriften, zur Sicherheit und zu gesetzlichen Bestimmungen für die Switches der Serie Nexus 9000.

|===


== ONTAP-Systemdokumentation

Um ein ONTAP -System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Version des Betriebssystems von https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] Die

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controllerspezifische _Installations- und Einrichtungsanweisungen_
 a| 
Beschreibt die Installation von NetApp -Hardware.



 a| 
ONTAP-Dokumentation
 a| 
Bietet detaillierte Informationen zu allen Aspekten der ONTAP Releases.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Bietet Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===


== Dokumentation für Schienenbausatz und Schrank

Informationen zur Installation eines Cisco 9336-FX2 Switches in einem NetApp -Schrank finden Sie in der folgenden Hardware-Dokumentation.

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U Systemschrank, Tiefenführung"^]
 a| 
Beschreibt die mit dem 42U-Systemschrank verbundenen FRUs und gibt Anweisungen zur Wartung und zum Austausch der FRUs.



 a| 
link:install-switch-and-passthrough-panel-9336c-cluster.html["Installieren Sie einen Cisco 9336-FX2 Switch in einem NetApp Schrank"^]
 a| 
Beschreibt, wie Cisco Nexus 9336C-FX2- und 9336C-FX2-T-Switches in einem NetApp Schrank mit vier Pfosten installiert werden.

|===