---
permalink: switch-cisco-9336c-fx2/reset-switch-9336c.html 
sidebar: sidebar 
keywords: 9336C-FX2 reset switch to factory defaults, 9336C-FX2 switches configuration, efos 
summary: Lesen Sie die folgenden Informationen, bevor Sie Ihren Cisco Nexus 9336C-FX2-Switch konfigurieren. 
---
= Setzen Sie die Cluster-Switches 9336C-FX2 und 9336C-FX2-T auf die Werkseinstellungen zurück
:allow-uri-read: 


[role="lead"]
Um die Cluster-Switches 9336C-FX2 und 9336C-FX2-T auf die Werkseinstellungen zurückzusetzen, müssen Sie die Switch-Einstellungen 9336C-FX2 und 9336C-FX2-T löschen.

.Informationen zu diesem Vorgang
* Sie müssen über die serielle Konsole mit dem Switch verbunden sein.
* Diese Aufgabe setzt die Konfiguration des Managementnetzwerks zurück.


.Schritte
. Löschen Sie die vorhandene Konfiguration:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Laden Sie die Switch-Software neu:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Das System wird neu gestartet und der Konfigurationsassistent wird aufgerufen. Wenn Sie während des Startvorgangs die Aufforderung „Auto Provisioning abbrechen und mit der normalen Einrichtung fortfahren?“ erhalten, (ja/nein)[n]“, sollten Sie mit *ja* antworten, um fortzufahren.



.Was kommt als nächstes
Nachdem Sie Ihre Schalter zurückgesetzt haben, können Sielink:configure-switch-overview-9336c-cluster.html["neu konfigurieren"] sie nach Bedarf.
