---
permalink: switch-cisco-9336c-fx2/setup-considerations-smart-call.html 
sidebar: sidebar 
keywords: cisco smart call,small call home 
summary: Smart Call Home überwacht die Hardware- und Softwarekomponenten in Ihrem Netzwerk, um eine E-Mail-basierte Benachrichtigung über wichtige Systembedingungen zu generieren. Wenn ein Ereignis auf Ihrem Gerät auftritt, wird Smart Call Home an alle Empfänger, die im Zielprofil konfiguriert sind, eine Warnmeldung ausgegeben. 
---
= Überlegungen für die Verwendung von Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Smart Call Home überwacht die Hardware- und Softwarekomponenten in Ihrem Netzwerk, um eine E-Mail-basierte Benachrichtigung über wichtige Systembedingungen zu generieren. Wenn ein Ereignis auf Ihrem Gerät auftritt, wird Smart Call Home an alle Empfänger, die im Zielprofil konfiguriert sind, eine Warnmeldung ausgegeben.

Sie müssen einen Cluster-Netzwerk-Switch konfigurieren, um per E-Mail mit dem Smart Call Home-System kommunizieren zu können. Sie können optional Ihren Cluster-Netzwerk-Switch einrichten, um die integrierte Smart Call Home-Support-Funktion von Cisco zu nutzen.

Bevor Sie die Smart Call Home-Funktion verwenden können, müssen Sie die folgenden Überlegungen beachten:

* Es muss ein E-Mail-Server vorhanden sein.
* Der Switch muss über eine IP-Verbindung zum E-Mail-Server verfügen.
* Der Name des Kontakts (SNMP-Serverkontakt), die Telefonnummer und die Adresse der Straße müssen konfiguriert werden.
* Dies ist erforderlich, um den Ursprung der empfangenen Nachrichten zu bestimmen.
* Eine CCO-ID muss mit einem entsprechenden Cisco SMARTnet-Servicevertrag für Ihr Unternehmen verknüpft sein.
* Cisco SMARTnet Service muss vorhanden sein, damit das Gerät registriert werden kann.


Die Cisco Support Site enthält Informationen zu den Befehlen zur Konfiguration von Smart Call Home.

http://www.cisco.com/c/en/us/products/switches/index.html["Cisco Support-Website"^]
