---
permalink: switch-cisco-9336c-fx2/setup-required-documentation.html 
sidebar: sidebar 
keywords: controller, documentation, ontap, cluster, required documentation - cisco nexus 9336c-fx2 
summary: Zum Einrichten des ONTAP Clusters benötigen Sie spezifische Switch- und Controller-Dokumentation. 
---
= Erforderliche Dokumentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Einrichten des ONTAP Clusters benötigen Sie spezifische Switch- und Controller-Dokumentation.

Zum Einrichten der Cisco Nexus 9336C-FX2- und 92300YC-Switches benötigen Sie die folgende Dokumentation auf der https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Der Cisco Nexus 9000-Serie Unterstützen"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 9000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 9000 Series Switch Software Configuration Guides_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Enthält Informationen zum Downgrade des Switch auf ONTAP unterstützte Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 9000 Series NX-OS Command Reference Master Index_
 a| 
Enthält Links zu den verschiedenen von Cisco bereitgestellten Befehlsreferenzen.



 a| 
_Cisco Nexus 9000 MIBs Referenz_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 9000-Switches.



 a| 
_Nexus 9000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 9000 Serie, Informationen und andere, die bei der Diagnose von Problemen mit Links, interner Hardware oder der Systemsoftware helfen können.



 a| 
_Versionshinweise zur Cisco Nexus 9000-Serie NX-OS (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Bugs und Einschränkungen der Cisco Nexus 9000 Serie.



 a| 
Compliance- und Sicherheitsinformationen für die Cisco Nexus 9000-Serie
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 9000.

|===
Für die Einrichtung der Cisco Nexus 3232C- und 3132Q-V-Switches benötigen Sie die folgende Dokumentation auf dem https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Switches Der Cisco Nexus 3000-Serie Unterstützen"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 3000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 3000 Series Switch Software Configuration Guides_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 3000 Series NX-OS Software Upgrade and Downgrade Guide_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Enthält Informationen zum Downgrade des Switch auf ONTAP unterstützte Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 3000 Series NX-OS Command Reference Master Index_
 a| 
Enthält Links zu den verschiedenen von Cisco bereitgestellten Befehlsreferenzen.



 a| 
_Cisco Nexus 3000 MIBs Referenz_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 3000-Switches.



 a| 
_Nexus 3000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 3000 Serie, Informationen und andere, die bei der Diagnose von Problemen mit Links, interner Hardware oder der Systemsoftware helfen können.



 a| 
_Versionshinweise zur Cisco Nexus 3000-Serie NX-OS (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Bugs und Einschränkungen der Cisco Nexus 3000 Serie.



 a| 
Gesetzliche Vorschriften, Compliance und Sicherheitsinformationen für die Cisco Nexus 6000, Cisco Nexus 5000 Serie, Cisco Nexus 3000 Serie und Cisco Nexus 2000 Serie
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 3000.

|===
Zum Einrichten des Cisco Nexus 5596-Switches benötigen Sie die folgenden Dokumente von https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/series.html["Switches Der Cisco Nexus 5000-Serie Unterstützen"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 5000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 5000 Series Switch Software Configuration Guide_ (wählen Sie das Handbuch für die Software, die Sie verwenden)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 5000 Series NX-OS Software-Upgrade und Downgrade Guide_
 a| 
Enthält Informationen zum Downgrade des Switches auf die unterstützte ONTAP Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 5000 Series NX-OS Command Reference Master Index_
 a| 
Enthält eine alphabetische Liste aller Befehle, die für eine bestimmte NX-OS-Version unterstützt werden.



 a| 
_Cisco Nexus 5000 und Nexus 2000 MIBs Reference_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 5000-Switches.



 a| 
_Nexus 5000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Informationen zur Fehlerbehebung.



 a| 
_Informationen zu Vorschriften, Compliance und Sicherheit für die Cisco Serie Nexus 6000, die Cisco Nexus 5000 Serie, die Cisco Nexus 3000 Serie und die Cisco Nexus 2000 Serie_
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 5000.

|===
Um ein ONTAP-System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Betriebssystemversion über das https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 Dokumentationszentrum"^].

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP-Dokumentation
 a| 
Dieser Service bietet detaillierte Informationen zu allen Aspekten der ONTAP Versionen.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Liefert Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===
Informationen zur Installation eines Cisco Switch in einem NetApp Rack finden Sie in der folgenden Hardware-Dokumentation:

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42-HE-System-Cabinet, Deep Guide"^]
 a| 
Beschreibt die FRUs, die dem 42U-Systemschrank zugeordnet sind, und bietet Anweisungen für Wartung und FRU-Austausch.



 a| 
https://library.netapp.com/ecm/ecm_get_file/ECMLP2843148["Installation eines Cisco Nexus 3232C-Cluster-Switch und Pass-Through-Panel in einem NetApp-Rack"^]
 a| 
Beschreibt die Installation eines Cisco Nexus 3232C-Switch in einem NetApp Rack mit vier Pfosten.



 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMLP2518305["Installation eines Cisco Nexus 3132Q-V Switches und Pass-Through-Panels in einem NetApp Rack"^]
 a| 
Beschreibt die Installation eines Cisco Nexus 3132Q-V Switches in einem NetApp Rack mit vier Pfosten.



 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMP1141864["Installation eines Cisco Nexus 5596 Switches und Pass-Through-Panel in einem NetApp Rack"^]
 a| 
Beschreibt die Installation eines Cisco Nexus 5596 Switch in einem NetApp Rack.

|===