---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: Sie können dieses Verfahren verwenden, um die entsprechende Konfigurationsdatei für die Integritätsüberwachung des Cluster-Switch von Nexus 92300YC Cluster Switches zu installieren. Bei ONTAP Releases 9.5P7 und früher sowie 9.6P2 und früher müssen Sie die Konfigurationsdatei des Cluster Switch zur Systemzustandsüberwachung separat herunterladen. In ONTAP Versionen 9.5P8 und höher, 9.6P3 und höher und 9.7 und höher wird die Konfigurationsdatei des Cluster-Switch-Systemzustandsüberwachung mit ONTAP gebündelt. 
---
= Installieren Sie die Konfigurationsdatei des Cluster Switch Health Monitor (CSHM) für 92300YC-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können dieses Verfahren verwenden, um die entsprechende Konfigurationsdatei für die Integritätsüberwachung des Cluster-Switch von Nexus 92300YC Cluster Switches zu installieren. Bei ONTAP Releases 9.5P7 und früher sowie 9.6P2 und früher müssen Sie die Konfigurationsdatei des Cluster Switch zur Systemzustandsüberwachung separat herunterladen. In ONTAP Versionen 9.5P8 und höher, 9.6P3 und höher und 9.7 und höher wird die Konfigurationsdatei des Cluster-Switch-Systemzustandsüberwachung mit ONTAP gebündelt.

Bevor Sie die Switch-Systemzustandsüberwachung für 92300YC Cluster Switches einrichten, müssen Sie sicherstellen, dass der ONTAP Cluster in Betrieb ist.


NOTE: Es wird empfohlen, SSH zu aktivieren, um alle in CSHM verfügbaren Funktionen nutzen zu können.

. Laden Sie die ZIP-Datei für die Cluster-Switch-Systemzustandsüberwachung auf Basis der entsprechenden ONTAP Release-Version herunter. Diese Datei ist im verfügbar https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp Software-Download"^] Seite.
+
.. Wählen Sie auf der Software-Download-Seite *Switch Health Monitor Configuration Files*
.. Wählen Sie Plattform = *ONTAP* und klicken Sie auf *Los!*
.. Klicken Sie auf der Seite Switch Health Monitor Configuration Files for ONTAP auf *Anzeigen & Download*
.. Klicken Sie auf der Seite Switch Health Monitor Configuration Files for ONTAP - Description auf *Download* für das entsprechende Cluster Switch-Modell, zum Beispiel: *Cisco Nexus 92300YC*
.. Klicken Sie auf der Seite Endbenutzer-Lizenzvereinbarung auf *Akzeptieren*
.. Wählen Sie auf der Seite Switch Health Monitor Configuration Files for ONTAP - Download die entsprechende Konfigurationsdatei aus, beispielsweise *Cisco_Nexus_92300YC.zip*


. Laden Sie die entsprechende Zip-Datei auf Ihren internen Webserver hoch, wobei DIE IP-Adresse X.X.X.X ist
+
Für einen internen Webserver IP-Adresse von 192.168.2.20 und unter der Annahme, dass ein Verzeichnis /usr/download existiert, können Sie Ihre ZIP-Datei mit scp auf Ihren Webserver hochladen:

+
[listing]
----
% scp Cisco_Nexus_92300YC.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_92300YC.zip
----
. Greifen Sie mit dem Befehl set-Privilege Advanced von einem der ONTAP Systeme im Cluster auf die Einstellung des erweiterten Modus zu:
+
[listing]
----
cluster1::> set -privilege advanced
----
. Führen Sie den Switch Health Monitor configure command System Cluster-Switch configure-Health-Monitor -Node * -package-url X. X. X. X. X. übers.X/location_to_download_zip_file aus:
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_92300YC.zip
----
. Überprüfen Sie, ob die Befehlsausgabe den Textstring „das heruntergeladene Paket wurde erfolgreich verarbeitet“ enthält. Sollte ein Fehler auftreten, wenden Sie sich an den NetApp Support.
. Führen Sie den Befehl System Cluster-Switch show auf dem ONTAP System aus und stellen Sie sicher, dass die Cluster-Switches erkannt werden, während das überwachte Feld auf „true“ gesetzt ist.
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: Wenn Sie zu einem beliebigen Zeitpunkt auf eine frühere Version von ONTAP zurückkehren, müssen Sie die CSHM-Konfigurationsdatei erneut installieren, um die Überwachung des Switch-Funktionszustands von 92300YC-Clusterschaltern zu ermöglichen.


