---
permalink: switch-cisco-9336c-fx2/setup-required-information.html 
sidebar: sidebar 
keywords: configure, cluster, appropriate, number, cable, connector, switch, type, configuring, configure, console, port, network, information, required cluster configuration information - cisco nexus 9336c-fx2 
summary: Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Switches. Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen. Außerdem müssen Sie spezifische Netzwerkinformationen bereitstellen. 
---
= Erforderliche Informationen zur Cluster-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Switches. Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen. Außerdem müssen Sie spezifische Netzwerkinformationen bereitstellen.

.Erforderliche Netzwerkinformationen für alle Switches
Sie benötigen die folgenden Netzwerkinformationen für alle Switch-Konfigurationen:

* IP-Subnetz für den Management-Netzwerkdatenverkehr
* Host-Namen und IP-Adressen für jeden Storage-System-Controller und alle entsprechenden Switches
* Die meisten Storage-System-Controller werden über die Schnittstelle E0M verwaltet durch eine Verbindung zum Ethernet-Service-Port (Symbol Schraubenschlüssel). Auf AFF A800 und AFF A700 Systemen verwendet die E0M Schnittstelle einen dedizierten Ethernet-Port.


Siehe https://hwu.netapp.com["Hardware Universe"^] Aktuelle Informationen.



== Erforderliche Netzwerkinformationen für die Cisco Nexus 9336C-FX2, 92300YC, 3232C, 3132Q-V und 5596UP/5596T Switches

Für die Cisco Nexus 9336C-FX2, 92300YC, 3232C, 3132Q-V und 5596UP/5596T Switches gilt die Beim ersten Booten des Switches müssen Sie die folgenden Fragen zur Ersteinrichtung entsprechend beantworten. Die Sicherheitsrichtlinie Ihres Standorts definiert die zu erstellenenden Antworten und Services.

* Automatische Bereitstellung abbrechen und mit der normalen Einrichtung fortfahren? (ja/nein)
+
Antworten Sie mit *ja*. Der Standardwert ist Nein

* Wollen Sie den sicheren Kennwortstandard durchsetzen? (ja/nein)
+
Antworten Sie mit *ja*. Die Standardeinstellung ist ja.

* Geben Sie das Passwort für den Administrator ein:
+
Das Standardpasswort lautet „`admin`“. Sie müssen ein neues, starkes Passwort erstellen. Ein schwaches Kennwort kann abgelehnt werden.

* Möchten Sie das Dialogfeld Grundkonfiguration aufrufen? (ja/nein)
+
Reagieren Sie mit *ja* bei der Erstkonfiguration des Schalters.

* Noch ein Login-Konto erstellen? (ja/nein)
+
Ihre Antwort hängt von den Richtlinien Ihrer Site ab, die von alternativen Administratoren abhängen. Der Standardwert ist *no*.

* Schreibgeschützte SNMP-Community-String konfigurieren? (ja/nein)
+
Antworten Sie mit *Nein*. Der Standardwert ist Nein

* Lese-Schreib-SNMP-Community-String konfigurieren? (ja/nein)
+
Antworten Sie mit *Nein*. Der Standardwert ist Nein

* Geben Sie den Switch-Namen ein.
+
Der Switch-Name ist auf 63 alphanumerische Zeichen begrenzt.

* Mit Out-of-Band-Management-Konfiguration (mgmt0) fortfahren? (ja/nein)
+
Beantworten Sie mit *ja* (der Standardeinstellung) bei dieser Aufforderung. Geben Sie an der Eingabeaufforderung mgmt0 IPv4 Adresse: ip_address Ihre IP-Adresse ein.

* Standard-Gateway konfigurieren? (ja/nein)
+
Antworten Sie mit *ja*. Geben Sie an der IPv4-Adresse des Standard-Gateway: Prompt Ihren Standard_Gateway ein.

* Erweiterte IP-Optionen konfigurieren? (ja/nein)
+
Antworten Sie mit *Nein*. Der Standardwert ist Nein

* Telnet-Dienst aktivieren? (ja/nein)
+
Antworten Sie mit *Nein*. Der Standardwert ist Nein

* SSH-Dienst aktiviert? (ja/nein)
+
Antworten Sie mit *ja*. Die Standardeinstellung ist ja.

+

NOTE: SSH wird empfohlen, wenn Sie Cluster Switch Health Monitor (CSHM) für seine Protokollerfassung verwenden. SSHv2 wird auch für erhöhte Sicherheit empfohlen.

* Geben Sie den Typ des zu generierende SSH-Schlüssels ein (dsa/rsa/rsa1). Der Standardwert ist *rsa*.
* Geben Sie die Anzahl der Schlüsselbits ein (1024-2048).
* Konfigurieren Sie den NTP-Server? (ja/nein)
+
Antworten Sie mit *Nein*. Der Standardwert ist Nein

* Standard-Schnittstellenebene konfigurieren (L3/L2):
+
Antworten Sie mit *L2*. Der Standardwert ist L2.

* Konfigurieren Sie den Status der Switch-Schnittstelle (shut/noshut) als Standard-Switch-Port:
+
Antworten Sie mit *noshut*. Die Standardeinstellung ist noshut.

* Konfiguration des CoPP-Systemprofils (streng/mittel/lenient/dense):
+
Reagieren Sie mit * Strict*. Die Standardeinstellung ist streng.

* Möchten Sie die Konfiguration bearbeiten? (ja/nein)
+
Die neue Konfiguration sollte jetzt angezeigt werden. Überprüfen Sie die soeben eingegebene Konfiguration und nehmen Sie alle erforderlichen Änderungen vor. Wenn Sie mit der Konfiguration zufrieden sind, antworten Sie mit *No* an der Eingabeaufforderung. Beantworten Sie mit *ja*, wenn Sie Ihre Konfigurationseinstellungen bearbeiten möchten.

* Verwenden Sie diese Konfiguration und speichern Sie sie? (ja/nein)
+
Antworten Sie mit *ja*, um die Konfiguration zu speichern. Dadurch werden die Kickstart- und Systembilder automatisch aktualisiert.

+

NOTE: Wenn Sie die Konfiguration zu diesem Zeitpunkt nicht speichern, werden keine Änderungen beim nächsten Neustart des Switches wirksam.

+
Weitere Informationen zur Erstkonfiguration des Switches finden Sie in den folgenden Anleitungen:

+
https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#InstallandUpgradeGuides["Cisco Nexus 9336C-FX2 – Installations- und Upgrade-Leitfäden"^]

+
https://www.cisco.com/c/en/us/support/switches/nexus-92300yc-switch/model.html#InstallandUpgradeGuides["Cisco Nexus 92300YC – Installations- und Upgrade-Leitfäden"^]

+
https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/products-installation-guides-list.html["Hardware-Installationsleitfaden Der Cisco Nexus 5000-Serie"^]

+
https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Hardware-Installationsleitfaden Der Cisco Nexus 3000-Serie"^]


