---
permalink: switch-cisco-9336c-fx2/setup-switches.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Wenn Sie noch nicht über die erforderlichen Konfigurationsinformationen und Dokumentation verfügen, müssen Sie diese Informationen erfassen, bevor Sie die Cluster- und Management-Netzwerk-Switches einrichten. 
---
= Richten Sie die Schalter ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie noch nicht über die erforderlichen Konfigurationsinformationen und Dokumentation verfügen, müssen Sie diese Informationen erfassen, bevor Sie die Cluster- und Management-Netzwerk-Switches einrichten.

* Sie müssen auf einen HTTP-, FTP- oder TFTP-Server auf der Installationswebsite zugreifen können, um die entsprechenden NX-OS- und RCF-Versionen (Reference Configuration File) herunterzuladen.
* Sie müssen über die Dokumentation des Cluster-Netzwerks und des Management-Netzwerk-Switches verfügen.
+
Siehe xref:setup-required-documentation.adoc[Erforderliche Dokumentation] Finden Sie weitere Informationen.

* Sie müssen über die erforderliche Controller-Dokumentation und die ONTAP-Dokumentation verfügen.
+
https://netapp.com/us/documenation/index.aspx["NetApp Dokumentation"^]

* Sie müssen über die entsprechenden Lizenzen, Netzwerk- und Konfigurationsinformationen sowie Kabel verfügen.
* Sie müssen über die ausgefüllten Verkabelungsarbeitsblätter verfügen.
+

NOTE: Aufgrund der Komplexität, die sich aus der Darstellung von Verkabelungsschichten ergeben kann, bietet dieser Leitfaden keine Verkabelungsgrafiken. In diesem Leitfaden finden Sie Beispielarbeitsblätter mit empfohlenen Port-Zuweisungen und leeren Arbeitsblättern, mit denen Sie Ihr Cluster einrichten können.

+

NOTE: Weitere Informationen finden Sie im https://hwu.netapp.com["Hardware Universe"^].

* Alle Netzwerk- und Management-Netzwerk-Switches von Cisco sind mit der Standardkonfiguration von Cisco geliefert. Diese Switches verfügen auch über die aktuelle Version der NX-OS-Software, aber nicht über die RCFs geladen.



NOTE: Sie müssen die entsprechenden RCs für das NetApp Cluster-Netzwerk und das Management-Netzwerk von der NetApp Support Site unter herunterladen http://mysupport.netapp.com/["mysupport.netapp.com"^] Für die Switches, die Sie empfangen.

* Darüber hinaus müssen Sie unter Umständen die erforderliche Konfigurationsdatei installieren, um den Cluster Switch Health Monitor (CSHM) für die 92300YC Cluster Switches zu unterstützen. Siehe link:setup_install_cshm_file.md#["Installieren der Konfigurationsdatei des Cluster Switch Health Monitor (CSHM) für 92300YC-Switches"] Entsprechende Details.


.Schritte
. Rack-Aufbau des Cluster-Netzwerks und der Management-Netzwerk-Switches und -Controller
+
[cols="1,2"]
|===
| Wenn Sie das installieren... | Dann... 


 a| 
Cisco Nexus 9336C-FX2 in einem NetApp Systemschrank
 a| 
Anweisungen zur Installation des Switches in einem NetApp Rack sind im Dokument _Installation eines Cisco Nexus 9336C-FX2 Cluster-Switch und Pass-Through-Panel in einem NetApp Rack enthalten.



 a| 
Cisco Nexus 3232C in einem NetApp System-Rack
 a| 
Anweisungen zur Installation des Switches in einem NetApp Schrank sind im Abschnitt _Installieren eines Cisco Nexus 3232C-Cluster-Switch und Pass-Through-Panel in einem NetApp Rack verfügbar.



 a| 
Cisco Nexus 3132Q-V in einem NetApp System-Rack
 a| 
Anweisungen zur Installation des Switches in einem NetApp Schrank finden Sie im Dokument _Installation eines Cisco Nexus 3132Q-V Cluster-Switch und Pass-Through-Panel in einem NetApp Rack.



 a| 
Geräte in einem Telco-Rack
 a| 
Siehe die Verfahren in den Installationsleitfäden für die Switch-Hardware sowie in den Installations- und Setup-Anleitungen für NetApp.



 a| 
Cisco Nexus 5596UP/5596T in einem NetApp System-Rack
 a| 
Anweisungen zur Installation des Switches in einem NetApp Schrank finden Sie im Dokument _Installieren eines Cisco Nexus 5596 Cluster-Switches und Pass-Through-Panel in einem NetApp Rack_.

|===
. Verkabeln Sie die Switches für das Cluster-Netzwerk und das Management-Netzwerk mithilfe der ausgefüllten Verkabelungsarbeitsblätter mit den Controllern.
. Schalten Sie das Cluster-Netzwerk sowie die Switches und Controller des Managementnetzwerks ein.
. Führen Sie eine Erstkonfiguration der Cluster-Netzwerk-Switches anhand der Informationen in durch xref:setup-required-information.adoc[Erforderliche Konfigurationsinformationen].
. Überprüfen Sie die Konfigurationseinstellungen, die Sie am Ende der Einrichtung in der Anzeige vorgenommen haben, und stellen Sie sicher, dass Sie die Konfiguration speichern.
. Prüfen Sie die Version auf den Cluster-Netzwerk-Switches und laden Sie ggf. die von NetApp unterstützte Version der Software auf die Switches herunter.
+
Wenn Sie die von NetApp unterstützte Version der Software herunterladen, müssen Sie auch die _NetApp Cluster Network Switch Reference Configuration File_ herunterladen und mit der Konfiguration zusammenführen, die Sie in Schritt 5 gespeichert haben. Sie können die Datei und die Anweisungen von herunterladen https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Seite.

. Prüfen Sie die Softwareversion auf den Netzwerk-Switches und laden Sie ggf. die von NetApp unterstützte Version der Software auf die Switches herunter. Wenn Sie Ihre eigenen Schalter haben, lesen Sie die https://cisco.com["Cisco Website"^].
+
Wenn Sie die von NetApp unterstützte Version der Software herunterladen, müssen Sie auch die _NetApp Management Network Switch Reference Configuration File_ herunterladen und mit der Konfiguration zusammenführen, die Sie in Schritt 5 gespeichert haben. Sie können die Datei und Anweisungen von herunterladen https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Seite.



.Verwandte Informationen
xref:setup-required-information.adoc[Erforderliche Informationen zur Cluster-Konfiguration]

xref:setup-required-documentation.adoc[Erforderliche Dokumentation]

xref:setup-worksheets-sample-cabling.adoc[Beispiele und leere Verkabelungsarbeitsblätter]
