---
permalink: switch-bes-53248/complete-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches, upgrade completion, upgrade bes-53248 switch 
summary: Lesen Sie vor der Konfiguration von BES-53248-Cluster-Switches eine Übersicht über den Prozess und die Terminologie. 
---
= Führen Sie das Upgrade Ihres BES-53248 Cluster-Switches durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie die folgenden Schritte aus, um das Upgrade Ihrer BES-54328-Cluster-Switches durchzuführen.

. link:configure-ssh.html["Aktivieren Sie SSH bei BES-53248 Cluster-Switches"].
+
Wenn Sie den Cluster Switch Health Monitor (CSHM) und die Funktionen zur Protokollerfassung verwenden, aktivieren Sie SSH auf den Switches.

. link:configure-log-collection.html["Aktivieren Sie die Protokollerfassungsfunktion"].
+
Verwenden Sie diese Funktion, um Switch-bezogene Protokolldateien in ONTAP zu sammeln.

. link:CSHM_snmpv3.html["Konfigurieren Sie SNMPv3 für die Überwachung"].
+
Wenn Sie die Funktion Cluster Switch Health Monitor (CSHM) verwenden, konfigurieren Sie SNMPv3, das die Ethernet-Switch-Statusüberwachung (CSHM) unterstützt.


