---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: Sie können die Portzuordnungstabelle des BES-53248 Cluster-Switches als Leitfaden für die Konfiguration Ihres Clusters verwenden. 
---
= Konfigurationsanforderungen für BES-53248 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Installation und Wartung des BES-53248-Switches sollten Sie unbedingt die Support- und Konfigurationsanforderungen für EFOS und ONTAP beachten.



== EFOS- und ONTAP Unterstützung

Siehe die https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^] Und https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Broadcom-Switch-Kompatibilitätsmatrix"^] Informationen zur Kompatibilität von EFOS und ONTAP mit BES-53248-Switches finden Sie hier. Die Unterstützung von EFOS und ONTAP kann je nach Maschinentyp des BES-53248-Switches variieren. Einzelheiten zu allen Weichenmaschinentypen des Typs BES-52348 finden Sie unterlink:components-bes53248.html["Komponenten und Teilenummern für BES-53248 Cluster-Schalter"] Die Sehen link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Welche zusätzlichen Informationen benötige ich für die Installation meiner Geräte, die nicht in HWU enthalten sind?"]^ Weitere Informationen zu den Installationsanforderungen des Schalters finden Sie hier.



== Konfigurationsanforderungen

Zur Konfiguration eines Clusters benötigen Sie die entsprechende Anzahl und Art von Kabeln und Kabelverbindern für die Cluster-Switches.  Je nachdem, welchen Cluster-Switch Sie initial konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Konsolenport des Switches herstellen.



=== Portzuweisungen für Cluster-Switches

Die von Broadcom unterstützte Tabelle der Portzuweisungen für den BES-53248 Cluster-Switch kann als Leitfaden für die Konfiguration Ihres Clusters verwendet werden.

[cols="1,2"]
|===
| Switch-Ports | Portnutzung 


 a| 
01-16
 a| 
10/25GbE-Cluster-Portknoten, Basiskonfiguration



 a| 
17-48
 a| 
10/25GbE-Cluster-Portknoten mit Lizenzen



 a| 
49-54
 a| 
40/100GbE-Cluster-Portknoten mit Lizenzen, hinzugefügt von rechts nach links



 a| 
55-56
 a| 
100GbE-Cluster-Inter-Switch-Link (ISL)-Ports, Basiskonfiguration

|===
Siehe die https://hwu.netapp.com/Switch/Index["Hardware Universe"] Weitere Informationen zu Switch-Ports finden Sie hier. Sehen link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Welche zusätzlichen Informationen benötige ich für die Installation meiner Geräte, die nicht in HWU enthalten sind?"^] Für weitere Informationen zu den Installationsanforderungen des Schalters.



=== Geschwindigkeitsbeschränkung der Portgruppe

* Bei den Cluster-Switches BES-53248 sind die 48 10/25GbE (SFP28/SFP+)-Ports in 12 x 4-Port-Gruppen wie folgt zusammengefasst: Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 und 45-48.
* Die SFP28/SFP+-Portgeschwindigkeit muss bei allen Ports der 4-Port-Gruppe gleich sein (10GbE oder 25GbE).




=== Zusätzliche Anforderungen

* Wenn Sie zusätzliche Lizenzen erwerben, siehelink:configure-licenses.html["Aktivieren Sie neu lizenzierte Ports"] Einzelheiten zur Aktivierung finden Sie dort.
* Wenn SSH aktiv ist, müssen Sie es nach Ausführung des Befehls manuell wieder aktivieren. `erase startup-config` und den Switch neu starten.


.Was kommt als nächstes
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie Ihre link:components-bes53248.html["Komponenten und Teilenummern"]Die
