---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: 'SSH ist eine Voraussetzung für die Verwendung des Cluster Switch Health Monitor (CSHM) und der Protokollerfassungsfunktionen. Um SSH auf BES-53248 Cluster-Switches zu aktivieren, müssen Sie zuerst die SSH-Schlüssel generieren und anschließend SSH aktivieren.' 
---
= Aktivieren Sie SSH auf BES-53248 Cluster-Switches.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Funktionen Ethernet Switch Health Monitor (CSHM) und Protokollerfassung verwenden, müssen Sie die SSH-Schlüssel generieren und anschließend SSH auf den Cluster-Switches aktivieren.

.Schritte
. Überprüfen Sie, ob SSH deaktiviert ist:
+
`show ip ssh`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
** Falls SSH nicht deaktiviert ist, deaktivieren Sie es wie folgt:
+
`no ip ssh server enable`

+
`no ip scp server enable`

+
[NOTE]
====
*** Für EFOS 3.12 und höher ist Konsolenzugriff erforderlich, da aktive SSH-Sitzungen verloren gehen, wenn SSH deaktiviert ist.
*** Bei EFOS 3.11 und früher bleiben aktuelle SSH-Sitzungen nach der Deaktivierung des SSH-Servers offen.


====
+

WARNING: Stellen Sie sicher, dass Sie SSH deaktivieren, bevor Sie die Schlüssel ändern, andernfalls wird eine Warnung auf dem Switch angezeigt.



. Generieren Sie im Konfigurationsmodus die SSH-Schlüssel:
+
`crypto key generate`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====
. Legen Sie im Konfigurationsmodus die AAA-Autorisierung für die ONTAP Protokollerfassung fest:
+
`aaa authorization commands "noCmdAuthList" none`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====
. Aktivieren Sie SSH/SCP erneut.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====
. Speichern Sie diese Änderungen in der Startkonfiguration:
+
`write memory`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Verschlüsseln Sie die SSH-Schlüssel (nur für den *FIPS-Modus*):
+

CAUTION: Im FIPS-Modus müssen die Schlüssel aus Sicherheitsgründen mit einer Passphrase verschlüsselt werden.  Fehlt ein verschlüsselter Schlüssel, kann die Anwendung nicht gestartet werden.  Die Schlüssel werden mithilfe der folgenden Befehle erstellt und verschlüsselt:

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Starten Sie den Switch neu:
+
`reload`

. Überprüfen Sie, ob SSH aktiviert ist:
+
`show ip ssh`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.Wie geht es weiter?
Nachdem Sie SSH aktiviert haben, können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
