---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: Mit diesem Verfahren können Sie die EFOS-Software auf dem BES-53248-Cluster-Switch installieren. Sie können die entsprechende Broadcom EFOS-Software für Ihre Cluster-Switches von der Broadcom Ethernet-Switch-Support-Website herunterladen. 
---
= Installieren Sie die EFOS-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Verfahren können Sie die EFOS-Software auf dem BES-53248-Cluster-Switch installieren. Sie können die entsprechende Broadcom EFOS-Software für Ihre Cluster-Switches von der Broadcom Ethernet-Switch-Support-Website herunterladen.



== Über diese Aufgabe

[]
====
*Beachten Sie Folgendes:*

* Beim Upgrade von EFOS 3.4.x.x auf EFOS 3.7.x.x oder höher muss auf dem Switch EFOS 3.4.4.6 (oder höher 3.4.x.x-Version) ausgeführt werden. Wenn Sie vor dieser Version eine Version ausführen, aktualisieren Sie zuerst den Switch auf EFOS 3.4.4.6 (oder höher 3.4.x.x Version), und aktualisieren Sie dann den Switch auf EFOS 3.7.x.x oder höher.
* Die Konfiguration für EFOS 3.4.x.x und 3.7.x.x oder höher ist unterschiedlich. Wenn Sie die EFOS-Version von 3.4.x.x auf 3.7.x.x oder höher ändern oder umgekehrt, müssen Sie den Switch auf die Werkseinstellungen zurücksetzen und die RCF-Dateien für die entsprechende EFOS-Version werden (neu) angewendet. Für dieses Verfahren ist ein Zugriff über den seriellen Konsolen-Port erforderlich.
* Ab EFOS Version 3.7.x.x oder höher ist eine FIPS-konforme Version und eine FIPS-konforme Version verfügbar. Verschiedene Schritte gelten für den Wechsel von einem nicht FIPS-konformen auf eine FIPS-konforme Version oder umgekehrt. Wenn EFOS von einer nicht FIPS-konformen Version oder umgekehrt geändert wird, wird der Switch auf die Werkseinstellungen zurückgesetzt. Für dieses Verfahren ist ein Zugriff über den seriellen Konsolen-Port erforderlich.


====
|===


| *Verfahren* | *Aktuelle EFOS-Version* | * Neue EFOS-Version* | *Hohe Stufen* 


 a| 
Schritte zur Aktualisierung von EFOS zwischen zwei (nicht) FIPS-konformen Versionen
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Installieren Sie das neue EFOS-Image mit Methode 1) die Konfigurations- und Lizenzinformationen bleiben erhalten



 a| 
3.4.4.6 (oder höher 3.4.x.x)
 a| 
3.7.x.x oder höher ohne FIPS-konform
 a| 
EFOS mit Methode 1 aktualisieren. Setzen Sie den Schalter auf die Werkseinstellungen zurück, und wenden Sie die RCF-Datei für EFOS 3.7.x.x oder höher an



.2+| 3.7.x.x oder höher ohne FIPS-konform  a| 
3.4.4.6 (oder höher 3.4.x.x)
 a| 
EFOS mit Methode 1 abstufen. Setzen Sie den Schalter auf die Werkseinstellungen zurück, und wenden Sie die RCF-Datei für EFOS 3.4.x.x an



 a| 
3.7.x.x oder höher ohne FIPS-konform
 a| 
Installieren Sie das neue EFOS-Image mit Methode 1. Die Konfigurations- und Lizenzdaten bleiben erhalten



 a| 
3.7.x.x oder höher FIPS-konform
 a| 
3.7.x.x oder höher FIPS-konform
 a| 
Installieren Sie das neue EFOS-Image mit Methode 1. Die Konfigurations- und Lizenzdaten bleiben erhalten



 a| 
Schritte zum Upgrade auf/von einer FIPS-konformen EFOS-Version
 a| 
Nicht FIPS-konform
 a| 
FIPS-konform
 a| 
Installation des EFOS-Images unter Verwendung von Methode 2. Informationen zur Switch-Konfiguration und -Lizenz gehen verloren.



 a| 
FIPS-konform
 a| 
Nicht FIPS-konform

|===

IMPORTANT: Beachten Sie, dass nach dem Upgrade von BES-53248-Cluster-Switches von EFOS 3.3.x.x oder 3.4.x.x auf EFOS 3.7.0.4 oder 3.8.0.2 Inter-Switch Links (ISLs) und Port Channel im Status *Down* markiert sind. Siehe das https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["KB-Artikel"^] Entnehmen.

.Schritte
. Verbinden Sie den BES-53248-Cluster-Switch mit dem Managementnetzwerk.
. Verwenden Sie die `ping` Befehl zum Überprüfen der Verbindung mit dem Server, der EFOS, Lizenzen und der RCF-Datei hostet.
+
In diesem Beispiel wird überprüft, ob der Switch mit der IP-Adresse 172.19.2 verbunden ist:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Sichern Sie das aktuelle aktive Bild auf cs2:
+
`show bootvar`

+
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.4.3.3     Q.10.22.1     3.4.3.3           3.4.3.3

(cs2)# *copy active backup*
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :
 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.4.3.3     3.4.3.3     3.4.3.3           3.4.3.3
(cs2)#
----
. Überprüfen Sie die laufende Version der EFOS-Software:
+
`show version`

+
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. Quanta IX8-B 48x25GB SFP 8x100GB QSFP, 3.4.3.3, Linux 4.4.117-ceeeb99d, 2016.05.00.04
Machine Type................................... Quanta IX8-B 48x25GB SFP 8x100GB QSFP
Machine Model.................................. IX8-B
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.4.3.3
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
. Laden Sie die Bilddatei auf den Switch herunter.
+
Durch Kopieren der Bilddatei auf das aktive Image wird bei einem Neustart die aktuell ausgeführte EFOS-Version erstellt. Das vorherige Bild bleibt als Backup verfügbar.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.4.4.6.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Anzeigen der Boot-Images für die aktive und die Backup-Konfiguration:
+
`show bootvar`

+
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------
    1     3.4.3.3     3.4.3.3            3.4.3.3            3.4.4.6
----
. Starten Sie den Switch neu:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
. Melden Sie sich erneut an, und überprüfen Sie die neue Version der EFOS-Software:
+
`show version`

+
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. x86_64-quanta_common_rglbmc-r0, 3.4.4.6, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... x86_64-quanta_common_rglbmc-r0
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.4.4.6
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----




== Aktualisieren Sie EFOS mit der ONIE OS-Installation

Sie können die folgenden Schritte durchführen, wenn eine EFOS-Version FIPS-konform ist und die andere EFOS-Version nicht FIPS-konform ist. Mit diesen Schritten kann das nicht-FIPS- oder FIPS-konforme EFOS 3.7.x.x-Image von ONIE installiert werden, wenn der Switch nicht startet.


NOTE: Diese Funktion ist nur für EFOS 3.7.x.x oder höher ohne FIPS-konform verfügbar.

.Schritte
. Starten Sie den Schalter in den ONIE-Installationsmodus.
+
Wählen Sie während des Startvorgangs ONIE aus, wenn der folgende Bildschirm angezeigt wird:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Nach der Auswahl von *ONIE"* wird der Schalter geladen und Ihnen folgende Optionen zur Verfügung stellen:

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Der Schalter startet nun in den ONIE-Installationsmodus.

. Beenden Sie die ONIE-Erkennung, und konfigurieren Sie die Ethernet-Schnittstelle.
+
Wenn die folgende Meldung angezeigt wird, drücken Sie <Enter>, um die ONIE-Konsole zu öffnen:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: Die ONIE-Erkennung wird fortgesetzt, und Meldungen werden auf die Konsole gedruckt.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Konfigurieren Sie die Ethernet-Schnittstelle und fügen Sie die Route mit hinzu `ifconfig eth0 <ipAddress> netmask <netmask> up` Und `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Stellen Sie sicher, dass der Server, der die ONIE-Installationsdatei hostet, erreichbar ist:
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. Installieren Sie die neue Switch-Software:
+
[listing]
----
ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
Die Software wird installiert und startet den Switch dann neu. Lassen Sie den Switch normal in die neue EFOS-Version neu starten.

. Vergewissern Sie sich, dass die neue Switch-Software installiert ist: `show bootvar`
+
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	  3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(cs2) #
----
. Schließen Sie die Installation ab.
+
Der Switch wird neu gestartet, ohne dass die Konfiguration angewendet wurde, und setzt die Werkseinstellungen zurück.



*Verwandte Informationen*

https://www.broadcom.com/support/bes-switch["Unterstützung Für Broadcom Ethernet-Switches"^]
