---
permalink: switch-bes-53248/configure-install-rcf.html 
sidebar: sidebar 
keywords: install rcf,setup rcf 
summary: 'Sie können die Referenzkonfigurationsdatei (RCF) installieren, nachdem Sie den BES-53248-Cluster-Switch konfiguriert und die neuen Lizenzen angewendet haben.' 
---
= Installieren Sie die Referenzkonfigurationsdatei (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Referenzkonfigurationsdatei (RCF) installieren, nachdem Sie den BES-53248-Cluster-Switch konfiguriert und die neuen Lizenzen angewendet haben.

Wenn Sie ein RCF von einer älteren Version aktualisieren, müssen Sie die Broadcom-Switch-Einstellungen zurücksetzen und die Grundkonfiguration durchführen, um das RCF erneut anzuwenden. Sie müssen diesen Vorgang jedes Mal durchführen, wenn Sie ein RCF aktualisieren oder ändern möchten. Siehe https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["KB-Artikel"^] Entsprechende Details.

.Schritte
. Verbinden Sie den Cluster-Switch mit dem Managementnetzwerk.
. Verwenden Sie die `ping` Befehl zum Überprüfen der Verbindung mit dem Server, der EFOS, Lizenzen und RCF hostet.
+
Wenn es sich bei der Konnektivität um ein Problem handelt, verwenden Sie ein nicht geroutetes Netzwerk, und konfigurieren Sie den Service-Port mithilfe der IP-Adresse 192.168.x oder 172.19.x Sie können den Service-Port später an die Produktionsmanagement-IP-Adresse neu konfigurieren.

+
.Beispiel anzeigen
[%collapsible]
====
In diesem Beispiel wird überprüft, ob der Switch mit der IP-Adresse 172.19.2 verbunden ist:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Installieren Sie das RCF mithilfe des am BES-53248-Cluster-Switch `copy` Befehl.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr*

Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...

File transfer operation completed successfully.
----
====
+

NOTE: Je nach Umgebung müssen Sie im möglicherweise einen Doppelschrägstrich verwenden `copy` Befehl, z. B.: `+copy sftp://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Der `.scr` Die Erweiterung muss als Teil des Dateinamens festgelegt werden, bevor das Skript aufgerufen wird. Diese Erweiterung ist die Erweiterung für das EFOS-Betriebssystem. Der Switch validiert das Skript automatisch, wenn es auf den Switch heruntergeladen wird und die Ausgabe an die Konsole geht. Außerdem können Sie den Namen des ändern `.scr` So passen Sie den Konsolenbildschirm an, um die Lesbarkeit zu erleichtern: `+copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Der Dateiname darf die Symbole nicht enthalten `\/:*?"<>|` Und die maximal zulässige Länge beträgt 32 Zeichen.

. Überprüfen Sie, ob das Skript heruntergeladen und auf dem Dateinamen gespeichert wurde, den Sie ihm gegeben haben:
+
`script list`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
====
. Das Skript auf den Switch anwenden:
+
`script apply`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.6-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
====
. Überprüfen Sie die Ports auf eine zusätzliche Lizenz, nachdem die RCF angewendet wurde:
+
`show port all | exclude Detach`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
====
. Überprüfen Sie auf dem Switch, ob Ihre Änderungen vorgenommen wurden:
+
`show running-config`

+
[listing, subs="+quotes"]
----
(cs2)# *show running-config*
----
. Speichern Sie die laufende Konfiguration, damit sie die Startkonfiguration wird, wenn Sie den Switch neu starten:
+
`write memory`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Starten Sie den Switch neu und vergewissern Sie sich, dass die laufende Konfiguration korrekt ist:
+
`reload`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*

System will now restart!
----
====


.Was kommt als Nächstes?
link:configure-health-monitor.html["Installieren Sie die CSHM-Konfigurationsdatei"].
