---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: Mit diesem Verfahren können Sie die Erstinstallation des Cluster-Switches BES-53248 durchführen. 
---
= Konfigurieren des Cluster-Switches BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie die folgenden Schritte aus, um die Ersteinrichtung des Cluster-Switches BES-53248 durchzuführen.

.Bevor Sie beginnen
* Die Hardware wird wie beschrieben installiert.link:install-hardware-bes53248.html["Installieren Sie die Hardware"] Die
* Sie haben Folgendes geprüft:
+
** link:configure-reqs-bes53248.html["Konfigurationsanforderungen"]
** link:components-bes53248.html["Komponenten und Teilenummern"]
** link:required-documentation-bes53248.html["Dokumentationsanforderungen"]




.Zu den Beispielen
Die Beispiele in den Konfigurationsanleitungen verwenden die folgende Switch- und Knotennomenklatur:

* Die Namen der NetApp -Switches lauten: `cs1` Und `cs2` Die  Das Upgrade beginnt mit dem zweiten Switch, _cs2._
* Die Cluster-LIF-Namen sind `node1_clus1` Und `node1_clus2` für Knoten1 und `node2_clus1` Und `node2_clus2` für Knoten 2.
* Der IPspace-Name lautet Cluster.
* Der `cluster1::>` Die Eingabeaufforderung zeigt den Namen des Clusters an.
* Die Cluster-Ports auf jedem Knoten sind benannt `e0a` Und `e0b` Die  Siehe die https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^] für die tatsächlich von Ihrer Plattform unterstützten Cluster-Ports.
* Die für die NetApp Switches unterstützten Inter-Switch-Links (ISLs) sind die Ports 0/55 und 0/56.
* Die für die NetApp Switches unterstützten Knotenverbindungen sind die Ports 0/1 bis 0/16 mit Standardlizenzierung.
* Die Beispiele verwenden zwei Knoten, aber ein Cluster kann bis zu 24 Knoten umfassen.


.Schritte
. Verbinden Sie den seriellen Port mit einem Host oder einem seriellen Port.
. Verbinden Sie den Management-Port (den RJ-45-Schraubenschlüssel-Anschluss auf der linken Seite des Switches) mit demselben Netzwerk, in dem sich Ihr TFTP-Server befindet.
. Nehmen Sie an der Konsole die seriellen Einstellungen auf dem Host vor:
+
** 115200 Baud
** 8 Datenbits
** 1 Stoppbit
** Parität: keine
** Flusssteuerung: keine


. Melden Sie sich am Switch an als `admin` und drücken Sie *Enter*, wenn Sie zur Eingabe eines Passworts aufgefordert werden.  Der Standard-Switch-Name lautet *routing*.  Geben Sie bei Aufforderung Folgendes ein `enable` Die  Dies ermöglicht Ihnen den Zugriff auf den privilegierten EXEC-Modus zur Switch-Konfiguration.
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. Ändern Sie den Schalternamen in *cs2*.
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. So legen Sie eine statische IPv4- oder IPv6-Verwaltungsadresse für den Service-Port des Switches fest:


[role="tabbed-block"]
====
.IPv4
--
Der Serviceport ist standardmäßig auf die Verwendung von DHCP eingestellt.  Die IP-Adresse, die Subnetzmaske und die Standardgateway-Adresse werden automatisch zugewiesen.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
Der Serviceport ist standardmäßig auf die Verwendung von DHCP eingestellt.  Die IP-Adresse, die Subnetzmaske und die Standardgateway-Adresse werden automatisch zugewiesen.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[step7]]Überprüfen Sie die Ergebnisse mit dem Befehl:
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. Konfigurieren Sie die Domäne und den Nameserver:
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. Konfigurieren Sie den NTP-Server.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 und höher
--
Konfigurieren Sie die Zeitzone und die Zeitsynchronisierung (NTP):

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 und früher
--
Konfigurieren Sie die Zeitzone und die Zeitsynchronisierung (SNTP):

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]Konfigurieren Sie die Zeit manuell, wenn Sie im vorherigen Schritt keinen NTP-Server konfiguriert haben.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 und höher
--
Die Zeit manuell einstellen.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 und früher
--
Die Zeit manuell einstellen.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step11]]Speichern Sie die laufende Konfiguration in der Startkonfiguration:
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.Wie geht es weiter?
Nachdem Sie Ihre Schalter konfiguriert haben, können Sie link:configure-efos-software.html["Installieren Sie die EFOS-Software"]Die
