---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Führen Sie diese Schritte aus, um die Ethernet Fabric OS (EFOS)-Software auf dem BES-53248-Cluster-Switch zu installieren.' 
---
= Installieren Sie die EFOS-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie diese Schritte aus, um die Ethernet Fabric OS (EFOS)-Software auf dem BES-53248-Cluster-Switch zu installieren.

EFOS Software umfasst eine Reihe erweiterter Netzwerkfunktionen und Protokolle für die Entwicklung von Ethernet- und IP-Infrastruktursystemen. Diese Softwarearchitektur ist für jedes Netzwerkorganisationsgerät geeignet, das Anwendungen verwendet, die eine gründliche Paketinspektion oder -Trennung erfordern.



== Installation vorbereiten

.Bevor Sie beginnen
* Dieses Verfahren ist nur für Neuinstallationen geeignet.
* Laden Sie die entsprechende Broadcom EFOS-Software für Ihre Cluster-Switches von herunter https://www.broadcom.com/support/bes-switch["Unterstützung Für Broadcom Ethernet-Switches"^] Standort.
* Stellen Sie sicher, dass die link:configure-install-initial.html["Der BES-53248 Cluster-Switch ist konfiguriert"].




== Installieren Sie die Software

Verwenden Sie eine der folgenden Methoden, um die EFOS-Software zu installieren:

* <<Methode 1: EFOS installieren>>. In den meisten Fällen eingesetzt.
* <<Methode 2: Installieren Sie EFOS im ONIE-Modus>>. Verwenden Sie diese Option, wenn eine EFOS-Version FIPS-konform ist und die andere EFOS-Version nicht FIPS-konform ist.




=== Methode 1: EFOS installieren

Führen Sie die folgenden Schritte durch, um die EFOS-Software zu installieren.

.Schritte
. Loggen Sie sich beim seriellen Konsolenport des Switches ein oder stellen Sie eine Verbindung mit SSH her.
. Verwenden Sie die `ping` Befehl zum Überprüfen der Verbindung mit dem Server, der EFOS, Lizenzen und der RCF-Datei hostet.
+
.Beispiel anzeigen
[%collapsible]
====
In diesem Beispiel wird überprüft, ob der Switch mit der IP-Adresse 172.19.2 verbunden ist:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Laden Sie die Bilddatei auf den Switch herunter.
+
In der folgenden Tabelle finden Sie Informationen zu unterstützten Kopierprotokollen:

+
|===


| *Protokoll* | *Voraussetzung* 


 a| 
Trivial File Transfer Protocol (TFTP)
 a| 
Keine



 a| 
SSH File Transfer Protocol (SFTP)
 a| 
Ihr Softwarepaket muss die sichere Verwaltung unterstützen



 a| 
FTP
 a| 
Passwort erforderlich



 a| 
XMODEM
 a| 
Keine



 a| 
YMODEM
 a| 
Keine



 a| 
ZMODEM
 a| 
Keine



 a| 
Secure Copy Protocol (SCP)
 a| 
Ihr Softwarepaket muss die sichere Verwaltung unterstützen



 a| 
HTTP
 a| 
CLI-basierte Dateiübertragungen werden auf ausgewählten Plattformen unterstützt, wenn ein natives WGET-Dienstprogramm verfügbar ist



 a| 
HTTPS
 a| 
CLI-basierte Dateiübertragungen werden auf ausgewählten Plattformen unterstützt, wenn ein natives WGET-Dienstprogramm verfügbar ist

|===
+
Durch Kopieren der Bilddatei auf das aktive Image wird bei einem Neustart die aktuell ausgeführte EFOS-Version erstellt. Das vorherige Bild bleibt als Backup verfügbar.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Anzeigen der Boot-Images für die aktive und die Backup-Konfiguration:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Starten Sie den Switch neu:
+
`reload`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Melden Sie sich erneut an, und überprüfen Sie die neue Version der EFOS-Software:
+
`show version`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Schließen Sie die Installation ab.
Führen Sie die folgenden fünf Schritte aus, um den Switch neu zu konfigurieren:
+
.. link:configure-licenses.html["Installieren von Lizenzen"]
.. link:configure-install-rcf.html["Installieren Sie die RCF-Datei"]
.. link:configure-ssh.html["Aktivieren Sie SSH"]
.. link:CSHM_log_collection.html["Aktivieren Sie die Protokollerfassung"]
.. link:CSHM_snmpv3.html["Konfigurieren Sie SNMPv3 für die Überwachung"]


. Wiederholen Sie die Schritte 1 bis 7 auf dem Partner-Switch.




=== Methode 2: Installieren Sie EFOS im ONIE-Modus

Sie können die folgenden Schritte durchführen, wenn eine EFOS-Version FIPS-konform ist und die andere EFOS-Version nicht FIPS-konform ist. Mit diesen Schritten kann das nicht-FIPS- oder FIPS-konforme EFOS 3.7.x.x-Image von ONIE installiert werden, wenn der Switch nicht startet.

.Schritte
. Stellen Sie eine Verbindung zu einer Konsole her, die an den seriellen Port des Switches angeschlossen ist.
. Starten Sie den Schalter in den ONIE-Installationsmodus.
+
Wählen Sie während des Startvorgangs ONIE aus, wenn die Eingabeaufforderung angezeigt wird.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Nachdem Sie *ONIE* ausgewählt haben, lädt der Schalter und bietet Ihnen mehrere Auswahlmöglichkeiten. Wählen Sie *Betriebssystem installieren*.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Der Schalter startet in den ONIE-Installationsmodus.

. Beenden Sie die ONIE-Erkennung, und konfigurieren Sie die Ethernet-Schnittstelle.
+
Wenn die folgende Meldung angezeigt wird, drücken Sie *Enter*, um die ONIE-Konsole aufzurufen:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: Die ONIE-Erkennung wird fortgesetzt, und Meldungen werden an der Konsole gedruckt.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Konfigurieren Sie die Ethernet-Schnittstelle des Switch-Management-Ports, und fügen Sie die Route mithilfe hinzu `ifconfig eth0 <ipAddress> netmask <netmask> up` Und `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Stellen Sie sicher, dass der Server, der die ONIE-Installationsdatei hostet, erreichbar ist:
+
`ping`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installieren Sie die neue Switch-Software:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Die Software wird installiert und startet den Switch anschließend neu. Lassen Sie den Switch normal in die neue EFOS-Version neu starten.

. Melden Sie sich an, und überprüfen Sie, ob die neue Switch-Software installiert ist:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Schließen Sie die Installation ab.
Der Switch wird ohne angewendete Konfiguration neu gestartet und auf die Werkseinstellungen zurückgesetzt. Führen Sie die folgenden sechs Schritte aus, um den Switch neu zu konfigurieren:
+
.. link:configure-install-initial.html["Konfigurieren Sie den Switch"]
.. link:configure-licenses.html["Installieren von Lizenzen"]
.. link:configure-install-rcf.html["Installieren Sie die RCF-Datei"]
.. link:configure-ssh.html["Aktivieren Sie SSH"]
.. link:CSHM_log_collection.html["Aktivieren Sie die Protokollerfassung"]
.. link:CSHM_snmpv3.html["Konfigurieren Sie SNMPv3 für die Überwachung"]


. Wiederholen Sie die Schritte 1 bis 8 auf dem Partner-Switch.

