---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: Die Protokollerfassungsfunktion für die Cluster-Switch-Systemzustandsüberwachung wird verwendet, um mit dem Switch bezogene Protokolldateien in ONTAP zu erfassen. Die Einrichtung der Umgebung muss mithilfe der BES-53248 Cluster Switch CLI wie hier beschrieben erfolgen. 
---
= Aktivieren Sie die Protokollerfassungsfunktion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Protokollerfassungsfunktion verwenden, um Switch-bezogene Protokolldateien in ONTAP zu sammeln.


IMPORTANT: Um die Protokollerfassungsfunktion zu aktivieren, müssen Sie ONTAP Version 9.12.1 und höher sowie EFOS 3.8.0.2 und höher ausführen.

Stellen Sie sicher, dass Sie Ihre Umgebung mit dem BES-53248 Cluster Switch * CLI* eingerichtet haben.

.Schritte
. Erstellen Sie ein Passwort für die Protokollerfassungsfunktion der Ethernet-Switch-Statusüberwachung:
`system switch ethernet log setup-password`
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Aktivieren Sie die Funktion zur Statusüberwachung des Ethernet-Switches.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Warten Sie 10 Minuten, und überprüfen Sie dann, ob die Protokollsammlung mit dem folgenden Befehl abgeschlossen ist:

+
`system switch ethernet log show`

+

CAUTION: Wenn einer dieser Befehle einen Fehler zurückgibt oder die Protokollsammlung nicht abgeschlossen ist, wenden Sie sich an den NetApp Support.



.Was kommt als Nächstes?
Wenn Sie den Switch aktualisieren, gehen Sie zu link:replace-verify.html["Upgrade-Konfiguration überprüfen"].
