---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: Das Basismodell des Cluster-Switches BES-53248 ist für 16 10GbE- oder 25GbE-Ports und zwei 100GbE-Ports lizenziert.  Neue Häfen können durch den Kauf weiterer Lizenzen hinzugefügt werden. 
---
= Lizenzen für BES-53248 Cluster-Switches installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Basismodell des Cluster-Switches BES-53248 ist für 16 10GbE- oder 25GbE-Ports und zwei 100GbE-Ports lizenziert.  Sie können neue Ports hinzufügen, indem Sie weitere Lizenzen erwerben.


CAUTION: Für EFOS 3.12 und höher befolgen Sie die Installationsschritte inlink:efos-install-rcf-license-file.html["Installieren Sie die Referenzkonfigurationsdatei (RCF) und die Lizenzdatei."] Die



== Prüfen Sie die verfügbaren Lizenzen.

Für die Verwendung auf dem Cluster-Switch BES-53248 stehen folgende Lizenzen zur Verfügung:

[cols="1,2,3"]
|===
| Lizenztyp | Lizenzdetails | Unterstützte Firmware-Version 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Broadcom 8PT-10G25G + 2PT-40G100G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Broadcom 8-Port 10G25G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Broadcom 6-Port 40G100G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher

|===

NOTE: Um einen Transaktionsschlüssel für eine Portlizenzschlüsseldatei einzulösen, gehen Sie zulink:https://support.broadcom.com/web/csg/license-generation["Lizenzportal für Broadcom-unterstützte Ethernet-Switches"^] Seite. Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Broadcom-KBs/How_to_add_Additional_Port_Licensing_for_the_Broadcom_BES_53248_Switch["So fügen Sie zusätzliche Portlizenzen für den Broadcom BES-53248 Switch hinzu"^] für weitere Einzelheiten.



== Legacy-Lizenzen

Die folgende Tabelle listet die älteren Lizenzen auf, die für die Verwendung auf dem Cluster-Switch BES-53248 verfügbar waren:

[cols="1,2,3"]
|===
| Lizenztyp | Lizenzdetails | Unterstützte Firmware-Version 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25,2P40-100 Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.3.3 und höher



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25,4P40-100 Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.3.3 und höher



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-25,6P40-100 Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.3.3 und höher



 a| 
SW-BES54248-40-100G-LIC
 a| 
Broadcom 6-Port 40G100G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Broadcom 8Port 10G25G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Broadcom 16-Port 10G25G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Broadcom 24-Port 10G25G Lizenzschlüssel, X190005/R
 a| 
EFOS 3.4.4.6 und höher

|===

NOTE: Für die Basiskonfiguration ist keine Lizenz erforderlich.



== Lizenzdateien installieren

Befolgen Sie diese Schritte, um Lizenzen für BES-53248 Cluster-Switches zu installieren.

.Schritte
. Verbinden Sie den Cluster-Switch mit dem Management-Netzwerk.
. Verwenden Sie die `ping` Befehl zur Überprüfung der Verbindung zum Server, auf dem EFOS, Lizenzen und die RCF-Datei gehostet werden.
+
.Beispiel anzeigen
[%collapsible]
====
Dieses Beispiel überprüft, ob der Switch mit dem Server unter der IP-Adresse 172.19.2.1 verbunden ist:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Überprüfen Sie die aktuelle Lizenznutzung auf Switch CS2:
+
`show license`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. Installieren Sie die Lizenzdatei.
+
Wiederholen Sie diesen Schritt, um weitere Lizenzen zu laden und andere Schlüsselindexnummern zu verwenden.

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird SFTP verwendet, um eine Lizenzdatei auf einen Schlüsselindex 1 zu kopieren.

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. Zeigen Sie alle aktuellen Lizenzinformationen an und notieren Sie den Lizenzstatus, bevor Switch CS2 neu gestartet wird:
+
`show license`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. Alle lizenzierten Ports anzeigen:
+
`show port all | exclude Detach`

+
Die Ports aus den zusätzlichen Lizenzdateien werden erst nach einem Neustart des Switches angezeigt.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. Starten Sie den Switch neu:
+
`reload`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. Prüfen Sie, ob die neue Lizenz aktiv ist und vermerken Sie, dass die Lizenz angewendet wurde:
+
`show license`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. Prüfen Sie, ob alle neuen Ports verfügbar sind:
+
`show port all | exclude Detach`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: Bei der Installation zusätzlicher Lizenzen müssen Sie die neuen Schnittstellen manuell konfigurieren.  Ein RCF darf nicht erneut auf einen bereits funktionierenden Produktionsschalter angewendet werden.



== Behebung von Installationsproblemen

Wenn bei der Installation einer Lizenz Probleme auftreten, führen Sie die folgenden Debug-Befehle aus, bevor Sie die Lizenz installieren. `copy` Den Befehl erneut geben.

Zu verwendende Debug-Befehle: `debug transfer` Und `debug license`

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
Wenn Sie die `copy` Befehl mit dem `debug transfer` Und `debug license` Wenn diese Optionen aktiviert sind, wird die Protokollausgabe zurückgegeben.

.Beispiel anzeigen
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
Prüfen Sie in der Debug-Ausgabe Folgendes:

* Prüfen Sie, ob die Seriennummer übereinstimmt: `Serial number QTFCU38290012 matched.`
* Prüfen Sie, ob das Schaltermodell übereinstimmt: `Model BES-53248 matched.`
* Prüfen Sie, ob der angegebene Lizenzindex nicht bereits verwendet wurde.  Wenn bereits ein Lizenzindex verwendet wird, wird folgender Fehler zurückgegeben: `License file /mnt/download//license.dat.1 already exists.`
* Eine Portlizenz ist keine Funktionslizenz.  Daher ist folgende Aussage zu erwarten: `Feature not found in license file with index = 1.`


Verwenden Sie die `copy` Befehl zum Sichern der Portlizenzen auf dem Server:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: Falls Sie die Switch-Software von Version 3.4.4.6 downgraden müssen, werden die Lizenzen entfernt.  Dies ist ein erwartbares Verhalten.

Bevor Sie auf eine ältere Version der Software zurückgreifen können, müssen Sie eine entsprechende ältere Lizenz installieren.



== Aktivieren Sie neu lizenzierte Ports

Um neu lizenzierte Ports zu aktivieren, müssen Sie die neueste Version der RCF bearbeiten und die entsprechenden Portdetails einkommentieren.

Die Standardlizenz aktiviert die Ports 0/1 bis 0/16 und 0/55 bis 0/56, während die neu lizenzierten Ports je nach Art und Anzahl der verfügbaren Lizenzen zwischen den Ports 0/17 und 0/54 liegen.  Um beispielsweise die Lizenz SW-BES54248-40-100G-LIC zu aktivieren, müssen Sie den folgenden Abschnitt in der RCF-Datei einkommentieren:

.Beispiel anzeigen
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: Bei Hochgeschwindigkeitsports zwischen 0/49 und 0/54 (einschließlich) entfernen Sie die Kommentarzeichen vor jedem Port, jedoch nur vor einer *speed*-Zeile in der RCF für jeden dieser Ports, entweder: *speed 100G full-duplex* oder *speed 40G full-duplex*, wie im Beispiel gezeigt.  Bei langsamen Ports zwischen 0/17 und 0/48 (einschließlich) muss der gesamte Abschnitt mit 8 Ports einkommentiert werden, sobald eine entsprechende Lizenz aktiviert wurde.

.Wie geht es weiter?
Nach der Installation der Lizenzen können Sie link:configure-install-rcf.html["Installieren Sie die Referenzkonfigurationsdatei (RCF)."] oder link:upgrade-rcf.html["RCF aufrüsten"]Die
