---
permalink: switch-bes-53248/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation,BES-53248 Broadcom setup,BES-53248 switches configuration,EFOS 
summary: 'Die Funktion zur Protokollerfassung des Ethernet Switch Health Monitor (CSHM) wird verwendet, um Protokolle von Cluster- oder Speichernetzwerk-Switches in ONTAP zu erfassen.' 
---
= Protokollerfassung für die Zustandsüberwachung von Ethernet-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Ethernet Switch Health Monitor (CSHM) ist dafür zuständig, den Betriebszustand der Cluster- und Speichernetzwerk-Switches sicherzustellen und Switch-Protokolle zu Debugging-Zwecken zu sammeln.  Dieses Verfahren führt Sie durch den Prozess der Einrichtung und des Starts der Erfassung detaillierter *Support*-Protokolle vom Switch und startet eine stündliche Erfassung von *periodischen* Daten, die von AutoSupport erfasst werden.

.Bevor Sie beginnen
* Um die Protokollerfassungsfunktion zu aktivieren, müssen Sie ONTAP Version 9.10.1P15, 9.11.1P12 oder 9.12.1 oder höher und EFOS 3.8.0.2 oder höher verwenden.
* Die Zustandsüberwachung des Switches muss aktiviert sein.  Überprüfen Sie dies, indem Sie sicherstellen, dass `Is Monitored:` Das Feld wird in der Ausgabe auf *true* gesetzt. `system switch ethernet show` Befehl.


.Schritte
. Um die Protokollerfassung einzurichten, führen Sie für jeden Switch den folgenden Befehl aus.  Sie werden aufgefordert, den Switch-Namen, den Benutzernamen und das Passwort für die Protokollerfassung einzugeben.
+
`system switch ethernet log setup-password`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Um die Protokollerfassung zu starten, führen Sie den folgenden Befehl aus und ersetzen Sie DEVICE durch den im vorherigen Befehl verwendeten Schalter.  Damit werden beide Arten der Protokollerfassung gestartet: die detaillierten *Support*-Protokolle und eine stündliche Erfassung von *periodischen* Daten.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Warten Sie 10 Minuten und überprüfen Sie dann, ob die Protokollerfassung abgeschlossen ist:

+
`system switch ethernet log show`

+

CAUTION: Falls einer dieser Befehle einen Fehler zurückgibt oder die Protokollerfassung nicht abgeschlossen wird, wenden Sie sich an den NetApp -Support.



.Fehlerbehebung
Wenn Sie auf einen der folgenden Fehlerstatus stoßen, die von der Protokollerfassungsfunktion gemeldet werden (sichtbar in der Ausgabe von `system switch ethernet log show` ), versuchen Sie die entsprechenden Debugging-Schritte:

|===


| *Fehlerstatus bei der Protokollerfassung* | *Auflösung* 


 a| 
*RSA-Schlüssel nicht vorhanden*
 a| 
ONTAP SSH-Schlüssel neu generieren. Wenden Sie sich an den NetApp Support.



 a| 
*Fehler beim Switch-Passwort*
 a| 
Überprüfen Sie die Anmeldeinformationen, testen Sie die SSH-Verbindung und generieren Sie die ONTAP SSH-Schlüssel neu.  Lesen Sie die Dokumentation zum Switch oder kontaktieren Sie den NetApp Support, um weitere Anweisungen zu erhalten.



 a| 
*ECDSA-Schlüssel für FIPS nicht vorhanden*
 a| 
Wenn der FIPS-Modus aktiviert ist, müssen auf dem Switch ECDSA-Schlüssel generiert werden, bevor ein erneuter Versuch unternommen werden kann.



 a| 
*Vorhandenes Protokoll gefunden*
 a| 
Entfernen Sie die vorherige Protokolldatei auf dem Switch.



 a| 
*Fehler im Switch-Dump-Protokoll*
 a| 
Stellen Sie sicher, dass der Switch-Benutzer über die Berechtigung zur Protokollerfassung verfügt.  Beachten Sie die oben genannten Voraussetzungen.

|===