---
permalink: switch-bes-53248/index.html 
sidebar: sidebar 
keywords: broadcom, support, bes, cluster, switch, broadcam-supported bes-53248 cluster switches 
summary: Für die Installation und Wartung von BES-53248 Switches sollten Sie die Unterstützung des Betriebssystems, die Teilenummern, die Konfigurationsanforderungen und die Dokumentationsanforderungen prüfen. 
---
= Überblick und Anforderungen: BES-53248 Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung von BES-53248 Switches sollten Sie die Unterstützung des Betriebssystems, die Teilenummern, die Konfigurationsanforderungen und die Dokumentationsanforderungen prüfen.



== Unterstützung von Betriebssystemen (OS)

Der BES-53248-Switch unterstützt Folgendes:

* * EFOS Firmware 3.4.4.6 und höher*. Der BES-53248-Switch wird auf einem in Broadcom eingebetteten Betriebssystem ausgeführt, das als Ethernet Fabric OS (EFOS) bekannt ist. Die Unterstützung für 40/100-GbE-Cluster-Ports beginnt mit der EFOS-Firmware-Version 3.4.4.6 und höher.
* *ONTAP 9.5P8 und höher*. Die von Broadcom unterstützten BES-53248-Cluster-Switches sind für den Einsatz in Clustern mit einer Größe von zwei bis 24 Nodes in ONTAP 9.5P8 und höher konzipiert.




== Teilenummern für Switch-Komponenten wechseln

In der folgenden Tabelle sind die Teilenummer und Beschreibung der BES-53248-Cluster-Switch-Komponenten aufgeführt, einschließlich Rack-montierter Schienen-Kit, Lüfter und Netzteile.

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25 GB, PTSX, BRDCM-SUPPORT (PTSX = Port Side Exhaust)



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25 GB, PSIN, BRDCM-SUPPORT (PSIN = Port Side Intake)



 a| 
X-RAIL-4POST-190005
 a| 
Rack Mount Rail Kit Ozeki 4 Post 19 Zoll



 a| 
X-FAN-190005-R
 a| 
Lüfter, Anschlußseite X190005



 a| 
X-FAN-190005-F
 a| 
Lüfter, Auslass auf der Anschlussseite X190005



 a| 
X-PSU-190005-R
 a| 
Netzteil, Anschlusseingang X190005

Ansaugluftstrom (Umkehrluft): Kühle Luft tritt durch das Anschlussende im Kaltgang in das Gehäuse ein und entgastet durch die Lüfter- und Stromversorgungsmodule im heißen Gang.



 a| 
X-PSU-190005-F
 a| 
Netzteil, Auspuff an der Anschlussseite X190005

Anschlussseitiger Abluftstrom (Standardluft): Kühle Luft tritt durch die Lüfter- und Stromversorgungsmodule im Kaltgang in das Gehäuse ein und entgast durch das Anschlussende des Gehäuses im heißen Gang. Die blaue Färbung zeigt die Luftzirkulation an der Anschlussseite an. Dies ist die am häufigsten verwendete Option.

|===


== Konfigurationsanforderungen

Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Cluster-Switches. Je nach Art des zu Beginn konfigurierende Cluster Switch müssen Sie mit dem enthaltenen Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen und spezielle Netzwerkinformationen benötigen.

.Zuweisung von Cluster-Switch-Ports
Sie können die von Broadcom unterstützte Tabelle zur Konfiguration des Clusters für die Zuweisung von BES-53248-Cluster-Switches als Leitfaden verwenden.

[cols="1,2"]
|===
| Switch-Ports | Anzahl der Ports 


 a| 
01-16
 a| 
10/25-GbE-Cluster-Port-Nodes, Basiskonfiguration



 a| 
17-48
 a| 
10/25-GbE-Cluster-Port-Nodes, mit Lizenzen



 a| 
49-54
 a| 
100-GbE-Cluster-Port-Nodes mit Lizenzen, die links hinzugefügt wurden



 a| 
55-56
 a| 
Ports mit 100 GbE Cluster Inter-Switch Link (ISL), Basiskonfiguration

|===
.Einschränkung bei der Geschwindigkeit der Port-Gruppe
Bei BES-53248 Cluster Switches werden die 48 10/25-GbE-Ports (SFP28/SFP+) wie folgt in 12 x 4-Port-Gruppen kombiniert: 1–4 Ports, 5–8, 9–12, 13–16, 17–20, 21–24, 25–28, 29–32, 33–36, 37–40, 41-44 und 45-48.

Die Port-Geschwindigkeit von SFP28/SFP+ muss für alle Ports der 4-Port-Gruppe gleich (10 GbE oder 25 GbE) sein.



== Dokumentationsanforderungen

Zum Einrichten eines BES-53248 Cluster Switch und eines ONTAP Clusters benötigen Sie spezifische Switch- und Controller-Dokumentation.



=== Broadcom-Dokumentation

Zum Einrichten des BES-53248-Cluster-Switches benötigen Sie die folgenden Dokumente, die über die Broadcom Support Site verfügbar sind: https://www.broadcom.com/support/bes-switch["Produkte Der Broadcom Ethernet-Switches-Reihe"^]

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
_EFOS Administratorhandbuch v3.4.3_
 a| 
Enthält Beispiele für die Verwendung des BES-53248-Switches in einem typischen Netzwerk.



 a| 
_EFOS CLI Command Reference v3.4.3_
 a| 
Beschreibt die Befehle der Befehlszeilenschnittstelle (CLI), mit denen Sie die BES-53248-Software anzeigen und konfigurieren können.



 a| 
_EFOS Handbuch erste Schritte v3.4.3_
 a| 
Enthält detaillierte Informationen zum BES-53248-Switch.



 a| 
_EFOS SNMP-Referenzhandbuch v3.4.3_
 a| 
Enthält Beispiele für die Verwendung des BES-53248-Switches in einem typischen Netzwerk.



 a| 
_EFOS-Skalierungsparameter und Werte v3.4.3_
 a| 
Beschreibt die Standard-Skalierungsparameter, mit denen EFOS-Software auf den unterstützten Plattformen bereitgestellt und validiert wird.



 a| 
_EFOS Funktionsspezifikationen v3.4.3_
 a| 
Beschreibt die Spezifikationen für die EFOS-Software auf den unterstützten Plattformen.



 a| 
_EFOS Release Notes Version 3.4.3_
 a| 
Enthält Release-spezifische Informationen zur BES-53248-Software.



 a| 
_Kompatibilitätsmatrix für Cluster-Netzwerk und Management-Netzwerk_
 a| 
Bietet Informationen zur Netzwerkkompatibilität. Die Matrix ist über die BES-53248 Switch Download-Site unter erhältlich https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom Cluster-Switches"^].

|===


=== Dokumentation zu ONTAP Systemen und KB-Artikel

Um ein ONTAP System einzurichten, benötigen Sie die folgenden Dokumente über die NetApp Support Site unter http://mysupport.netapp.com/["mysupport.netapp.com"^] Oder die Knowledgebase (KB)-Website unter https://kb.netapp.com/["kb.netapp.com"^].

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]
 a| 
Beschreibt die Anforderungen an Stromversorgung und Standort für die gesamte NetApp Hardware, einschließlich System-Cabinets, und bietet Informationen zu den entsprechenden Anschlüssen und Kabeloptionen zur Verwendung zusammen mit den Teilenummern.



 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP 9
 a| 
Enthält ausführliche Informationen zu allen Aspekten der Version ONTAP 9.



 a| 
_Hinzufügen zusätzlicher Portlizenzen für den von Broadcom unterstützten BES-53248 Switch_
 a| 
Enthält detaillierte Informationen zum Hinzufügen von Portlizenzen. Wechseln Sie zum https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["KB-Artikel"^].

|===