---
permalink: switch-bes-53248/migrate-cn1610-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches,replacing with BES-53248 switches, migrate cluster switches 
summary: Wenn Sie CN1610 Cluster-Switches zu von Broadcom unterstützten BES-53248 Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten. 
---
= Migrieren Sie die CN1610 Cluster-Switches auf von Broadcom unterstützte BES-53248 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie CN1610 Cluster-Switches zu von Broadcom unterstützten BES-53248 Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten.

* Folgende Cluster-Switches werden unterstützt:
+
** CN1610
** BES-53248


* Die Cluster-Switches unterstützen die folgenden Node-Verbindungen:
+
** NetApp CN1610: 0/1 bis 0/12 (10 GbE)
** BES-53248: 0/1-0/16 Ports (10/25 GbE)
+

NOTE: Zusätzliche Ports können durch den Kauf von Portlizenzen aktiviert werden.



* Bei den Cluster-Switches werden die folgenden Inter-Switch-Link-Ports (ISL) verwendet:
+
** NetApp CN1610: 0/13 bis 0/16 (10 GbE)
** BES-53248: 0/55–0/56 Ports (100 GbE)


* Der https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe_"^] Enthält Informationen zur ONTAP-Kompatibilität, zu unterstützter EFOS-Firmware und zur Verkabelung mit BES-53248-Cluster-Switches.
* Die entsprechende ISL-Verkabelung lautet wie folgt:
+
** *Beginn:* für CN1610 bis CN1610 (SFP+ auf SFP+), vier SFP+-Glasfaserkabel oder Kupfer-Direct-Attach-Kabel.
** *Interim:* für CN1610 bis BES-53248 (SFP+ zu SFP28), vier optische 10G SFP+ Transceiver/Glasfaser oder Kupfer Direct-Attach Kabel.
** *Endfassung:* für BES-53248 bis BES-53248 (QSFP28 zu QSFP28), zwei optische QSFP28-Transceiver/Glasfaser oder Kupfer-Direct-Attach-Kabel.





NOTE: Nach Abschluss der Migration müssen Sie möglicherweise die erforderliche Konfigurationsdatei installieren, um den Cluster Switch Health Monitor (CSHM) für BES-53248 Cluster Switches zu unterstützen.

Siehe link:configure-health-monitor.html["Installieren Sie die Konfigurationsdatei des Cluster Switch Health Monitor (CSHM)"] Und link:configure-log-collection.html["Konfigurieren Sie die Protokollerfassung für den Cluster-Switch"] Für die Schritte, die erforderlich sind, um die Protokollerfassung des Cluster-Zustandsschalters zu aktivieren, die zum Erfassen von Switch-bezogenen Protokolldateien verwendet wird.
