---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters,migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches,migrating two-node switched clusters,2-node 
summary: Wenn Sie über ein 2-Node-Cluster ohne Switches verfügen, können Sie unterbrechungsfrei auf ein 2-Node-Cluster mit Switches migrieren, das von Broadcom unterstützte BES-53248 Cluster-Switches enthält. Der dokumentierte Prozess funktioniert bei allen Cluster-Node-Ports mit optischen oder Twinax-Ports, wird bei diesem Switch jedoch nicht unterstützt, wenn Knoten integrierte 10GBASE-T RJ45-Ports für die Cluster-Netzwerk-Ports verwenden. 
---
= Migration zu einem Switch-basierten Cluster mit zwei Nodes mit von Broadcom unterstützten BES-53248-Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie über ein 2-Node-Cluster ohne Switches verfügen, können Sie unterbrechungsfrei auf ein 2-Node-Cluster mit Switches migrieren, das von Broadcom unterstützte BES-53248 Cluster-Switches enthält. Der dokumentierte Prozess funktioniert bei allen Cluster-Node-Ports mit optischen oder Twinax-Ports, wird bei diesem Switch jedoch nicht unterstützt, wenn Knoten integrierte 10GBASE-T RJ45-Ports für die Cluster-Netzwerk-Ports verwenden.

Die meisten Systeme benötigen an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports.

Vergewissern Sie sich, dass der BES-53248-Cluster-Switch wie unter beschrieben eingerichtet ist link:replace-requirements.html["Von Broadcom unterstützte BES-53248-Switches Einrichtung und Konfiguration"^] Bevor Sie mit diesem Migrationsprozess beginnen.


NOTE: Nach Abschluss der Migration müssen Sie möglicherweise die erforderliche Konfigurationsdatei installieren, um den Cluster Switch Health Monitor (CSHM) für BES-53248 Cluster Switches zu unterstützen.

Siehe link:configure-health-monitor.html["Installieren Sie die Konfigurationsdatei des Cluster Switch Health Monitor (CSHM)"] Und link:configure-log-collection.html["Konfigurieren Sie die Protokollerfassung für den Cluster-Switch"] Für die Schritte, die erforderlich sind, um die Protokollerfassung des Cluster-Zustandsschalters zu aktivieren, die zum Erfassen von Switch-bezogenen Protokolldateien verwendet wird.
