---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: Um die vorhandenen CN1610-Cluster-Switches in einem Cluster durch Broadcom-unterstützte BES-53248-Cluster-Switches zu ersetzen, müssen Sie eine bestimmte Abfolge von Aufgaben durchführen. 
---
= CN1610-Cluster-Switches auf BES-53248-Cluster-Switches migrieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die CN1610-Cluster-Switches in einem Cluster auf Broadcom-unterstützte BES-53248-Cluster-Switches zu migrieren, überprüfen Sie die Migrationsanforderungen und folgen Sie dann dem Migrationsverfahren.

Folgende Cluster-Switches werden unterstützt:

* CN1610
* BES-53248




== Überprüfungsanforderungen

Vergewissern Sie sich, dass Ihre Konfiguration die folgenden Anforderungen erfüllt:

* Einige der Ports der BES-53248-Switches sind für den Betrieb mit 10GbE konfiguriert.
* Die 10GbE-Konnektivität von den Knoten zu den BES-53248 Cluster-Switches wurde geplant, migriert und dokumentiert.
* Der Cluster ist voll funktionsfähig (es sollten keine Fehler in den Protokollen oder ähnliche Probleme auftreten).
* Die Erstkonfiguration der BES-53248-Switches ist abgeschlossen, sodass:
+
** Die BES-53248-Switches verwenden die neueste empfohlene Version der EFOS-Software.
** Referenzkonfigurationsdateien (RCFs) wurden auf die Switches angewendet.
** Sämtliche Standortanpassungen, wie z. B. DNS, NTP, SMTP, SNMP und SSH, werden auf den neuen Switches konfiguriert.






=== Knotenverbindungen

Die Cluster-Switches unterstützen folgende Knotenverbindungen:

* NetApp CN1610: Ports 0/1 bis 0/12 (10GbE)
* BES-53248: Ports 0/1-0/16 (10GbE/25GbE)
+

NOTE: Zusätzliche Ports können durch den Kauf von Portlizenzen aktiviert werden.





=== ISL-Ports

Die Cluster-Switches verwenden die folgenden Inter-Switch-Link-Ports (ISL):

* NetApp CN1610: Ports 0/13 bis 0/16 (10GbE)
* BES-53248: Ports 0/55-0/56 (100GbE)


Der https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe_"^] Enthält Informationen zur ONTAP Kompatibilität, zur unterstützten EFOS-Firmware und zur Verkabelung von BES-53248 Cluster-Switches.



=== ISL-Verkabelung

Die entsprechende ISL-Verkabelung sieht wie folgt aus:

* *Anfang:* Für CN1610 zu CN1610 (SFP+ zu SFP+) vier SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel.
* *Final:* Für BES-53248 zu BES-53248 (QSFP28 zu QSFP28), zwei QSFP28 optische Transceiver/Glasfaser- oder Kupfer-Direktanschlusskabel.




== Migrieren Sie die Schalter

Gehen Sie wie folgt vor, um CN1610-Cluster-Switches auf BES-53248-Cluster-Switches zu migrieren.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die Beispiele verwenden zwei Knoten, von denen jeder zwei 10-GbE-Cluster-Verbindungsports bereitstellt: `e0a` Und `e0b` Die
* Die Befehlsausgaben können je nach Version der ONTAP -Software variieren.
* Die auszutauschenden CN1610-Schalter sind `CL1` Und `CL2` Die
* Die BES-53248-Schalter als Ersatz für die CN1610-Schalter sind `cs1` Und `cs2` Die
* Die Knoten sind `node1` Und `node2` Die
* Zuerst wird der Schalter CL2 durch cs2 ersetzt, dann CL1 durch cs1.
* Die BES-53248 Switches sind mit den unterstützten Versionen der Reference Configuration File (RCF) und des Ethernet Fabric OS (EFOS) vorinstalliert, wobei ISL-Kabel an den Ports 55 und 56 angeschlossen sind.
* Die Cluster-LIF-Namen sind `node1_clus1` Und `node1_clus2` für Knoten1 und `node2_clus1` Und `node2_clus2` für Knoten 2.


.Informationen zu diesem Vorgang
Dieses Verfahren umfasst folgendes Szenario:

* Der Cluster beginnt mit zwei Knoten, die mit zwei CN1610 Cluster-Switches verbunden sind.
* Der CN1610-Schalter CL2 wird durch den BES-53248-Schalter cs2 ersetzt:
+
** Schalten Sie die Ports zu den Clusterknoten ab.  Um eine Instabilität des Clusters zu vermeiden, müssen alle Ports gleichzeitig abgeschaltet werden.
** Trennen Sie die Kabel von allen Cluster-Ports auf allen mit CL2 verbundenen Knoten und verwenden Sie dann unterstützte Kabel, um die Ports wieder mit dem neuen Cluster-Switch cs2 zu verbinden.


* Der CN1610-Schalter CL1 wird durch den BES-53248-Schalter cs1 ersetzt:
+
** Schalten Sie die Ports zu den Clusterknoten ab.  Um eine Instabilität des Clusters zu vermeiden, müssen alle Ports gleichzeitig abgeschaltet werden.
** Trennen Sie die Kabel von allen Cluster-Ports auf allen mit CL1 verbundenen Knoten und verwenden Sie dann unterstützte Kabel, um die Ports wieder mit dem neuen Cluster-Switch cs1 zu verbinden.





NOTE: Während dieses Vorgangs ist kein betriebsbereiter Inter-Switch-Link (ISL) erforderlich. Dies ist beabsichtigt, da RCF-Versionsänderungen die ISL-Konnektivität vorübergehend beeinträchtigen können. Um einen unterbrechungsfreien Clusterbetrieb zu gewährleisten, migriert das folgende Verfahren alle Cluster-LIFs zum operativen Partner-Switch, während die Schritte auf dem Ziel-Switch ausgeführt werden.



=== Schritt 1: Vorbereitung auf die Migration

. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
wobei x die Dauer des Wartungsfensters in Stunden ist.

+

NOTE: Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

+
Der folgende Befehl unterdrückt die automatische Fallerstellung für zwei Stunden:

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie *y* eingeben, wenn Sie zur Fortsetzung aufgefordert werden:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.





=== Schritt 2: Anschlüsse und Verkabelung konfigurieren

. Prüfen Sie an den neuen Switches, ob die ISL-Verbindung zwischen den Switches cs1 und cs2 hergestellt und funktionsfähig ist:
+
`show port-channel`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die ISL-Ports am Switch cs1 *aktiv* sind:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
Das folgende Beispiel zeigt, dass die ISL-Ports am Switch cs2 *aktiv* sind:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Zeigen Sie die Cluster-Ports auf jedem Knoten an, der mit den vorhandenen Cluster-Switches verbunden ist:
+
`network device-discovery show -protocol cdp`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie viele Cluster-Interconnect-Schnittstellen in jedem Knoten für jeden Cluster-Interconnect-Switch konfiguriert wurden:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. Ermitteln Sie den administrativen oder operativen Status jeder Clusterschnittstelle.
+
.. Überprüfen Sie, ob alle Cluster-Ports aktiv sind. `up` mit einem `healthy` Status:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Überprüfen Sie, ob alle Cluster-Schnittstellen (LIFs) an ihren jeweiligen Heimatports angeschlossen sind:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Überprüfen Sie, ob der Cluster Informationen für beide Cluster-Switches anzeigt:


[role="tabbed-block"]
====
.ONTAP 9.8 und höher
--
Ab ONTAP 9.8 verwenden Sie folgenden Befehl: `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 und früher
--
Für ONTAP 9.7 und ältere Versionen verwenden Sie folgenden Befehl: `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]Automatische Rücksetzung der Cluster-LIFs deaktivieren.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. Schalten Sie auf dem Cluster-Switch CL2 die mit den Cluster-Ports der Knoten verbundenen Ports ab, um ein Failover der Cluster-LIFs zu erzwingen:
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. Überprüfen Sie, ob die Cluster-LIFs auf die Ports des Cluster-Switches CL1 umgeschaltet haben. Dies kann einige Sekunden dauern.
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Verlegen Sie alle Cluster-Knotenverbindungskabel vom alten CL2-Switch zum neuen cs2-Switch.
. Überprüfen Sie den Zustand der auf CS2 verschobenen Netzwerkverbindungen:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Alle verschobenen Cluster-Ports sollten `up` Die

. Überprüfen Sie die Nachbarinformationen an den Cluster-Ports:
+
`network device-discovery show -protocol cdp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. Prüfen Sie aus Sicht des Switches CS2, ob die Portverbindungen des Switches einwandfrei funktionieren:
+
[listing, subs="+quotes"]
----
cs2# *show interface all*
cs2# *show isdp neighbors*
----
. Schalten Sie auf dem Cluster-Switch CL1 die mit den Cluster-Ports der Knoten verbundenen Ports ab, um ein Failover der Cluster-LIFs durchzuführen:
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
Alle Cluster-LIFs schalten auf den Switch cs2 um.

. Überprüfen Sie, ob für die Cluster-LIFs ein Failover auf die auf Switch cs2 gehosteten Ports durchgeführt wurde. Dies kann einige Sekunden dauern:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Verlegen Sie die Cluster-Knoten-Verbindungskabel von CL1 zum neuen Switch cs1.
. Überprüfen Sie den Zustand der Netzwerkverbindungen, die zu CS1 verschoben wurden:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Alle verschobenen Cluster-Ports sollten `up` Die

. Überprüfen Sie die Nachbarinformationen an den Cluster-Ports:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. Prüfen Sie aus Sicht des Switches cs1, ob die Portverbindungen des Switches einwandfrei funktionieren:
+
[listing, subs="+quotes"]
----
cs1# *show interface all*
cs1# *show isdp neighbors*
----
. Überprüfen Sie, ob die ISL zwischen cs1 und cs2 noch funktionsfähig ist:
+
`show port-channel`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die ISL-Ports am Switch cs1 *aktiv* sind:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
Das folgende Beispiel zeigt, dass die ISL-Ports am Switch cs2 *aktiv* sind:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Löschen Sie die ersetzten CN1610-Switches aus der Switch-Tabelle des Clusters, falls sie nicht automatisch entfernt werden:


[role="tabbed-block"]
====
.ONTAP 9.8 und höher
--
Ab ONTAP 9.8 verwenden Sie folgenden Befehl: `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 und früher
--
Für ONTAP 9.7 und ältere Versionen verwenden Sie folgenden Befehl: `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== Schritt 3: Konfiguration überprüfen

. Automatische Wiederherstellung der Cluster-LIFs aktivieren.
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. Auf Switch cs2 müssen alle Cluster-Ports heruntergefahren und neu gestartet werden, um eine automatische Rücksetzung aller Cluster-LIFs auszulösen, die sich nicht an ihren Home-Ports befinden.
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. Überprüfen Sie, ob die Cluster-LIFs wieder auf ihre ursprünglichen Ports zurückgesetzt wurden (dies kann eine Minute dauern):
+
`network interface show -vserver Cluster`

+
Falls eine der Cluster-LIFs nicht auf ihren Heimatport zurückgesetzt wurde, setzen Sie sie manuell zurück. Sie müssen eine Verbindung zur jeweiligen Node-Management-LIF- oder SP/ BMC -Systemkonsole des lokalen Knotens herstellen, dem die LIF gehört:

+
`network interface revert -vserver Cluster -lif *`

. Überprüfen Sie, ob der Cluster fehlerfrei funktioniert:
+
`cluster show`

. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können die `network interface check cluster-connectivity` Befehl zum Starten einer Zugriffsprüfung für die Clusterkonnektivität und anschließenden Anzeigen der Details:

`network interface check cluster-connectivity start`Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Vorgang ausführen. `show` Befehl zum Anzeigen der Details.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Alle ONTAP Versionen
--
Für alle ONTAP Versionen können Sie auch die `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Verbindung:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]]Wenn Sie die automatische Fallerstellung unterdrückt haben, aktivieren Sie sie wieder, indem Sie eine AutoSupport Nachricht aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.Wie geht es weiter?
Nach der Migration Ihrer Switches können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
