---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: Sie können das RCF nach dem ersten Einrichten des BES-53248 Cluster-Switch und nach der Anwendung der neuen Lizenz oder Lizenzen installieren. Wenn Sie ein RCF von einer älteren Version aktualisieren, werden die Dateien effektiv zusammengeführt und Sie führen die hier beschriebenen Schritte aus. 
---
= Installieren Sie die Referenzkonfigurationsdatei (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das RCF nach dem ersten Einrichten des BES-53248 Cluster-Switch und nach der Anwendung der neuen Lizenz oder Lizenzen installieren. Wenn Sie ein RCF von einer älteren Version aktualisieren, müssen Sie die Broadcom-Switch-Einstellungen zurücksetzen und die Grundkonfiguration durchführen, um das RCF erneut anzuwenden. Sie müssen diesen Vorgang jedes Mal durchführen, wenn Sie ein RCF aktualisieren oder ändern möchten. Siehe folgendes https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["KB-Artikel"^] Entsprechende Details.



== Setzen Sie den Broadcom IP-Switch auf die Werkseinstellungen zurück

Bevor Sie eine neue Switch-Softwareversion und RCFs installieren, müssen Sie die Broadcom-Switch-Einstellungen löschen und eine grundlegende Konfiguration durchführen.

.Über diese Aufgabe
* Sie müssen diese Schritte bei jedem der Cluster-Switches wiederholen.
* Sie müssen über die serielle Konsole mit dem Switch verbunden sein.
* Mit dieser Aufgabe wird die Konfiguration des Managementnetzwerks zurückgesetzt.


.Schritte
. Wechseln Sie zur erhöhten Eingabeaufforderung (`#`): `enable`
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)#
----
. Löschen Sie die Startkonfiguration, und entfernen Sie das Banner
+
.. Löschen der Startkonfiguration:
+
*`erase startup-config`*

+
[listing, subs="+quotes"]
----
(cs2)# *erase startup-config*
Are you sure you want to clear the configuration? (y/n) *y*
(cs2)#
----
+
Dieser Befehl löscht das Banner nicht.

.. Entfernen Sie das Banner:
+
*`no set clibanner`*

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *no set clibanner*
(cs2)(Config)#
----


. Starten Sie den Switch neu:*`(cs2) #reload*`
+
[listing, subs="+quotes"]
----
Are you sure you would like to reset the system? (y/n) *y*
----
+

NOTE: Wenn das System fragt, ob die nicht gespeicherte oder geänderte Konfiguration vor dem erneuten Laden des Switches gespeichert werden soll, wählen Sie *Nein* aus.

. Warten Sie, bis der Schalter neu geladen wurde, und melden Sie sich dann am Switch an.
+
Der Standardbenutzer lautet „`admin`“, und es ist kein Passwort festgelegt. Es wird eine Eingabeaufforderung wie die folgende angezeigt:

+
[listing]
----
(Routing)>
----
. Zur erhöhten Eingabeaufforderung wechseln:
+
`enable`

+
[listing, subs="+quotes"]
----
Routing)> *enable*
(Routing)#
----
. Legen Sie das Service-Port-Protokoll auf fest `none`:
+
`serviceport protocol none`

+
[listing, subs="+quotes"]
----
(Routing)# *serviceport protocol none*
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) *y*
(Routing) #
----
. Weisen Sie die IP-Adresse dem Service-Port zu:
+
`serviceport ip _ip-address_ _netmask_ _gateway_`

+
Das folgende Beispiel zeigt eine dem Service-Port zugewiesene IP-Adresse „10.10.10.10“ mit dem Subnetz „255.255.255.0“ und dem Gateway „10.10.10.1“:

+
[listing, subs="+quotes"]
----
(Routing)# *serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1*
----
. Überprüfen Sie, ob der Service-Port ordnungsgemäß konfiguriert ist:
+
`show serviceport`

+
Das folgende Beispiel zeigt, dass der Port als aktiv ist und die richtigen Adressen zugewiesen wurden:

+
[listing, subs="+quotes"]
----
(Routing)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7
(Routing) #
----
. Konfigurieren Sie auf Wunsch den SSH-Server.
+

NOTE: Die RCF-Datei deaktiviert das Telnet-Protokoll. Wenn Sie den SSH-Server nicht konfigurieren, können Sie nur über die serielle Port-Verbindung auf die Bridge zugreifen.

+
.. Generieren von RSA-Schlüsseln.
+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *crypto key generate rsa*
----
.. DSA-Schlüssel generieren (optional)
+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *crypto key generate dsa*
----
.. Wenn Sie die FIPS-konforme Version von EFOS verwenden, generieren Sie die ECDSA-Schlüssel. Im folgenden Beispiel werden die Schlüssel mit einer Länge von 256 erstellt. Gültige Werte sind 256, 384 oder 521.
+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *crypto key generate ecdsa 256*
----
.. Aktivieren Sie den SSH-Server.
+
Schließen Sie bei Bedarf den Konfigurationskontext.

+
[listing, subs="+quotes"]
----
(Routing) (Config)# *end*
(Routing)# *ip ssh server enable*
----
+

NOTE: Wenn Schlüssel bereits vorhanden sind, werden Sie möglicherweise aufgefordert, sie zu überschreiben.



. Konfigurieren Sie bei Bedarf die Domäne und den Namensserver:
+
`configure`

+
Das folgende Beispiel zeigt die `ip domain` Und `ip name server` Befehl:

+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *ip domain name lab.netapp.com*
(Routing) (Config)# *ip name server 10.99.99.1 10.99.99.2*
(Routing) (Config)# *exit*
----
. Konfigurieren Sie auf Wunsch die Zeitzone und die Zeitsynchronisierung (SNTP).
+
Das folgende Beispiel zeigt die `sntp` Befehle, die IP-Adresse des SNTP-Servers und der relativen Zeitzone angeben.

+
[listing, subs="+quotes"]
----
(Routing)# *configure*
(Routing) (Config)# *sntp client mode unicast*
(Routing) (Config)# *sntp server 10.99.99.5*
(Routing) (Config)# *clock timezone -7*
(Routing) (Config)# *exit*
----
. Konfigurieren Sie den Switch-Namen:
+
`hostname cs2`

+
In der Switch-Eingabeaufforderung wird der neue Name angezeigt:

+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
----
. Konfiguration speichern:
+
`write memory`

+
Sie erhalten Eingabeaufforderungen und Ausgabe ähnlich dem folgenden Beispiel:

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----




== Installieren Sie die Referenzkonfigurationsdatei (RCF).

.Schritte
. Verbinden Sie den Cluster-Switch mit dem Managementnetzwerk.
. Mit dem Ping-Befehl können Sie die Verbindung zum Server, der EFOS, Lizenzen und RCF hostet, überprüfen.
+
Wenn es sich bei der Konnektivität um ein Problem handelt, verwenden Sie ein nicht geroutetes Netzwerk, und konfigurieren Sie den Service-Port mithilfe der IP-Adresse 192.168.x oder 172.19.x Sie können den Service-Port später an die Produktionsmanagement-IP-Adresse neu konfigurieren.

+
In diesem Beispiel wird überprüft, ob der Switch mit der IP-Adresse 172.19.2 verbunden ist:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Installieren Sie das RCF auf dem BES-53248 Cluster Switch mit dem Befehl copy.
+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr*

Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...

File transfer operation completed successfully.
----
+

NOTE: Je nach Umgebung müssen Sie im Kopierbefehl möglicherweise einen Doppelschrägstrich verwenden, beispielsweise: `+copy sftp://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Der `.scr` Die Erweiterung muss als Teil des Dateinamens festgelegt werden, bevor das Skript aufgerufen wird. Diese Erweiterung ist die Erweiterung für das EFOS-Betriebssystem. Der Switch validiert das Skript automatisch, wenn es auf den Switch heruntergeladen wird und die Ausgabe an die Konsole geht. Außerdem können Sie den Namen des ändern `.scr` So passen Sie den Konsolenbildschirm an, um die Lesbarkeit zu erleichtern: `+copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script RCF_v1.6-Cluster-HA.scr+`.

+

NOTE: Der Dateiname darf die Symbole nicht enthalten `\/:*?"<>|` Und die maximal zulässige Länge beträgt 32 Zeichen.

. Überprüfen Sie, ob das Skript heruntergeladen und auf dem Dateinamen gespeichert wurde, den Sie ihm gegeben haben:
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr          2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. Das Skript auf den Switch anwenden.
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.6-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. Überprüfen Sie die Ports auf eine zusätzliche Lizenz, nachdem die RCF angewendet wurde:
+
`show port all | exclude Detach`

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ------------ ---------- ------ ------- ------ -------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. Überprüfen Sie auf dem Switch, ob Ihre Änderungen vorgenommen wurden:
+
`show running-config`

+
[listing, subs="+quotes"]
----
(cs2)# *show running-config*
----
. Speichern Sie die laufende Konfiguration, damit sie die Startkonfiguration wird, wenn Sie den Switch neu starten:
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
. Starten Sie den Switch neu und vergewissern Sie sich, dass die laufende Konfiguration korrekt ist:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*

System will now restart!
----



NOTE: Sobald die RCF auf dem ersten Switch installiert ist, wiederholen Sie diese Schritte, um die RCF auf dem zweiten Cluster-Switch zu installieren.


CAUTION: Siehe das link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/BES-53248_communication_issue_after_firmware%2F%2FRCF_upgrade["KB"^] Weitere Informationen zur Installation eines RCF für MetroCluster.
