---
permalink: switch-bes-53248/replace-required-documentation.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Zum Einrichten der Cluster-Mode-Konfiguration benötigen Sie spezifische Switch- und Controller-Dokumentation. 
---
= Dokumentation für den Cluster-Switch BES-53248 erforderlich
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Einrichten der Cluster-Mode-Konfiguration benötigen Sie spezifische Switch- und Controller-Dokumentation.

.Erforderliche Dokumentation für BES-53248 Cluster Switches
Zum Einrichten des BES-53248-Cluster-Switches benötigen Sie die folgenden Dokumente, die über die Broadcom Support Site verfügbar sind: https://www.broadcom.com/support/bes-switch["Produkte Der Broadcom Ethernet-Switches-Reihe"^]

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
_EFOS Administratorhandbuch v3.4.3_
 a| 
Enthält Beispiele für die Verwendung des BES-53248-Switches in einem typischen Netzwerk.



 a| 
_EFOS CLI Command Reference v3.4.3_
 a| 
Beschreibt die Befehle der Befehlszeilenschnittstelle (CLI), mit denen Sie die BES-53248-Software anzeigen und konfigurieren können.



 a| 
_EFOS Handbuch erste Schritte v3.4.3_
 a| 
Enthält detaillierte Informationen zum BES-53248-Switch.



 a| 
_EFOS SNMP-Referenzhandbuch v3.4.3_
 a| 
Enthält Beispiele für die Verwendung des BES-53248-Switches in einem typischen Netzwerk.



 a| 
_EFOS-Skalierungsparameter und Werte v3.4.3_
 a| 
Beschreibt die Standard-Skalierungsparameter, mit denen EFOS-Software auf den unterstützten Plattformen bereitgestellt und validiert wird.



 a| 
_EFOS Funktionsspezifikationen v3.4.3_
 a| 
Beschreibt die Spezifikationen für die EFOS-Software auf den unterstützten Plattformen.



 a| 
_EFOS Release Notes Version 3.4.3_
 a| 
Enthält Release-spezifische Informationen zur BES-53248-Software.

|===
.Erforderliche Dokumentation für unterstützte ONTAP Systeme
Um ein ONTAP System einzurichten, benötigen Sie die folgenden Dokumente über die NetApp Support Site unter http://mysupport.netapp.com/["mysupport.netapp.com"^]

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]
 a| 
Hier werden die Strom- und Standortanforderungen für sämtliche NetApp Hardware, einschließlich Systemschränke, beschrieben.



 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP 9
 a| 
Enthält ausführliche Informationen zu allen Aspekten der Version ONTAP 9.

|===