---
permalink: switch-bes-53248/replace-install.html 
sidebar: sidebar 
keywords: procedure, perform, initial, installation, bes, cluster, switch, initial installation of the bes-53428 cluster switch - bes-53428 switches 
summary: Anhand dieses Verfahrens können Sie die Erstinstallation des BES-53248-Cluster-Switches durchführen. 
---
= Erstinstallation des BES-53248 Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anhand dieses Verfahrens können Sie die Erstinstallation des BES-53248-Cluster-Switches durchführen.

Sie können die entsprechende Broadcom EFOS-Software für Ihre Cluster-Switches von herunterladen https://www.broadcom.com/support/bes-switch["Unterstützung Für Broadcom Ethernet-Switches"^] Standort.

EFOS ist ein breites Spektrum an Software-Funktionen und Protokollen, die für die Entwicklung einer Vielzahl von Ethernet- und IP-Infrastruktursystemen für Anwendungen im Rechenzentrum erforderlich sind. Die EFOS-Software ist eine Architektur, die für jedes Netzwerkorganisationsgerät geeignet ist und Anwendungen der Spitzenklasse nutzt, die eine gründliche Paketerinspektion oder -Trennung erfordern.

Dieses Verfahren enthält eine Zusammenfassung des Verfahrens zur Installation der Switches und zum Ausführen der Switches:

.Schritte
. Schließen Sie den seriellen Port an den Host oder den seriellen Port Ihrer Wahl an.
. Verbinden Sie den Verwaltungsport (den RJ-45-Schraubenschlüssel-Port auf der linken Seite des Switches) mit dem gleichen Netzwerk, in dem sich Ihr TFTP-Server befindet.
. Legen Sie an der Konsole die seriellen Einstellungen der Host-Seite fest:
+
** 115200 Baud
** 8 Datenbits
** 1 Stoppbit
** Parität: Keine
** Flusskontrolle: Keine


. Melden Sie sich als Administrator beim Switch an, und drücken Sie die Eingabetaste, wenn Sie zur Eingabe eines Passworts aufgefordert werden. Der Standard-Switch-Name ist Routing. An der Eingabeaufforderung: `enable`. Dadurch haben Sie Zugriff auf den privilegierten EXEC-Modus für die Switch-Konfiguration.
+
[listing, subs="+quotes"]
----
User: admin
Password:
(Routing)> *enable*
Password:
(Routing) #
----
. Ändern Sie den Switch-Namen in cs2:
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. Verwenden Sie zum Festlegen einer statischen IP-Adresse die serviceport-Protokolle, das Netzwerkprotokoll und die serviceport-ip-Befehle, wie im Beispiel dargestellt.
+
für den serviceport ist standardmäßig DHCP verwendet. Die IP-Adresse, die Subnetzmaske und die Standard-Gateway-Adresse werden automatisch zugewiesen.

+
[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip ipaddr netmask gateway*
----
. Überprüfen Sie die Ergebnisse mit dem Befehl:
+
`show serviceport`

+
Im folgenden Beispiel werden die vom DHCP-Server bereitgestellten IP-Informationen angezeigt.

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. Konfigurieren Sie die Domäne und den Namensserver:
+
`configure`

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *ip domain name company.com*
(cs2) (Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2) (Config)# *exit*
(cs2)#
----
. Konfigurieren Sie den NTP-Server.
+
.. Konfigurieren der Zeitzone und der Zeitsynchronisierung (SNTP):
+
`sntp`

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *sntp client mode unicast*
(cs2) (Config)# *sntp server 10.99.99.5*
(cs2) (Config)# *clock timezone -7*
(cs2) (Config)# *exit*
(cs2)#
----
.. Konfigurieren Sie die Zeit manuell:
+
`clock`

+
[listing, subs="+quotes"]
----
(cs2) # *configure*
(cs2) (Config)# *no sntp client mode*
(cs2) (Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60* zone EST
(cs2) (Config)# *clock timezone -5 zone EST*
(cs2) (Config)# *clock set 07:00:00*
(cs2) (Config)# *clock set 10/20/2020*

(cs2) (Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2) (Config)# *exit*

(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
----



