---
permalink: switch-bes-53248/replace-switch-reqs.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 'Der Austausch eines defekten, von Broadcom unterstützten BES-53248 Cluster-Switches in einem Cluster-Netzwerk ist ein nicht-unterbrechendes Verfahren (NDU).' 
---
= Ersatzbedarf
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie den Schalter austauschen, stellen Sie sicher, dass die folgenden Bedingungen in der aktuellen Umgebung und am Ersatzschalter erfüllt sind.



== Vorhandene Cluster- und Netzwerkinfrastruktur

Stellen Sie sicher, dass:

* Der bestehende Cluster wurde als voll funktionsfähig verifiziert, wobei mindestens ein Cluster-Switch vollständig angeschlossen ist.
* Alle Cluster-Ports sind *aktiv*.
* Alle logischen Schnittstellen (LIFs) des Clusters sind administrativ und betriebsbereit und an ihren jeweiligen Ports angeschlossen.
* Das ONTAP `cluster ping-cluster -node node1` Der Befehl muss angeben, dass die Einstellungen `basic connectivity` Und `larger than PMTU communication` sind auf allen Wegen erfolgreich.




== BES-53248 Ersatz-Clusterschalter

Stellen Sie sicher, dass:

* Die Management-Netzwerkanbindung des Ersatz-Switches ist funktionsfähig.
* Der Konsolenzugriff auf den Ersatzschalter ist eingerichtet.
* Die Knotenverbindungen erfolgen über die Ports 0/1 bis 0/16 mit Standardlizenzierung.
* Alle Inter-Switch Link (ISL)-Ports sind an den Ports 0/55 und 0/56 deaktiviert.
* Die gewünschte Referenzkonfigurationsdatei (RCF) und das EFOS-Betriebssystem-Switch-Image werden auf den Switch geladen.
* Die erste Anpassung des Schalters ist abgeschlossen, wie in folgendem Abschnitt detailliert beschrieben:link:configure-install-initial.html["Konfigurieren des Cluster-Switches BES-53248"] Die


Alle zuvor vorgenommenen Anpassungen am Standort, wie z. B. STP, SNMP und SSH, werden auf den neuen Switch kopiert.



== Konsolenprotokollierung aktivieren

NetApp empfiehlt dringend, die Konsolenprotokollierung auf den verwendeten Geräten zu aktivieren und beim Austausch Ihres Switches die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während der Wartungsarbeiten aktiviert.
* Lösen Sie vor und nach der Wartung einen Wartungs AutoSupport aus, um die Fallerstellung für die Dauer der Wartung zu deaktivieren.  Siehe diesen Wissensdatenbankartikel https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Wie man die automatische Fallerstellung während geplanter Wartungsfenster unterdrückt"^] für weitere Einzelheiten.
* Aktivieren Sie die Sitzungsprotokollierung für alle CLI-Sitzungen.  Anweisungen zum Aktivieren der Sitzungsprotokollierung finden Sie im Abschnitt „Protokollierung der Sitzungsausgabe“ in diesem Wissensdatenbankartikel. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP -Systemen?"^] Die




== Weitere Informationen

* https://mysupport.netapp.com/["NetApp Support Site"^]
* https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]

