---
permalink: switch-bes-53248/replace-verify.html 
sidebar: sidebar 
keywords: command, verify, operational, bes, cluster, switch, upgrade, verify the configuration after a cluster switch upgrade - bes-53428 switches 
summary: Mithilfe der hier angegebenen Befehle können Sie überprüfen, ob nach einem Upgrade des BES-53248 Cluster-Switch alle Funktionen betriebsbereit sind. 
---
= Überprüfen Sie das ONTAP-Cluster-Netzwerk nach einem EFOS-Software- oder RCF-Upgrade der BES-53248-Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die folgenden Befehle verwenden, um den Zustand des ONTAP-Cluster-Netzwerks nach einem Upgrade der EFOS-Software oder RCF für BES-53248-Cluster-Switches zu überprüfen.

.Schritte
. Zeigen Sie mit dem Befehl Informationen zu den Netzwerk-Ports auf dem Cluster an:
+
[source, cli]
----
network port show -ipspace Cluster
----
+
`Link` Muss den Wert haben `up` Und `Health Status` Muss sein `healthy`.

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird die Ausgabe des Befehls angezeigt:

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Überprüfen Sie dies für jede LIF `Is Home` Ist `true` Und `Status Admin/Oper` Ist `up` Auf beiden Nodes, mit dem Befehl:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.217.125/16 node1         e0a     true
            node1_clus2  up/up    169.254.205.88/16  node1         e0b     true
            node2_clus1  up/up    169.254.252.125/16 node2         e0a     true
            node2_clus2  up/up    169.254.110.131/16 node2         e0b     true
----
====
. Überprüfen Sie das `Health Status` Von jedem Node ist `true` Verwenden des Befehls:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====


.Was kommt als Nächstes?
Nachdem Sie das Upgrade Ihrer EFOS-Software oder Ihres RCF bestätigt haben, können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
