---
permalink: switch-bes-53248/replace-restrictions.html 
sidebar: sidebar 
keywords: problem, install, license, debug, command, restriction, limitation, switch, restrictions and limitations - bes-53428 switches 
summary: Wenn beim Installieren einer Lizenz Probleme auftreten, sollten die folgenden Debug-Befehle ausgeführt werden, bevor der Befehl copy erneut ausgeführt wird, um die Lizenz zu installieren. 
---
= Einschränkungen und Einschränkungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn beim Installieren einer Lizenz Probleme auftreten, sollten die folgenden Debug-Befehle ausgeführt werden, bevor der ausgeführt wird `copy` Befehl zum Installieren der Lizenz erneut.

Die zu verwendenden Debug-Befehle sind: `debug transfer` Und `debug license`

[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
Wenn Sie den ausführen `copy` Befehl mit dem `debug transfer` Und `debug license` Aktivierte Optionen, die folgende Protokollausgabe wird zurückgegeben:

[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
Überprüfen Sie bei der Debug-Ausgabe auf Folgendes:

* Überprüfen Sie, ob die Seriennummer übereinstimmt: `Serial number QTFCU38290012 matched.`
* Überprüfen Sie, ob das Switch-Modell mit folgenden Punkten übereinstimmt: `Model BES-53248 matched.`
* Überprüfen Sie, ob der angegebene Lizenzindex zuvor nicht verwendet wurde. Wenn bereits ein Lizenzindex verwendet wird, wird der folgende Fehler zurückgegeben: `License file /mnt/download//license.dat.1 already exists.`
* Eine Port-Lizenz ist keine Feature-Lizenz. Daher wird folgende Aussage erwartet: `Feature not found in license file with index = 1.`


Verwenden Sie die `copy` Befehl zum Sichern der Portlizenzen auf dem Server:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----
Siehe link:configure-licenses.html["Installieren von Lizenzen für BES-53248 Cluster-Switches"] Details zu den für verfügbare Lizenzen unterstützten Firmware-Versionen.


WARNING: Wenn Sie die Switch-Software von Version 3.4.4.6 herunterstufen müssen, werden die Lizenzen entfernt. Dieses Verhalten ist zu erwarten.

Bevor Sie auf eine ältere Softwareversion zurücksetzen, müssen Sie eine entsprechende ältere Lizenz installieren.
