---
permalink: switch-bes-53248/replace-requirements.html 
sidebar: sidebar 
keywords: requirements, bes-53428 switches 
summary: Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Cluster-Switches. Je nach Art des zu Beginn konfigurierende Cluster Switch müssen Sie mit dem enthaltenen Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen und spezielle Netzwerkinformationen benötigen. 
---
= Konfigurationsanforderungen für Cluster-Switch BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Cluster-Switches. Je nach Art des zu Beginn konfigurierende Cluster Switch müssen Sie mit dem enthaltenen Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen und spezielle Netzwerkinformationen benötigen.



== Zuweisung von BES-53248-Cluster-Switch-Ports

Sie können die von Broadcom unterstützte Tabelle zur Konfiguration des Clusters für die Zuweisung von BES-53248-Cluster-Switches als Leitfaden verwenden.

[cols="1,2"]
|===
| Switch-Ports | Anzahl der Ports 


 a| 
01-16
 a| 
10/25-GbE-Cluster-Port-Nodes, Basiskonfiguration



 a| 
17-48
 a| 
10/25-GbE-Cluster-Port-Nodes, mit Lizenzen



 a| 
49-54
 a| 
100-GbE-Cluster-Port-Nodes mit Lizenzen, die links hinzugefügt wurden



 a| 
55-56
 a| 
Ports mit 100 GbE Cluster Inter-Switch Link (ISL), Basiskonfiguration

|===
.Einschränkung bei der Geschwindigkeit der Port-Gruppe
Bei BES-53248 Cluster Switches werden die 48 10/25-GbE-Ports (SFP28/SFP+) wie folgt in 12 Gruppen mit 4 Ports kombiniert:

* Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21–24, 25–28, 29–32, 33–36, 37–40, 41-44 und 45-48.


Die Port-Geschwindigkeit von SFP28/SFP+ muss für alle Ports der 4-Port-Gruppe gleich (10 GbE oder 25 GbE) sein.
