---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 'Das Upgrade von BES-53248-Cluster-Switches beginnt mit der Vorbereitung des Controllers auf das Upgrade, der Installation der EFOS-Software, der Lizenzen und der Referenzkonfigurationsdatei \ (RCF\). Nach der Installation können Sie die Controller-Konfiguration in einer Umgebung mit unterbrechungsfreiem Upgrade \(NDU\) und unterbrechungsfreiem Betrieb \(NDO\) wiederherstellen.' 
---
= Aktualisieren Sie den BES-53248 Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie diese Schritte aus, um einen BES-53248-Cluster-Switch zu aktualisieren.

Dieser Vorgang gilt für ein funktionierendes Cluster und ermöglicht eine unterbrechungsfreie Upgrade- (NDU) und eine unterbrechungsfreie Betriebsumgebung (Non-Disruptive Operations, NDO). Weitere Informationen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/hardware/How_to_prepare_ONTAP_for_a_cluster_switch_upgrade["Vorbereiten von ONTAP auf ein Cluster-Switch-Upgrade"^].



== Prüfen Sie die Anforderungen

Vor der Installation der EFOS Software, der Lizenzen und der RCF-Datei auf einem vorhandenen NetApp BES-53248 Cluster-Switch stellen Sie sicher, dass:

* Das Cluster ist ein voll funktionsfähiges Cluster (keine Fehlermeldungen oder andere Probleme).
* Das Cluster enthält keine fehlerhaften Cluster-Netzwerkkarten (NICs).
* Alle verbundenen Ports auf beiden Cluster-Switches funktionieren ordnungsgemäß.
* Alle Cluster-Ports sind aktiv.
* Alle Cluster-LIFs sind administrativ und betrieblich und auf ihren Home-Ports aktiv.
* Die ersten beiden Cluster-LIFs an jedem Node sind auf separaten NICs konfiguriert und mit separaten Cluster-Switch-Ports verbunden.
* Das ONTAP `cluster ping-cluster -node node1` Der Befehl „Advanced Privilege“ zeigt das an `larger than PMTU communication` Ist auf allen Pfaden erfolgreich.



NOTE: Zwischen der Befehlssyntax in der RCF- und EFOS-Version kann es zu Befehlsabhängigkeiten kommen.


NOTE: Informationen zur Switch-Kompatibilität finden Sie in der Kompatibilitätstabelle auf der https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom Cluster-Switches"^] Seite für die unterstützten EFOS-, RCF- und ONTAP-Versionen.



== Bereiten Sie den Controller vor

Gehen Sie folgendermaßen vor, um den Controller für ein Upgrade des BES-53248-Cluster-Switches vorzubereiten.

.Schritte
. Verbinden Sie den Cluster-Switch mit dem Managementnetzwerk.
. Mit dem Ping-Befehl können Sie die Verbindung zum Server, der EFOS, Lizenzen und RCF hostet, überprüfen.
+
Wenn es sich um ein Problem handelt, verwenden Sie ein nicht geroutetes Netzwerk, und konfigurieren Sie den Service-Port mithilfe der IP-Adresse 192.168.x oder 172.19.x Sie können den Service-Port später an die Produktionsmanagement-IP-Adresse neu konfigurieren.

+
.Beispiel anzeigen
[%collapsible]
====
In diesem Beispiel wird überprüft, ob der Switch mit der IP-Adresse 172.19.2 verbunden ist:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Überprüfen Sie, ob die Cluster-Ports ordnungsgemäß sind und über einen Link verfügen. Verwenden Sie dazu den Befehl:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Art der Ausgabe, in der alle Ports mit einem verfügen `Link` Wert von up und a `Health Status` Für gesund:

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Überprüfen Sie mithilfe des Befehls, dass die Cluster-LIFs administrativ und betrieblich sind und sich in ihren Home Ports befinden:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
In diesem Beispiel ist der `-vserver` Mit dem Parameter werden Informationen zu den LIFs angezeigt, die den Cluster-Ports zugeordnet sind. `Status Admin/Oper` Muss up-und sein `Is Home` Muss wahr sein:

[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====




== Software installieren

Befolgen Sie diese Anweisungen, um die Software zu installieren.

. link:configure-efos-software.html["Installieren Sie die EFOS-Software"]. Laden Sie die Ethernet Fabric OS (EFOS)-Software auf dem BES-53248-Cluster-Switch herunter und installieren Sie sie.
. link:configure-licenses.html["Installation von Lizenzen für BES-53248 Cluster-Switches"]. Optional können Sie neue Ports durch den Kauf und die Installation weiterer Lizenzen hinzufügen. Das Switch-Basismodell ist für 16 10-GbE- oder 25-GbE-Ports und zwei 100-GbE-Ports lizenziert.
. link:configure-install-rcf.html["Installieren Sie die Referenzkonfigurationsdatei (RCF)."]. Installieren oder aktualisieren Sie die RCF auf dem BES-53248 Cluster-Switch und überprüfen Sie nach der Anwendung des RCF die Ports für eine zusätzliche Lizenz.
. link:configure-health-monitor.html["Installieren Sie die Konfigurationsdatei des Cluster Switch Health Monitor (CSHM)"]. Installieren Sie die entsprechende Konfigurationsdatei für das Monitoring des Clusterstatus.
. link:configure-ssh.html["Aktivieren Sie SSH bei BES-53248 Cluster-Switches"]. Wenn Sie den Cluster Switch Health Monitor (CSHM) und die Funktionen zur Protokollerfassung verwenden, aktivieren Sie SSH auf den Switches.
. link:configure-log-collection.html["Aktivieren Sie die Protokollerfassungsfunktion"]. Verwenden Sie diese Funktion, um Switch-bezogene Protokolldateien in ONTAP zu sammeln.

