---
permalink: switch-bes-53248/replace-install-cshm-file.html 
sidebar: sidebar 
keywords: CSHM,initial setup,switch health monitor 
summary: Mit diesen Verfahren können Sie die entsprechende Konfigurationsdatei für die Zustandsüberwachung von BES-53248 Cluster-Switches für Cluster-Switches installieren. Bei ONTAP Releases 9.5P7 und früher sowie 9.6P2 und früher müssen Sie die Konfigurationsdatei des Cluster Switch zur Systemzustandsüberwachung separat herunterladen. In ONTAP Versionen 9.5P8 und höher, 9.6P3 und höher und 9.7 und höher wird die Konfigurationsdatei des Cluster-Switch-Systemzustandsüberwachung mit ONTAP gebündelt. 
---
= Installieren Sie die Konfigurationsdatei des Cluster Switch Health Monitor (CSHM)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesen Verfahren können Sie die entsprechende Konfigurationsdatei für die Zustandsüberwachung von BES-53248 Cluster-Switches für Cluster-Switches installieren. Bei ONTAP Releases 9.5P7 und früher sowie 9.6P2 und früher müssen Sie die Konfigurationsdatei des Cluster Switch zur Systemzustandsüberwachung separat herunterladen. In ONTAP Versionen 9.5P8 und höher, 9.6P3 und höher und 9.7 und höher wird die Konfigurationsdatei des Cluster-Switch-Systemzustandsüberwachung mit ONTAP gebündelt.

Bevor Sie die Switch-Systemzustandsüberwachung für BES-53248 Cluster-Switches einrichten, müssen Sie sicherstellen, dass das ONTAP Cluster betriebsbereit ist und ausgeführt wird.


NOTE: Es wird empfohlen, SSH zu aktivieren, um alle in CSHM verfügbaren Funktionen nutzen zu können.

.Schritte
. Laden Sie die ZIP-Datei für die Cluster-Switch-Systemzustandsüberwachung auf Basis der entsprechenden ONTAP Release-Version herunter. Diese Datei ist auf der folgenden Seite verfügbar: https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp Software-Download"^]
+
.. Wählen Sie auf der Software-Download-Seite *Switch Health Monitor Configuration Files*
.. Wählen Sie Plattform = *ONTAP* und klicken Sie auf *Los!*
.. Klicken Sie auf der Seite Switch Health Monitor Configuration Files for ONTAP auf *Anzeigen & Download*
.. Klicken Sie auf der Seite Switch Health Monitor Configuration Files for ONTAP - Description auf *Download* für das entsprechende Cluster Switch-Modell, zum Beispiel: *Broadcom-supported BES-53248*
.. Klicken Sie auf der Seite Endbenutzer-Lizenzvereinbarung auf *Akzeptieren*
.. Wählen Sie auf der Seite Switch Health Monitor Configuration Files for ONTAP - Download die entsprechende Konfigurationsdatei aus, beispielsweise *Broadcom_BES-53248.zip*


. Laden Sie die entsprechende Zip-Datei auf Ihren internen Webserver hoch, wobei DIE IP-Adresse X.X.X.X ist
+
Für einen internen Webserver IP-Adresse von 192.168.2.20 und unter der Annahme, dass ein Verzeichnis /usr/download existiert, können Sie Ihre ZIP-Datei mit scp auf Ihren Webserver hochladen:

+
[listing]
----
% scp Broadcom_BES-53248.zip admin@192.168.2.20:/usr/download/Broadcom_BES-53248.zip
----
. Greifen Sie mit dem Befehl auf die Einstellung für den erweiterten Modus von einem der ONTAP Systeme im Cluster zu `set -privilege advanced`:
+
[listing, subs="+quotes"]
----
cluster1::> *set -privilege advanced*
----
. Führen Sie den Konfigurationsbefehl der Switch-Systemzustandsüberwachung aus `system cluster-switch configure-health-monitor -node * -package-url \http://server/file-location`:
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url
http://192.168.2.20/usr/download/Broadcom_BES-53248.zip*
----
. Überprüfen Sie, ob die Befehlsausgabe den Textstring „das heruntergeladene Paket wurde erfolgreich verarbeitet“ enthält. Sollte ein Fehler auftreten, wenden Sie sich an den NetApp Support.
. Führen Sie den Befehl aus `system cluster-switch show` Stellen Sie auf dem ONTAP-System sicher, dass die Cluster-Switches erkannt werden, wobei das überwachte Feld auf „true“ gesetzt ist.
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch show*
----
+

NOTE: Wenn Sie zu einem beliebigen Zeitpunkt auf eine frühere Version von ONTAP zurückkehren, müssen Sie die CSHM-Konfigurationsdatei erneut installieren, um die Switch-Zustandsüberwachung von BES-53248-Cluster-Switches zu ermöglichen.


