---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Sie benötigen spezifische Dokumentationen zu Switch und Controller, um Ihre Cluster-Modus-Konfiguration einzurichten. 
---
= Dokumentationsanforderungen für BES-53248 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung des BES-53248-Switches sollten Sie unbedingt die spezifische Dokumentation des Switches und des Controllers beachten.



== Broadcom-Dokumentation

Für die Einrichtung des Cluster-Switches BES-53248 benötigen Sie die folgenden Dokumente, die auf der Broadcom-Support-Website verfügbar sind: https://www.broadcom.com/support/bes-switch["Broadcom Ethernet-Switch-Produktlinie"^]

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
_EFOS-Administratorhandbuch v3.4.3_
 a| 
Liefert Beispiele für die Verwendung des BES-53248-Switches in einem typischen Netzwerk.



 a| 
_EFOS CLI-Befehlsreferenz v3.4.3_
 a| 
Beschreibt die Befehle der Kommandozeilenschnittstelle (CLI), die Sie zum Anzeigen und Konfigurieren der BES-53248-Software verwenden.



 a| 
_EFOS-Einführungsleitfaden v3.4.3_
 a| 
Bietet detaillierte Informationen zum BES-53248-Switch.



 a| 
_EFOS SNMP-Referenzhandbuch v3.4.3_
 a| 
Liefert Beispiele für die Verwendung des BES-53248-Switches in einem typischen Netzwerk.



 a| 
_EFOS-Skalierungsparameter und -werte v3.4.3_
 a| 
Beschreibt die Standard-Skalierungsparameter, mit denen die EFOS-Software ausgeliefert und auf den unterstützten Plattformen validiert wird.



 a| 
_EFOS-Funktionsspezifikationen v3.4.3_
 a| 
Beschreibt die Spezifikationen der EFOS-Software auf den unterstützten Plattformen.



 a| 
_EFOS Versionshinweise v3.4.3_
 a| 
Bietet versionsspezifische Informationen zur BES-53248-Software.



 a| 
_Kompatibilitätsmatrix für Clusternetzwerke und Managementnetzwerke_
 a| 
Liefert Informationen zur Netzwerkkompatibilität.  Die Matrix ist auf der Downloadseite des BES-53248-Switches verfügbar unter https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom-Cluster-Switches"^] Die

|===


== Dokumentation und Wissensdatenbankartikel zu ONTAP Systemen

Um ein ONTAP -System einzurichten, benötigen Sie die folgenden Dokumente von der NetApp Support-Website unter http://mysupport.netapp.com/["mysupport.netapp.com"^] oder die Wissensdatenbank (KB)-Website unter https://kb.netapp.com/["kb.netapp.com"^] Die

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]
 a| 
Beschreibt die Stromversorgungs- und Standortanforderungen für die gesamte NetApp Hardware, einschließlich der Systemschränke, und liefert Informationen zu den relevanten Steckverbindern und Kabeloptionen sowie deren Teilenummern.



 a| 
Controllerspezifische _Installations- und Einrichtungsanweisungen_
 a| 
Beschreibt die Installation von NetApp -Hardware.



 a| 
ONTAP 9
 a| 
Bietet detaillierte Informationen zu allen Aspekten der ONTAP 9-Version.



 a| 
_So fügen Sie zusätzliche Portlizenzen für den Broadcom-unterstützten BES-53248-Switch hinzu_
 a| 
Bietet detaillierte Informationen zum Hinzufügen von Portlizenzen.  Gehe zu https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["KB-Artikel"^] Die

|===