---
permalink: switch-bes-53248/reset-switch-bes-53248.html 
sidebar: sidebar 
keywords: BES-53248 reset switch to factory defaults, BES-53248 switches configuration, efos 
summary: Bevor Sie Ihren Broadcom BES-53248 Switch konfigurieren, lesen Sie bitte die folgenden Informationen. 
---
= Setzen Sie den Cluster-Schalter BES-53248 auf die Werkseinstellungen zurück.
:allow-uri-read: 


[role="lead"]
Um den Cluster-Switch BES-53248 auf die Werkseinstellungen zurückzusetzen, müssen Sie die Switch-Einstellungen BES-53248 löschen.

.Informationen zu diesem Vorgang
* Sie müssen über die serielle Konsole mit dem Switch verbunden sein.
* Diese Aufgabe setzt die Konfiguration des Managementnetzwerks zurück.


.Schritte
. Wechseln Sie zur Eingabeaufforderung mit Administratorrechten.
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)#
----
. Startkonfiguration löschen.
+
`erase startup-config`

+
[listing, subs="+quotes"]
----
(cs2)# *erase startup-config*

Are you sure you want to clear the configuration? (y/n) *y*
----
. Starten Sie den Switch neu.
+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
----



NOTE: Wenn das System fragt, ob die nicht gespeicherte oder geänderte Konfiguration vor dem Neustart des Switches gespeichert werden soll, wählen Sie *Nein*.

. [[step4]] Warten Sie, bis der Switch neu geladen ist, und melden Sie sich dann am Switch an.
+
Der Standardbenutzer ist „admin“, und es ist kein Passwort festgelegt.  Es wird eine Eingabeaufforderung ähnlich der folgenden angezeigt:

+
[listing]
----
(Routing)>
----

