---
permalink: switch-bes-53248/upgrade-switch-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Lesen Sie vor der Konfiguration von BES-53248-Cluster-Switches eine Übersicht über den Prozess und die Terminologie. 
---
= Überblick über den Upgrade-Prozess für BES-53248 Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie die folgenden Schritte aus, um die EFOS-Software und die Referenzkonfigurationsdateien (RCFs) auf Broadcom BES-54328-Cluster-Switches zu aktualisieren.

. link:upgrade-efos-software.html["Aktualisieren Sie Ihre EFOS-Version"]
+
Laden Sie die Ethernet Fabric OS (EFOS)-Software auf dem BES-53248-Cluster-Switch herunter und installieren Sie sie.

. link:upgrade-rcf.html["Aktualisieren Sie Ihre RCF-Version"]
+
Aktualisieren Sie die RCF auf dem BES-53248-Cluster-Switch, und überprüfen Sie dann die Ports für eine zusätzliche Lizenz, nachdem die RCF angewendet wurde.

. link:replace-verify.html["Überprüfen Sie nach dem Upgrade das ONTAP-Cluster-Netzwerk"]
+
Überprüfen Sie den Zustand des ONTAP-Cluster-Netzwerks nach einem Upgrade der EFOS-Software oder RCF für BES-53248-Cluster-Switches.


