---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Führen Sie diese Schritte aus, um die Ethernet Fabric OS (EFOS)-Software auf dem Cluster-Switch BES-53248 zu aktualisieren.' 
---
= Aktualisieren Sie die EFOS-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie diese Schritte aus, um die EFOS-Software auf dem Cluster-Switch BES-53248 zu aktualisieren.

Die EFOS-Software umfasst eine Reihe fortschrittlicher Netzwerkfunktionen und -protokolle zur Entwicklung von Ethernet- und IP-Infrastruktursystemen.  Diese Softwarearchitektur eignet sich für jedes Netzwerkgerät, das Anwendungen nutzt, die eine gründliche Paketprüfung oder -trennung erfordern.



== Bereiten Sie sich auf das Upgrade vor

.Bevor Sie beginnen
* Laden Sie die passende Broadcom EFOS-Software für Ihre Cluster-Switches von der Website herunter. https://www.broadcom.com/support/bes-switch["Broadcom Ethernet-Switch-Unterstützung"^] Website.
* Beachten Sie bitte die folgenden Hinweise zu den EFOS-Versionen.


[]
====
*Bitte beachten Sie Folgendes:*

* Beim Upgrade von EFOS 3.4.xx auf EFOS 3.7.xx oder höher muss auf dem Switch EFOS 3.4.4.6 (oder eine spätere Version der 3.4.xx-Reihe) installiert sein.  Wenn Sie eine ältere Version verwenden, aktualisieren Sie den Switch zuerst auf EFOS 3.4.4.6 (oder eine spätere Version der 3.4.xx-Reihe) und anschließend auf EFOS 3.7.xx oder höher.
* Die Konfigurationen für EFOS 3.4.xx und 3.7.xx oder höher sind unterschiedlich.  Um die EFOS-Version von 3.4.xx auf 3.7.xx oder höher zu ändern oder umgekehrt, muss die Switch auf die Werkseinstellungen zurückgesetzt und die RCF-Dateien für die entsprechende EFOS-Version (erneut) angewendet werden.  Für dieses Verfahren ist der Zugriff über die serielle Konsole erforderlich.
* Ab EFOS Version 3.7.xx oder höher ist eine nicht FIPS-konforme und eine FIPS-konforme Version verfügbar.  Beim Wechsel von einer nicht FIPS-konformen zu einer FIPS-konformen Version oder umgekehrt sind unterschiedliche Schritte erforderlich.  Durch den Wechsel von einer nicht FIPS-konformen EFOS-Version zu einer FIPS-konformen Version oder umgekehrt wird der Switch auf die Werkseinstellungen zurückgesetzt.  Für dieses Verfahren ist der Zugriff über die serielle Konsole erforderlich.


====
|===


| *Verfahren* | *Aktuelle EFOS -Version* | *Neue EFOS-Version* | *Hochrangige Schritte* 


 a| 
Schritte zum Upgrade von EFOS zwischen zwei (nicht) FIPS-konformen Versionen
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Aktualisieren Sie das neue EFOS-Image mit<<Methode 1: EFOS-Upgrade>> Die  Die Konfigurations- und Lizenzinformationen bleiben erhalten.



 a| 
3.4.4.6 (oder später 3.4.xx)
 a| 
3.7.xx oder später nicht FIPS-konform
 a| 
EFOS aktualisieren mit<<Methode 1: EFOS-Upgrade>> Die  Setzen Sie den Switch auf die Werkseinstellungen zurück und wenden Sie die RCF-Datei für EFOS 3.7.xx oder höher an.



.2+| 3.7.xx oder später nicht FIPS-konform  a| 
3.4.4.6 (oder später 3.4.xx)
 a| 
EFOS downgraden mit<<Methode 1: EFOS-Upgrade>> Die  Setzen Sie den Switch auf die Werkseinstellungen zurück und wenden Sie die RCF-Datei für EFOS 3.4.xx an.



 a| 
3.7.xx oder später nicht FIPS-konform
 a| 
Aktualisieren Sie das neue EFOS-Image mit<<Methode 1: EFOS-Upgrade>> Die  Die Konfigurations- und Lizenzinformationen bleiben erhalten.



 a| 
3.7.xx oder höher FIPS-konform
 a| 
3.7.xx oder höher FIPS-konform
 a| 
Aktualisieren Sie das neue EFOS-Image mit<<Methode 1: EFOS-Upgrade>> Die  Die Konfigurations- und Lizenzinformationen bleiben erhalten.



 a| 
Schritte zum Upgrade auf/von einer FIPS-konformen EFOS-Version
 a| 
Nicht FIPS-konform
 a| 
FIPS-konform
 a| 
Aktualisierung des EFOS-Images mit<<Methode 2: EFOS mithilfe der ONIE OS-Installation aktualisieren>> Die  Die Switch-Konfiguration und die Lizenzinformationen gehen verloren.



 a| 
FIPS-konform
 a| 
Nicht FIPS-konform

|===
[IMPORTANT]
====
Um zu überprüfen, ob Ihre EFOS-Version FIPS-konform oder nicht FIPS-konform ist, verwenden Sie die `show fips status` Befehl.  In den folgenden Beispielen verwendet *IP_switch_a1* FIPS-konformes EFOS und *IP_switch_a2* verwendet nicht FIPS-konformes EFOS.

* Auf Switch IP_switch_a1 (FIPS-konformes EFOS):
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* Auf Switch IP_switch_a2 (nicht FIPS-konformes EFOS):
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Aktualisieren Sie die Software

Verwenden Sie eine der folgenden Methoden:

* <<Methode 1: EFOS-Upgrade>>. Für die meisten Anwendungsfälle geeignet (siehe Tabelle oben).
* <<Methode 2: EFOS mithilfe der ONIE OS-Installation aktualisieren>>. Verwenden Sie diese Option, wenn eine EFOS-Version FIPS-konform ist und die andere EFOS-Version nicht FIPS-konform ist.



NOTE: Um den kontinuierlichen Betrieb des Clusternetzwerks zu gewährleisten, aktualisieren Sie EFOS auf jeweils einem Switch.



=== Methode 1: EFOS-Upgrade

Führen Sie die folgenden Schritte aus, um die EFOS-Software zu aktualisieren.


IMPORTANT: Bitte beachten Sie, dass nach dem Upgrade von BES-53248 Cluster-Switches von EFOS 3.3.xx oder 3.4.xx auf EFOS 3.7.0.4 oder 3.8.0.2 die Inter-Switch Links (ISLs) und Port-Channels im Status *Down* markiert sind.  Dies ist das erwartete Verhalten, und Sie können das Upgrade bedenkenlos fortsetzen, es sei denn, Sie haben Probleme mit der automatischen Rücksetzung von LIFs.  Siehe den Artikel in der Wissensdatenbank: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248 Cluster Switch NDU konnte nicht auf EFOS 3.7.0.4 und höher aktualisiert werden."^] für weitere Einzelheiten.

.Schritte
. Verbinden Sie den Cluster-Switch BES-53248 mit dem Management-Netzwerk.
. Verwenden Sie die `ping` Befehl zur Überprüfung der Verbindung zum Server, auf dem EFOS, Lizenzen und die RCF-Datei gehostet werden.
+
Dieses Beispiel überprüft, ob der Switch mit dem Server unter der IP-Adresse 172.19.2.1 verbunden ist:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Automatische Wiederherstellung der Cluster-LIFs deaktivieren.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Anzeige der Startabbilder für die aktive und die Sicherungskonfiguration:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. Laden Sie die Image-Datei auf den Switch herunter.
+
Durch das Kopieren der Image-Datei in das Backup-Image wird beim Neustart die laufende EFOS-Version dieses Images erstellt und das Update abgeschlossen.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Anzeige der Startabbilder für die aktive und die Sicherungskonfiguration:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. Starten Sie das System von der Sicherungskonfiguration:
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. Anzeige der Startabbilder für die aktive und die Sicherungskonfiguration:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. Die laufende Konfiguration in der Startkonfiguration speichern:
+
`write memory`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. Starten Sie den Switch neu:
+
`reload`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Melden Sie sich erneut an und überprüfen Sie die neue Version der EFOS-Software:
+
`show version`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Wiederholen Sie die Schritte 5 bis 11 am Schalter cs1.
. Automatische Wiederherstellung der Cluster-LIFs aktivieren.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Überprüfen Sie, ob die Cluster-LIFs wieder auf ihren Heimatport zurückgekehrt sind:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Weitere Einzelheiten finden Sie unterlink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["LIF zum Heimathafen zurückversetzen"] Die





=== Methode 2: EFOS mithilfe der ONIE OS-Installation aktualisieren

Die folgenden Schritte können Sie durchführen, wenn eine EFOS-Version FIPS-konform und die andere EFOS-Version nicht FIPS-konform ist.  Diese Schritte können verwendet werden, um das Nicht-FIPS- oder FIPS-konforme EFOS 3.7.xx-Image von ONIE zu aktualisieren, falls der Switch nicht bootet.


NOTE: Diese Funktionalität ist nur für EFOS 3.7.xx oder spätere, nicht FIPS-konforme Versionen verfügbar.


CAUTION: Wenn Sie EFOS mithilfe der ONIE OS-Installation aktualisieren, werden die Konfigurationen auf die Werkseinstellungen zurückgesetzt und die Lizenzen gelöscht.  Sie müssen den Switch einrichten und Lizenzen sowie eine unterstützte RCF installieren, um den Switch wieder in den Normalbetrieb zu versetzen.

.Schritte
. Automatische Wiederherstellung der Cluster-LIFs deaktivieren.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Starten Sie den Switch im ONIE-Installationsmodus.
+
Wählen Sie während des Systemstarts ONIE aus, wenn die entsprechende Aufforderung angezeigt wird:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Nachdem Sie *ONIE* ausgewählt haben, lädt die Schaltfläche und zeigt Ihnen mehrere Optionen an.  Wählen Sie *Betriebssystem installieren*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Der Switch startet im ONIE-Installationsmodus.

. Beenden Sie die ONIE-Erkennung und konfigurieren Sie die Ethernet-Schnittstelle.
+
Wenn die folgende Meldung erscheint, drücken Sie *Enter*, um die ONIE-Konsole aufzurufen:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: Die ONIE-Erkennung wird fortgesetzt und Meldungen werden auf der Konsole ausgegeben.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Konfigurieren Sie die Ethernet-Schnittstelle und fügen Sie die Route hinzu mit `ifconfig eth0 <ipAddress> netmask <netmask> up` Und `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Überprüfen Sie, ob der Server, auf dem die ONIE-Installationsdatei gehostet wird, erreichbar ist:
+
`ping`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installieren Sie die neue Switch-Software:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Die Software installiert sich und startet den Switch anschließend neu.  Lassen Sie den Switch normal in die neue EFOS-Version neu starten.

. Überprüfen Sie, ob die neue Switch-Software installiert ist:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Schließen Sie die Installation ab.  Der Switch startet ohne angewendete Konfiguration neu und wird auf die Werkseinstellungen zurückgesetzt.  Führen Sie die folgenden Schritte aus, um den Switch neu zu konfigurieren:
+
.. link:configure-licenses.html["Lizenzen installieren"]
.. link:configure-install-rcf.html["Installieren Sie den RCF"]
.. link:configure-ssh.html["Aktivieren von SSH"]
.. link:CSHM_log_collection.html["Protokollerfassung aktivieren"]
.. link:CSHM_snmpv3.html["SNMPv3 für die Überwachung konfigurieren"]


. Wiederholen Sie die Schritte 2 bis 8 am Schalter cs1.
. Automatische Wiederherstellung der Cluster-LIFs aktivieren.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Überprüfen Sie, ob die Cluster-LIFs wieder auf ihren Heimatport zurückgekehrt sind:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Weitere Einzelheiten finden Sie unterlink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["LIF zum Heimathafen zurückversetzen"] Die


