---
permalink: switch-cisco-3132q-v/cn1610-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Sie können Cisco Nexus 3132q-v Switches als Cluster-Switches in Ihrem AFF oder FAS Cluster verwenden. 
---
= Konfigurieren Sie Ihre Ports für die Migration von CN1610-Switches zu 3132Q-V-Switches.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um Ihre Ports für die Migration von den CN1610-Switches auf die neuen Nexus 3132Q-V-Switches zu konfigurieren.

.Schritte
. Entfernen Sie an allen Knoten die Kabel, die an den CN1610-Switch CL2 angeschlossen sind.
+
Bei Verwendung geeigneter Kabel müssen Sie die getrennten Ports an allen Knoten wieder mit dem Switch Nexus 3132Q-V C2 verbinden.

. Entfernen Sie vier ISL-Kabel von den Ports 13 bis 16 des CN1610-Switches CL1.
+
Sie müssen geeignete Cisco QSFP-zu-SFP+-Breakout-Kabel anschließen, die Port 1/24 des neuen Cisco 3132Q-V Switches C2 mit den Ports 13 bis 16 des vorhandenen CN1610 Switches CL1 verbinden.

+

NOTE: Beim Wiederanschließen von Kabeln an den neuen Cisco 3132Q-V Switch müssen Sie entweder Glasfaser- oder Cisco Twinax-Kabel verwenden.

. Um die ISL dynamisch zu gestalten, konfigurieren Sie die ISL-Schnittstelle 3/1 am aktiven CN1610-Switch so, dass der statische Modus deaktiviert wird: `no port-channel static`
+
Diese Konfiguration entspricht der ISL-Konfiguration auf dem 3132Q-V-Schalter C2, wenn die ISLs in Schritt 11 auf beiden Schaltern aktiviert werden.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Konfiguration der ISL-Schnittstelle 3/1 unter Verwendung der `no port-channel static` Befehl zur dynamischen Gestaltung der ISL:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 3/1
(CL1)(Interface 3/1)# no port-channel static
(CL1)(Interface 3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Schalten Sie die ISLs 13 bis 16 auf dem aktiven CN1610-Switch CL1 ein.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel veranschaulicht den Vorgang, die ISL-Ports 13 bis 16 auf der Portkanal-Schnittstelle 3/1 zu aktivieren:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 0/13-0/16,3/1
(CL1)(Interface 0/13-0/16,3/1)# no shutdown
(CL1)(Interface 0/13-0/16,3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Überprüfen Sie, ob die ISLs `up` auf dem CN1610-Schalter CL1:
+
`show port-channel`

+
Der "Verbindungsstatus" sollte sein `Up` "Typ" sollte sein `Dynamic` und die Spalte "Port aktiv" sollte `True` für die Ports 0/13 bis 0/16:

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(CL1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. Überprüfen Sie, ob die ISLs `up` am Schalter C2 des Modells 3132Q-V:
+
`show port-channel summary`

+
.Beispiel anzeigen
[%collapsible]
====
Die Ports Eth1/24/1 bis Eth1/24/4 sollten anzeigen `(P)` Das bedeutet, dass alle vier ISL-Ports im Portkanal aktiv sind.  Eth1/31 und Eth1/32 sollten anzeigen `(D)` da sie nicht miteinander verbunden sind:

[listing]
----
C2# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2     Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. Aktivieren Sie alle Cluster-Verbindungsports, die mit dem Switch C2 3132Q-V auf allen Knoten verbunden sind:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die mit dem Switch C2 3132Q-V verbundenen Cluster-Interconnect-Ports aktiviert werden:

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
----
====
. Alle migrierten Cluster-Interconnect-LIFs, die auf allen Knoten mit C2 verbunden sind, sollen zurückgesetzt werden:
+
`network interface revert`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
----
====
. Überprüfen Sie, ob alle Cluster-Verbindungsports wieder auf ihre ursprünglichen Ports zurückgesetzt wurden:
+
`network interface show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die LIFs auf clus2 auf ihre ursprünglichen Ports zurückgesetzt werden und dass die Rücksetzung erfolgreich war, wenn die Ports in der Spalte „Aktueller Port“ den Status „“ aufweisen. `true` in der Spalte „Ist zu Hause“.  Wenn der Wert von "Is Home" `false` Dann wird der LIF nicht zurückgesetzt.

[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. Überprüfen Sie, ob alle Cluster-Ports verbunden sind:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt das Ergebnis des vorherigen Schritts. `network port modify` Befehl, der überprüft, ob alle Clusterverbindungen vorhanden sind. `up` :

[listing]
----
cluster::*> network port show -role Cluster
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

Node: n2
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

8 entries were displayed.
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können die `network interface check cluster-connectivity` Befehl zum Starten einer Zugriffsprüfung für die Clusterkonnektivität und anschließenden Anzeigen der Details:

`network interface check cluster-connectivity start`Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Befehl „show“ ausführen, um die Details anzuzeigen.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source      Destination   Packet
Node   Date                       LIF         LIF           Loss
------ -------------------------- ---------- -------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2       none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2       none
----
--
.Alle ONTAP Versionen
--
Für alle ONTAP Versionen können Sie auch die `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Verbindung:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step12]] Auf jedem Knoten im Cluster werden die Schnittstellen migriert, die dem ersten zu ersetzenden CN1610-Switch CL1 zugeordnet sind:
+
`network interface migrate`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Ports oder LIFs, die auf den Knoten n1 und n2 migriert werden:

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -destination-node n1 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n1_clus4 -destination-node n1 -destination-port e0c
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -destination-node n2 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n2_clus4 -destination-node n2 -destination-port e0c
----
====
. Überprüfen Sie den Clusterstatus:
+
`network interface show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die erforderlichen Cluster-LIFs auf die entsprechenden Cluster-Ports auf dem Cluster-Switch C2 migriert wurden:

[listing]
----
cluster::*> network interface show -role Cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. Schalten Sie die Knotenports ab, die auf allen Knoten mit CL1 verbunden sind:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die angegebenen Ports auf den Knoten n1 und n2 deaktiviert werden:

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin false
cluster::*> network port modify -node n1 -port e0d -up-admin false
cluster::*> network port modify -node n2 -port e0a -up-admin false
cluster::*> network port modify -node n2 -port e0d -up-admin false
----
====
. Schalten Sie die ISL-Ports 24, 31 und 32 am aktiven Switch C2 3132Q-V ab:
+
`shutdown`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die ISLs 24, 31 und 32 am aktiven 3132Q-V-Switch C2 abgeschaltet werden:

[listing]
----
C2# configure
C2(config)# interface ethernet 1/24/1-4
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
C2#
----
====
. Entfernen Sie die Kabel, die an den CN1610-Switch CL1 an allen Knoten angeschlossen sind.
+
Bei Verwendung geeigneter Kabel müssen Sie die getrennten Ports an allen Knoten wieder mit dem Switch Nexus 3132Q-V C1 verbinden.

. Entfernen Sie die QSFP-Kabel vom Nexus 3132Q-V C2 Port e1/24.
+
Sie müssen die Ports e1/31 und e1/32 auf C1 mit den Ports e1/31 und e1/32 auf C2 mithilfe von unterstützten Cisco QSFP Glasfaser- oder Direktanschlusskabeln verbinden.

. Stellen Sie die Konfiguration auf Port 24 wieder her und entfernen Sie den temporären Portkanal 2 auf C2, indem Sie die `running-configuration` Datei an die `startup-configuration` Datei.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel kopiert das `running-configuration` Datei an die `startup-configuration` Datei:

[listing]
----
C2# configure
C2(config)# no interface breakout module 1 port 24 map 10g-4x
C2(config)# no interface port-channel 2
C2(config-if)# interface e1/24
C2(config-if)# description 40GbE Node Port
C2(config-if)# spanning-tree port type edge
C2(config-if)# spanning-tree bpduguard enable
C2(config-if)# mtu 9216
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Aktivieren Sie die ISL-Ports 31 und 32 an C2, dem aktiven Switch 3132Q-V:
+
`no shutdown`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die ISLs 31 und 32 am Schalter C2 des 3132Q-V aktiviert werden:

[listing]
----

C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====


.Wie geht es weiter?
link:cn1610-complete-migration.html["Schließen Sie Ihre Migration ab."].
