---
permalink: switch-cisco-3132q-v/cn1610-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Sie können Cisco Nexus 3132q-V Switches als Cluster-Switches in Ihrem AFF oder FAS Cluster verwenden. 
---
= Konfigurieren Sie Ihre Ports für die Migration von CN1610-Switches auf 3132Q-V-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um Ihre Ports für die Migration von den CN1610-Switches auf die neuen Nexus 3132Q-V-Switches zu konfigurieren.

.Schritte
. Entfernen Sie auf allen Knoten die Kabel, die am CN1610 Switch CL2 angeschlossen sind.
+
Bei der unterstützten Verkabelung müssen Sie die getrennten Ports auf allen Knoten wieder an den Nexus 3132Q-V Switch C2 anschließen.

. Entfernen Sie vier ISL-Kabel von den Ports 13 bis 16 am CN1610-Switch CL1.
+
Sie müssen geeignete Cisco QSFP an SFP+-Breakout-Kabel anschließen, die Port 1/24 am neuen Cisco 3132Q-V Switch C2 an die Ports 13 bis 16 am vorhandenen CN1610-Switch CL1 anschließen.

+

NOTE: Beim erneuten Anschließen von Kabeln an den neuen Cisco 3132Q-V Switch müssen Sie entweder eine Glasfaser oder ein Cisco Twinax-Kabel verwenden.

. Um die ISL dynamisch zu machen, konfigurieren Sie die ISL-Schnittstelle 3/1 auf dem aktiven CN1610-Switch, um den statischen Modus zu deaktivieren: `no port-channel static`
+
Diese Konfiguration entspricht der ISL-Konfiguration auf dem 3132Q-V-Switch C2, wenn die ISLs auf beiden Switches in Schritt 11 hochgefahren werden.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Konfiguration der ISL-Schnittstelle 3/1 mit dem `no port-channel static` Befehl für die ISL-Dynamik:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 3/1
(CL1)(Interface 3/1)# no port-channel static
(CL1)(Interface 3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. ISLs 13 bis 16 auf dem aktiven CN1610-Switch CL1 bringen.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel veranschaulicht, wie die ISL-Ports 13 bis 16 auf die Port-Channel-Schnittstelle 3/1 gebracht werden:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 0/13-0/16,3/1
(CL1)(Interface 0/13-0/16,3/1)# no shutdown
(CL1)(Interface 0/13-0/16,3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Überprüfen Sie, ob es sich bei den ISLs um handelt `up` Am CN1610-Schalter CL1:
+
`show port-channel`

+
Der „Verbindungsstatus“ sollte sein `Up`, "Typ" sollte sein `Dynamic`, Und die Spalte "Port Active" sollte sein `True` Für Ports 0/13 bis 0/16:

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(CL1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. Überprüfen Sie, ob es sich bei den ISLs um handelt `up` Am 3132Q-V Schalter C2:
+
`show port-channel summary`

+
.Beispiel anzeigen
[%collapsible]
====
Die Ports eth1/24/1 bis eth1/24/4 sollten angegeben werden `(P)`, Das bedeutet, dass alle vier ISL-Ports im Port-Channel aktiv sind. Eth1/31 und eth1/32 sollten angegeben werden `(D)` Da sie nicht verbunden sind:

[listing]
----
C2# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2     Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. Alle Cluster-Interconnect-Ports, die an allen Knoten mit dem 3132Q-V Switch C2 verbunden sind, werden angezeigt:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die Cluster Interconnect Ports, die mit dem 3132Q-V Switch C2 verbunden sind, geöffnet werden:

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
----
====
. Zurücksetzen aller migrierten Cluster-Interconnect-LIFs, die auf allen Nodes mit C2 verbunden sind:
+
`network interface revert`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
----
====
. Vergewissern Sie sich, dass alle Cluster-Interconnect-Ports auf die Home-Ports zurückgesetzt werden:
+
`network interface show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die LIFs auf clu2 auf ihre Home-Ports zurückgesetzt werden und zeigt an, dass die LIFs erfolgreich zurückgesetzt werden, wenn die Ports in der Spalte „Current Port“ den Status von aufweisen `true` In der Spalte „is Home“. Wenn der Wert „Home“ lautet `false`, Dann ist das LIF nicht zurückgesetzt.

[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. Vergewissern Sie sich, dass alle Cluster-Ports verbunden sind:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt das Ergebnis des vorherigen `network port modify` Befehl, um sicherzustellen, dass alle Cluster Interconnects vorhanden sind `up`:

[listing]
----
cluster::*> network port show -role Cluster
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

Node: n2
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

8 entries were displayed.
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können das verwenden `network interface check cluster-connectivity` Befehl, um eine Zugriffsprüfung für die Cluster-Konnektivität zu starten und dann Details anzuzeigen:

`network interface check cluster-connectivity start` Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Befehl show ausführen, um die Details anzuzeigen.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source      Destination   Packet
Node   Date                       LIF         LIF           Loss
------ -------------------------- ---------- -------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2       none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2       none
----
--
.Alle ONTAP Versionen
--
Sie können für alle ONTAP Versionen auch den verwenden `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Konnektivität:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step12]] Migrieren Sie auf jedem Knoten im Cluster die Schnittstellen, die dem ersten CN1610-Switch CL1 zugeordnet sind, um sie zu ersetzen:
+
`network interface migrate`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden die Ports oder LIFs angezeigt, die auf den Nodes n1 und n2 migriert werden:

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -destination-node n1 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n1_clus4 -destination-node n1 -destination-port e0c
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -destination-node n2 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n2_clus4 -destination-node n2 -destination-port e0c
----
====
. Überprüfen Sie den Cluster-Status:
+
`network interface show`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird gezeigt, dass die erforderlichen Cluster-LIFs zu den entsprechenden Cluster-Ports migriert wurden, die auf Cluster-Switch gehostet werden.C2:

[listing]
----
cluster::*> network interface show -role Cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. Fahren Sie die Node-Ports, die auf allen Nodes mit CL1 verbunden sind, herunter:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die angegebenen Ports an den Knoten n1 und n2 heruntergefahren werden:

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin false
cluster::*> network port modify -node n1 -port e0d -up-admin false
cluster::*> network port modify -node n2 -port e0a -up-admin false
cluster::*> network port modify -node n2 -port e0d -up-admin false
----
====
. Fahren Sie die ISL-Ports 24, 31 und 32 am aktiven Switch 3132Q-V C2 herunter.
+
`shutdown`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie ISLs 24, 31 und 32 auf dem aktiven Switch 3132Q-V C2 heruntergefahren werden:

[listing]
----
C2# configure
C2(config)# interface ethernet 1/24/1-4
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
C2#
----
====
. Entfernen Sie die Kabel, die an allen Knoten am CN1610-Switch CL1 angeschlossen sind.
+
Bei der unterstützten Verkabelung müssen Sie die getrennten Ports auf allen Knoten wieder an den Nexus 3132Q-V Switch C1 anschließen.

. Entfernen Sie die QSFP-Kabel vom Nexus 3132Q-V C2-Port e1/24.
+
Sie müssen die Ports e1/31 und e1/32 auf C1 mit den Ports e1/31 und e1/32 auf C2 verbinden, die von unterstützten Cisco QSFP-Glasfaserkabeln oder Direct-Attach-Kabeln verwendet werden.

. Stellen Sie die Konfiguration an Port 24 wieder her, und entfernen Sie den temporären Port-Kanal 2 auf C2, indem Sie den kopieren `running-configuration` Datei in der `startup-configuration` Datei:
+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird das kopiert `running-configuration` Datei in der `startup-configuration` Datei:

[listing]
----
C2# configure
C2(config)# no interface breakout module 1 port 24 map 10g-4x
C2(config)# no interface port-channel 2
C2(config-if)# interface e1/24
C2(config-if)# description 40GbE Node Port
C2(config-if)# spanning-tree port type edge
C2(config-if)# spanning-tree bpduguard enable
C2(config-if)# mtu 9216
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. ISL-Ports 31 und 32 auf C2, dem aktiven 3132Q-V Switch:
+
`no shutdown`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie ISLs 31 und 32 auf dem 3132Q-V Switch C2:

[listing]
----

C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====


.Was kommt als Nächstes?
link:cn1610-complete-migration.html["Schließen Sie die Migration ab"].
