---
permalink: switch-cisco-3132q-v/configure-reqs-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Bei der Installation und Wartung des Cisco Nexus 3132Q-V Switches sollten Sie unbedingt die Netzwerk- und Konfigurationsanforderungen überprüfen. 
---
= Konfigurationsanforderungen für Cisco Nexus 3132Q-V-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Installation und Wartung des Cisco Nexus 3132Q-V Switches sollten Sie unbedingt die Netzwerk- und Konfigurationsanforderungen beachten.



== Konfigurationsanforderungen

Zur Konfiguration Ihres Clusters benötigen Sie die entsprechende Anzahl und Art von Kabeln und Kabelverbindern für Ihre Switches.  Je nach Art des Switches, den Sie initial konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Konsolenport des Switches herstellen; außerdem müssen Sie spezifische Netzwerkinformationen angeben.



== Netzwerkanforderungen

Für alle Switch-Konfigurationen benötigen Sie folgende Netzwerkinformationen:

* IP-Subnetz für den Verwaltungsnetzwerkverkehr.
* Hostnamen und IP-Adressen für jeden der Speichersystem-Controller und alle entsprechenden Switches.
* Die meisten Speichersystem-Controller werden über die e0M-Schnittstelle verwaltet, indem eine Verbindung zum Ethernet-Service-Port (Schraubenschlüsselsymbol) hergestellt wird. Bei den Systemen AFF A800 und AFF A700 verwendet die e0M-Schnittstelle einen dedizierten Ethernet-Anschluss.


Siehe die https://hwu.netapp.com["Hardware Universe"^] für die aktuellsten Informationen.

.Was kommt als nächstes
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie die link:required-documentation-3132q.html["erforderliche Dokumentation"]Die
