---
permalink: switch-cisco-3132q-v/configure-reqs-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Prüfen Sie die Netzwerk- und Konfigurationsanforderungen für die Installation und Wartung von Cisco Nexus 3132Q-V Switches 
---
= Konfigurationsanforderungen für Cisco Nexus 3132Q-V Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prüfen Sie die Netzwerk- und Konfigurationsanforderungen für die Installation und Wartung von Cisco Nexus 3132Q-V Switches.



== Konfigurationsanforderungen

Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Switches. Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen. Außerdem müssen Sie spezifische Netzwerkinformationen bereitstellen.



== Netzwerkanforderungen

Sie benötigen die folgenden Netzwerkinformationen für alle Switch-Konfigurationen:

* IP-Subnetz für den Management-Netzwerkdatenverkehr.
* Host-Namen und IP-Adressen für jeden Storage-System-Controller und alle entsprechenden Switches.
* Die meisten Storage-System-Controller werden über die Schnittstelle E0M verwaltet durch eine Verbindung zum Ethernet-Service-Port (Symbol Schraubenschlüssel). Auf AFF A800 und AFF A700 Systemen verwendet die E0M Schnittstelle einen dedizierten Ethernet-Port.


Siehe https://["Hardware Universe"^] Aktuelle Informationen.
