---
permalink: switch-cisco-3132q-v/reset-switch-3132q-v.html 
sidebar: sidebar 
keywords: 3132Q-V reset switch to factory defaults, 3132Q-V2 switches configuration, efos 
summary: Lesen Sie die folgenden Informationen, bevor Sie Ihren Cisco Nexus 3132Q-V-Switch konfigurieren. 
---
= Setzen Sie den 3132Q-V-Cluster-Switch auf die Werkseinstellungen zurück
:allow-uri-read: 


[role="lead"]
Um den Cluster-Switch 3132Q-V auf die Werkseinstellungen zurückzusetzen, müssen Sie die Switch-Einstellungen 3132Q-V löschen.

.Informationen zu diesem Vorgang
* Sie müssen über die serielle Konsole mit dem Switch verbunden sein.
* Diese Aufgabe setzt die Konfiguration des Managementnetzwerks zurück.


.Schritte
. Löschen Sie die vorhandene Konfiguration:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Laden Sie die Switch-Software neu:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Das System wird neu gestartet und der Konfigurationsassistent wird aufgerufen. Wenn Sie während des Startvorgangs die Aufforderung „Auto Provisioning abbrechen und mit der normalen Einrichtung fortfahren?“ erhalten, (ja/nein)[n]“, sollten Sie mit *ja* antworten, um fortzufahren.



.Was kommt als nächstes
Nach dem Zurücksetzen des Schalters können Sielink:install-overview-cisco-3132qv.html["neu konfigurieren"] Es wird Ihren Anforderungen entsprechend angefertigt.
