---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: Beim Austausch von Cisco Nexus 3132Q-V Cluster-Switches müssen Sie bestimmte Konfigurationsinformationen, Portverbindungen und Verkabelungsanforderungen beachten. 
---
= Anforderungen für den Austausch von Cisco Nexus 3132Q-V Cluster-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Achten Sie beim Austausch von Cluster-Switches darauf, die Konfigurationsanforderungen, Portverbindungen und Verkabelungsanforderungen zu verstehen.



== Cisco Nexus 3132Q-V Anforderungen

* Der Cluster-Switch Cisco Nexus 3132Q-V wird unterstützt.
* Die Anzahl der 10-GbE- und 40-GbE-Ports ist in den Referenzkonfigurationsdateien (RCFs) definiert, die unter [URL] verfügbar sind.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Die
* Die Cluster-Switches verwenden die Inter-Switch Link (ISL)-Ports e1/31-32.
* Derlink:https://hwu.netapp.com["Hardware Universe"^] enthält Informationen zur unterstützten Verkabelung für Nexus 3132Q-V Switches:
+
** Die Knoten mit 10-GbE-Clusterverbindungen benötigen QSFP-Lichtwellenleitermodule mit Breakout-Glasfaserkabeln oder QSFP-zu-SFP+-Kupfer-Breakout-Kabel.
** Die Knoten mit 40-GbE-Clusterverbindungen benötigen unterstützte QSFP/QSFP28-Optikmodule mit Glasfaserkabeln oder QSFP/QSFP28-Kupfer-Direktanschlusskabel.
** Die Cluster-Switches verwenden die entsprechende ISL-Verkabelung: 2x QSFP28 Glasfaser- oder Kupfer-Direktanschlusskabel.


* Beim Nexus 3132Q-V können Sie die QSFP-Ports entweder im 40-Gb-Ethernet- oder im 4x10-Gb-Ethernet-Modus betreiben.
+
Standardmäßig stehen im 40-GbE-Ethernet-Modus 32 Ports zur Verfügung.  Diese 40-Gb-Ethernet-Ports sind nach dem 2-Tupel-Namensschema nummeriert.  Beispielsweise ist der zweite 40-Gb-Ethernet-Anschluss mit 1/2 nummeriert.  Der Vorgang, bei dem die Konfiguration von 40-Gb-Ethernet auf 10-Gb-Ethernet geändert wird, wird als _breakout_ bezeichnet, und der Vorgang, bei dem die Konfiguration von 10-Gb-Ethernet auf 40-Gb-Ethernet geändert wird, wird als _breakin_ bezeichnet.  Wenn man einen 40-Gb-Ethernet-Anschluss in 10-Gb-Ethernet-Anschlüsse aufteilt, werden die resultierenden Anschlüsse nach dem 3-Tupel-Namensschema nummeriert.  Beispielsweise sind die Breakout-Ports des zweiten 40-Gb-Ethernet-Ports mit 1/2/1, 1/2/2, 1/2/3 und 1/2/4 nummeriert.

* Auf der linken Seite des Nexus 3132Q-V befindet sich ein Satz von vier SFP+-Ports, die mit dem ersten QSFP-Port gemultiplext sind.
+
Standardmäßig ist das RCF so konfiguriert, dass es den ersten QSFP-Port verwendet.

+
Sie können vier SFP+-Ports anstelle eines QSFP-Ports für den Nexus 3132Q-V aktivieren, indem Sie die `hardware profile front portmode sfp-plus` Befehl.  Ebenso können Sie den Nexus 3132Q-V so zurücksetzen, dass er anstelle von vier SFP+-Ports einen QSFP-Port verwendet, indem Sie die folgende Anleitung verwenden: `hardware profile front portmode qsfp` Befehl.

* Sie müssen einige der Ports am Nexus 3132Q-V so konfiguriert haben, dass sie mit 10 GbE oder 40 GbE laufen.
+
Sie können die ersten sechs Ports im 4x10-GbE-Modus konfigurieren, indem Sie die `interface breakout module 1 port 1-6 map 10g-4x` Befehl.  Ebenso können Sie die ersten sechs QSFP+-Ports aus der Breakout-Konfiguration mithilfe der folgenden Funktion neu gruppieren: `no interface breakout module 1 port 1-6 map 10g-4x` Befehl.

* Sie müssen die Planung und Migration durchgeführt und die erforderliche Dokumentation zur 10-GbE- und 40-GbE-Konnektivität von den Knoten zu den Nexus 3132Q-V Cluster-Switches gelesen haben.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^]enthält Informationen über die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen.





== Cisco Nexus 5596 Anforderungen

* Folgende Cluster-Switches werden unterstützt:
+
** Nexus 5596
** Nexus 3132Q-V


* Die Anzahl der 10-GbE- und 40-GbE-Ports ist in den Referenzkonfigurationsdateien (RCFs) definiert, die unter [URL] verfügbar sind.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco Cluster-Netzwerk-Switch-Referenzkonfigurationsdatei herunterladen"^] Die
* Die Cluster-Switches verwenden die folgenden Ports für die Verbindungen zu den Knoten:
+
** Ports e1/1-40 (10 GbE): Nexus 5596
** Anschlüsse e1/1-30 (40 GbE): Nexus 3132Q-V


* Die Cluster-Switches verwenden die folgenden Inter-Switch Link (ISL)-Ports:
+
** Ports e1/41–48 (10 GbE): Nexus 5596
** Anschlüsse e1/31-32 (40 GbE): Nexus 3132Q-V


* Derlink:https://hwu.netapp.com/["Hardware Universe"^] enthält Informationen zur unterstützten Verkabelung von Nexus 3132Q-V Switches:
+
** Knoten mit 10-GbE-Clusterverbindungen benötigen QSFP-zu-SFP+-Glasfaser-Breakout-Kabel oder QSFP-zu-SFP+-Kupfer-Breakout-Kabel.
** Knoten mit 40-GbE-Clusterverbindungen benötigen unterstützte QSFP/QSFP28-Optikmodule mit Glasfaserkabeln oder QSFP/QSFP28-Kupfer-Direktanschlusskabel.


* Die Cluster-Switches verwenden die entsprechende ISL-Verkabelung:
+
** Beginn: Nexus 5596 zu Nexus 5596 (SFP+ zu SFP+)
+
*** 8x SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel


** Interim: Nexus 5596 zu Nexus 3132Q-V (QSFP zu 4xSFP+ Breakout)
+
*** 1x QSFP-zu-SFP+-Glasfaser- oder Kupfer-Breakout-Kabel


** Endgültig: Nexus 3132Q-V zu Nexus 3132Q-V (QSFP28 zu QSFP28)
+
*** 2x QSFP28 Glasfaser- oder Kupfer-Direktanschlusskabel




* Bei Nexus 3132Q-V Switches können Sie QSFP/QSFP28 Ports entweder im 40 Gigabit Ethernet-Modus oder im 4 x 10 Gigabit Ethernet-Modus betreiben.
+
Standardmäßig stehen im 40-Gigabit-Ethernet-Modus 32 Ports zur Verfügung.  Diese 40 Gigabit-Ethernet-Ports sind nach dem 2-Tupel-Namensschema nummeriert.  Beispielsweise ist der zweite 40-Gigabit-Ethernet-Anschluss mit 1/2 nummeriert.  Der Vorgang der Umstellung der Konfiguration von 40-Gigabit-Ethernet auf 10-Gigabit-Ethernet wird als _breakout_ bezeichnet, und der Vorgang der Umstellung der Konfiguration von 10-Gigabit-Ethernet auf 40-Gigabit-Ethernet wird als _breakin_ bezeichnet.  Wenn man einen 40-Gigabit-Ethernet-Port in 10 Gigabit-Ethernet-Ports aufteilt, werden die resultierenden Ports nach dem 3-Tupel-Namensschema nummeriert.  Beispielsweise sind die Breakout-Ports des zweiten 40-Gigabit-Ethernet-Ports mit 1/2/1, 1/2/2, 1/2/3 und 1/2/4 nummeriert.

* Auf der linken Seite der Nexus 3132Q-V Switches befindet sich ein Satz von 4 SFP+ Ports, die mit dem QSFP28 Port gemultiplext sind.
+
Standardmäßig ist das RCF so konfiguriert, dass es den QSFP28-Port verwendet.

+

NOTE: Sie können 4x SFP+-Ports anstelle eines QSFP-Ports für Nexus 3132Q-V-Switches aktivieren, indem Sie die `hardware profile front portmode sfp-plus` Befehl.  Ebenso können Sie Nexus 3132Q-V-Switches so zurücksetzen, dass sie einen QSFP-Port anstelle von 4x SFP+-Ports verwenden, indem Sie Folgendes verwenden: `hardware profile front portmode qsfp` Befehl.

* Sie haben einige Ports an Nexus 3132Q-V Switches so konfiguriert, dass sie mit 10 GbE oder 40 GbE laufen.
+

NOTE: Sie können die ersten sechs Ports in den 4x10-GbE-Modus aufteilen, indem Sie die `interface breakout module 1 port 1-6 map 10g-4x` Befehl.  Ebenso können Sie die ersten sechs QSFP+-Ports aus der Breakout-Konfiguration mithilfe der folgenden Funktion neu gruppieren: `no interface breakout module 1 port 1-6 map 10g-4x` Befehl.

* Sie haben die Planung und Migration durchgeführt und die erforderliche Dokumentation zur 10-GbE- und 40-GbE-Konnektivität von den Knoten zu den Nexus 3132Q-V Cluster-Switches gelesen.
* Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen sind:link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Die




== NetApp CN1610 Anforderungen

* Folgende Cluster-Switches werden unterstützt:
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* Die Cluster-Switches unterstützen folgende Knotenverbindungen:
+
** NetApp CN1610: Ports 0/1 bis 0/12 (10 GbE)
** Cisco Nexus 3132Q-V: Ports e1/1-30 (40 GbE)


* Die Cluster-Switches verwenden die folgenden Inter-Switch-Link-Ports (ISL):
+
** NetApp CN1610: Ports 0/13 bis 0/16 (10 GbE)
** Cisco Nexus 3132Q-V: Ports e1/31-32 (40 GbE)


* Derlink:https://hwu.netapp.com/["Hardware Universe"^] enthält Informationen zur unterstützten Verkabelung von Nexus 3132Q-V Switches:
+
** Knoten mit 10-GbE-Clusterverbindungen benötigen QSFP-zu-SFP+-Glasfaser-Breakout-Kabel oder QSFP-zu-SFP+-Kupfer-Breakout-Kabel.
** Knoten mit 40-GbE-Clusterverbindungen benötigen unterstützte QSFP/QSFP28-Optikmodule mit Glasfaserkabeln oder QSFP/QSFP28-Kupfer-Direktanschlusskabel.


* Die entsprechende ISL-Verkabelung sieht wie folgt aus:
+
** Beginn: Für CN1610 zu CN1610 (SFP+ zu SFP+), vier SFP+ Glasfaser- oder Kupfer-Direktanschlusskabel
** Interim: Für CN1610 zu Nexus 3132Q-V (QSFP auf vier SFP+ Breakout), ein QSFP auf SFP+ Glasfaser- oder Kupfer-Breakout-Kabel
** Abschließend: Für Nexus 3132Q-V zu Nexus 3132Q-V (QSFP28 zu QSFP28) zwei QSFP28 Glasfaser- oder Kupfer-Direktanschlusskabel


* NetApp Twinax-Kabel sind nicht mit Cisco Nexus 3132Q-V Switches kompatibel.
+
Wenn Ihre aktuelle CN1610-Konfiguration NetApp Twinax-Kabel für Cluster-Node-zu-Switch-Verbindungen oder ISL-Verbindungen verwendet und Sie Twinax weiterhin in Ihrer Umgebung nutzen möchten, müssen Sie Cisco Twinax-Kabel beschaffen.  Alternativ können Sie Glasfaserkabel sowohl für die ISL-Verbindungen als auch für die Verbindungen zwischen Clusterknoten und Switch verwenden.

* Bei Nexus 3132Q-V Switches können Sie QSFP/QSFP28 Ports entweder im 40-Gb-Ethernet-Modus oder im 4x 10-Gb-Ethernet-Modus betreiben.
+
Standardmäßig stehen im 40-GbE-Ethernet-Modus 32 Ports zur Verfügung.  Diese 40-Gb-Ethernet-Ports sind nach dem 2-Tupel-Namensschema nummeriert.  Beispielsweise ist der zweite 40-Gb-Ethernet-Anschluss mit 1/2 nummeriert.  Der Vorgang, bei dem die Konfiguration von 40-Gb-Ethernet auf 10-Gb-Ethernet geändert wird, wird als _breakout_ bezeichnet, und der Vorgang, bei dem die Konfiguration von 10-Gb-Ethernet auf 40-Gb-Ethernet geändert wird, wird als _breakin_ bezeichnet.  Wenn man einen 40-Gb-Ethernet-Anschluss in 10-Gb-Ethernet-Anschlüsse aufteilt, werden die resultierenden Anschlüsse nach dem 3-Tupel-Namensschema nummeriert.  Beispielsweise sind die Breakout-Ports des zweiten 40-Gb-Ethernet-Ports mit 1/2/1, 1/2/2, 1/2/3 und 1/2/4 nummeriert.

* Auf der linken Seite der Nexus 3132Q-V Switches befindet sich ein Satz von vier SFP+ Ports, die mit dem ersten QSFP Port gemultiplext sind.
+
Standardmäßig ist die Referenzkonfigurationsdatei (RCF) so strukturiert, dass der erste QSFP-Port verwendet wird.

+
Sie können vier SFP+-Ports anstelle eines QSFP-Ports für Nexus 3132Q-V-Switches aktivieren, indem Sie die `hardware profile front portmode sfp-plus` Befehl.  Ebenso können Sie Nexus 3132Q-V-Switches so zurücksetzen, dass sie einen QSFP-Port anstelle von vier SFP+-Ports verwenden, indem Sie die folgende Methode verwenden: `hardware profile front portmode qsfp` Befehl.

+

NOTE: Wenn Sie die ersten vier SFP+-Ports verwenden, wird der erste 40GbE QSFP-Port deaktiviert.

* Sie müssen einige Ports an den Nexus 3132Q-V Switches so konfiguriert haben, dass sie mit 10 GbE oder 40 GbE laufen.
+
Sie können die ersten sechs Ports in den 4x10-GbE-Modus aufteilen, indem Sie die `interface breakout module 1 port 1-6 map 10g-4x` Befehl.  Ebenso können Sie die ersten sechs QSFP+-Ports aus der _breakout_-Konfiguration mithilfe der folgenden Funktion neu gruppieren: `no interface breakout module 1 port 1-6 map 10g-4x` Befehl.

* Sie müssen die Planung und Migration durchgeführt und die erforderliche Dokumentation zur 10-GbE- und 40-GbE-Konnektivität von den Knoten zu den Nexus 3132Q-V Cluster-Switches gelesen haben.
* Die in diesem Verfahren unterstützten ONTAP und NX-OS-Versionen sind aufgelistet auflink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Die
* Die in diesem Verfahren unterstützten ONTAP und FASTPATH-Versionen sind aufgelistet auflink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 und CN1610 Switches"^] Die

