---
permalink: switch-cisco-3132q-v/task-install-nx-os-software-and-rcfs-on-cisco-nexus-3132q-v-cluster-switches.html 
sidebar: sidebar 
keywords: install, nx-os software, rcfs, cisco nexus 3132q-v, cluster switches 
summary: 'Die Cisco NX-OS-Software und die Referenzkonfigurationsdateien (RCFs) müssen auf den Cisco Nexus 3132Q-V Cluster Switches installiert sein.' 
---
= Installieren Sie NX-OS und RCFs auf Cisco Nexus 3132Q-V Cluster Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Cisco NX-OS-Software und die Referenzkonfigurationsdateien (RCFs) müssen auf den Cisco Nexus 3132Q-V Cluster Switches installiert sein.

Die folgenden Bedingungen müssen vorliegen, bevor Sie die NX-OS-Software und RCFs (Reference Configurations Files) auf dem Cluster-Switch installieren:

* Das Cluster muss voll funktionsfähig sein (es sollten keine Fehler in den Protokollen oder ähnlichen Problemen geben).
* Sie müssen die gewünschte Boot-Konfiguration im RCF aktiviert oder eingestellt haben, um die gewünschten Boot-Images zu reflektieren, wenn Sie nur NX-OS installieren und Ihre aktuelle RCF-Version behalten.
* Wenn Sie die Startkonfiguration ändern müssen, um die aktuellen Startabbilder zu berücksichtigen, müssen Sie dies vor dem erneuten Anwenden des RCF tun, damit die korrekte Version bei zukünftigen Neustarts instanziiert wird.
* Sie müssen über eine Konsolenverbindung mit dem Switch verfügen, die bei der Installation des RCF erforderlich ist.
* Sie müssen die Switch-Kompatibilitätstabelle auf dem konsultieren link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet Switch"^] Seite für die unterstützten ONTAP-, NX-OS- und RCF-Versionen.
* Es können Befehlsabhängigkeiten zwischen der Befehlssyntax im RCF und denen in Versionen von NX-OS zu finden sind.
* Sie müssen die entsprechenden Software- und Upgrade-Leitfäden auf der Cisco-Website für vollständige Dokumentation zum Upgrade und Downgrade von Cisco Switches unter abrufen https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Switches Der Cisco Nexus 3000-Serie"^].
* Sie müssen über den aktuellen RCF verfügen.


Die Beispiele in diesem Verfahren verwenden zwei Knoten. Diese Nodes verwenden zwei 10-GbE-Cluster-Interconnect-Ports `e0a` Und `e0b`.

Siehe link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] Um sicherzustellen, dass die korrekten Cluster-Ports auf Ihren Plattformen vorhanden sind.


NOTE: Die Ausgaben für die Befehle können je nach verschiedenen Versionen von ONTAP variieren.

Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die Namen der beiden Cisco Switches lauten `cs1` Und `cs2`.
* Die Node-Namen sind `cluster1-01` Und `cluster1-02`.
* Die LIF-Namen des Clusters sind `cluster1-01_clus1` Und `cluster1-01_clus2` Für Clustered 1-01 und `cluster1-02_clus1` Und `cluster1-02_clus2` Für Clustered 1-02.
* Der `cluster1::*>` Eine Eingabeaufforderung gibt den Namen des Clusters an.



NOTE: Das Verfahren erfordert die Verwendung von ONTAP Befehlen und den Switches der Cisco Nexus 3000 Serie. ONTAP Befehle werden verwendet, sofern nicht anders angegeben.

.Schritte
. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Wobei _x_ die Dauer des Wartungsfensters in Stunden ist.

+

NOTE: Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

. Ändern Sie die Berechtigungsebene in Erweitert, und geben Sie *y* ein, wenn Sie dazu aufgefordert werden, fortzufahren:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (`*>`Erscheint.

. Zeigen Sie an, wie viele Cluster-Interconnect-Schnittstellen in jedem Node für jeden Cluster Interconnect-Switch konfiguriert sind:
+
`network device-discovery show -protocol cdp`

+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e0a    cs1                       Eth1/2            N3K-C3132Q-V
            e0b    cs2                       Eth1/2            N3K-C3132Q-V
cluster1-01/cdp
            e0a    cs1                       Eth1/1            N3K-C3132Q-V
            e0b    cs2                       Eth1/1            N3K-C3132Q-V
----
. Überprüfen Sie den Administrations- oder Betriebsstatus der einzelnen Cluster-Schnittstellen.
+
.. Zeigen Sie die Attribute des Netzwerkports an:
+
`network port show –ipspace Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: cluster1-02
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: cluster1-01
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
.. Zeigt Informationen zu den LIFs an:
+
`network interface show -vserver Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical            Status     Network            Current       Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node          Port    Home
----------- ------------------ ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01   e0a     true
            cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01   e0b     true
            cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02   e0a     true
            cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02   e0b     true
----


. Ping für die Remote-Cluster-LIFs:
+
`cluster ping-cluster -node local`

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. Überprüfen Sie das `auto-revert` Befehl ist für alle Cluster-LIFs aktiviert:
+
`network interface show -vserver Cluster -fields auto-revert`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface           Auto-revert
--------- ––––––-------------- ------------
Cluster
          cluster1-01_clus1   true
          cluster1-01_clus2   true
          cluster1-02_clus1   true
          cluster1-02_clus2   true
----

