---
permalink: switch-cisco-3232c-storage/cabling-considerations-3232c-storage.html 
sidebar: sidebar 
keywords: 3232c cabling setup, 3232c switches configuration, nx-os 
summary: Bevor Sie Ihren Cisco 3232C Switch konfigurieren, lesen Sie bitte die folgenden Informationen. 
---
= Überprüfung der Verkabelung und Konfigurationsüberlegungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Ihre 3232C-Switches konfigurieren, überprüfen Sie die Verkabelungs- und Konfigurationsanforderungen.



== Unterstützung für NVIDIA CX6-, CX6-DX- und CX7-Ethernet-Anschlüsse

Wenn Sie einen Switch-Port mit einem ONTAP Controller über NVIDIA ConnectX-6 (CX6), ConnectX-6 Dx (CX6-DX) oder ConnectX-7 (CX7) NIC-Ports verbinden, müssen Sie die Switch-Port-Geschwindigkeit fest codieren.

[listing, subs="+quotes"]
----
(s1)(config)# interface Ethernet1/19
*For 100GbE speed:*
(s1)(config-if)# *speed 100000*
*For 40GbE speed:*
(s1)(config-if)# *speed 40000*
(s1)(config-if)# no negotiate auto
(s1)(config-if)# exit
(s1)(config)# exit
*Save the changes:*
(s1)# *copy running-config startup-config*
----


== Ähnliche Informationen

* Weitere Informationen zu Switch-Ports finden Sie unter  https://hwu.netapp.com/Switch/Index["Hardware Universe"^].
* Weitere Informationen zu den Installationsanforderungen für Netzwerk-Switches finden Sie unter  https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Welche zusätzlichen Informationen benötige ich für die Installation meiner Geräte, die nicht in HWU enthalten sind?"^].

