---
sidebar: sidebar 
permalink: switch-cisco-3232c-storage/configure-reqs-3232c-storage.html 
keywords: shared storage cluster switch 
summary: Ab ONTAP 9.9.1 können Sie Cisco Nexus 3232C Switches verwenden, um Speicher- und Clusterfunktionalität in einem gemeinsam genutzten Switch-Szenario zu kombinieren. 
---
= Konfigurationsanforderungen für Cisco Nexus 3232C Storage Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei der Installation und Wartung des Cisco Nexus 3232C Switches sollten Sie unbedingt die Konfigurations- und Netzwerkanforderungen überprüfen.



== Konfigurationsanforderungen

Sie benötigen die passende Anzahl und Art von Kabeln und Kabelsteckern für Ihre Switches. Je nach Typ des Switches, den Sie zunächst konfigurieren, müssen Sie den Konsolenport des Switches mit dem mitgelieferten Konsolenkabel verbinden; außerdem müssen Sie spezifische Netzwerkinformationen bereitstellen.



== Netzwerkanforderungen

Für alle Switch-Konfigurationen benötigen Sie folgende Netzwerkinformationen:

* IP-Subnetz für den Verwaltungsnetzwerkverkehr
* Hostnamen und IP-Adressen für jeden Speichersystem-Controller und alle entsprechenden Switches
* Die meisten Speichersystem-Controller werden über die e0M-Schnittstelle verwaltet, indem eine Verbindung zum Ethernet-Service-Port (Schraubenschlüsselsymbol) hergestellt wird. Bei den Systemen AFF A800 und AFF A700 verwendet die e0M-Schnittstelle einen dedizierten Ethernet-Anschluss.


Siehe die https://hwu.netapp.com["Hardware Universe"^] für die aktuellsten Informationen. Sehen link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Welche zusätzlichen Informationen benötige ich für die Installation meiner Geräte, die nicht in HWU enthalten sind?"^] Für weitere Informationen zu den Installationsanforderungen des Schalters.

.Was kommt als nächstes
Nachdem Sie Ihre Konfigurationsanforderungen bestätigt haben, können Sie die link:required-documentation-3232c-storage.html["erforderliche Dokumentation"] überprüfen.
