---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH ist eine Voraussetzung für die Verwendung des Cluster Switch Health Monitor (CSHM) und der Protokollerfassungsfunktionen. Um SSH auf Cisco 3232c-Cluster-Switches zu aktivieren, generieren Sie zuerst die SSH-Schlüssel und aktivieren dann SSH.' 
---
= Installieren Sie die Referenzkonfigurationsdatei (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie installieren die Referenzkonfigurationsdatei (RCF), nachdem Sie die Nexus 3232C-Switches zum ersten Mal eingerichtet haben.

.Bevor Sie beginnen
Überprüfen Sie die folgenden Installationen und Verbindungen:

* Eine aktuelle Sicherungskopie der Switch-Konfiguration.
* Ein voll funktionsfähiger Cluster (keine Fehler in den Protokollen oder ähnliche Probleme).
* Der aktuelle RCF.
* Eine Konsolenverbindung zum Switch, dies ist erforderlich, wenn das RCF installiert wird.


.Informationen zu diesem Vorgang
Für dieses Verfahren werden sowohl ONTAP -Befehle als auch Cisco Nexus 3000 Series Switches-Befehle benötigt; es werden ONTAP -Befehle verwendet, sofern nicht anders angegeben.

Führen Sie die Prozedur in link:prepare-install-cisco-nexus-3232c-storage.html["Bereiten Sie die Installation von NX-OS und RCF vor."] durch und befolgen Sie dann die folgenden Schritte.



== Schritt 1: Installieren Sie die RCF auf den Schaltern

. Melden Sie sich bei Switch s2 über SSH oder über eine serielle Konsole an.
. Kopieren Sie die RCF in den Bootflash von Switch s2 mithilfe eines der folgenden Übertragungsprotokolle: FTP, TFTP, SFTP oder SCP. Weitere Informationen zu Cisco-Befehlen finden Sie im entsprechenden Handbuch in der https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 Serie NX-OS Befehlsreferenz"^].
+
.Beispiel anzeigen
[%collapsible]
====
Dieses Beispiel zeigt, wie TFTP verwendet wird, um eine RCF in den Bootflash auf dem Switch s2 zu kopieren:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Wenden Sie die zuvor heruntergeladene RCF-Datei auf den Bootflash an.
+
Weitere Informationen zu Cisco -Befehlen finden Sie im entsprechenden Handbuch im https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 Serie NX-OS Befehlsreferenz"^] .

+
.Beispiel anzeigen
[%collapsible]
====
Dieses Beispiel zeigt die RCF-Datei `NX9336C-FX2-RCF-v1.13-1-Storage.txt`, die auf Switch s2 installiert wird:

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
Lesen Sie unbedingt die Abschnitte *Installationshinweise*, *Wichtige Hinweise* und *Banner* Ihrer RCF sorgfältig durch. Sie müssen diese Anweisungen lesen und befolgen, um die korrekte Konfiguration und den ordnungsgemäßen Betrieb des Switches zu überprüfen.

====
. Untersuchen Sie die Bannerausgabe von `show banner motd` Befehl.  Um die korrekte Konfiguration und den ordnungsgemäßen Betrieb des Schalters sicherzustellen, müssen Sie die Anweisungen unter *Wichtige Hinweise* lesen und befolgen.
. Überprüfen Sie, ob es sich bei der RCF um die korrekte, neuere Version handelt:
+
`show running-config`

+
Wenn Sie die Ausgabe überprüfen, um sicherzustellen, dass Sie die richtige RCF-Datei haben, achten Sie darauf, dass die folgenden Informationen korrekt sind:

+
** Das RCF-Banner
** Die Knoten- und Porteinstellungen
** Anpassungen
+
Das Ergebnis variiert je nach Ihrer Website-Konfiguration.  Prüfen Sie die Port-Einstellungen und beachten Sie die Versionshinweise, um sich über etwaige Änderungen zu informieren, die speziell für die von Ihnen installierte RCF-Version gelten.



. Wenden Sie alle zuvor vorgenommenen Anpassungen auf die Switch-Konfiguration erneut an.
. Nachdem Sie überprüft haben, ob die RCF-Versionen und die Schaltereinstellungen korrekt sind, kopieren Sie die `running-config` Datei an die `startup-config` Datei.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. Schalter s2 neu starten:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Wiederholen Sie die Schritte 1 bis 8 auf Switch s1.
. Verbinden Sie die Node-Storage-Ports und Storage-Shelf-Ports aller Nodes im ONTAP Cluster mit den Switches s1 und s2.




== Schritt 2: Überprüfen Sie die Switch-Verbindungen

. Vergewissern Sie sich, dass die Switch-Ports *up* sind.
+
`show interface brief`

. Überprüfen Sie, ob sich die Knotenspeicherports und Speicherregalports mit den folgenden Befehlen in den richtigen VLANs befinden:
+
`show vlan brief`

+
`show interface trunk`





== Schritt 3: Richten Sie Ihren ONTAP Cluster ein.

NetApp empfiehlt, neue Cluster mit dem System Manager einzurichten.

System Manager bietet einen einfachen und unkomplizierten Arbeitsablauf für die Einrichtung und Konfiguration des Clusters, einschließlich der Zuweisung einer IP-Adresse für die Knotenverwaltung, der Initialisierung des Clusters, der Erstellung einer lokalen Ebene, der Konfiguration von Protokollen und der Bereitstellung des anfänglichen Speichers.

Siehe https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Konfigurieren Sie ONTAP auf einem neuen Cluster mit System Manager"] für Einrichtungsanweisungen.

.Wie geht es weiter?
Nach der Installation des RCF können Sie link:configure-ssh-keys.html["Überprüfen Sie die SSH-Konfiguration"]Die
