---
permalink: switch-cisco-3232c-storage/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: Ein defekter Cisco Nexus 3232C Storage-Switch kann unterbrechungsfrei ausgetauscht werden, indem eine bestimmte Abfolge von Aufgaben ausgeführt wird. 
---
= Ersetzen Sie einen Cisco Nexus 3232C Speicherswitch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um einen defekten Cisco Nexus 3232C Storage-Switch auszutauschen. Dies ist ein unterbrechungsfreies Verfahren.



== Überprüfungsanforderungen

Die bestehende Netzwerkkonfiguration muss folgende Eigenschaften aufweisen:

* Auf der Cisco Ethernet Switches-Seite finden Sie die neuesten RCF- und NX-OS-Versionen für Ihre Switches.
* Die Management-Konnektivität muss auf beiden Switches vorhanden sein.
+
[NOTE]
====
Stellen Sie sicher, dass alle Schritte zur Fehlerbehebung abgeschlossen sind, um zu bestätigen, dass Ihr Schalter ausgetauscht werden muss.

====


Der Ersatz-Switch Cisco Nexus 3232C muss folgende Eigenschaften aufweisen:

* Die Managementnetzwerkanbindung muss funktionsfähig sein.
* Der Zugang zum Ersatzschalter über die Konsole muss gewährleistet sein.
* Das entsprechende RCF- und NX-OS-Betriebssystemabbild muss auf den Switch geladen werden.
* Die Erstkonfiguration des Schalters muss abgeschlossen sein.




== Tauschen Sie den Schalter aus.

Bei diesem Verfahren wird der zweite Nexus 3232C Storage Switch s2 durch den neuen 3232C Switch ns2 ersetzt. Die beiden Knoten sind cluster1-01 und cluster1-02.



=== Schritt 1: Bestätigen Sie, dass der auszutauschende Switch S2 ist

. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ ist die Dauer des Wartungsfensters in Stunden.

+
[NOTE]
====
Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

====
. Überprüfen Sie den Gesundheitszustand der Speicherknoten-Ports, um sicherzustellen, dass eine Verbindung zum Storage Switch s1 besteht:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
cluster1-02
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. Überprüfen Sie, ob der Storage-Switch s1 verfügbar ist:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02                     e4a               AFF-A700
            e4e    cluster1-02                     e4e               AFF-A700
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02                     e4a               -
            e4e    cluster1-02                     e4e               -
cluster1-02/cdp
            e3a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01                     e4a               AFF-A700
            e4e    cluster1-01                     e4e               AFF-A700
cluster1-02/lldp
            e3a    s1                        Ethernet1/2       -
            e4a    cluster1-01                     e4a               -
            e4e    cluster1-01                     e4e               -
.
.
----
====
. Führe die `show lldp neighbors` Führen Sie einen Befehl auf dem funktionierenden Switch aus, um zu bestätigen, dass Sie beide Knoten und alle Regale sehen können:
+
`show lldp neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
cluster1-01             Eth1/1          121        S           e5a
cluster1-02             Eth1/2          121        S           e5a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== Schritt 2: Verkabelung konfigurieren

. [[fünf]]Überprüfen Sie die Regalanschlüsse im Speichersystem:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  s1
3.20   1   -            -
3.20   2   Ethernet1/6  s1
3.20   3   -            -
3.30   0   Ethernet1/7  s1
3.20   1   -            -
3.30   2   Ethernet1/8  s1
3.20   3   -            -
----
====
. Entfernen Sie alle an den Storage Switch s2 angeschlossenen Kabel.
. Schließen Sie alle Kabel wieder an den Ersatz-Netzwerk-Switch ns2 an.




=== Schritt 3: Überprüfen Sie alle Gerätekonfigurationen auf Switch ns2

. Überprüfen Sie den Gesundheitszustand der Speicherknotenports:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30

.
.
----
====
. Vergewissern Sie sich, dass beide Schalter verfügbar sind:
+
`network device-discovery show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02               e4a               AFF-A700
            e4e    cluster1-02               e4e               AFF-A700
            e7b    ns2                       Ethernet1/1       NX3232C
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02               e4a               -
            e4e    cluster1-02               e4e               -
            e7b    ns2                       Ethernet1/1       -
cluster1-02/cdp
            e5a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01               e4a               AFF-A700
            e4e    cluster1-01               e4e               AFF-A700
            e7b    ns2                       Ethernet1/2       NX3232C
cluster1-02/lldp
            e5a    s1                        Ethernet1/2       -
            e4a    cluster1-01               e4a               -
            e4e    cluster1-01               e4e               -
            e7b    ns2                       Ethernet1/2       -
.
.
----
====
. Überprüfen Sie die Regalanschlüsse im Lagersystem:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 s1
3.20  1  Ethernet1/5 ns2
3.20  2  Ethernet1/6 s1
3.20  3  Ethernet1/6 ns2
3.30  0  Ethernet1/7 s1
3.20  1  Ethernet1/7 ns2
3.30  2  Ethernet1/8 s1
3.20  3  Ethernet1/8 ns2
.
.
----
====
. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Wie geht es weiter?
Nachdem Sie Ihren Schalter ausgetauscht haben, können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"].
