---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: Bei den NetApp CN1601 Management Switches und CN1610 Cluster Switches mit ONTAP 8.3.1 oder höher sind die Installationsschritte identisch. Die beiden Modelle benötigen jedoch unterschiedliche Software und RCFs. 
---
= Installieren SIE FASTPATH Software und RCs für ONTAP 8.3.1 und höher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Folgen Sie diesem Verfahren, um FASTPATH-Software und RCFs für ONTAP 8.3.1 und höher zu installieren.

Bei den NetApp CN1601 Management Switches und CN1610 Cluster Switches mit ONTAP 8.3.1 oder höher sind die Installationsschritte identisch. Die beiden Modelle benötigen jedoch unterschiedliche Software und RCFs.



== Prüfen Sie die Anforderungen

.Was Sie benötigen
* Ein aktuelles Backup der Switch-Konfiguration.
* Ein voll funktionsfähiges Cluster (keine Fehler in den Protokollen und keine fehlerhaften Cluster Network Interface Cards (NICs) oder ähnlichen Problemen).
* Voll funktionsfähige Portverbindungen am Cluster-Switch.
* Es sind alle Cluster-Ports eingerichtet.
* Einrichtung aller logischen Cluster-Schnittstellen (LIFs) (darf nicht migriert worden sein)
* Ein erfolgreicher Kommunikationspfad: Der ONTAP (Privilege: Erweitert) `cluster ping-cluster -node node1` Der Befehl muss das angeben `larger than PMTU communication` Ist auf allen Pfaden erfolgreich.
* Eine unterstützte Version von FASTPATH, RCF und ONTAP.
+
Beachten Sie unbedingt die Kompatibilitätstabelle für Switches auf der http://["NetApp CN1601 und CN1610 Switches"^] Seite für die unterstützten FASTPATH-, RCF- und ONTAP-Versionen.





== Installieren Sie die FASTPATH Software

Im folgenden Verfahren wird die Syntax „Clustered Data ONTAP 8.2“ verwendet. Aus diesem Grund unterscheiden sich der Cluster-Vserver, LIF-Namen und die CLI-Ausgabe von denen in Data ONTAP 8.3.

Zwischen der Befehlssyntax für „RCF“ und „FASTPATH“-Versionen kann eine Befehlssyntax bestehen.


NOTE: In RCF Version 1.2 wurde die Unterstützung für Telnet explizit aufgrund von Sicherheitsbedenken deaktiviert. Um Verbindungsprobleme bei der Installation von RCF 1.2 zu vermeiden, vergewissern Sie sich, dass Secure Shell (SSH) aktiviert ist. Der https://["Administratorleitfaden für den NetApp CN1610 Switch"^] Hat weitere Informationen über SSH.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die beiden NetApp Switch-Namen sind cs1 und cs2.
* Die Namen der Cluster Logical Interface (LIF) sind node1_clus1 und node1_clus2 für node1, und node2_clus1 und node2_clus2 für node2. (Ein Cluster kann bis zu 24 Nodes enthalten.)
* Der Name der Storage Virtual Machine (SVM) lautet „Cluster“.
* Der `cluster1::*>` Eine Eingabeaufforderung gibt den Namen des Clusters an.
* Die Cluster-Ports auf jedem Node lauten e0a und e0b.
+
https://["Hardware Universe"^] Bietet weitere Informationen zu den tatsächlichen, auf Ihrer Plattform unterstützten Cluster-Ports.

* Die unterstützten Inter-Switch Links (ISLs) sind die Ports 0/13 bis 0/16.
* Die unterstützten Node-Verbindungen sind die Ports 0/1 bis 0/12.




=== Schritt 1: Migration des Clusters

. Zeigen Sie Informationen zu den Netzwerkports auf dem Cluster an:
+
`network port show -_ipspace cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird der Ausgabetyp aus dem Befehl angezeigt:

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Zeigt Informationen zu den LIFs auf dem Cluster an:
+
`network interface show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden die logischen Schnittstellen auf dem Cluster angezeigt. In diesem Beispiel die `-role` Mit dem Parameter werden Informationen zu den LIFs angezeigt, die den Cluster-Ports zugeordnet sind:

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. Migrieren Sie auf jedem entsprechenden Knoten mithilfe einer Knoten-Management-LIF node1_clus2 zu e0a auf node1 und node2_clus2 zu e0a auf node2:
+
`network interface migrate`

+
Sie müssen die Befehle an den Controller-Konsolen eingeben, die über die jeweiligen Cluster-LIFs verfügen.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: Für diesen Befehl wird die Groß-/Kleinschreibung des Clusters beachtet, und der Befehl sollte auf jedem Node ausgeführt werden. Dieser Befehl kann nicht in der allgemeinen Cluster LIF ausgeführt werden.

. Stellen Sie sicher, dass die Migration mit dem durchgeführt wurde `network interface show` Befehl auf einem Node.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass clus2 zu Port e0a auf Nodes node1 und node2 migriert hat:

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. Ändern Sie die Berechtigungsebene in Erweitert. Geben Sie Y ein, wenn Sie dazu aufgefordert werden, fortzufahren:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Fahren Sie Cluster-Port e0b auf beiden Nodes herunter:
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
Sie müssen die Befehle an den Controller-Konsolen eingeben, die über die jeweiligen Cluster-LIFs verfügen.

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden die Befehle zum Herunterfahren von Port e0b auf allen Nodes angezeigt:

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. Vergewissern Sie sich, dass Port e0b auf beiden Nodes heruntergefahren wird:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. Fahren Sie die Inter-Switch Link (ISL)-Ports auf cs1 herunter.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. Sichern Sie das aktuelle aktive Bild auf cs2.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




=== Schritt: INSTALLIEREN Sie die FASTPATH-Software und RCF

. Überprüfen Sie die laufende Version der FASTPATH-Software.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. Laden Sie die Bilddatei auf den Switch herunter.
+
Durch Kopieren der Bilddatei auf das aktive Bild wird beim Neustart die laufende FASTPATH-Version erstellt. Das vorherige Bild bleibt als Backup verfügbar.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Aktuelle und nächste aktive Bootabbilde bestätigen:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. Installieren Sie den kompatiblen RCF für die neue Bildversion auf dem Switch.
+
Wenn die RCF-Version bereits korrekt ist, die ISL-Ports heraufbringen.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: Der `.scr` Die Erweiterung muss als Teil des Dateinamens festgelegt werden, bevor das Skript aufgerufen wird. Diese Erweiterung gilt für DAS FASTPATH-Betriebssystem.

+
Der Switch überprüft das Skript automatisch, wenn es auf den Switch heruntergeladen wird. Die Ausgabe geht zur Konsole.

. Überprüfen Sie, ob das Skript heruntergeladen und auf dem Dateinamen gespeichert wurde, den Sie ihm gegeben haben.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. Das Skript auf den Switch anwenden.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. Überprüfen Sie, ob die Änderungen auf den Switch angewendet wurden, und speichern Sie sie:
+
`show running-config`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. Speichern Sie die laufende Konfiguration, damit sie die Startkonfiguration wird, wenn Sie den Switch neu starten.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Starten Sie den Switch neu.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




=== Schritt 3: Installation validieren

. Melden Sie sich erneut an, und überprüfen Sie dann, ob auf dem Switch die neue Version der FASTPATH-Software ausgeführt wird.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
Nach Abschluss des Neubootens müssen Sie sich anmelden, um die Bildversion zu überprüfen, die laufende Konfiguration anzuzeigen, und nach der Beschreibung auf der Schnittstelle 3/64 suchen, die die Versionsbezeichnung für die RCF ist.

. ISL-Ports an cs1, dem aktiven Switch, herauf.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. Vergewissern Sie sich, dass die ISLs betriebsbereit sind:
+
`show port-channel 3/1`

+
Das Feld „Verbindungsstatus“ sollte angezeigt werden `Up`.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Bringen Sie Cluster Port e0b auf allen Nodes hinzu:
+
`network port modify`

+
Sie müssen die Befehle an den Controller-Konsolen eingeben, die über die jeweiligen Cluster-LIFs verfügen.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass Port e0b auf node1 und node2 gebracht wird:

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. Vergewissern Sie sich, dass der Port e0b auf allen Nodes aktiviert ist:
+
`network port show -ipspace cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Vergewissern Sie sich, dass das LIF jetzt die Startseite ist (`true`) Auf beiden Knoten:
+
`network interface show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. Zeigt den Status der Node-Mitglieder an:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. Zurück zur Administratorberechtigungsebene:
+
`set -privilege admin`

. Wiederholen Sie die vorherigen Schritte, um DIE FASTPATH-Software und RCF auf dem anderen Switch, cs1, zu installieren.

