---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Wenn Sie die FASTPATH-Software auf Ihren NetApp -Switches installieren, müssen Sie das Upgrade mit dem zweiten Switch, cs2, beginnen. 
---
= Installieren Sie die FASTPATH-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die FASTPATH-Software auf Ihren NetApp -Switches installieren, müssen Sie das Upgrade mit dem zweiten Switch, _cs2_, beginnen.



== Überprüfungsanforderungen

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Eine aktuelle Sicherungskopie der Switch-Konfiguration.
* Ein voll funktionsfähiger Cluster (keine Fehler in den Protokollen und keine defekten Cluster-Netzwerkschnittstellenkarten (NICs) oder ähnliche Probleme).
* Voll funktionsfähige Portverbindungen am Cluster-Switch.
* Alle Cluster-Ports eingerichtet.
* Alle logischen Schnittstellen (LIFs) des Clusters müssen eingerichtet sein (dürfen nicht migriert worden sein).
* Ein erfolgreicher Kommunikationsweg: ONTAP (Privileg: fortgeschritten) `cluster ping-cluster -node node1` Der Befehl muss angeben, dass `larger than PMTU communication` ist auf allen Wegen erfolgreich.
* Eine unterstützte Version von FASTPATH ​​und ONTAP.
+
Bitte konsultieren Sie die Tabelle zur Schalterkompatibilität auf der Website. http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 und CN1610 Switches"^] Seite für die unterstützten FASTPATH- und ONTAP Versionen.





== Installieren Sie FASTPATH

Das folgende Verfahren verwendet die Clustered Data ONTAP 8.2 Syntax.  Daher unterscheiden sich der Cluster-Vserver, die LIF-Namen und die CLI-Ausgabe von denen in Data ONTAP 8.3.

Zwischen der Befehlssyntax in den RCF- und FASTPATH-Versionen können Befehlsabhängigkeiten bestehen.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die beiden NetApp Switches sind cs1 und cs2.
* Die beiden Cluster-LIFs sind clus1 und clus2.
* Die Vserver sind vs1 und vs2.
* Der `cluster::*>` Die Eingabeaufforderung zeigt den Namen des Clusters an.
* Die Cluster-Ports auf jedem Knoten tragen die Namen e1a und e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]enthält weitere Informationen zu den tatsächlichen Cluster-Ports, die auf Ihrer Plattform unterstützt werden.

* Die unterstützten Inter-Switch-Links (ISLs) sind die Ports 0/13 bis 0/16.
* Die unterstützten Knotenverbindungen sind die Ports 0/1 bis 0/12.




=== Schritt 1: Cluster migrieren

. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ ist die Dauer des Wartungsfensters in Stunden.

+

NOTE: Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

. Melden Sie sich als Administrator am Switch an.  Es gibt standardmäßig kein Passwort.  Am `(cs2) #` Eingabeaufforderung, geben Sie die `enable` Befehl.  Auch hier gilt: Standardmäßig ist kein Passwort erforderlich.  Dies ermöglicht Ihnen den Zugriff auf den privilegierten EXEC-Modus, mit dem Sie die Netzwerkschnittstelle konfigurieren können.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. Auf der Konsole jedes Knotens migrieren Sie clus2 auf Port e1a:
+
`network interface migrate`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. Überprüfen Sie auf der Konsole jedes Knotens, ob die Migration durchgeführt wurde:
+
`network interface show`

+
Das folgende Beispiel zeigt, dass clus2 auf beiden Knoten auf Port e1a migriert wurde:

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== Schritt 2: Installieren Sie die FASTPATH-Software

. Schalten Sie den Cluster-Port e2a auf beiden Knoten ab:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie Port e2a auf beiden Knoten abgeschaltet wird:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Überprüfen Sie, ob Port e2a auf beiden Knoten deaktiviert ist:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Schalten Sie die Inter-Switch Link (ISL)-Ports am aktiven NetApp Switch cs1 ab:
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Sichern Sie das aktuell aktive Image auf cs2.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Laden Sie die Image-Datei auf den Switch herunter.
+
Durch das Kopieren der Image-Datei in das aktive Image wird beim Neustart die laufende FASTPATH-Version aus diesem Image erstellt.  Das vorherige Image bleibt als Backup verfügbar.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Überprüfen Sie die laufende Version der FASTPATH-Software.
+
`show version`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Sehen Sie sich die Startabbilder für die aktive und die Sicherungskonfiguration an.
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Starten Sie den Switch neu.
+
`reload`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== Schritt 3: Installation überprüfen

. Melden Sie sich erneut an und überprüfen Sie die neue Version der FASTPATH-Software.
+
`show version`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Schalten Sie die ISL-Ports auf cs1, dem aktiven Switch, ein.
+
`configure`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Überprüfen Sie, ob die ISLs betriebsbereit sind:
+
`show port-channel 3/1`

+
Das Feld „Verbindungsstatus“ sollte Folgendes anzeigen: `Up` Die

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Kopiere die `running-config` Datei an die `startup-config` Die Datei wird erst geladen, wenn Sie mit den Softwareversionen und Schaltereinstellungen zufrieden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Aktivieren Sie den zweiten Cluster-Port, e2a, auf jedem Knoten:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Rückgängig machen von clus2, das mit Port e2a verknüpft ist:
+
`network interface revert`

+
Die LIF-Einstellungen können sich je nach Version Ihrer ONTAP -Software automatisch zurücksetzen.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Überprüfen Sie, ob sich das LIF jetzt im Startbereich befindet.(`true` ) auf beiden Knoten:
+
`network interface show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Den Status der Knoten anzeigen:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Wiederholen Sie die vorherigen Schritte, um die FASTPATH-Software auf dem anderen Switch, cs1, zu installieren.
. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


