---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 'Bei der Installation einer Referenzkonfigurationsdatei (RCF) müssen Sie zuerst die Cluster-LIFs vom Switch cs2 migrieren.  Nach der Installation und Validierung des RCF können die LIFs zurückmigriert werden.' 
---
= Installieren einer Referenzkonfigurationsdatei auf einem CN1610-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie wie folgt vor, um eine Referenzkonfigurationsdatei (RCF) zu installieren.

Vor der Installation eines RCF müssen Sie zuerst die Cluster-LIFs vom Switch cs2 migrieren.  Nach der Installation und Validierung des RCF können die LIFs zurückmigriert werden.



== Überprüfungsanforderungen

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Eine aktuelle Sicherungskopie der Switch-Konfiguration.
* Ein voll funktionsfähiger Cluster (keine Fehler in den Protokollen und keine defekten Cluster-Netzwerkschnittstellenkarten (NICs) oder ähnliche Probleme).
* Voll funktionsfähige Portverbindungen am Cluster-Switch.
* Alle Cluster-Ports eingerichtet.
* Alle logischen Schnittstellen (LIFs) des Clusters wurden eingerichtet.
* Ein erfolgreicher Kommunikationsweg: ONTAP (Privileg: fortgeschritten) `cluster ping-cluster -node node1` Der Befehl muss angeben, dass `larger than PMTU communication` ist auf allen Wegen erfolgreich.
* Eine unterstützte Version von RCF und ONTAP.
+
Bitte konsultieren Sie die Tabelle zur Schalterkompatibilität auf der Website. http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 und CN1610 Switches"^] Seite für die unterstützten RCF- und ONTAP Versionen.





== Installieren Sie den RCF

Das folgende Verfahren verwendet die Clustered Data ONTAP 8.2 Syntax.  Daher unterscheiden sich der Cluster-Vserver, die LIF-Namen und die CLI-Ausgabe von denen in Data ONTAP 8.3.

Zwischen der Befehlssyntax in den RCF- und FASTPATH-Versionen können Befehlsabhängigkeiten bestehen.


NOTE: In RCF Version 1.2 wurde die Unterstützung für Telnet aus Sicherheitsgründen explizit deaktiviert.  Um Verbindungsprobleme während der Installation von RCF 1.2 zu vermeiden, vergewissern Sie sich, dass Secure Shell (SSH) aktiviert ist.  Der https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 Switch – Administratorhandbuch"^] enthält weitere Informationen zu SSH.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die beiden NetApp Switches sind cs1 und cs2.
* Die beiden Cluster-LIFs sind clus1 und clus2.
* Die Vserver sind vs1 und vs2.
* Der `cluster::*>` Die Eingabeaufforderung zeigt den Namen des Clusters an.
* Die Cluster-Ports auf jedem Knoten tragen die Namen e1a und e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]enthält weitere Informationen zu den tatsächlichen Cluster-Ports, die auf Ihrer Plattform unterstützt werden.

* Die unterstützten Inter-Switch-Links (ISLs) sind die Ports 0/13 bis 0/16.
* Die unterstützten Knotenverbindungen sind die Ports 0/1 bis 0/12.
* Eine unterstützte Version von FASTPATH, RCF und ONTAP.
+
Bitte konsultieren Sie die Tabelle zur Schalterkompatibilität auf der Website. http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 und CN1610 Switches"^] Seite für die unterstützten FASTPATH-, RCF- und ONTAP Versionen.





=== Schritt 1: Cluster migrieren

. Speichern Sie Ihre aktuellen Switch-Konfigurationsinformationen:
+
`write memory`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die aktuelle Switch-Konfiguration in der Startkonfiguration gespeichert wird.(`startup-config` ) Datei auf Switch CS2:

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Auf der Konsole jedes Knotens migrieren Sie clus2 auf Port e1a:
+
`network interface migrate`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. Überprüfen Sie auf der Konsole jedes Knotens, ob die Migration stattgefunden hat:
+
`network interface show -role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass clus2 auf beiden Knoten auf Port e1a migriert wurde:

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. Schalten Sie Port e2a auf beiden Knoten ab:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie Port e2a auf beiden Knoten abgeschaltet wird:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Überprüfen Sie, ob Port e2a auf beiden Knoten deaktiviert ist:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. Schalten Sie die ISL-Ports am aktiven NetApp Switch cs1 ab.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== Schritt 2: RCF installieren

. Kopieren Sie die RCF-Datei auf den Switch.
+

NOTE: Sie müssen die `.scr` Die Dateinamenserweiterung muss vor dem Aufruf des Skripts Teil des Dateinamens sein.  Diese Erweiterung ist für das FASTPATH-Betriebssystem.

+
Der Switch validiert das Skript automatisch beim Herunterladen auf den Switch, und die Ausgabe wird in der Konsole angezeigt.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. Überprüfen Sie, ob das Skript heruntergeladen und unter dem von Ihnen angegebenen Dateinamen gespeichert wurde.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. Überprüfen Sie das Skript.
+

NOTE: Das Skript wird während des Downloads validiert, um sicherzustellen, dass jede Zeile eine gültige Switch-Befehlszeile ist.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. Wende das Skript auf den Schalter an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. Überprüfen Sie, ob Ihre Änderungen auf dem Switch implementiert wurden.
+
[listing]
----
(cs2) # show running-config
----
+
Das Beispiel zeigt die `running-config` Datei auf dem Switch.  Sie müssen die Datei mit der RCF-Datei vergleichen, um zu überprüfen, ob die von Ihnen festgelegten Parameter Ihren Erwartungen entsprechen.

. Speichern Sie die Änderungen.
. Stellen Sie die `running-config` Die Datei soll die Standarddatei sein.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. Starten Sie den Switch neu und überprüfen Sie, ob der `running-config` Die Datei ist korrekt.
+
Nach Abschluss des Neustarts müssen Sie sich anmelden und die `running-config` Datei und suchen Sie dann nach der Beschreibung auf Schnittstelle 3/64, das ist die Versionsbezeichnung für die RCF.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Schalten Sie die ISL-Ports auf cs1, dem aktiven Switch, ein.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. Überprüfen Sie, ob die ISLs betriebsbereit sind:
+
`show port-channel 3/1`

+
Das Feld „Verbindungsstatus“ sollte Folgendes anzeigen: `Up` Die

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Aktivieren Sie den Cluster-Port e2a auf beiden Knoten:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie Port e2a auf Knoten 1 und Knoten 2 aktiviert wird:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== Schritt 3: Installation überprüfen

. Überprüfen Sie, ob Port e2a auf beiden Knoten aktiv ist:
+
`network port show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. Auf beiden Knoten muss der mit Port e2a verknüpfte clus2-Befehl zurückgesetzt werden:
+
`network interface revert`

+
Die LIF-Einstellungen werden möglicherweise automatisch zurückgesetzt, abhängig von Ihrer ONTAP-Version.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. Überprüfen Sie, ob sich das LIF jetzt im Startbereich befindet.(`true` ) auf beiden Knoten:
+
`network interface show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Den Status der Knotenmitglieder anzeigen:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. Kopiere die `running-config` Datei an die `startup-config` Die Datei wird erst geladen, wenn Sie mit den Softwareversionen und Schaltereinstellungen zufrieden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Wiederholen Sie die vorherigen Schritte, um den RCF auf dem anderen Switch, cs1, zu installieren.


.Wie geht es weiter?
link:../switch-cshm/config-overview.html["Switch-Zustandsüberwachung konfigurieren"]
