---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: Die Installationsschritte sind für NetApp CN1601 Management-Switches und CN1610 Cluster-Switches mit ONTAP 8.3.1 oder höher identisch.  Allerdings benötigen die beiden Modelle unterschiedliche Software und RCFs. 
---
= Installieren Sie die FASTPATH-Software und die RCFs für ONTAP 8.3.1 und höher.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Folgen Sie diesem Verfahren, um die FASTPATH-Software und RCFs für ONTAP 8.3.1 und höher zu installieren.

Die Installationsschritte sind für NetApp CN1601 Management-Switches und CN1610 Cluster-Switches mit ONTAP 8.3.1 oder höher identisch.  Allerdings benötigen die beiden Modelle unterschiedliche Software und RCFs.



== Überprüfungsanforderungen

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Eine aktuelle Sicherungskopie der Switch-Konfiguration.
* Ein voll funktionsfähiger Cluster (keine Fehler in den Protokollen und keine defekten Cluster-Netzwerkschnittstellenkarten (NICs) oder ähnliche Probleme).
* Voll funktionsfähige Portverbindungen am Cluster-Switch.
* Alle Cluster-Ports eingerichtet.
* Alle logischen Schnittstellen (LIFs) des Clusters müssen eingerichtet sein (dürfen nicht migriert worden sein).
* Ein erfolgreicher Kommunikationsweg: ONTAP (Privileg: fortgeschritten) `cluster ping-cluster -node node1` Der Befehl muss angeben, dass `larger than PMTU communication` ist auf allen Wegen erfolgreich.
* Eine unterstützte Version von FASTPATH, RCF und ONTAP.
+
Bitte konsultieren Sie die Tabelle zur Schalterkompatibilität auf der Website. http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 und CN1610 Switches"^] Seite für die unterstützten FASTPATH-, RCF- und ONTAP Versionen.





== Installieren Sie die FASTPATH-Software

Das folgende Verfahren verwendet die Clustered Data ONTAP 8.2 Syntax.  Daher unterscheiden sich der Cluster-Vserver, die LIF-Namen und die CLI-Ausgabe von denen in Data ONTAP 8.3.

Zwischen der Befehlssyntax in den RCF- und FASTPATH-Versionen können Befehlsabhängigkeiten bestehen.


NOTE: In RCF Version 1.2 wurde die Unterstützung für Telnet aus Sicherheitsgründen explizit deaktiviert.  Um Verbindungsprobleme während der Installation von RCF 1.2 zu vermeiden, vergewissern Sie sich, dass Secure Shell (SSH) aktiviert ist.  Der https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 Switch – Administratorhandbuch"^] enthält weitere Informationen zu SSH.

.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die beiden NetApp Switches tragen die Namen cs1 und cs2.
* Die Namen der logischen Clusterschnittstellen (LIF) lauten node1_clus1 und node1_clus2 für Knoten 1 sowie node2_clus1 und node2_clus2 für Knoten 2.  (Ein Cluster kann bis zu 24 Knoten enthalten.)
* Der Name der Storage Virtual Machine (SVM) lautet Cluster.
* Der `cluster1::*>` Die Eingabeaufforderung zeigt den Namen des Clusters an.
* Die Cluster-Ports auf jedem Knoten tragen die Namen e0a und e0b.
+
https://hwu.netapp.com/["Hardware Universe"^]enthält weitere Informationen zu den tatsächlichen Cluster-Ports, die auf Ihrer Plattform unterstützt werden.

* Die unterstützten Inter-Switch-Links (ISLs) sind die Ports 0/13 bis 0/16.
* Die unterstützten Knotenverbindungen sind die Ports 0/1 bis 0/12.




=== Schritt 1: Cluster migrieren

. Informationen zu den Netzwerkports des Clusters anzeigen:
+
`network port show -_ipspace cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Art der Ausgabe des Befehls:

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Informationen zu den LIFs im Cluster anzeigen:
+
`network interface show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die logischen Schnittstellen des Clusters.  In diesem Beispiel `-role` Der Parameter zeigt Informationen über die LIFs an, die den Cluster-Ports zugeordnet sind:

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. Auf jedem der jeweiligen Knoten migrieren Sie mithilfe eines Knotenverwaltungs-LIF node1_clus2 auf node1 nach e0a und node2_clus2 auf node2 nach e0a:
+
`network interface migrate`

+
Sie müssen die Befehle auf den Controller-Konsolen eingeben, denen die jeweiligen Cluster-LIFs gehören.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: Bei diesem Befehl ist die Groß-/Kleinschreibung des Clusternamens zu beachten, und der Befehl muss auf jedem Knoten ausgeführt werden.  Dieser Befehl kann im allgemeinen Cluster-LIF nicht ausgeführt werden.

. Überprüfen Sie mithilfe des `network interface show` Befehl auf einem Knoten.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass clus2 auf den Knoten node1 und node2 auf Port e0a migriert wurde:

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie bei Aufforderung „y“ eingeben:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Schalten Sie den Cluster-Port e0b auf beiden Knoten ab:
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
Sie müssen die Befehle auf den Controller-Konsolen eingeben, denen die jeweiligen Cluster-LIFs gehören.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die Befehle zum Herunterfahren des Ports e0b auf allen Knoten:

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. Überprüfen Sie, ob Port e0b auf beiden Knoten deaktiviert ist:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. Schalten Sie die Inter-Switch Link (ISL)-Ports auf cs1 ab.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. Sichern Sie das aktuell aktive Image auf cs2.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




=== Schritt 2: Installieren Sie die FASTPATH-Software und RCF.

. Überprüfen Sie die laufende Version der FASTPATH-Software.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. Laden Sie die Image-Datei auf den Switch herunter.
+
Durch das Kopieren der Image-Datei in das aktive Image wird beim Neustart die laufende FASTPATH-Version aus diesem Image erstellt.  Das vorherige Image bleibt als Backup verfügbar.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Bestätigen Sie die aktuelle und die nächste aktive Boot-Image-Version:
+
`show bootvar`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. Installieren Sie die kompatible RCF-Datei für die neue Image-Version auf dem Switch.
+
Wenn die RCF-Version bereits korrekt ist, aktivieren Sie die ISL-Ports.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: Der `.scr` Die Dateinamenserweiterung muss vor dem Aufruf des Skripts festgelegt werden.  Diese Erweiterung ist für das FASTPATH-Betriebssystem.

+
Der Switch validiert das Skript automatisch, sobald es auf den Switch heruntergeladen wird.  Die Ausgabe erfolgt in der Konsole.

. Überprüfen Sie, ob das Skript heruntergeladen und unter dem von Ihnen angegebenen Dateinamen gespeichert wurde.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. Wende das Skript auf den Schalter an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. Überprüfen Sie, ob die Änderungen am Switch übernommen wurden, und speichern Sie sie anschließend:
+
`show running-config`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. Speichern Sie die laufende Konfiguration, damit sie beim Neustart des Switches als Startkonfiguration verwendet wird.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Starten Sie den Switch neu.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




=== Schritt 3: Installation überprüfen

. Melden Sie sich erneut an und überprüfen Sie dann, ob auf dem Switch die neue Version der FASTPATH-Software ausgeführt wird.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
Nach Abschluss des Neustarts müssen Sie sich anmelden, um die Image-Version zu überprüfen, die laufende Konfiguration anzuzeigen und nach der Beschreibung auf der Schnittstelle 3/64 zu suchen. Dies ist die Versionsbezeichnung für die RCF.

. Schalten Sie die ISL-Ports auf cs1, dem aktiven Switch, ein.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. Überprüfen Sie, ob die ISLs betriebsbereit sind:
+
`show port-channel 3/1`

+
Das Feld „Verbindungsstatus“ sollte Folgendes anzeigen: `Up` Die

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Aktivieren Sie den Cluster-Port e0b auf allen Knoten:
+
`network port modify`

+
Sie müssen die Befehle auf den Controller-Konsolen eingeben, denen die jeweiligen Cluster-LIFs gehören.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie Port e0b auf Knoten 1 und Knoten 2 aktiviert wird:

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. Überprüfen Sie, ob Port e0b auf allen Knoten aktiv ist:
+
`network port show -ipspace cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Überprüfen Sie, ob sich das LIF jetzt im Startbereich befindet.(`true` ) auf beiden Knoten:
+
`network interface show -_role cluster_`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. Den Status der Knotenmitglieder anzeigen:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. Zurück zur Administratorrechteebene:
+
`set -privilege admin`

. Wiederholen Sie die vorherigen Schritte, um die FASTPATH-Software und RCF auf dem anderen Switch, cs1, zu installieren.

