---
permalink: switch-netapp-cn1610/migrate-switched-netapp-cn1610.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: Wenn Sie eine vorhandene Cluster-Umgebung mit zwei Nodes ohne Switches nutzen, können Sie mit CN1610 Cluster-Netzwerk-Switches zu einer Switch-basierten Cluster-Umgebung mit zwei Nodes migrieren. So können Sie eine Skalierung über zwei Nodes hinaus vornehmen. 
---
= Migration von einer Cluster-Umgebung ohne Switches zu einer Switch-basierten NetApp CN1610 Cluster-Umgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine vorhandene Cluster-Umgebung mit zwei Nodes ohne Switches nutzen, können Sie mit CN1610 Cluster-Netzwerk-Switches zu einer Switch-basierten Cluster-Umgebung mit zwei Nodes migrieren. So können Sie eine Skalierung über zwei Nodes hinaus vornehmen.



== Prüfen Sie die Anforderungen

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie Folgendes haben:

Stellen Sie bei einer Konfiguration mit zwei Nodes ohne Switches Folgendes sicher:

* Die Konfiguration mit zwei Nodes ohne Switches ist ordnungsgemäß eingerichtet und funktionsfähig.
* Auf den Knoten wird ONTAP 8.2 oder höher ausgeführt.
* Alle Cluster-Ports befinden sich im `up` Bundesland.
* Alle logischen Cluster-Schnittstellen (LIFs) befinden sich im `up` Geben Sie den Staat und die Anschlüsse zu Hause an.


Bei der Switch-Konfiguration des CN1610-Cluster:

* Die CN1610 Cluster-Switch-Infrastruktur funktioniert bei beiden Switches voll und ganz.
* Beide Switches verfügen über Management-Netzwerk-Konnektivität.
* Auf die Cluster-Switches kann über eine Konsole zugegriffen werden.
* Bei Node-to-Node-Switch und Switch-to-Switch-Verbindungen bei CN1610 werden Twinax- oder Glasfaserkabel verwendet.
+
Derlink:https://hwu.netapp.com/["Hardware Universe"^] enthält weitere Informationen zur Verkabelung.

* Inter-Switch Link (ISL)-Kabel sind an beiden CN1610 Switches mit den Ports 13 bis 16 verbunden.
* Die Erstanpassung der beiden CN1610 Switches ist abgeschlossen.
+
Alle Anpassungen der vorherigen Site, wie SMTP, SNMP und SSH, sollten auf die neuen Switches kopiert werden.



.Verwandte Informationen
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 und CN1610"]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Einrichtung und Konfiguration der Switches CN1601 und CN1610"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB Artikel 1010449: Wie kann die automatische Case-Erstellung während geplanter Wartungszeiten unterdrückt werden"^]




== Migrieren Sie die Switches

.Zu den Beispielen
In den Beispielen dieses Verfahrens wird die folgende Terminologie für Cluster-Switch und Node verwendet:

* Die Namen der CN1610-Switches lauten cs1 und cs2.
* Die Namen der LIFs sind Faclu1 und clut2.
* Die Namen der Nodes sind node1 und node2.
* Der `cluster::*>` Eine Eingabeaufforderung gibt den Namen des Clusters an.
* Die in diesem Verfahren verwendeten Cluster-Ports sind e1a und e2a.
+
Derlink:https://hwu.netapp.com/["Hardware Universe"^] enthält die neuesten Informationen zu den tatsächlichen Cluster-Ports für Ihre Plattformen.





=== Schritt: Bereiten Sie sich auf die Migration vor

. Ändern Sie die Berechtigungsebene in erweitert, indem Sie eingeben `y` Wenn Sie dazu aufgefordert werden, fortzufahren:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_X_ ist die Dauer des Wartungsfensters in Stunden.

+

NOTE: Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

+
.Beispiel anzeigen
[%collapsible]
====
Mit dem folgenden Befehl wird die automatische Case-Erstellung für zwei Stunden unterdrückt:

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====




=== Schritt 2: Ports konfigurieren

. Deaktivieren Sie alle Node-Ports (keine ISL-Ports) auf den neuen Cluster-Switches cs1 und cs2.
+
Sie dürfen die ISL-Ports nicht deaktivieren.

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die Node-Ports 1 bis 12 auf Switch cs1 deaktiviert sind:

[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
Das folgende Beispiel zeigt, dass die Node-Ports 1 bis 12 auf Switch cs2 deaktiviert sind:

[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. Stellen Sie sicher, dass ISL und die physischen Ports auf der ISL zwischen den beiden CN1610 Cluster-Switches cs1 und cs2 liegen `up`:
+
`show port-channel`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass es sich um die ISL-Ports handelt `up` Schalter cs1 ein:

[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
Das folgende Beispiel zeigt, dass es sich um die ISL-Ports handelt `up` Schalter cs2 ein:

[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Liste der benachbarten Geräte anzeigen:
+
`show isdp neighbors`

+
Dieser Befehl enthält Informationen zu den Geräten, die mit dem System verbunden sind.

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel sind die benachbarten Geräte auf Switch cs1 aufgeführt:

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
Im folgenden Beispiel sind die benachbarten Geräte auf Switch cs2 aufgeführt:

[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. Zeigt die Liste der Cluster-Ports an:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden die verfügbaren Cluster-Ports angezeigt:

[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
====
. Vergewissern Sie sich, dass jeder Cluster-Port mit dem entsprechenden Port auf seinem Partner-Cluster-Node verbunden ist:
+
`run * cdpd show-neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass Cluster-Ports e1a und e2a mit demselben Port auf ihrem Cluster-Partner-Node verbunden sind:

[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
====
. Vergewissern Sie sich, dass alle Cluster-LIFs sind `up` Und in Betrieb:
+
`network interface show -vserver Cluster`

+
Jede Cluster-LIF sollte angezeigt werden `true` In der Spalte „`is Home`“.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
====
+

NOTE: Die folgenden Änderungs- und Migrationsbefehle in den Schritten 10 bis 13 müssen vom lokalen Node aus ausgeführt werden.

. Vergewissern Sie sich, dass alle Cluster-Ports vorhanden sind `up`:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Stellen Sie die ein `-auto-revert` Parameter an `false` Auf Cluster LIFs clue1 und clu2 zu beiden Knoten:
+
`network interface modify`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
+

NOTE: Verwenden Sie für Version 8.3 und höher den folgenden Befehl: `network interface modify -vserver Cluster -lif * -auto-revert false`

. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können das verwenden `network interface check cluster-connectivity` Befehl, um eine Zugriffsprüfung für die Cluster-Konnektivität zu starten und dann Details anzuzeigen:

`network interface check cluster-connectivity start` Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Befehl ausführen `show`, um die Details anzuzeigen.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Alle ONTAP Versionen
--
Sie können für alle ONTAP Versionen auch den verwenden `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Konnektivität:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] Migration von clus1 zu Port e2a auf der Konsole jedes Knotens:
+
`network interface migrate`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt den Prozess der Migration von Faclu1 zu Anschluss e2a auf node1 und node2:

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
====
+

NOTE: Verwenden Sie für Version 8.3 und höher den folgenden Befehl: `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`

. Vergewissern Sie sich, dass die Migration stattgefunden hat:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird überprüft, ob Faclu1 zu Port e2a auf node1 und node2 migriert wird:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. Fahren Sie Cluster-Port e1a auf beiden Knoten herunter:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie der Port e1a auf node1 und node2 heruntergefahren wird:

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
====
. Überprüfen Sie den Portstatus:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass der Anschluss e1a lautet `down` Auf Knoten 1 und Knoten 2:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Trennen Sie das Kabel vom Cluster-Port e1a in Node1, und verbinden sie dann e1a mit Port 1 am Cluster-Switch cs1. Verwenden Sie dabei die geeignete Verkabelung, die von den CN1610-Switches unterstützt wird.
+
Der link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] Enthält weitere Informationen zur Verkabelung.

. Trennen Sie das Kabel vom Cluster-Port e1a auf node2, und verbinden sie dann e1a mit Port 2 am Cluster-Switch cs1. Verwenden Sie dabei die geeignete Verkabelung, die von den CN1610-Switches unterstützt wird.
. Aktivieren Sie alle Node-Ports auf Cluster-Switch cs1.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die Ports 1 bis 12 auf Switch cs1 aktiviert sind:

[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
====
. Aktivieren Sie den ersten Cluster-Port e1a auf jedem Knoten:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie der Port e1a auf node1 und node2 aktiviert wird:

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
====
. Vergewissern Sie sich, dass alle Cluster-Ports vorhanden sind `up`:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden alle Cluster-Ports angezeigt `up` Auf Knoten 1 und Knoten 2:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Fazit 1 (der zuvor migriert wurde) auf beiden Knoten zu e1a zurücksetzen:
+
`network interface revert`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie der Anschluss Nr. 1 und Nr. 2 auf den Port e1a zurückgesetzt wird:

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
====
+

NOTE: Verwenden Sie für Version 8.3 und höher den folgenden Befehl: `network interface revert -vserver Cluster -lif <nodename_clus<N>>`

. Vergewissern Sie sich, dass alle Cluster-LIFs sind `up`, Betrieb, und Anzeige als `true` In der Spalte „is Home“:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass alle LIFs sind `up` Auf node1 und node2 und dass die "is Home" Spalte Ergebnisse sind `true`:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. Informationen zum Status der Nodes im Cluster anzeigen:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden Informationen über den Systemzustand und die Berechtigung der Nodes im Cluster angezeigt:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Fazit 2 auf Port e1a auf der Konsole jedes Knotens migrieren:
+
`network interface migrate`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt den Prozess für die Migration von Fak2 auf Port e1a in Node1 und node2:

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
====
+

NOTE: Verwenden Sie für Version 8.3 und höher den folgenden Befehl: `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`

. Vergewissern Sie sich, dass die Migration stattgefunden hat:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel wird überprüft, ob Faclu2 in den Anschluss e1a in den Knoten 1 und node2 migriert wird:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
====
. Fahren Sie Cluster-Port e2a auf beiden Nodes herunter:
+
`network port modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie der Port e2a auf node1 und node2 heruntergefahren wird:

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Überprüfen Sie den Portstatus:
+
`network port show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass Port e2a ist `down` Auf Knoten 1 und Knoten 2:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Trennen Sie das Kabel vom Cluster-Port e2a auf node1, und verbinden sie dann e2a mit Port 1 am Cluster-Switch cs2. Verwenden Sie dabei die geeignete Verkabelung, die von den CN1610-Switches unterstützt wird.
. Trennen Sie das Kabel vom Cluster-Port e2a auf node2, und verbinden sie dann e2a mit Port 2 am Cluster-Switch cs2. Verwenden Sie dabei die geeignete Verkabelung, die von den CN1610-Switches unterstützt wird.
. Aktivieren Sie alle Node-Ports auf Cluster-Switch cs2.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die Ports 1 bis 12 auf Switch cs2 aktiviert sind:

[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. Aktivieren Sie den zweiten Cluster-Port e2a auf jedem Knoten.
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie der Port e2a auf node1 und node2 aktiviert wird:

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====
. Vergewissern Sie sich, dass alle Cluster-Ports vorhanden sind `up`:
+
`network port show -ipspace Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Im folgenden Beispiel werden alle Cluster-Ports angezeigt `up` Auf Knoten 1 und Knoten 2:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Schluss2 (der zuvor migriert wurde) auf beiden Knoten zu e2a zurücksetzen:
+
`network interface revert`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie man clu2 auf den Port e2a auf node1 und node2 zurücksetzt:

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
+

NOTE: Für Release 8.3 und höher lauten die Befehle:
`cluster::*> network interface revert -vserver Cluster -lif node1_clus2` Und
`cluster::*> network interface revert -vserver Cluster -lif node2_clus2`





=== Schritt 3: Schließen Sie die Konfiguration ab

. Vergewissern Sie sich, dass alle Schnittstellen angezeigt werden `true` In der Spalte „is Home“:
+
`network interface show -vserver Cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass alle LIFs sind `up` Auf node1 und node2 und dass die "is Home" Spalte Ergebnisse sind `true`:

[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können das verwenden `network interface check cluster-connectivity` Befehl, um eine Zugriffsprüfung für die Cluster-Konnektivität zu starten und dann Details anzuzeigen:

`network interface check cluster-connectivity start` Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Befehl ausführen `show`, um die Details anzuzeigen.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Alle ONTAP Versionen
--
Sie können für alle ONTAP Versionen auch den verwenden `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Konnektivität:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] Stellen Sie sicher, dass beide Knoten zwei Verbindungen zu jedem Switch haben:
+
`show isdp neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die entsprechenden Ergebnisse für beide Switches:

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. Informationen zu den Geräten in Ihrer Konfiguration anzeigen:
+
`network device discovery show`

. Deaktivieren Sie die Konfigurationseinstellungen mit zwei Nodes ohne Switches auf beiden Nodes mithilfe des erweiterten Befehls „Privilege“:
+
`network options detect-switchless modify`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, wie die Konfigurationseinstellungen ohne Switches deaktiviert werden:

[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
====
+

NOTE: überspringen Sie diesen Schritt für Version 9.2 und höher, da die Konfiguration automatisch konvertiert wird.

. Vergewissern Sie sich, dass die Einstellungen deaktiviert sind:
+
`network options detect-switchless-cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Der `false` Die Ausgabe im folgenden Beispiel zeigt, dass die Konfigurationseinstellungen deaktiviert sind:

[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
====
+

NOTE: Für Version 9.2 und höher, warten Sie bis `Enable Switchless Cluster` Ist auf FALSE gesetzt. Dies kann bis zu drei Minuten dauern.

. Konfigurieren Sie Cluster clue1 und clu2, um jeden Knoten automatisch zurückzusetzen und zu bestätigen.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
+

NOTE: Verwenden Sie für Version 8.3 und höher den folgenden Befehl: `network interface modify -vserver Cluster -lif * -auto-revert true` Um die automatische Umrüstung auf allen Nodes im Cluster zu aktivieren.

. Überprüfen Sie den Status der Node-Mitglieder im Cluster:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt Informationen über den Systemzustand und die Berechtigung der Nodes im Cluster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Wenn Sie die automatische Erstellung eines Cases unterdrückten, können Sie sie erneut aktivieren, indem Sie eine AutoSupport Meldung aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. Ändern Sie die Berechtigungsebene zurück in den Administrator:
+
`set -privilege admin`


