---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: Wenn Sie FAS22xx-Systeme in einem bestehenden Zwei-Knoten-Switchless-Cluster haben, in dem jedes Controller-Modul über eine einzelne, Back-to-Back-10-GbE-Verbindung für die Cluster-Konnektivität verfügt, können Sie die Switchless-Cluster-Netzwerkoption nutzen und die direkte Back-to-Back-Konnektivität durch Switch-Verbindungen ersetzen. 
---
= Migration zu einem Zwei-Knoten-Switched-Cluster in FAS22xx-Systemen mit einer einzigen Cluster-Netzwerkverbindung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie FAS22xx-Systeme in einem bestehenden Zwei-Knoten-Switchless-Cluster haben, in dem jedes Controller-Modul über eine einzelne, Back-to-Back-10-GbE-Verbindung für die Cluster-Konnektivität verfügt, können Sie die Switchless-Cluster-Netzwerkoption nutzen und die direkte Back-to-Back-Konnektivität durch Switch-Verbindungen ersetzen.



== Überprüfungsanforderungen

.Bevor Sie beginnen
Bitte stellen Sie sicher, dass Sie Folgendes haben:

* Zwei Clusterverbindungen für die Migration von einer schalterlosen Konfiguration zu einer geschalteten Konfiguration.
* Der Cluster ist intakt und besteht aus zwei Knoten, die direkt miteinander verbunden sind.
* Auf den Knoten läuft ONTAP 8.2 oder höher.
* Die Funktion „Switchless Cluster“ kann nicht mit mehr als zwei Knoten verwendet werden.
* Alle Cluster-Ports befinden sich im `up` Zustand.


.Ähnliche Informationen
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB-Artikel 1010449: So unterdrücken Sie die automatische Fallerstellung während geplanter Wartungsfenster"^]



== Migrieren Sie die Schalter

Dieses Verfahren ist ein nicht-disruptives Verfahren, das die direkte Cluster-Konnektivität in einer switchlosen Umgebung aufhebt und jede Verbindung zum Switch durch eine Verbindung zum Partnerknoten ersetzt.



=== Schritt 1: Vorbereitung auf die Migration

. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie Folgendes eingeben `y` wenn Sie aufgefordert werden, fortzufahren:
+
`set -privilege advanced`

+
Die erweiterte Aufforderung(`*>` ) erscheint.

. Überprüfen Sie den Clusterstatus der Knoten an der Systemkonsole eines der beiden Knoten:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt Informationen über den Zustand und die Eignung der Knoten im Cluster an:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Überprüfen Sie den Status des HA-Paares an der Systemkonsole eines der beiden Knoten: `storage failover show`
+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt den Status von Knoten 1 und Knoten 2:

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`ist die Dauer des Wartungsfensters in Stunden.

+

NOTE: Die Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, damit die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

+
.Beispiel anzeigen
[%collapsible]
====
Der folgende Befehl unterdrückt die automatische Fallerstellung für zwei Stunden:

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. Überprüfen Sie, ob der aktuelle Status des schalterlosen Clusters `true` und deaktivieren Sie anschließend den schalterlosen Clustermodus:
+
`network options switchless-cluster modify -enabled false`

. Übernehmen Sie den Zielknoten:
+
`storage failover takeover -ofnode _target_node_name_`

+
Es spielt keine Rolle, welcher Knoten der Zielknoten ist.  Nach der Übernahme startet der Zielknoten automatisch neu und zeigt das `Waiting for giveback...` Nachricht.

+
Der aktive Knoten dient nun der Datenbereitstellung für den übernommenen Partnerknoten (Zielknoten).

. Warten Sie nach der Übernahme des betroffenen Knotens zwei Minuten, um zu bestätigen, dass die Übernahme erfolgreich abgeschlossen wurde.
. Der Zielknoten zeigt Folgendes an: `Waiting for giveback...` Nachricht, schalte es ab.
+
Die Methode, mit der Sie den Knoten herunterfahren, hängt davon ab, ob Sie die Fernverwaltung über den Knoten-Serviceprozessor (SP) verwenden.

+
|===
| Wenn SP | Dann... 


 a| 
Ist konfiguriert
 a| 
Melden Sie sich am beeinträchtigten Knoten SP an und schalten Sie dann das System aus: `system power off`



 a| 
Ist nicht konfiguriert
 a| 
Drücken Sie bei der Aufforderung zum Beeinträchtigen des Knotens `Ctrl-C` und dann antworten `y` den Knoten anhalten.

|===




=== Schritt 2: Kabel und Anschlüsse konfigurieren

. Trennen Sie an jedem Controllermodul das Kabel, das den 10-GbE-Clusterport mit dem switchlosen Cluster verbindet.
. Verbinden Sie den 10-GbE-Cluster-Port mit dem Switch auf beiden Controller-Modulen.
. Überprüfen Sie, ob die am Switch angeschlossenen 10-GbE-Cluster-Ports so konfiguriert sind, dass sie Teil desselben VLANs sind.
+
Wenn Sie die Cluster-Ports jedes Controller-Moduls mit verschiedenen Switches verbinden möchten, müssen Sie sicherstellen, dass die Ports, an denen die Cluster-Ports auf den jeweiligen Switches angeschlossen sind, für dasselbe VLAN konfiguriert sind und dass Trunking auf beiden Switches ordnungsgemäß konfiguriert ist.

. Speicher dem Zielknoten zurückgeben:
+
`storage failover giveback -ofnode node2`

. Überwachen Sie den Fortschritt der Rückgabeaktion:
+
`storage failover show-giveback`

. Nach Abschluss der Rückgabeoperation ist zu bestätigen, dass das HA-Paar fehlerfrei funktioniert und eine Übernahme möglich ist:
+
`storage failover show`

+
.Beispiel anzeigen
[%collapsible]
====
Die Ausgabe sollte in etwa wie folgt aussehen:

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. Überprüfen Sie, ob die Cluster-Port-LIFs ordnungsgemäß funktionieren:
+
`network interface show -role cluster`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt, dass die LIFs `up` auf Knoten 1 und Knoten 2 und dass die Ergebnisse der Spalte "Ist zu Hause" `true` :

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. Überprüfen Sie den Clusterstatus der Knoten an der Systemkonsole eines der beiden Knoten:
+
`cluster show`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt Informationen über den Zustand und die Eignung der Knoten im Cluster an:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Überprüfen Sie die Konnektivität der Remote-Cluster-Schnittstellen:


[role="tabbed-block"]
====
.ONTAP 9.9.1 und höher
--
Sie können die `network interface check cluster-connectivity` Befehl zum Starten einer Zugriffsprüfung für die Clusterkonnektivität und anschließenden Anzeigen der Details:

`network interface check cluster-connectivity start`Und `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*HINWEIS:* Warten Sie einige Sekunden, bevor Sie den Vorgang ausführen. `show` Befehl zum Anzeigen der Details.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Alle ONTAP Versionen
--
Für alle ONTAP Versionen können Sie auch die `cluster ping-cluster -node <name>` Befehl zum Überprüfen der Verbindung:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== Schritt 3: Schließen Sie den Vorgang ab.

. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. Ändern Sie die Berechtigungsstufe wieder auf Administrator:
+
`set -privilege admin`


