---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: Sie können einen defekten NetApp CN1610 Cluster Switch unterbrechungsfrei ersetzen, indem Sie eine bestimmte Abfolge von Aufgaben durchführen. 
---
= Ersetzen Sie einen NetApp CN1610 Cluster Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie diese Schritte aus, um einen defekten NetApp CN1610-Switch in einem Cluster-Netzwerk auszutauschen. Dies ist ein unterbrechungsfreies Verfahren (Nondisruptive Procedure, NDU).



== Prüfen Sie die Anforderungen

.Was Sie benötigen
Bevor Sie den Switch austauschen, müssen die folgenden Bedingungen erfüllt sein, bevor Sie den Switch in der aktuellen Umgebung und am Ersatz-Switch für das vorhandene Cluster und die Netzwerkinfrastruktur austauschen:

* Das vorhandene Cluster muss mit mindestens einem vollständig verbundenen Cluster-Switch als voll funktionsfähig verifiziert werden.
* Alle Cluster-Ports müssen *up* sein.
* Alle logischen Cluster-Schnittstellen (LIFs) müssen aktiviert sein und dürfen nicht migriert worden sein.
* Dem ONTAP Cluster `ping-cluster -node node1` Befehl muss angeben, dass die grundlegende Konnektivität und die Kommunikation größer als PMTU auf allen Pfaden erfolgreich ist.




== Aktivieren Sie die Konsolenprotokollierung

NetApp empfiehlt dringend, die Konsolenprotokollierung auf den verwendeten Geräten zu aktivieren und beim Austausch des Switches die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während der Wartung aktiviert.
* Lösen Sie vor und nach der Wartung einen Wartungs-AutoSupport aus, um die Case-Erstellung für die Dauer der Wartung zu deaktivieren. Lesen Sie diesen Knowledge Base-Artikel https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Unterdrücken der automatischen Case-Erstellung während geplanter Wartungsfenster"^] Entnehmen.
* Aktivieren Sie die Sitzungsprotokollierung für beliebige CLI-Sitzungen. Anweisungen zum Aktivieren der Sitzungsprotokollierung finden Sie im Abschnitt „Protokollierung der Sitzungsausgabe“ in diesem Knowledge Base Artikel https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["So konfigurieren Sie PuTTY für optimale Konnektivität zu ONTAP-Systemen"^].




== Tauschen Sie den Schalter aus

.Über diese Aufgabe
Sie müssen den Befehl zum Migrieren einer Cluster-LIF von dem Node ausführen, auf dem die Cluster-LIF gehostet wird.

In den Beispielen dieses Verfahrens wird die folgende Terminologie für Cluster-Switch und Node verwendet:

* Die Namen der beiden CN1610 Cluster-Switches lauten `cs1` Und `cs2`.
* Der Name des zu ersetzenden CN1610-Schalters (der defekte Schalter) lautet `old_cs1`.
* Der Name des neuen CN1610-Schalters (der Ersatzschalter) lautet `new_cs1`.
* Der Name des Partner-Switches, der nicht ersetzt wird, lautet `cs2`.


.Schritte
. Vergewissern Sie sich, dass die Startkonfigurationsdatei mit der ausgeführten Konfigurationsdatei übereinstimmt. Sie müssen diese Dateien lokal speichern, um sie während des Austauschs verwenden zu können.
+
Die Konfigurationsbefehle im folgenden Beispiel gelten für FASTPATH 1.2.0.7:

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. Erstellen Sie eine Kopie der ausgeführten Konfigurationsdatei.
+
Der Befehl im folgenden Beispiel ist für FASTPATH 1.2.0.7:

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: Sie können jeden Dateinamen außer verwenden `CN1610_CS_RCF_v1.2.scr`. Der Dateiname muss die Erweiterung *.SCR* haben.

. [[step3]]Speichern Sie die laufende Konfigurationsdatei des Switches auf einem externen Host, um den Austausch vorzubereiten.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. Überprüfen Sie, ob die Switch- und ONTAP-Versionen in der Kompatibilitätsmatrix übereinstimmen. Siehe https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601 und CN1610 Switches"^] Für Details.
. Von https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["Seite „Software-Downloads“"^] Wählen Sie auf der NetApp Support Website NetApp Cluster Switches aus, um die entsprechenden RCF- und FASTPATH-Versionen herunterzuladen.
. Richten Sie einen TFTP-Server (Trivial File Transfer Protocol) mit DER FASTPATH-, RCF- und gespeicherten Konfiguration ein `.scr` Datei zur Verwendung mit dem neuen Switch.
. Verbinden Sie den seriellen Port (der RJ-45-Anschluss mit der Bezeichnung „IOIOIOI“ auf der rechten Seite des Switches) mit einem verfügbaren Host mit Terminalemulation.
. Stellen Sie auf dem Host die Einstellungen für die serielle Terminalverbindung ein:
+
.. 9600 Baud
.. 8 Datenbits
.. 1 Stoppbit
.. Parität: Keine
.. Flusskontrolle: Keine


. Verbinden Sie den Verwaltungsport (den RJ-45-Schraubenschlüssel-Port auf der linken Seite des Switches) mit dem gleichen Netzwerk, in dem sich Ihr TFTP-Server befindet.
. Bereiten Sie sich auf die Netzwerkverbindung mit dem TFTP-Server vor.
+
Wenn Sie DHCP (Dynamic Host Configuration Protocol) verwenden, müssen Sie derzeit keine IP-Adresse für den Switch konfigurieren. Der Service-Port ist standardmäßig auf DHCP eingestellt. Der Netzwerkverwaltungsport ist für die IPv4- und IPv6-Protokolleinstellungen auf none festgelegt. Wenn der Schlüsselport mit einem Netzwerk verbunden ist, das über einen DHCP-Server verfügt, werden die Servereinstellungen automatisch konfiguriert.

+
Um eine statische IP-Adresse festzulegen, sollten Sie die befehle serviceport-Protokoll, Netzwerkprotokoll und serviceport ip verwenden.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. Wenn sich der TFTP-Server auf einem Laptop befindet, schließen Sie den CN1610-Switch optional über ein Standard-Ethernet-Kabel an den Laptop an, und konfigurieren Sie dann den Netzwerkanschluss im gleichen Netzwerk mit einer alternativen IP-Adresse.
+
Sie können das verwenden `ping` Befehl zum Verifizieren der Adresse. Wenn Sie die Verbindung nicht herstellen können, sollten Sie ein nicht geroutetes Netzwerk verwenden und den Service-Port mit IP 192.168.x oder 172.16.x konfigurieren Sie können den Service-Port zu einem späteren Zeitpunkt auf die Produktions-Management-IP-Adresse neu konfigurieren.

. Überprüfen und installieren Sie optional die entsprechenden Versionen der RCF- und FASTPATH-Software für den neuen Switch. Wenn Sie überprüft haben, ob der neue Switch korrekt eingerichtet ist und keine Updates für die RCF- und FASTPATH-Software erforderlich sind, fahren Sie mit Schritt 13 fort.
+
.. Überprüfen Sie die neuen Schaltereinstellungen.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. Laden Sie den RCF auf den neuen Switch herunter.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. Stellen Sie sicher, dass der RCF auf den Switch heruntergeladen wurde.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. Den RCF auf den CN1610-Schalter auftragen.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. Speichern Sie die laufende Konfigurationsdatei, damit sie beim Neustart des Switches zur Startkonfigurationsdatei wird.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Laden Sie das Bild auf den Switch CN1610 herunter.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. Führen Sie das neue aktive Startabbild durch, indem Sie den Switch neu starten.
+
Der Switch muss neu gestartet werden, damit der Befehl in Schritt 6 das neue Image widerspiegelt. Es gibt zwei mögliche Ansichten für eine Antwort, die Sie nach Eingabe des Befehls reload möglicherweise sehen werden.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. Kopieren Sie die gespeicherte Konfigurationsdatei vom alten Switch auf den neuen Switch.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. Wenden Sie die zuvor gespeicherte Konfiguration auf den neuen Switch an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Speichern Sie die laufende Konfigurationsdatei in der Startkonfigurationsdatei.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_X_ ist die Dauer des Wartungsfensters in Stunden.

+
[NOTE]
====
Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

====
. Melden Sie sich beim neuen Switch New_cs1 als Admin-Benutzer an, und fahren Sie alle Ports herunter, die mit den Node-Cluster-Schnittstellen (Ports 1 bis 12) verbunden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. Migrieren Sie die Cluster-LIFs von den Ports, die mit dem Switch old_cs1 verbunden sind.
+
Sie müssen jede LIF des Clusters von der Managementoberfläche des aktuellen Node migrieren.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. Vergewissern Sie sich, dass alle Cluster-LIFs auf den entsprechenden Cluster-Port auf jedem Node verschoben wurden.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. Fahren Sie die Cluster-Ports herunter, die an den Switch angeschlossen sind, den Sie ausgetauscht haben.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. Überprüfen Sie den Systemzustand des Clusters.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Vergewissern Sie sich, dass die Ports ausgefallen sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. Fahren Sie auf dem Switch cs2 die ISL-Ports 13 bis 16 herunter.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. Überprüfen Sie, ob der Speicheradministrator für den Austausch des Switches bereit ist.
. Entfernen Sie alle Kabel vom Switch old_cs1, und schließen Sie dann die Kabel an dieselben Ports am Switch New_cs1 an.
. Aktivieren Sie auf dem cs2-Switch die ISL-Ports 13 bis 16.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. Aktivieren Sie die Ports auf dem neuen Switch, der den Clusterknoten zugeordnet ist.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. Rufen Sie auf einem einzelnen Node den Clusterknoten-Port auf, der mit dem ausgetauschten Switch verbunden ist, und bestätigen Sie anschließend, dass die Verbindung hergestellt ist.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. Setzen Sie die Cluster-LIFs zurück, die dem Port in Schritt 25 auf demselben Node zugeordnet sind.
+
In diesem Beispiel werden die LIFs auf node1 erfolgreich zurückgesetzt, wenn die Spalte „is Home“ den Wert „true“ lautet.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. Wenn die Cluster-LIF des ersten Node hochgefahren ist und auf den Home Port zurückgesetzt wird, wiederholen Sie die Schritte 25 und 26, um die Cluster-Ports hochzuschalten und die Cluster-LIFs auf den anderen Nodes im Cluster zurückzusetzen.
. Zeigt Informationen zu den Nodes im Cluster an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Vergewissern Sie sich, dass die Startkonfigurationsdatei und die laufende Konfigurationsdatei auf dem ersetzten Switch korrekt sind. Diese Konfigurationsdatei sollte mit der Ausgabe in Schritt 1 übereinstimmen.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie es erneut, indem Sie eine AutoSupport Meldung aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


