---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: Ein defekter NetApp CN1610 Cluster-Switch kann unterbrechungsfrei durch Ausführen einer bestimmten Abfolge von Aufgaben ausgetauscht werden. 
---
= Ersetzen Sie einen NetApp CN1610 Cluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Schritte, um einen defekten NetApp CN1610 Switch in einem Clusternetzwerk auszutauschen.  Dies ist ein nicht-unterbrechendes Verfahren (NDU).



== Überprüfungsanforderungen

.Bevor Sie beginnen
Bevor Sie den Switch austauschen, müssen die folgenden Bedingungen in der aktuellen Umgebung und am Ersatz-Switch für die bestehende Cluster- und Netzwerkinfrastruktur erfüllt sein:

* Der bestehende Cluster muss auf seine volle Funktionsfähigkeit überprüft werden, wobei mindestens ein Cluster-Switch vollständig angeschlossen sein muss.
* Alle Cluster-Ports müssen *aktiv* sein.
* Alle logischen Schnittstellen (LIFs) des Clusters müssen aktiv sein und dürfen nicht migriert worden sein.
* Der ONTAP Cluster `ping-cluster -node node1` Der Befehl muss anzeigen, dass die grundlegende Konnektivität und die Kommunikation über PMTU hinaus auf allen Pfaden erfolgreich sind.




== Konsolenprotokollierung aktivieren

NetApp empfiehlt dringend, die Konsolenprotokollierung auf den verwendeten Geräten zu aktivieren und beim Austausch Ihres Switches die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während der Wartungsarbeiten aktiviert.
* Lösen Sie vor und nach der Wartung einen Wartungs AutoSupport aus, um die Fallerstellung für die Dauer der Wartung zu deaktivieren.  Siehe diesen Wissensdatenbankartikel https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Wie man die automatische Fallerstellung während geplanter Wartungsfenster unterdrückt"^] für weitere Einzelheiten.
* Aktivieren Sie die Sitzungsprotokollierung für alle CLI-Sitzungen.  Anweisungen zum Aktivieren der Sitzungsprotokollierung finden Sie im Abschnitt „Protokollierung der Sitzungsausgabe“ in diesem Wissensdatenbankartikel. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP -Systemen?"^] Die




== Tauschen Sie den Schalter aus.

.Informationen zu diesem Vorgang
Sie müssen den Befehl zur Migration eines Cluster-LIF von dem Knoten ausführen, auf dem der Cluster-LIF gehostet wird.

Die Beispiele in diesem Verfahren verwenden die folgende Cluster-Switch- und Knotennomenklatur:

* Die Namen der beiden CN1610 Cluster-Switches lauten: `cs1` Und `cs2` Die
* Die Bezeichnung des zu ersetzenden CN1610-Schalters (des defekten Schalters) lautet: `old_cs1` Die
* Die Bezeichnung des neuen CN1610-Schalters (des Ersatzschalters) lautet: `new_cs1` Die
* Der Name des Partnerschalters, der nicht ausgetauscht wird, lautet: `cs2` Die


.Schritte
. Vergewissern Sie sich, dass die Startkonfigurationsdatei mit der laufenden Konfigurationsdatei übereinstimmt.  Sie müssen diese Dateien lokal speichern, um sie während des Austauschs verwenden zu können.
+
Die Konfigurationsbefehle im folgenden Beispiel gelten für FASTPATH 1.2.0.7:

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. Erstellen Sie eine Kopie der laufenden Konfigurationsdatei.
+
Der Befehl im folgenden Beispiel gilt für FASTPATH 1.2.0.7:

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: Sie können jeden beliebigen Dateinamen verwenden, außer `CN1610_CS_RCF_v1.2.scr` Die  Der Dateiname muss die Dateiendung *.scr* haben.

. [[step3]]Speichern Sie die laufende Konfigurationsdatei des Switches auf einem externen Host, um den Austausch vorzubereiten.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. Prüfen Sie, ob die Versionen von Switch und ONTAP in der Kompatibilitätsmatrix übereinstimmen.  Siehe die https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601 und CN1610 Switches"^] Weitere Details finden Sie auf der entsprechenden Seite.
. vom https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["Seite für Software-Downloads"^] Auf der NetApp Support-Website können Sie unter „NetApp Cluster Switches“ die entsprechenden RCF- und FASTPATH-Versionen herunterladen.
. Richten Sie einen Trivial File Transfer Protocol (TFTP)-Server mit FASTPATH, RCF und gespeicherter Konfiguration ein. `.scr` Datei zur Verwendung mit dem neuen Schalter.
. Verbinden Sie den seriellen Port (den RJ-45-Anschluss mit der Bezeichnung „IOIOI“ auf der rechten Seite des Switches) mit einem verfügbaren Host mit Terminalemulation.
. Auf dem Host die Einstellungen für die serielle Terminalverbindung vornehmen:
+
.. 9600 Baud
.. 8 Datenbits
.. 1 Stoppbit
.. Parität: keine
.. Flusssteuerung: keine


. Verbinden Sie den Management-Port (den RJ-45-Schraubenschlüssel-Anschluss auf der linken Seite des Switches) mit demselben Netzwerk, in dem sich Ihr TFTP-Server befindet.
. Bereiten Sie die Verbindung zum Netzwerk mit dem TFTP-Server vor.
+
Wenn Sie das Dynamic Host Configuration Protocol (DHCP) verwenden, müssen Sie dem Switch zu diesem Zeitpunkt keine IP-Adresse konfigurieren.  Der Service-Port ist standardmäßig auf DHCP eingestellt.  Der Netzwerkmanagement-Port ist für die IPv4- und IPv6-Protokolleinstellungen auf „Keine“ gesetzt.  Wenn Ihr Schraubenschlüsselanschluss mit einem Netzwerk verbunden ist, das über einen DHCP-Server verfügt, werden die Servereinstellungen automatisch konfiguriert.

+
Um eine statische IP-Adresse festzulegen, sollten Sie die Befehle serviceport protocol, network protocol und serviceport ip verwenden.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. Optionalerweise kann, falls sich der TFTP-Server auf einem Laptop befindet, der CN1610-Switch mit einem Standard-Ethernet-Kabel an den Laptop angeschlossen und anschließend sein Netzwerkport im selben Netzwerk mit einer alternativen IP-Adresse konfiguriert werden.
+
Sie können die `ping` Befehl zur Überprüfung der Adresse.  Falls Sie keine Verbindung herstellen können, sollten Sie ein nicht geroutetes Netzwerk verwenden und den Service-Port mit der IP-Adresse 192.168.x oder 172.16.x konfigurieren.  Sie können den Service-Port zu einem späteren Zeitpunkt auf die Produktionsmanagement-IP-Adresse umkonfigurieren.

. Optional können Sie die entsprechenden Versionen der RCF- und FASTPATH-Software für den neuen Switch überprüfen und installieren.  Wenn Sie überprüft haben, dass der neue Switch korrekt eingerichtet ist und keine Aktualisierungen der RCF- und FASTPATH-Software erforderlich sind, sollten Sie mit Schritt 13 fortfahren.
+
.. Überprüfen Sie die neuen Schaltereinstellungen.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. Laden Sie die RCF-Datei auf den neuen Switch herunter.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. Überprüfen Sie, ob die RCF-Datei auf den Switch heruntergeladen wurde.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. Bringen Sie den RCF am Schalter CN1610 an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. Speichern Sie die laufende Konfigurationsdatei, damit sie beim Neustart des Switches zur Startkonfigurationsdatei wird.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Laden Sie das Image auf den CN1610-Switch herunter.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. Starten Sie den Switch neu, um das neue aktive Boot-Image zu laden.
+
Der Switch muss neu gestartet werden, damit der Befehl in Schritt 6 das neue Image widerspiegelt.  Es gibt zwei mögliche Ansichten für eine Antwort, die Ihnen nach Eingabe des Befehls „reload“ angezeigt werden könnte.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. Kopieren Sie die gespeicherte Konfigurationsdatei vom alten Switch auf den neuen Switch.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. Wenden Sie die zuvor gespeicherte Konfiguration auf den neuen Switch an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Speichern Sie die laufende Konfigurationsdatei in der Startkonfigurationsdatei.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ ist die Dauer des Wartungsfensters in Stunden.

+
[NOTE]
====
Die AutoSupport Meldung benachrichtigt den technischen Support über diese Wartungsaufgabe, sodass die automatische Fallerstellung während des Wartungsfensters unterdrückt wird.

====
. Melden Sie sich auf dem neuen Switch new_cs1 als Administrator an und schalten Sie alle Ports ab, die mit den Schnittstellen des Knotenclusters verbunden sind (Ports 1 bis 12).
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. Migrieren Sie die Cluster-LIFs von den Ports, die mit dem Switch old_cs1 verbunden sind.
+
Sie müssen jeden Cluster-LIF von der Verwaltungsschnittstelle seines aktuellen Knotens migrieren.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. Überprüfen Sie, ob alle Cluster-LIFs auf den entsprechenden Cluster-Port auf jedem Knoten verschoben wurden.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. Schalten Sie die Cluster-Ports ab, die an den ausgetauschten Switch angeschlossen sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. Überprüfen Sie den Zustand des Clusters.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Überprüfen Sie, ob die Ports deaktiviert sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. Schalten Sie am Switch cs2 die ISL-Ports 13 bis 16 ab.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. Prüfen Sie, ob der Speicheradministrator für den Austausch des Switches bereit ist.
. Entfernen Sie alle Kabel vom alten Switch cs1 und schließen Sie die Kabel dann an die gleichen Ports am neuen Switch cs1 an.
. Aktivieren Sie am Switch cs2 die ISL-Ports 13 bis 16.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. Schalten Sie die Ports des neuen Switches ein, die mit den Clusterknoten verbunden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. Auf einem einzelnen Knoten wird der Clusterknotenport aktiviert, der mit dem ausgetauschten Switch verbunden ist. Anschließend wird überprüft, ob die Verbindung hergestellt wurde.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. Setzen Sie die Cluster-LIFs, die dem Port in Schritt 25 auf demselben Knoten zugeordnet sind, zurück.
+
In diesem Beispiel werden die LIFs auf Knoten 1 erfolgreich zurückgesetzt, wenn die Spalte „Is Home“ den Wert „true“ hat.

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. Wenn der Cluster-LIF des ersten Knotens aktiv ist und auf seinen Heimatport zurückgesetzt wird, wiederholen Sie die Schritte 25 und 26, um die Cluster-Ports zu aktivieren und die Cluster-LIFs auf den anderen Knoten im Cluster zurückzusetzen.
. Zeigt Informationen über die Knoten im Cluster an.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Prüfen Sie, ob die Startkonfigurationsdatei und die laufende Konfigurationsdatei auf dem ausgetauschten Switch korrekt sind.  Diese Konfigurationsdatei sollte mit der Ausgabe in Schritt 1 übereinstimmen.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


