---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Bevor Sie NetApp CN1610 Switches konfigurieren, lesen Sie bitte die Verfahrensübersicht. 
---
= Übersicht über Installation und Konfiguration von NetApp CN1610-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der CN1610 ist ein Managed Layer 2 Switch mit hoher Bandbreite, der 16 10-Gigabit Small Form-Factor Pluggable Plus (SFP+) Ports bietet.

Der Switch verfügt über redundante Netzteile und Lüftereinschübe, die Hot-Swapping für hohe Verfügbarkeit unterstützen.  Dieser 1U-Switch kann in einem Standard-19-Zoll NetApp 42U-Systemschrank oder in einem Schrank eines Drittanbieters installiert werden.

Der Switch unterstützt die lokale Verwaltung über den Konsolenanschluss oder die Fernverwaltung mittels Telnet oder SSH über eine Netzwerkverbindung.  Der CN1610 verfügt über einen dedizierten 1-Gigabit-Ethernet-RJ45-Management-Port für die Out-of-Band-Switch-Verwaltung.  Sie können den Switch verwalten, indem Sie Befehle in die Befehlszeilenschnittstelle (CLI) eingeben oder ein SNMP-basiertes Netzwerkmanagementsystem (NMS) verwenden.
