---
permalink: switch-netapp-cn1610/task-install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Wenn Sie die FASTPATH-Software auf Ihren NetApp Switches installieren, müssen Sie mit dem Upgrade mit dem zweiten Switch, cs2, beginnen. 
---
= INSTALLIEREN Sie DIE FASTPATH Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die FASTPATH Software auf Ihren NetApp Switches installieren, müssen Sie das Upgrade mit dem zweiten Switch _cs2_ beginnen.

.Schritte
. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_X_ ist die Dauer des Wartungsfensters in Stunden.

+

NOTE: Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

. Melden Sie sich als Administrator beim Switch an. Standardmäßig ist kein Passwort vorhanden. Am `(cs2) #` Geben Sie die ein `enable` Befehl. Auch hier gibt es standardmäßig kein Passwort. Dadurch haben Sie Zugriff auf den privilegierten EXEC-Modus, mit dem Sie die Netzwerkschnittstelle konfigurieren können.
+
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
. Migrieren Sie auf der Konsole jedes Knotens Fazit 2 zu Port e1a: `network interface migrate`
+
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
. Vergewissern Sie sich an der Konsole jedes Node, dass die Migration stattgefunden hat: `network interface show`
+
Das folgende Beispiel zeigt, dass Faclu2 auf beiden Knoten zu Port e1a migriert hat:

+
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
. Fahren Sie Cluster-Port e2a auf beiden Nodes herunter: `network port modify`
+
Das folgende Beispiel zeigt, dass Port e2a auf beiden Nodes heruntergefahren wird:

+
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
. Vergewissern Sie sich, dass Port e2a auf beiden Knoten heruntergefahren wird: `network port show`
+
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
. Fahren Sie die Inter-Switch Link (ISL)-Ports auf cs1, den aktiven NetApp Switch, herunter:
+
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
. Sichern Sie das aktuelle aktive Bild auf cs2.
+
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
. Laden Sie die Bilddatei auf den Switch herunter.
+
Durch Kopieren der Bilddatei auf das aktive Bild wird beim Neustart die laufende FASTPATH-Version erstellt. Das vorherige Bild bleibt als Backup verfügbar.

+
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
. Überprüfen Sie die laufende Version der FASTPATH-Software.
+
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
. Zeigen Sie die Boot-Images für die aktive und die Backup-Konfiguration an.
+
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
. Starten Sie den Switch neu.
+
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
. Melden Sie sich erneut an und überprüfen Sie die neue Version der FASTPATH Software.
+
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
. ISL-Ports an cs1, dem aktiven Switch, herauf.
+
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
. Vergewissern Sie sich, dass die ISLs betriebsbereit sind: `show port-channel 3/1`
+
Das Feld „Verbindungsstatus“ sollte angezeigt werden `Up`.

+
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. Kopieren Sie die `running-config` Datei in der `startup-config` Datei, wenn Sie mit den Software-Versionen und Switch-Einstellungen zufrieden sind.
+
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
. Aktivieren Sie den zweiten Cluster-Port e2a auf jedem Node: `network port modify`
+
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
. Fazit 2 zurücksetzen, der Port e2a zugeordnet ist: `network interface revert`
+
Das LIF ist möglicherweise automatisch zurückgesetzt, je nach Ihrer Version der ONTAP Software.

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. Vergewissern Sie sich, dass das LIF jetzt die Startseite ist (`true`) Auf beiden Knoten: `network interface show -_role cluster_`
+
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
. Status der Nodes anzeigen: `cluster show`
+
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
. Wiederholen Sie Schritt 1 bis Schritt 18, um die FASTPATH-Software auf dem anderen Switch, cs1, zu aktualisieren.
. Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie es erneut, indem Sie eine AutoSupport Meldung aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


