---
permalink: switch-netapp-cn1610/task-migrate-to-a-two-node-switched-cluster-with-netapp-cn1610-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Wenn Sie über einen 2-Node-Cluster ohne Switches verfügen, können Sie unterbrechungsfrei auf ein 2-Node-Cluster mit Switch migrieren, das die NetApp CN1610 Cluster-Netzwerk-Switches umfasst. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben. 
---
= Migrieren Sie mit NetApp CN1610 Cluster-Switches zu einem Cluster mit zwei Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie über einen 2-Node-Cluster ohne Switches verfügen, können Sie unterbrechungsfrei auf ein 2-Node-Cluster mit Switch migrieren, das die NetApp CN1610 Cluster-Netzwerk-Switches umfasst. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben.

Die meisten Systeme benötigen an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports.

FAS22xx Nodes ermöglichen einen einzelnen Cluster-Port an jedem Controller.

Es sind zwei Migrationsoptionen verfügbar:

* link:task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html["Migration von einem Cluster ohne Switches zu einer Switch-basierten NetApp CN1610 Cluster-Umgebung"]
* xref:task-migrate-from-a-switchless-cluster-fas22xx-systems-with-a-single-cluster-network-connection.adoc[Migration von einem Cluster ohne Switches (FAS22xx Systeme mit einer einzigen Cluster-Netzwerkverbindung)]

