---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: Erfahren Sie mehr über Cluster, Speicher und gemeinsam genutzte Switches. 
---
= Erfahren Sie mehr über AFX-Systeme, Cluster, Speicher und gemeinsam genutzte Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp bietet AFX-Systeme, Cluster, Speicher und gemeinsam genutzte Switches, die eine interne Kommunikation ermöglichen und die unterbrechungsfreie Verschiebung von Daten und Netzwerkschnittstellen über den Cluster ermöglichen.

Die „Front-End“-Switches stellen die Verbindung zum Host-Speicher her, während die „Back-End“-Cluster-Switches Verbindungen zwischen zwei oder mehr NetApp Controllern herstellen.


NOTE: Es werden ausschließlich von NetApp validierte Back-End-Switches (bestellt bei NetApp) unterstützt.



== AFX-Systemschalter

Mit den Switches von AFX Systems können Sie schnelle, energieeffiziente und platzsparende Netzwerk-Switches erstellen. Aufgrund ihrer geringen Größe und hohen Portdichte sind sie ideal für die Handhabung großer Netzwerke. Die Ports unterstützen unterschiedliche Geschwindigkeiten und können in mehrere Verbindungen aufgeteilt werden. Zu den von NetApp unterstützten AFX-System-Switches gehören:

* Cisco Nexus 9332D-GX2B
* Cisco Nexus 9364D-GX2A




== Cluster-Switches

Mit Cluster-Switches können Sie ONTAP Cluster mit mehr als zwei Knoten erstellen. Zu den von NetApp unterstützten Cluster-Switches gehören:

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== Speicherschalter

Storage-Switches ermöglichen das Routing von Daten zwischen Servern und Storage-Arrays in einem Storage Area Network (SAN).  Zu den von NetApp unterstützten Speicher-Switches gehören:

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== Gemeinsam genutzte Switches

Gemeinsam genutzte Switches ermöglichen es Ihnen, Cluster- und Speicherfunktionen in einer gemeinsamen Switch-Konfiguration zu kombinieren, indem sie die Verwendung gemeinsam genutzter Cluster- und Speicher-RCFs unterstützen.  Der von NetApp unterstützte Shared Switch ist:

* Cisco Nexus 9336C-FX2




== Ende der Verfügbarkeit

Die folgenden Speichersysteme sind nicht mehr käuflich erhältlich, werden aber weiterhin unterstützt:

* Cisco Nexus 3232C
* Cisco Nexus 3132Q-V
* Cisco Nexus 92300YC
* NetApp CN1610

