---
permalink: other-procedures/transition-to-two-node-switchless-cluster-index.html 
sidebar: sidebar 
keywords: transition, two-node, switchless, cluster, two, node 
summary: Sie können zu einem Cluster mit zwei Nodes wechseln, das Cluster-Interconnect-Switches zu einem Cluster verwendet, mit dem zwei Nodes direkt verbunden sind. 
---
= Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Wenn Sie bereits über ein zwei-Node-Cluster mit Cluster Interconnect Switches verfügen und ONTAP 9.3 oder höher ausgeführt wird, können Sie die Switches durch direkte Back-to-Back-Verbindungen zwischen den Nodes ersetzen.

Sie können die Cluster Interconnect-Funktion ohne Switches nicht mit mehr als zwei Nodes verwenden.

Der Umstieg auf eine Cluster-Konfiguration mit zwei Nodes ohne Switches ist ein unterbrechungsfreier Betrieb. Die meisten Systeme verfügen auf jedem Node über zwei dedizierte Cluster Interconnect Ports, jedoch können Sie dieses Verfahren auch für Systeme mit einer größeren Anzahl an dedizierten Cluster Interconnect Ports auf jedem Node verwenden, z. B. vier, sechs oder acht.

Dieses Verfahren beschreibt den Umstieg eines Clusters mit einem Switch-Cluster-Netzwerk auf einen, mit dem zwei Nodes direkt für ONTAP 9.3 und höher verbunden sind.
