---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Cluster-Netzwerk-Switches.  Sie können zusätzliche Management-Schalter verwenden, die optional sind. 
---
= Cisco Nexus 92300YC Switch – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Cluster-Netzwerk-Switches.  Sie können zusätzliche Management-Schalter verwenden, die optional sind.

Sie können den Cisco Nexus 92300YC Switch (X190003/R) mit den im Lieferumfang enthaltenen Standardhalterungen in einem NetApp -Systemschrank oder einem Schrank eines Drittanbieters installieren.

Die folgende Tabelle listet die Teilenummer und Beschreibung für den Schalter 92300YC, die Lüfter und die Netzteile auf:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Port Side Exhaust)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Port Side Intake)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Lüfter, Cisco N9K, seitlicher Lufteinlass



 a| 
X-NXA-FAN-35CFM-F
 a| 
Lüfter, Cisco N9K, seitlicher Luftauslass



 a| 
X-NXA-PAC-650W-B
 a| 
Netzteil, Cisco 650W - Einlass an der Portseite



 a| 
X-NXA-PAC-650W-F
 a| 
Netzteil, Cisco 650W - Auslassöffnung an der Portseite

|===
Details zum Luftstrom des Cisco Nexus 92300YC Switches:

* Abluftstrom an der Backbordseite (Standardluft) --Kühle Luft strömt über die Lüfter- und Netzteilmodule im Kaltgang in das Gehäuse und wird über das Backbordende des Gehäuses im Warmgang wieder ausgestoßen.  Abluftstrom auf der Backbordseite mit blauer Färbung.
* Luftansaugung an der Backbordseite (umgekehrte Luftführung) – Kühle Luft strömt durch die Backbordseite im Kaltgang in das Gehäuse und wird durch die Lüfter- und Stromversorgungsmodule im Warmgang wieder ausgestoßen.  Lufteinlass auf der Backbordseite mit bordeauxroter Färbung.


.Verfügbare Dokumentation
Die folgende Tabelle listet die für die Cisco Nexus 92300YC Switches verfügbare Dokumentation auf.

|===


| Titel | Beschreibung 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["_Einrichten der Cisco Nexus 92300YC Cluster-Switches_"^]
 a| 
Beschreibt, wie Sie Ihre Cisco Nexus 92300YC Cluster-Switches einrichten und konfigurieren.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_NX-OS und Referenzkonfigurationsdateien (RCFs) installieren_"^]
 a| 
Beschreibt die Installation von NX-OS und Referenzkonfigurationsdateien (RCFs) auf dem Cluster-Switch Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["_Konfigurieren eines neuen Cisco Nexus 92300YC Switches_"^]
 a| 
Beschreibt, wie man von Umgebungen, die ältere Cisco Switches verwenden, zu Umgebungen migriert, die Cisco 92300YC-Switches verwenden.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc.html["_Migration von einem älteren Cisco Switch zu einem Cisco Nexus 92300YC-Switch_"^]
 a| 
Beschreibt das Verfahren zum Austausch eines älteren Cisco Switches durch einen Cisco Nexus 92300YC Cluster-Switch.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_Migration von einem Zwei-Knoten-Switchless-Cluster_"^]
 a| 
Beschreibt, wie man von einer Zwei-Knoten-Clusterumgebung ohne Switches zu einer Zwei-Knoten-Umgebung mit Switches unter Verwendung von Cisco Nexus 92300YC Cluster-Switches migriert.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_Ersetzen eines Cisco Nexus 92300YC Cluster-Switches_"^]
 a| 
Beschreibt das Vorgehen zum Austausch eines defekten Cisco Nexus 92300YC Switches in einem Cluster sowie zum Herunterladen des Switch-Betriebssystems und der Referenzkonfigurationsdatei.

|===