---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Cluster-Netzwerk-Switches.  Sie können zusätzliche Management-Schalter verwenden, die optional sind. 
---
= Komponenten und Teilenummern für Cisco Nexus 92300YC-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Installation und Wartung des Cisco Nexus 92300YC Switches sollten Sie unbedingt alle Switch-Komponenten und Teilenummern überprüfen. Siehe die https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] für Details.

Die folgende Tabelle listet die Teilenummer und Beschreibung für den Schalter 92300YC, die Lüfter und die Netzteile auf:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Port Side Exhaust)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Port Side Intake)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Lüfter, Cisco N9K, seitlicher Lufteinlass



 a| 
X-NXA-FAN-35CFM-F
 a| 
Lüfter, Cisco N9K, seitlicher Luftauslass



 a| 
X-NXA-PAC-650W-B
 a| 
Netzteil, Cisco 650W - Einlass an der Portseite



 a| 
X-NXA-PAC-650W-F
 a| 
Netzteil, Cisco 650W - Auslassöffnung an der Portseite

|===
Details zum Luftstrom des Cisco Nexus 92300YC Switches:

* Abluftstrom auf der Backbordseite (Standardluft) -- Kühle Luft strömt durch die Lüfter- und Netzteilmodule im Kaltgang in das Gehäuse und wird durch das Backbordende des Gehäuses im Warmgang wieder ausgestoßen.  Abluftstrom auf der Backbordseite mit blauer Färbung.
* Luftansaugung an der Backbordseite (umgekehrte Luftführung) -- Kühle Luft strömt durch die Backbordseite im Kaltgang in das Gehäuse und wird durch die Lüfter- und Stromversorgungsmodule im Warmgang wieder ausgestoßen.  Lufteinlass auf der Backbordseite mit bordeauxroter Färbung.


.Was kommt als nächstes
Nachdem Sie Ihre Komponenten und Teilenummern bestätigt haben, können Sie die folgenden überprüfen: link:required-documentation-92300.html["erforderliche Dokumentation"]Die
