---
permalink: switch-cisco-92300/configure-install-initial.html 
sidebar: sidebar 
keywords: install cisco 92300YC cluster switch, cisco nx 92300yc 
summary: Sie können dieses Verfahren verwenden, um die Erstinstallation des Cisco Nexus 92300YC-Switch durchzuführen. 
---
= Erstinstallation des Cisco Nexus 92300YC Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können dieses Verfahren verwenden, um die Erstinstallation des Cisco Nexus 92300YC-Switch durchzuführen.

Sie können die entsprechende NetApp Cisco NX-OS Software für Ihre Switches vom herunterladen http://mysupport.netapp.com/["NetApp Support"^] Standort.

Bei NX-OS handelt es sich um ein Netzwerkbetriebssystem für die Ethernet Switches der Nexus Serie und die MDS Serie mit Fibre Channel (FC) Storage Area Network Switches von Cisco Systems.

Dieses Verfahren enthält eine Zusammenfassung des Verfahrens zur Installation der Switches und zum Ausführen der Switches:

.Schritte
. Schließen Sie den seriellen Port an den Host oder den seriellen Port Ihrer Wahl an.
. Verbinden Sie den Verwaltungsport (auf der Seite des Switches ohne Port) mit dem gleichen Netzwerk, in dem sich der SFTP-Server befindet.
. Legen Sie an der Konsole die seriellen Einstellungen der Host-Seite fest:
+
** 9600 Baud
** 8 Datenbits
** 1 Stoppbit
** Parität: Keine
** Flusskontrolle: Keine


. Der Nexus 92300YC-Switch wird zum ersten Mal gestartet oder nach dem Löschen der laufenden Konfiguration neu gestartet. Unterbrechen Sie diesen Zyklus, indem Sie *yes* eingeben, um das Einschalten der automatischen Provisionierung abzubrechen. Sie werden dann mit dem System Admin Account Setup dargestellt:


[listing]
----
$ VDC-1 %$ %POAP-2-POAP_INFO:   - Abort Power On Auto Provisioning [yes - continue with normal setup, skip - bypass password and basic configuration, no - continue with Power On Auto Provisioning] (yes/skip/no)[no]: *y*
Disabling POAP.......Disabling POAP
2019 Apr 10 00:36:17 switch %$ VDC-1 %$ poap: Rolling back, please wait... (This may take 5-15 minutes)

          ---- System Admin Account Setup ----

Do you want to enforce secure password standard (yes/no) [y]:
----
. Geben Sie * y* ein, um den sicheren Kennwortstandard durchzusetzen:
+
[listing, subs="+quotes"]
----
Do you want to enforce secure password standard (yes/no) [y]: *y*
----
. Geben Sie das Passwort für den Benutzer admin ein und bestätigen Sie es:
+
[listing]
----
Enter the password for "admin":
Confirm the password for "admin":
----
. Rufen Sie das Dialogfeld grundlegende Systemkonfiguration auf:
+
[listing]
----
This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus9000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus9000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.

Would you like to enter the basic configuration dialog (yes/no):
----
. Ein weiteres Anmeldekonto erstellen:
+
[listing]
----
Create another login account (yes/no) [n]:
----
. Konfigurieren Sie die SNMP-Community-Strings Read-Only und read-write:
+
[listing]
----
Configure read-only SNMP community string (yes/no) [n]:

Configure read-write SNMP community string (yes/no) [n]:
----
. Konfigurieren Sie den Namen des Cluster-Switches:
+
[listing, subs="+quotes"]
----
Enter the switch name : *cs2*
----
. Konfigurieren Sie die Out-of-Band-Managementoberfläche:
+
[listing, subs="+quotes"]
----
Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]: *y*

Mgmt0 IPv4 address : 172.22.133.216

Mgmt0 IPv4 netmask : 255.255.224.0

Configure the default gateway? (yes/no) [y]: *y*

IPv4 address of the default gateway : 172.22.128.1
----
. Erweiterte IP-Optionen konfigurieren:
+
[listing, subs="+quotes"]
----
Configure advanced IP options? (yes/no) [n]: *n*
----
. Telnet-Dienste konfigurieren:
+
[listing, subs="+quotes"]
----
Enable the telnet service? (yes/no) [n]: *n*
----
. Konfigurieren von SSH-Diensten und SSH-Schlüsseln:
+
[listing, subs="+quotes"]
----
Enable the ssh service? (yes/no) [y]: *y*

       Type of ssh key you would like to generate (dsa/rsa) [rsa]: *rsa*

       Number of rsa key bits <1024-2048> [1024]: *2048*
----
. Weitere Einstellungen konfigurieren:
+
[listing, subs="+quotes"]
----
Configure the ntp server? (yes/no) [n]: *n*

  Configure default interface layer (L3/L2) [L2]: *L2*

  Configure default switchport interface state (shut/noshut) [noshut]: *noshut*

  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]: *strict*
----
. Bestätigen Sie die Switch-Informationen und speichern Sie die Konfiguration:
+
[listing, subs="+quotes"]
----
Would you like to edit the configuration? (yes/no) [n]: *n*

Use this configuration and save it? (yes/no) [y]: *y*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----

