---
permalink: switch-cisco-92300/configure-overview.html 
sidebar: sidebar 
keywords: confiure 92300yc cluster switch, cisco 92300yc 
summary: Sie können einen neuen Nexus 92300YC-Switch konfigurieren, indem Sie die in diesem Kapitel beschriebenen Schritte ausführen. 
---
= Konfigurieren Sie einen neuen Cisco Nexus 92300YC-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen neuen Nexus 92300YC-Switch konfigurieren, indem Sie die in diesem Kapitel beschriebenen Schritte ausführen.

Die Installation des Nexus 92300YC-Switch auf Systemen mit ONTAP 9.6 und höher beginnt mit der Einrichtung einer IP-Adresse und -Konfiguration, damit der Switch über die Managementoberfläche kommunizieren kann. Anschließend können Sie die NX-OS-Software und die Referenzkonfigurationsdatei (RCF) installieren. Dieses Verfahren dient zur Vorbereitung des Nexus 92300YC-Switch, bevor Controller hinzugefügt werden.

Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die Switch-Namen des Nexus 92300YC sind `cs1` Und `cs2`.
* Das in diesem Verfahren verwendete Beispiel startet das Upgrade auf dem zweiten Schalter _*cs2*._
* Die LIF-Namen des Clusters sind `node1_clus1` Und `node1_clus2` Für Node1, und `node2_clus1` Und `node2_clus2` Für Knoten 2.
* Der IPspace-Name lautet `Cluster`.
* Der `cluster1::*>` Eine Eingabeaufforderung gibt den Namen des Clusters an.
* Die Cluster-Ports an jedem Node werden mit benannt `e0a` Und `e0b`.
+
Siehe link:https://hwu.netapp.com/Home/Index["_Hardware Universe_"^] Für die tatsächlichen Cluster-Ports, die auf Ihrer Plattform unterstützt werden.

* Die Inter-Switch Links (ISLs) werden für Nexus 92300YC Switches unterstützt; die Ports 1/65 und 1/66.
* Die für Nexus 92300YC-Switches unterstützten Node-Verbindungen sind die Ports 1/1 bis 1/66.
* Die Beispiele in diesem Verfahren verwenden zwei Nodes, Sie können jedoch bis zu 24 Nodes in einem Cluster haben.

