---
permalink: switch-cisco-92300/index.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Wenn Sie ONTAP Cluster mit mehr als zwei Nodes erstellen möchten, sind zwei unterstützte Cluster-Netzwerk-Switches erforderlich. Sie können zusätzliche, optionale Management Switches verwenden. 
---
= Überblick und Anforderungen: Cisco Nexus 92300YC Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung von Cisco Nexus 92300YC-Switches müssen alle Anforderungen und die empfohlene Dokumentation geprüft werden.

Wenn Sie ONTAP Cluster mit mehr als zwei Nodes erstellen möchten, sind zwei unterstützte Cluster-Netzwerk-Switches erforderlich. Sie können zusätzliche, optionale Management Switches verwenden.



== Switch-Komponenten

In der folgenden Tabelle sind die Teilenummer und Beschreibung für den 92300YC-Switch, die Lüfter und die Netzteile aufgeführt:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48 Pt10/25 GB, 18 Pt100G, PTSX (PTSX = Port Side Exhaust)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25 GB, 18Pt100G, PSIN (PSIN = Port Side Intake)



 a| 
X-NXA-LÜFTER-35CFM-B
 a| 
Lüfter, Luftstrom für den seitlichen Cisco N9K-Anschluss



 a| 
X-NXA-LÜFTER-35CFM-F
 a| 
Lüfter, seitlicher Luftstrom des Cisco N9K-Ports



 a| 
X-NXA-PAC-650W-B
 a| 
Netzteil, Cisco 650W - Anschlusseingang



 a| 
X-NXA-PAC-650W-F
 a| 
Netzteil, Cisco 650W - Anschlussseite Auspuff

|===
Details zum Luftstrom des Cisco Nexus 92300YC-Switches:

* Port-Side Abluftstrom (Standardluft) -- Kühle Luft dringt durch die Lüfter- und Stromversorgungsmodule im Kaltgang in das Gehäuse ein und auspufft durch das Anschlussende des Gehäuses im heißen Gang. Port-Side Abluftstrom mit blauer Färbung.
* Port-Side Ansaugluftstrom (Rückwärtsluft) -- Kühle Luft dringt durch das Anschlussende im kalten Gang in das Gehäuse ein und entgastet durch die Lüfter- und Stromversorgungsmodule im heißen Gang. Port-Side-Luftstrom mit Burgunder Färbung.




== Konfigurationsanforderungen

Zum Konfigurieren des Clusters benötigen Sie die entsprechende Anzahl und den entsprechenden Kabeltyp und Kabelanschlüsse für Ihre Switches. Je nach Art des Switches, den Sie zunächst konfigurieren, müssen Sie mit dem mitgelieferten Konsolenkabel eine Verbindung zum Switch-Konsolen-Port herstellen. Außerdem müssen Sie spezifische Netzwerkinformationen bereitstellen.



== Netzwerkanforderungen

Sie benötigen die folgenden Netzwerkinformationen für alle Switch-Konfigurationen:

* IP-Subnetz für den Management-Netzwerkdatenverkehr
* Host-Namen und IP-Adressen für jeden Storage-System-Controller und alle entsprechenden Switches
* Die meisten Storage-System-Controller werden über die Schnittstelle E0M verwaltet durch eine Verbindung zum Ethernet-Service-Port (Symbol Schraubenschlüssel). Auf AFF A800 und AFF A700 Systemen verwendet die E0M Schnittstelle einen dedizierten Ethernet-Port.


Siehe https://hwu.netapp.com["Hardware Universe"^] Aktuelle Informationen.



== Anforderungen für Smart Call Home

Smart Call Home überwacht die Hardware- und Softwarekomponenten in Ihrem Netzwerk, um eine E-Mail-basierte Benachrichtigung über wichtige Systembedingungen zu generieren. Wenn ein Ereignis auf Ihrem Gerät auftritt, wird Smart Call Home an alle Empfänger, die im Zielprofil konfiguriert sind, eine Warnmeldung ausgegeben.

Sie müssen einen Cluster-Netzwerk-Switch konfigurieren, um per E-Mail mit dem Smart Call Home-System kommunizieren zu können. Sie können optional Ihren Cluster-Netzwerk-Switch einrichten, um die integrierte Smart Call Home-Support-Funktion von Cisco zu nutzen.

Bevor Sie die Smart Call Home-Funktion verwenden können, müssen Sie die folgenden Überlegungen beachten:

* Es muss ein E-Mail-Server vorhanden sein.
* Der Switch muss über eine IP-Verbindung zum E-Mail-Server verfügen.
* Der Name des Kontakts (SNMP-Serverkontakt), die Telefonnummer und die Adresse der Straße müssen konfiguriert werden. Dies ist erforderlich, um den Ursprung der empfangenen Nachrichten zu bestimmen.
* Eine CCO-ID muss mit einem entsprechenden Cisco SMARTnet-Servicevertrag für Ihr Unternehmen verknüpft sein.
* Cisco SMARTnet Service muss vorhanden sein, damit das Gerät registriert werden kann.


Der http://www.cisco.com/c/en/us/products/switches/index.html["Cisco Support-Website"^] Enthält Informationen zu den Befehlen zum Konfigurieren von Smart Call Home.



== Dokumentationsanforderungen

Sie benötigen spezifische Switch- und Controller-Dokumentation, um Ihre Cisco Nexus 92300YC Switches und den ONTAP Cluster einzurichten.



=== Switch-Dokumentation

Zum Einrichten der Cisco Nexus 92300YC Switches benötigen Sie die folgende Dokumentation von https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Der Cisco Nexus 9000-Serie Unterstützen"^] Seite:

[cols="1,2"]
|===
| Dokumenttitel | Beschreibung 


 a| 
Hardware-Installationshandbuch Der Serie _Nexus 9000_
 a| 
Detaillierte Informationen zu Standortanforderungen, Hardwaredetails zu Switches und Installationsoptionen.



 a| 
_Cisco Nexus 9000 Series Switch Software Configuration Guides_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Stellt Informationen zur Erstkonfiguration des Switches bereit, die Sie benötigen, bevor Sie den Switch für den ONTAP-Betrieb konfigurieren können.



 a| 
_Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide_ (wählen Sie das Handbuch für die auf Ihren Switches installierte NX-OS-Version)
 a| 
Enthält Informationen zum Downgrade des Switch auf ONTAP unterstützte Switch-Software, falls erforderlich.



 a| 
_Cisco Nexus 9000 Series NX-OS Command Reference Master Index_
 a| 
Enthält Links zu den verschiedenen von Cisco bereitgestellten Befehlsreferenzen.



 a| 
_Cisco Nexus 9000 MIBs Referenz_
 a| 
Beschreibt die MIB-Dateien (Management Information Base) für die Nexus 9000-Switches.



 a| 
_Nexus 9000 Series NX-OS System Message Reference_
 a| 
Beschreibt die Systemmeldungen für Switches der Cisco Nexus 9000 Serie, Informationen und andere, die bei der Diagnose von Problemen mit Links, interner Hardware oder der Systemsoftware helfen können.



 a| 
_Versionshinweise zur Cisco Nexus 9000-Serie NX-OS (wählen Sie die Hinweise für die auf Ihren Switches installierte NX-OS-Version aus)_
 a| 
Beschreibt die Funktionen, Bugs und Einschränkungen der Cisco Nexus 9000 Serie.



 a| 
Compliance- und Sicherheitsinformationen für die Cisco Nexus 9000-Serie
 a| 
Bietet internationale Compliance-, Sicherheits- und gesetzliche Informationen für Switches der Serie Nexus 9000.

|===


=== Dokumentation der ONTAP Systeme

Um ein ONTAP-System einzurichten, benötigen Sie die folgenden Dokumente für Ihre Betriebssystemversion über das https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 Dokumentationszentrum"^].

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
Controller-spezifisch _Installations- und Setup-Anleitung_
 a| 
Beschreibt die Installation von NetApp Hardware.



 a| 
ONTAP-Dokumentation
 a| 
Dieser Service bietet detaillierte Informationen zu allen Aspekten der ONTAP Versionen.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Liefert Informationen zur NetApp Hardwarekonfiguration und -Kompatibilität.

|===


=== Schienensatz und Rack-Dokumentation

Informationen zur Installation eines Cisco Nexus 92300YC Switch in einem NetApp-Schrank finden Sie in der folgenden Hardware-Dokumentation.

[cols="1,2"]
|===
| Name | Beschreibung 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42-HE-System-Cabinet, Deep Guide"^]
 a| 
Beschreibt die FRUs, die dem 42U-Systemschrank zugeordnet sind, und bietet Anweisungen für Wartung und FRU-Austausch.



 a| 
link:install-switch-and-passthrough-panel.html["Installieren Sie einen Cisco Nexus 92300YC Switch in einem NetApp Rack"]
 a| 
Beschreibt die Installation eines Cisco Nexus 92300YC Switches in einem NetApp Rack mit vier Säulen.

|===