---
permalink: switch-cisco-92300/install-nxos-overview.html 
sidebar: sidebar 
keywords: install nx-os rcf cisco nx 92300yc cluster switch 
summary: 'Die Cisco NX-OS-Software und die Referenzkonfigurationsdateien \(RCFs\) müssen auf Cisco Nexus 92300YC-Cluster-Switches installiert sein.' 
---
= Vorbereiten der Installation der NX-OS-Software und der Referenzkonfigurationsdatei (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie die NX-OS-Software und die RCF-Datei (Reference Configuration File) installieren, gehen Sie wie folgt vor:

.Was Sie benötigen
* Ein voll funktionsfähiges Cluster (keine Fehler in den Protokollen oder ähnlichen Problemen).
* Entsprechende Leitfäden für Software und Upgrades, die bei verfügbar sind https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html#InstallandUpgrade["Switches Der Cisco Nexus 9000-Serie"^].


.Zu den Beispielen
Die Beispiele in diesem Verfahren verwenden zwei Knoten. Diese Nodes verwenden zwei 10-GbE-Cluster-Interconnect-Ports `e0a` Und `e0b`. Siehe https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] Um sicherzustellen, dass die korrekten Cluster-Ports auf Ihren Plattformen vorhanden sind.

Die Beispiele in diesem Verfahren verwenden die folgende Nomenklatur für Switches und Knoten:

* Die Namen der beiden Cisco Switches lauten `cs1` Und `cs2`.
* Die Node-Namen sind `node1` Und `node2`.
* Die LIF-Namen des Clusters sind `node1_clus1` Und `node1_clus2` Für Node1 und `node2_clus1` Und `node2_clus2` Für Knoten 2.
* Der `cluster1::*>` Eine Eingabeaufforderung gibt den Namen des Clusters an.


.Über diese Aufgabe
Das Verfahren erfordert die Verwendung von ONTAP Befehlen und den Switches der Cisco Nexus 9000 Serie. ONTAP Befehle werden verwendet, sofern nicht anders angegeben. Die Ausgaben für die Befehle können je nach verschiedenen Versionen von ONTAP variieren.

.Schritte
. Ändern Sie die Berechtigungsebene in Erweitert, und geben Sie *y* ein, wenn Sie dazu aufgefordert werden, fortzufahren:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (`*>`Erscheint.

. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Wobei _x_ die Dauer des Wartungsfensters in Stunden ist.

+

NOTE: Die AutoSupport Meldung wird vom technischen Support dieser Wartungsaufgabe benachrichtigt, damit die automatische Case-Erstellung während des Wartungsfensters unterdrückt wird.

+
Mit dem folgenden Befehl wird die automatische Case-Erstellung für zwei Stunden unterdrückt:

+
[listing]
----
cluster1:> **system node autosupport invoke -node * -type all -message MAINT=2h**
----
. Zeigen Sie an, wie viele Cluster-Interconnect-Schnittstellen in jedem Node für jeden Cluster Interconnect-Switch konfiguriert sind: `network device-discovery show -protocol cdp`
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

 Node/      Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       Eth1/2            N9K-C92300YC
            e0b    cs2                       Eth1/2            N9K-C92300YC
node1      /cdp
            e0a    cs1                       Eth1/1            N9K-C92300YC
            e0b    cs2                       Eth1/1            N9K-C92300YC

4 entries were displayed.
----
====
. Überprüfen Sie den Administrations- oder Betriebsstatus der einzelnen Cluster-Schnittstellen.
+
.. Zeigen Sie die Attribute des Netzwerkports an:  `network port show –ipspace Cluster`
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node2
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node1
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
.. Zeigt Informationen zu den LIFs an: `network interface show -vserver Cluster`
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.
----
====


. Ping für die Remote-Cluster-LIFs:
+
`cluster ping-cluster -node node-name`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Vergewissern Sie sich, dass der automatische Zurücksetzen-Befehl auf allen Cluster-LIFs aktiviert ist:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====


.Was kommt als Nächstes?
link:install-nxos-software.html["Installieren Sie die NX-OS-Software"].
