---
permalink: switch-cisco-92300/migrate-to-92300yc-overview.html 
sidebar: sidebar 
keywords: migrate to cisco nx 92300yc cluster switch,new cluster switch migration 
summary: Sie müssen bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten, wenn Sie einige ältere Cisco Nexus Cluster Switches durch Cisco Nexus 92300YC Cluster Switches ersetzen. 
---
= Migrieren Sie von einem Cisco Switch zu einem Cisco Nexus 92300YC Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten, wenn Sie einige ältere Cisco Nexus Cluster Switches durch Cisco Nexus 92300YC Cluster Switches ersetzen.

* Folgende Cluster-Switches werden unterstützt:
+
** Nexus 92300YC
** Nexus 5596UP
** Nexus 5020
** Nexus 5010


* Die Cluster-Switches verwenden die folgenden Ports für Verbindungen zu den Nodes:
+
** Ports e1/1-48 (10/25 GbE), e1/49-64 (40/100 GbE): Nexus 92300YC
** Ports e1/1-40 (10 GbE): Nexus 5596UP
** Ports e1/1-32 (10 GbE): Nexus 5020
** Ports e1/1-12, e2/1-6 (10 GbE): Nexus 5010 mit Erweiterungsmodul


* Bei den Cluster-Switches werden die folgenden Inter-Switch Link (ISL)-Ports verwendet:
+
** Ports e1/65-66 (100 GbE): Nexus 92300YC
** Ports e1/41-48 (10 GbE): Nexus 5596UP
** Ports e1/33-40 (10 GbE): Nexus 5020
** Ports e1/13-20 (10 GbE): Nexus 5010


* Der https://hwu.netapp.com/SWITCH/INDEX["_Hardware Universe_"^] Die enthält Informationen über die unterstützte Verkabelung aller Cluster Switches.
* Sie haben einige der Ports auf Nexus 92300YC Switches für 10 GbE oder 40 GbE konfiguriert.
* Sie haben 10-GbE- und 40-GbE-Konnektivität zwischen den Knoten zu Nexus 92300YC Cluster Switches geplant, migriert und dokumentiert.
* Die in diesem Verfahren unterstützten ONTAP- und NX-OS-Versionen befinden sich auf dem https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco Ethernet-Switches"^] Seite.
+

NOTE: Nach Abschluss der Migration müssen Sie möglicherweise die erforderliche Konfigurationsdatei installieren, um den Cluster Switch Health Monitor (CSHM) für 92300YC Cluster Switches zu unterstützen. Siehe _Installieren der Konfigurationsdatei des Cluster Switch Health Monitor (CSHM) für 92300YC-Schalter_ im link:../com.netapp.doc.hw-sw-cisco-setup/home.html["Einrichtung"] Begleiten.


