---
permalink: switch-cisco-92300/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: TNSC,migrate two-node,migrate 2-node 
summary: Wenn Sie einen unterbrechungsfrei 2-Node-Cluster ohne Switches zu einem Cluster mit Cisco Nexus 92300YC Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben. Der dokumentierte Prozess funktioniert für alle Knoten mit optischen oder Twinax-Ports, wird aber auf diesem Switch nicht unterstützt, wenn Knoten integrierte 10-Gbit-BASE-T-RJ45-Ports für die Cluster-Netzwerk-Ports verwenden. 
---
= Migrieren Sie zu einem Switch-basierten 2-Node-Cluster mit Cisco Nexus 92300YC-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen unterbrechungsfrei 2-Node-Cluster ohne Switches zu einem Cluster mit Cisco Nexus 92300YC Cluster-Switches migrieren, müssen Sie bestimmte Konfigurationsinformationen, Port-Verbindungen und Verkabelungsanforderungen beachten. Die von Ihnen verwendete Vorgehensweise hängt davon ab, ob Sie an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports oder einen einzelnen Cluster-Port haben. Der dokumentierte Prozess funktioniert für alle Knoten mit optischen oder Twinax-Ports, wird aber auf diesem Switch nicht unterstützt, wenn Knoten integrierte 10-Gbit-BASE-T-RJ45-Ports für die Cluster-Netzwerk-Ports verwenden.

Die meisten Systeme benötigen an jedem Controller zwei dedizierte Cluster-Netzwerk-Ports.


NOTE: Nach Abschluss der Migration müssen Sie möglicherweise die erforderliche Konfigurationsdatei installieren, um den Cluster Switch Health Monitor (CSHM) für 92300YC Cluster Switches zu unterstützen. Siehe _Installieren der Konfigurationsdatei des Cluster Switch Health Monitor (CSHM) für 92300YC-Schalter_ im link:../com.netapp.doc.hw-sw-cisco-setup/home.html["Einrichtung"] Begleiten.
