---
permalink: switch-cshm/log-collection-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Sie können die hier bereitgestellten Befehle verwenden, um … 
---
= Fehlerbehebung bei der Protokollerfassung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie auf einen der folgenden Fehlerstatus stoßen, die von der Protokollerfassungsfunktion gemeldet werden (sichtbar in der Ausgabe von `system switch ethernet log show` Befehl), versuchen Sie die entsprechenden Debugging-Schritte:

|===


| *Fehlerstatus bei der Protokollerfassung* | *Auflösung* 


 a| 
*RSA-Schlüssel nicht vorhanden*
 a| 
ONTAP SSH-Schlüssel neu generieren.



 a| 
*Fehler beim Switch-Passwort*
 a| 
Überprüfen Sie die Anmeldeinformationen, testen Sie die SSH-Verbindung und generieren Sie die ONTAP SSH-Schlüssel neu.  Lesen Sie die Dokumentation des Switches oder wenden Sie sich an den NetApp Support, um weitere Anweisungen zu erhalten.



 a| 
*ECDSA-Schlüssel für FIPS nicht vorhanden*
 a| 
Wenn der FIPS-Modus aktiviert ist, müssen auf dem Switch ECDSA-Schlüssel generiert werden, bevor ein erneuter Versuch unternommen werden kann.



 a| 
*Vorhandenes Protokoll gefunden*
 a| 
Entfernen Sie die vorherige Protokolldatei auf dem Switch.



 a| 
*Fehler im Switch-Dump-Protokoll*
 a| 
Stellen Sie sicher, dass der Switch-Benutzer über die Berechtigung zur Protokollerfassung verfügt.  Beachten Sie die oben genannten Voraussetzungen.

|===

NOTE: Falls die beschriebenen Lösungsdetails nicht funktionieren, wenden Sie sich bitte an den NetApp Support.
