---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: Erfahren Sie, wie Sie Ethernet-Switches manuell erstellen, Standardüberwachungseinstellungen ändern und diese aus der Überwachung löschen. 
---
= Verwaltung der Überwachung von Ethernet-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In den meisten Fällen werden Ethernet-Switches von ONTAP automatisch erkannt und von CSHM überwacht.  Die auf den Switch angewendete Referenzkonfigurationsdatei (RCF) aktiviert unter anderem das Cisco Discovery Protocol (CDP) und/oder das Link Layer Discovery Protocol (LLDP).  Möglicherweise müssen Sie jedoch manuell einen Schalter hinzufügen, der nicht erkannt wird, oder einen Schalter entfernen, der nicht mehr verwendet wird.  Sie können die aktive Überwachung auch beenden, während der Schalter in der Konfiguration beibehalten wird, beispielsweise während Wartungsarbeiten.



== Erstellen Sie einen Switch-Eintrag, damit ONTAP ihn überwachen kann.

Verwenden Sie die `system switch ethernet create` Befehl zum manuellen Konfigurieren und Aktivieren der Überwachung für einen bestimmten Ethernet-Switch.  Dies ist hilfreich, wenn ONTAP den Schalter nicht automatisch hinzufügt oder wenn Sie den Schalter zuvor entfernt haben und ihn wieder hinzufügen möchten.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Ein typisches Beispiel ist das Hinzufügen eines Switches mit dem Namen [DeviceName], der IP-Adresse 1.2.3.4 und den auf *cshm1!* gesetzten SNMPv2c-Anmeldeinformationen.  Verwenden `-type storage-network` anstatt `-type cluster-network` wenn Sie einen Speicherswitch konfigurieren.



== Überwachung deaktivieren, ohne den Schalter zu löschen

Wenn Sie die Überwachung eines bestimmten Schalters pausieren oder beenden, ihn aber für die zukünftige Überwachung beibehalten möchten, ändern Sie dessen Einstellungen. `is-monitoring-enabled-admim` den Parameter, anstatt ihn zu löschen.

Beispiel:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Dadurch bleiben Schalterdetails und Konfigurationen erhalten, ohne dass neue Warnmeldungen oder erneute Erkennungen ausgelöst werden.



== Entfernen Sie einen Schalter, den Sie nicht mehr benötigen.

Verwenden `system switch ethernet delete` Einen Schalter löschen, der nicht mehr angeschlossen ist oder nicht mehr benötigt wird:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Standardmäßig ist dieser Befehl nur dann erfolgreich, wenn ONTAP den Switch aktuell nicht über CDP oder LLDP erkennt.  Um einen gefundenen Schalter zu entfernen, verwenden Sie die `-force` Parameter:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Wann `-force` Wird der Schalter verwendet, kann er automatisch wieder hinzugefügt werden, wenn ONTAP ihn erneut erkennt.
