---
permalink: switch-cshm/monitor-verify.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: Erfahren Sie, wie Sie überprüfen können, ob die Überwachung eines Ethernet-Switches funktioniert. 
---
= Überprüfen Sie die Überwachung der Ethernet-Switches.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Ethernet Switch Health Monitor (CSHM) versucht automatisch, die von ihm erkannten Switches zu überwachen; die Überwachung erfolgt jedoch möglicherweise nicht automatisch, wenn die Switches nicht korrekt konfiguriert sind.  Sie sollten überprüfen, ob der Health Monitor ordnungsgemäß konfiguriert ist, um Ihre Switches zu überwachen.



== Bestätigen Sie die Überwachung der angeschlossenen Ethernet-Switches.

Um zu bestätigen, dass die angeschlossenen Ethernet-Switches überwacht werden, führen Sie Folgendes aus:

[source, cli]
----
system switch ethernet show
----
Wenn die `Model` Die Spalte zeigt *ANDERE* oder die `IS Monitored` Wenn das Feld *false* anzeigt, kann ONTAP den Switch nicht überwachen.  Der Wert *OTHER* bedeutet in der Regel, dass ONTAP diesen Schalter für die Zustandsüberwachung nicht unterstützt.

Der `IS Monitored` Das Feld ist aus dem im Dokument angegebenen Grund auf *false* gesetzt. `Reason` Feld.

[NOTE]
====
Wenn ein Schalter in der Befehlsausgabe nicht aufgeführt ist, hat ONTAP ihn wahrscheinlich nicht erkannt.  Vergewissern Sie sich, dass der Schalter korrekt verkabelt ist.  Bei Bedarf können Sie den Schalter manuell hinzufügen.  Sehenlink:monitor-manage.html["Verwaltung der Überwachung von Ethernet-Switches"] für weitere Einzelheiten.

====


== Bitte prüfen Sie, ob die Firmware- und RCF-Versionen auf dem neuesten Stand sind.

Stellen Sie sicher, dass auf dem Switch die neueste unterstützte Firmware läuft und dass eine kompatible Referenzkonfigurationsdatei (RCF) angewendet wurde.  Weitere Informationen finden Sie auf der Websitehttps://mysupport.netapp.com/site/downloads["NetApp Support-Downloadseite"^] Die

Standardmäßig verwendet der Health Monitor SNMPv2c mit der Community-Zeichenfolge *cshm1!* für die Überwachung, aber SNMPv3 kann auch konfiguriert werden.

Wenn Sie die standardmäßige SNMPv2c-Community-Zeichenfolge ändern müssen, stellen Sie sicher, dass die gewünschte SNMPv2c-Community-Zeichenfolge auf dem Switch konfiguriert wurde.

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: Sehenlink:config-snmpv3.html["Optional: SNMPv3 konfigurieren"] Einzelheiten zur Konfiguration von SNMPv3 finden Sie hier.



== Bestätigen Sie die Verbindung zum Managementnetzwerk.

Überprüfen Sie, ob der Management-Port des Switches mit dem Management-Netzwerk verbunden ist.

Für die Durchführung von SNMP-Abfragen und die Protokollerfassung ONTAP ist eine korrekte Verbindung zum Management-Port erforderlich.
