---
permalink: switch-cshm/monitor-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Sie können die folgenden Befehle verwenden… 
---
= Fehlerbehebung bei Warnmeldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es werden Warnmeldungen ausgegeben, wenn bei einem Ethernet-Switch in Ihrem Cluster ein Fehler, ein Risiko oder ein kritischer Zustand festgestellt wird.

Wenn Warnmeldungen ausgegeben werden, meldet der Systemzustandsbericht einen beeinträchtigten Status für den Cluster.  Die ausgelösten Warnmeldungen enthalten die Informationen, die Sie benötigen, um auf eine Beeinträchtigung des Systemzustands zu reagieren.

Um die verfügbaren Warnmeldungen des Ethernet-Switch-Integritätsmonitors anzuzeigen, führen Sie folgenden Befehl aus: `system health alert definition show -monitor ethernet-switch`

Siehe den Artikel in der Wissensdatenbank. https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Cluster_Switch_Health_Monitor_CSHM_Alert_Resolution_Guide["Leitfaden zur Behebung von Warnungen des Switch Health Monitor"^] für detaillierte Informationen zur Fehlerbehebung bei Warnmeldungen.
