---
permalink: switch-nvidia-sn2100-storage/components-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt die Liste der Komponenten und die Teilenummern für das Gehäuse und das Schienenset überprüfen. 
---
= Komponenten und Teilenummern für NVIDIA SN2100-Schalter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt die Liste der Komponenten und die Teilenummern für das Gehäuse und das Schienenset überprüfen.



== Schrankdetails

Sie installieren den NVIDIA SN2100 Switch (X190006/X190106) im NVIDIA Dual-/Single-Switch-Schrank mit den Standardhalterungen, die im Lieferumfang des Switches enthalten sind.



== Details zum Schienenbausatz

Die folgende Tabelle listet die Teilenummer und die Beschreibung für die MSN2100-Weichen und Schienensätze auf:

[cols="1,2"]
|===
| Teilenummer | Beschreibung 


 a| 
X190006-PE
 a| 
Cluster-Switch, NVIDIA SN2100, 16PT 100G, PTSX



 a| 
X190006-PI
 a| 
Cluster-Switch, NVIDIA SN2100, 16PT 100G, PSIN



 a| 
X190106-FE-PE
 a| 
Switch, NVIDIA SN2100, 16PT 100G, PTSX, Front End



 a| 
X190106-FE-PI
 a| 
Switch, NVIDIA SN2100, 16PT 100G, PSIN, Front End



 a| 
X-MTEF-KIT-D
 a| 
Schienen-Kit, NVIDIA Dual-Schalter nebeneinander



 a| 
X-MTEF-KIT-E
 a| 
Schienensatz, NVIDIA Einzelschalter kurze Tiefe

|===

NOTE: Weitere Informationen finden Sie in der NVIDIA Dokumentation. https://docs.nvidia.com/networking/display/sn2000pub/Installation["Installation Ihres SN2100-Weichen- und Schienensatzes"^] Die

.Was kommt als nächstes
Nachdem Sie Ihre Komponenten und Teilenummern bestätigt haben, können Sie die folgenden überprüfen: link:required-documentation-sn2100-storage.html["erforderliche Dokumentation"]Die
