---
permalink: switch-nvidia-sn2100-storage/configure-reqs-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Prüfen Sie bei Installation und Wartung von NVIDIA SN2100-Switches alle Anforderungen. 
---
= Konfigurationsanforderungen für NVIDIA SN2100 Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prüfen Sie bei Installation und Wartung von NVIDIA SN2100-Switches alle Anforderungen.



== Installationsvoraussetzungen

Wenn Sie ONTAP Cluster mit mehr als zwei Nodes erstellen möchten, sind zwei unterstützte Cluster-Netzwerk-Switches erforderlich. Sie können zusätzliche, optionale Management Switches verwenden.

Sie installieren den NVIDIA SN2100-Switch (X190006/X190106) im NVIDIA-Dual/Single-Switch-Gehäuse mit den im Lieferumfang des Switches enthaltenen Standardhalterungen.

Richtlinien zur Verkabelung finden Sie unterlink:cabling-considerations-sn2100-storage.html["Überlegungen zur Verkabelung und Konfiguration"] .



== ONTAP und Linux Unterstützung

Der NVIDIA SN2100 Switch ist ein 10/25/40/100 GB Ethernet-Switch mit Cumulus Linux. Der Switch unterstützt Folgendes:

* ONTAP 9.10.1P3. Der SN2100 Switch dient Cluster- und Speicheranwendungen in ONTAP 9.10.1P3 über verschiedene Switch-Paare. Ab ONTAP 9.10.1P3 können Sie mit NVIDIA SN2100 Switches Storage- und Cluster-Funktionen in einer gemeinsamen Switch-Konfiguration kombinieren.
* Cumulus Linux (CL) OS-Version 4.4.3. Aktuelle Informationen zur Kompatibilität finden Sie im https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA Ethernet-Switches"^] Informationsseite.
* Sie können Cumulus Linux installieren, wenn auf dem Switch Cumulus Linux oder ONIE ausgeführt wird.


.Was kommt als nächstes
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie Ihre link:components-sn2100-storage.html["Komponenten und Teilenummern"]Die
