---
permalink: switch-nvidia-sn2100-storage/configure-software-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Überblick über den Softwarekonfigurationsprozess für NVIDIA SN2100 Storage-Switches 
---
= Workflow für die Softwareinstallation von NVIDIA SN2100 Storage-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
So installieren und konfigurieren Sie die Software für einen NVIDIA SN2100-Switch:

. link:install-cumulus-mode-sn2100-storage.html["Installieren Sie Cumulus Linux im Cumulus-Modus"] Oder link:install-onie-mode-sn2100-storage.html["Installieren Sie Cumulus Linux im ONIE-Modus"].
+
Sie können Cumulus Linux (CL) OS installieren, wenn der Switch Cumulus Linux oder ONIE ausführt.

. link:install-rcf-sn2100-storage.html["Installieren Sie das Skript für die Referenzkonfigurationsdatei"].
+
Für Clustering- und Speicheranwendungen stehen zwei RCF-Skripte zur Verfügung.

. link:setup-install-cshm-file.html["Installieren Sie die CSHM-Datei"].
+
Sie können die entsprechende Konfigurationsdatei für die Statusüberwachung von NVIDIA-Cluster-Switches des Ethernet-Switches installieren.


