---
permalink: switch-nvidia-sn2100-storage/configure-reqs-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt alle Anforderungen beachten. 
---
= Konfigurationsanforderungen für NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt alle Anforderungen beachten.



== Installationsvoraussetzungen

Wenn Sie ONTAP -Cluster mit mehr als zwei Knoten aufbauen möchten, benötigen Sie zwei unterstützte Cluster-Netzwerk-Switches.  Sie können zusätzliche Management-Schalter verwenden, die optional sind.

Sie installieren den NVIDIA SN2100 Switch (X190006/X190106) im NVIDIA Dual-/Single-Switch-Schrank mit den Standardhalterungen, die im Lieferumfang des Switches enthalten sind.

Richtlinien zur Verkabelung finden Sie unterlink:cabling-considerations-sn2100-storage.html["Überlegungen zu Verkabelung und Konfiguration"] Die



== ONTAP und Linux-Unterstützung

Der NVIDIA SN2100 Switch ist ein 10/25/40/100-Gb-Ethernet-Switch, auf dem Cumulus Linux läuft.  Der Schalter unterstützt Folgendes:

* ONTAP 9.10.1P3.  Der SN2100-Switch dient Cluster- und Speicheranwendungen in ONTAP 9.10.1P3 über verschiedene Switch-Paare.  Ab ONTAP 9.10.1P3 können Sie NVIDIA SN2100 Switches verwenden, um Speicher- und Clusterfunktionen in einer gemeinsamen Switch-Konfiguration zu kombinieren.
* Cumulus Linux (CL) Betriebssystemversion 4.4.3.  Aktuelle Informationen zur Kompatibilität finden Sie unter https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA Ethernet-Switches"^] Informationsseite.
* Sie können Cumulus Linux installieren, wenn auf dem Switch Cumulus Linux oder ONIE läuft.


.Was kommt als nächstes
Nachdem Sie die Konfigurationsanforderungen geprüft haben, können Sie Ihre link:components-sn2100-storage.html["Komponenten und Teilenummern"]Die
