---
permalink: switch-nvidia-sn2100-storage/install-hardware-sn2100-storage.html 
sidebar: sidebar 
keywords: switches hardware installation 
summary: Informationen zur Installation der SN2100-Hardware finden Sie in der NVIDIA Dokumentation. 
---
= Installieren Sie die Hardware für den NVIDIA SN2100-Switch.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation der NVIDIA SN2100 Switch-Hardware ist ein entscheidender erster Schritt beim Aufbau einer zuverlässigen und skalierbaren Netzwerkinfrastruktur zur Unterstützung von Datensicherung, Replikation und Management-Workflows.

Befolgen Sie diese Schritte, um Ihre SN2100-Switches einzurichten und zu konfigurieren. Ausführliche Anweisungen finden Sie in der Dokumentation von NVIDIA.

.Schritte
. Überprüfen Sie dielink:configure-reqs-sn2100-storage.html["Konfigurationsanforderungen"] Die
. Befolgen Sie die Anweisungen in der link:https://docs.nvidia.com/networking/display/sn2000pub/Installation["NVIDIA Switch Installationsanleitung"^].


.Wie geht es weiter?
Nachdem Sie Ihre Hardware installiert haben, können Sielink:cabling-considerations-sn2100-storage.html["Verkabelung und Konfiguration überprüfen"] Anforderungen.
