---
permalink: switch-nvidia-sn2100-storage/install-cumulus-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode 
summary: 'Das Betriebssystem Cumulus Linux (CL) kann entweder installiert werden, wenn auf dem Switch Cumulus Linux oder ONIE läuft.' 
---
= Installieren Sie Cumulus Linux im Cumulus-Modus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie diese Schritte aus, um Cumulus Linux (CL) OS zu installieren, wenn der Switch im Cumulus-Modus läuft.


NOTE: Cumulus Linux (CL) OS kann entweder installiert werden, wenn auf dem Switch Cumulus Linux oder ONIE läuft (siehelink:install-onie-mode-sn2100-storage.html["Installation im ONIE-Modus"] ).

.Bevor Sie beginnen
Stellen Sie sicher, dass Folgendes verfügbar ist:

* Linux-Kenntnisse auf mittlerem Niveau.
* Kenntnisse in grundlegender Textbearbeitung, UNIX-Dateiberechtigungen und Prozessüberwachung.  Eine Vielzahl von Texteditoren ist vorinstalliert, darunter `vi` Und `nano` Die
* Zugriff auf eine Linux- oder UNIX-Shell.  Wenn Sie Windows verwenden, nutzen Sie eine Linux-Umgebung als Befehlszeilentool für die Interaktion mit Cumulus Linux.
* Die Baudrate muss am seriellen Konsolenschalter für den Konsolenzugriff des NVIDIA SN2100-Switches wie folgt auf 115200 eingestellt werden:
+
** 115200 Baud
** 8 Datenbits
** 1 Stoppbit
** Parität: keine
** Flusssteuerung: keine




.Informationen zu diesem Vorgang
Beachten Sie Folgendes:


NOTE: Bei jeder Neuinstallation von Cumulus Linux wird die gesamte Dateisystemstruktur gelöscht und neu aufgebaut.


CAUTION: Das Standardpasswort für das Cumulus-Benutzerkonto lautet *cumulus*.  Beim ersten Anmelden bei Cumulus Linux müssen Sie dieses Standardpasswort ändern.  Aktualisieren Sie unbedingt alle Automatisierungsskripte, bevor Sie ein neues Image installieren.  Cumulus Linux bietet Befehlszeilenoptionen, um das Standardpasswort während des Installationsprozesses automatisch zu ändern.

.Schritte
[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Melden Sie sich am Switch an.
+
Für die erstmalige Anmeldung am Switch werden der Benutzername und das Passwort *cumulus*/*cumulus* benötigt. `sudo` Privilegien.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Überprüfen Sie die Cumulus Linux-Version: `net show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
. Konfigurieren Sie den Hostnamen, die IP-Adresse, die Subnetzmaske und das Standardgateway.  Der neue Hostname wird erst nach einem Neustart der Konsolen-/SSH-Sitzung wirksam.
+

NOTE: Ein Cumulus Linux-Switch bietet mindestens einen dedizierten Ethernet-Management-Port namens `eth0` Die  Diese Schnittstelle ist speziell für die Out-of-Band-Verwaltung vorgesehen.  Standardmäßig verwendet die Verwaltungsschnittstelle DHCPv4 zur Adressierung.

+

CAUTION: Verwenden Sie im Hostnamen keinen Unterstrich (_), keinen Apostroph (') und keine Nicht-ASCII-Zeichen.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
+
Dieser Befehl ändert beides `/etc/hostname` Und `/etc/hosts` Dateien.

. Prüfen Sie, ob Hostname, IP-Adresse, Subnetzmaske und Standardgateway aktualisiert wurden.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Stellen Sie Datum, Uhrzeit, Zeitzone und NTP-Server am Switch ein.
+
.. Überprüfen Sie die aktuelle Zeitzone:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *cat /etc/timezone*
----
.. Aktualisierung auf die neue Zeitzone:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure --frontend noninteractive tzdata*
----
.. Überprüfen Sie Ihre aktuelle Zeitzone:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Um die Zeitzone mithilfe des geführten Assistenten einzustellen, führen Sie folgenden Befehl aus:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Stellen Sie die Softwareuhr entsprechend der konfigurierten Zeitzone ein:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Den aktuellen Wert der Softwareuhr auf den Wert der Hardwareuhr setzen:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo hwclock -w*
----
.. Fügen Sie bei Bedarf einen NTP-Server hinzu:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp server _<cumulus.network.ntp.org>_ iburst*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
.. Überprüfen Sie, ob `ntpd` läuft auf dem System:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Geben Sie die NTP-Quellschnittstelle an.  Standardmäßig verwendet NTP die folgende Quellschnittstelle: `eth0` Die  Sie können eine andere NTP-Quellschnittstelle wie folgt konfigurieren:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp source _<src_int>_*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. Installieren Sie Cumulus Linux 4.4.3:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
+
Das Installationsprogramm startet den Download. Geben Sie *y* ein, wenn Sie dazu aufgefordert werden.

. Starten Sie den NVIDIA SN2100 Switch neu:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. Die Installation startet automatisch, und die folgenden GRUB-Bildschirmoptionen werden angezeigt.  Treffen Sie *keine* Auswahlen.
+
** Cumulus-Linux GNU/Linux
** ONIE: Betriebssystem installieren
** CUMULUS-INSTALL
** Cumulus-Linux GNU/Linux


. Wiederholen Sie die Schritte 1 bis 4, um sich anzumelden.
. Überprüfen Sie, ob die Cumulus Linux-Version 4.4.3 ist: `net show version`
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----
. Erstellen Sie einen neuen Benutzer und fügen Sie diesen Benutzer der folgenden Gruppe hinzu: `sudo` Gruppe.  Dieser Benutzer wird erst nach einem Neustart der Konsolen-/SSH-Sitzung wirksam.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----


--
.Cumulus Linux 5.4.0
--
. Melden Sie sich am Switch an.
+
Für die erstmalige Anmeldung am Switch werden der Benutzername und das Passwort *cumulus*/*cumulus* benötigt. `sudo` Privilegien.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Überprüfen Sie die Cumulus Linux-Version: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. Konfigurieren Sie den Hostnamen, die IP-Adresse, die Subnetzmaske und das Standardgateway.  Der neue Hostname wird erst nach einem Neustart der Konsolen-/SSH-Sitzung wirksam.
+

NOTE: Ein Cumulus Linux-Switch bietet mindestens einen dedizierten Ethernet-Management-Port namens `eth0` Die  Diese Schnittstelle ist speziell für die Out-of-Band-Verwaltung vorgesehen.  Standardmäßig verwendet die Verwaltungsschnittstelle DHCPv4 zur Adressierung.

+

CAUTION: Verwenden Sie im Hostnamen keinen Unterstrich (_), keinen Apostroph (') und keine Nicht-ASCII-Zeichen.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
Dieser Befehl ändert beides `/etc/hostname` Und `/etc/hosts` Dateien.

. Prüfen Sie, ob Hostname, IP-Adresse, Subnetzmaske und Standardgateway aktualisiert wurden.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Stellen Sie Zeitzone, Datum, Uhrzeit und NTP-Server am Switch ein.
+
.. Zeitzone einstellen:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. Überprüfen Sie Ihre aktuelle Zeitzone:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Um die Zeitzone mithilfe des geführten Assistenten einzustellen, führen Sie folgenden Befehl aus:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Stellen Sie die Softwareuhr entsprechend der konfigurierten Zeitzone ein:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Den aktuellen Wert der Softwareuhr auf den Wert der Hardwareuhr setzen:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. Fügen Sie bei Bedarf einen NTP-Server hinzu:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["Die NTP-Serverkonfiguration funktioniert nicht mit NVIDIA SN2100-Switches."^] für weitere Einzelheiten.

.. Überprüfen Sie, ob `ntpd` läuft auf dem System:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Geben Sie die NTP-Quellschnittstelle an.  Standardmäßig verwendet NTP die folgende Quellschnittstelle: `eth0` Die  Sie können eine andere NTP-Quellschnittstelle wie folgt konfigurieren:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Installieren Sie Cumulus Linux 5.4.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*
----
+
Das Installationsprogramm startet den Download. Geben Sie *y* ein, wenn Sie dazu aufgefordert werden.

. Starten Sie den NVIDIA SN2100 Switch neu:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. Die Installation startet automatisch, und die folgenden GRUB-Bildschirmoptionen werden angezeigt.  Treffen Sie *keine* Auswahlen.
+
** Cumulus-Linux GNU/Linux
** ONIE: Betriebssystem installieren
** CUMULUS-INSTALL
** Cumulus-Linux GNU/Linux


. Wiederholen Sie die Schritte 1 bis 4, um sich anzumelden.
. Überprüfen Sie, ob die Cumulus Linux-Version 5.4.0 ist: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. Überprüfen Sie, ob jeder Knoten eine Verbindung zu jedem Switch hat:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   Mgmt        mgmt-sw1                            Eth110/1/29
swp2s1     25G    Trunk/L2    node1                               e0a
swp15      100G   BondMember  sw2                                 swp15
swp16      100G   BondMember  sw2                                 swp16
----
. Erstellen Sie einen neuen Benutzer und fügen Sie diesen Benutzer der folgenden Gruppe hinzu: `sudo` Gruppe.  Dieser Benutzer wird erst nach einem Neustart der Konsolen-/SSH-Sitzung wirksam.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Fügen Sie dem Administrator weitere Benutzergruppen hinzu, auf die er zugreifen kann. `nv` Befehle:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user 'admin' to group 'nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Sehen https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIA Benutzerkonten"^] für weitere Informationen.



--
.Cumulus Linux 5.11.0
--
. Melden Sie sich am Switch an.
+
Wenn Sie sich zum ersten Mal am Switch anmelden, benötigen Sie den Benutzernamen/das Passwort *cumulus*/*cumulus* mit `sudo` Privilegien.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Überprüfen Sie die Cumulus Linux-Version: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. Konfigurieren Sie den Hostnamen, die IP-Adresse, die Subnetzmaske und das Standardgateway.  Der neue Hostname wird erst nach einem Neustart der Konsolen-/SSH-Sitzung wirksam.
+

NOTE: Ein Cumulus Linux-Switch bietet mindestens einen dedizierten Ethernet-Management-Port namens `eth0` Die  Diese Schnittstelle ist speziell für die Out-of-Band-Verwaltung vorgesehen.  Standardmäßig verwendet die Verwaltungsschnittstelle DHCPv4 zur Adressierung.

+

CAUTION: Verwenden Sie im Hostnamen keinen Unterstrich (_), keinen Apostroph (') und keine Nicht-ASCII-Zeichen.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
Dieser Befehl ändert beides `/etc/hostname` Und `/etc/hosts` Dateien.

. Prüfen Sie, ob Hostname, IP-Adresse, Subnetzmaske und Standardgateway aktualisiert wurden.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Stellen Sie Zeitzone, Datum, Uhrzeit und NTP-Server am Switch ein.
+
.. Zeitzone einstellen:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. Überprüfen Sie Ihre aktuelle Zeitzone:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Um die Zeitzone mithilfe des geführten Assistenten einzustellen, führen Sie folgenden Befehl aus:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Stellen Sie die Softwareuhr entsprechend der konfigurierten Zeitzone ein:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Den aktuellen Wert der Softwareuhr auf den Wert der Hardwareuhr setzen:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. Fügen Sie bei Bedarf einen NTP-Server hinzu:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
Siehe den Artikel in der Wissensdatenbank.link:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["Die NTP-Serverkonfiguration funktioniert nicht mit NVIDIA SN2100-Switches."^] für weitere Einzelheiten.

.. Überprüfen Sie, ob `ntpd` läuft auf dem System:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Geben Sie die NTP-Quellschnittstelle an.  Standardmäßig verwendet NTP die folgende Quellschnittstelle: `eth0` Die  Sie können eine andere NTP-Quellschnittstelle wie folgt konfigurieren:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Installieren Sie Cumulus Linux 5.11.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.11.0-mlx-amd64.bin*
----
+
Das Installationsprogramm startet den Download. Geben Sie *y* ein, wenn Sie dazu aufgefordert werden.

. Starten Sie den NVIDIA SN2100 Switch neu:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. Die Installation startet automatisch, und die folgenden GRUB-Bildschirmoptionen werden angezeigt.  Treffen Sie *keine* Auswahlen.
+
** Cumulus-Linux GNU/Linux
** ONIE: Betriebssystem installieren
** CUMULUS-INSTALL
** Cumulus-Linux GNU/Linux


. Wiederholen Sie die Schritte 1 bis 4, um sich anzumelden.
. Überprüfen Sie, ob die Cumulus Linux-Version 5.11.0 ist:
+
`nv show system`

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied                description
------------------- ---------------------- ---------------------
build               Cumulus Linux 5.11.0
uptime              153 days, 2:44:16
hostname            cumulus                cumulus
product-name        Cumulus Linux
product-release     5.11.0
platform            x86_64-mlnx_x86-r0
system-memory       2.76 GB used / 2.28 GB free / 7.47 GB total
swap-memory         0 Bytes used / 0 Bytes free / 0 Bytes total
health-status       not OK
date-time           2025-04-23 09:55:24
status              N/A
timezone            Etc/UTC
maintenance
  mode              disabled
  ports             enabled
version
  kernel            6.1.0-cl-1-amd64
  build-date        Thu Nov 14 13:06:38 UTC 2024
  image             5.11.0
  onie              2019.11-5.2.0020-115200
----
. Überprüfen Sie, ob jeder Knoten mit jedem Switch verbunden ist:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   eth   mgmt-sw1                                  Eth110/1/14
swp2s1     25G    Trunk/L2    node1                               e0a
swp1s1     10G    swp   sw2                                       e0a
swp9       100G   swp   sw3                                       e4a
swp10      100G   swp   sw4                                       e4a
swp15      100G   swp   sw5                                       swp15
swp16      100G   swp   sw6                                       swp16
----


Sehen https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIA Benutzerkonten"^] für weitere Informationen.

--
====
.Wie geht es weiter?
Nach der Installation von Cumulus Linux im Cumulus-Modus können Sielink:install-rcf-sn2100-storage.html["Installieren oder aktualisieren Sie das RCF-Skript"] Die
