---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: Ältere Cisco Switches eines ONTAP Clusters können ohne Unterbrechung auf NVIDIA SN2100-Speicher-Switches migriert werden. 
---
= Migration von einem Cisco -Speicher-Switch zu einem NVIDIA SN2100-Speicher-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ältere Cisco Switches für einen ONTAP Cluster können auf NVIDIA SN2100-Speicher-Switches migriert werden. Dies ist ein unterbrechungsfreies Verfahren.



== Überprüfungsanforderungen

Folgende Speichersysteme werden unterstützt:

* Cisco Nexus 9336C-FX2
* Cisco Nexus 3232C
* Siehe die https://hwu.netapp.com/["Hardware Universe"^] Für detaillierte Informationen zu den unterstützten Ports und deren Konfigurationen.


.Bevor Sie beginnen
Stellen Sie sicher, dass Sie über Folgendes verfügen:

* Der bestehende Cluster ist ordnungsgemäß eingerichtet und funktioniert.
* Alle Speicheranschlüsse sind aktiviert, um einen unterbrechungsfreien Betrieb zu gewährleisten.
* Die NVIDIA SN2100 Speicherswitches sind konfiguriert und arbeiten unter der richtigen Version von Cumulus Linux, auf der die Referenzkonfigurationsdatei (RCF) angewendet wurde.
* Die bestehende Speichernetzwerkkonfiguration weist folgende Merkmale auf:
+
** Ein redundanter und voll funktionsfähiger NetApp Cluster, der beide ältere Cisco Switches nutzt.
** Management-Konnektivität und Konsolenzugriff sowohl auf die älteren Cisco Switches als auch auf die neuen Switches.
** Alle Cluster-LIFs befinden sich im aktiven Zustand und sind an ihren Heimatports angeschlossen.
** ISL-Ports wurden aktiviert und zwischen den älteren Cisco Switches sowie zwischen den neuen Switches verkabelt.


* Siehe die https://hwu.netapp.com/["Hardware Universe"^] Für detaillierte Informationen zu den unterstützten Ports und deren Konfigurationen.
* Einige der Ports sind auf NVIDIA SN2100 Switches für den Betrieb mit 100 GbE konfiguriert.
* Sie haben die 100-GbE-Konnektivität von den Knoten zu den NVIDIA SN2100-Speicher-Switches geplant, migriert und dokumentiert.




== Migrieren Sie die Schalter

.Zu den Beispielen
In diesem Verfahren werden Cisco Nexus 9336C-FX2 Storage-Switches als Beispiel für Befehle und Ausgaben verwendet.

Die Beispiele in diesem Verfahren verwenden die folgende Schalter- und Knotennomenklatur:

* Die vorhandenen Cisco Nexus 9336C-FX2 Storage-Switches sind _S1_ und _S2_.
* Die neuen NVIDIA SN2100 Speicherschalter sind _sw1_ und _sw2_.
* Die Knoten heißen _node1_ und _node2_.
* Die Cluster-LIFs sind _node1_clus1_ und _node1_clus2_ auf Knoten 1 bzw. _node2_clus1_ und _node2_clus2_ auf Knoten 2.
* Der `cluster1::*>` Die Eingabeaufforderung zeigt den Namen des Clusters an.
* Die in diesem Verfahren verwendeten Netzwerkanschlüsse sind _e5a_ und _e5b_.
* Die Breakout-Ports haben folgendes Format: swp1s0-3.  Beispielsweise gibt es vier Breakout-Ports auf swp1: _swp1s0_, _swp1s1_, _swp1s2_ und _swp1s3_.
* Zuerst wird Schalter S2 durch Schalter sw2 ersetzt, dann wird Schalter S1 durch Schalter sw1 ersetzt.
+
** Die Verkabelung zwischen den Knoten und S2 wird dann von S2 getrennt und wieder mit sw2 verbunden.
** Die Verkabelung zwischen den Knoten und S1 wird dann von S1 getrennt und wieder mit sw1 verbunden.






=== Schritt 1: Vorbereitung auf die Migration

. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
wobei _x_ die Dauer des Wartungsfensters in Stunden ist.

. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie *y* eingeben, wenn Sie zur Fortsetzung aufgefordert werden:
+
`set -privilege advanced`

+
Die erweiterte Eingabeaufforderung (*>) wird angezeigt.

. Ermitteln Sie den administrativen oder betrieblichen Status jeder Speicherschnittstelle:
+
Jeder Port sollte als aktiviert angezeigt werden `Status` Die





=== Schritt 2: Kabel und Anschlüsse konfigurieren

. Netzwerkportattribute anzeigen:
+
`storage port show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Überprüfen Sie mithilfe des folgenden Befehls, ob die Speicherports an jedem Knoten wie folgt mit den vorhandenen Speicherswitches verbunden sind (aus Sicht der Knoten):
+
`network device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. Stellen Sie an den Switches S1 und S2 mithilfe des folgenden Befehls sicher, dass die Speicherports und Switches wie folgt verbunden sind (aus Sicht der Switches):
+
`show lldp neighbors`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. Schalten Sie am Switch sw2 die Ports ab, die mit den Speicherports und Knoten der Disk-Shelches verbunden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Verlegen Sie die Speicherknotenanschlüsse des Controllers und der Festplattengehäuse vom alten Switch S2 auf den neuen Switch sw2. Verwenden Sie dazu geeignete Kabel, die von NVIDIA SN2100 unterstützt werden.
. Schalten Sie am Switch sw2 die Ports ein, die mit den Speicherports der Knoten und den Festplattengehäusen verbunden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Überprüfen Sie aus Sicht der Knoten, ob die Speicheranschlüsse an jedem Knoten nun wie folgt mit den Switches verbunden sind:
+
`network device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. Überprüfen Sie die Netzwerkportattribute:
+
`storage port show`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Überprüfen Sie am Switch sw2, ob alle Speicherports der Knoten aktiv sind:
+
`net show interface`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Schalten Sie am Schalter sw1 die Ports ab, die mit den Speicherports der Knoten und den Festplattengehäusen verbunden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Verlegen Sie die Speicherknotenanschlüsse des Controllers und die Festplattengehäuse vom alten Switch S1 zum neuen Switch sw1. Verwenden Sie dazu geeignete Kabel, die von NVIDIA SN2100 unterstützt werden.
. Schalten Sie am Switch sw1 die Ports ein, die mit den Speicherports der Knoten und den Festplattengehäusen verbunden sind.
+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Überprüfen Sie aus Sicht der Knoten, ob die Speicheranschlüsse an jedem Knoten nun wie folgt mit den Switches verbunden sind:
+
`network device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== Schritt 3: Konfiguration überprüfen

. Überprüfen Sie die endgültige Konfiguration:
+
`storage port show`

+
Jeder Port sollte als aktiviert angezeigt werden `State` und aktiviert für `Status` Die

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Überprüfen Sie am Switch sw2, ob alle Speicherports der Knoten aktiv sind:
+
`net show interface`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Überprüfen Sie, ob beide Knoten jeweils eine Verbindung zu jedem Switch haben:
+
`net show lldp`

+
.Beispiel anzeigen
[%collapsible]
====
Das folgende Beispiel zeigt die entsprechenden Ergebnisse für beide Schalter:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. Ändern Sie die Berechtigungsstufe wieder auf Administrator:
+
`set -privilege admin`

. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Wie geht es weiter?
Nach der Migration Ihrer Switches können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
