---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 'Austausch eines defekten NVIDIA SN2100 Speicherschalters im Rahmen eines nicht-unterbrechungsfreien Verfahrens (NDU).' 
---
= Ersetzen Sie einen NVIDIA SN2100 Speicherschalter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen defekten NVIDIA SN2100 Speicherschalter austauschen. Dies ist ein unterbrechungsfreies Verfahren.

.Bevor Sie beginnen
Bevor Sie die Cumulus-Software und die RCFs auf einem NVIDIA SN2100-Speicher-Switch installieren, stellen Sie Folgendes sicher:

* Ihr System unterstützt NVIDIA SN2100 Speicherswitches.
* Sie haben die entsprechenden RCFs heruntergeladen.


Der http://hwu.netapp.com["Hardware Universe"^] Enthält detaillierte Informationen zu den unterstützten Ports und deren Konfigurationen.

Die bestehende Netzwerkkonfiguration muss folgende Eigenschaften aufweisen:

* Führen Sie alle Schritte zur Fehlerbehebung durch, um zu bestätigen, dass Sie Ihren Schalter austauschen müssen.
* Stellen Sie sicher, dass auf beiden Switches eine Management-Verbindung besteht.
+

NOTE: Stellen Sie sicher, dass alle Schritte zur Fehlerbehebung abgeschlossen sind, um zu bestätigen, dass Ihr Schalter ausgetauscht werden muss.



Der Ersatz-Switch NVIDIA SN2100 muss folgende Eigenschaften aufweisen:

* Die Managementnetzwerkanbindung ist funktionsfähig.
* Sie können über die Konsole auf den Ersatzschalter zugreifen.
* Das entsprechende RCF- und Cumulus-Betriebssystemabbild wird auf den Switch geladen.
* Die erste Konfiguration des Schalters ist abgeschlossen.


.Verfahrensübersicht
Bei diesem Verfahren wird der zweite NVIDIA SN2100 Speicherschalter sw2 durch den neuen NVIDIA SN2100 Schalter nsw2 ersetzt.  Die beiden Knoten sind Knoten1 und Knoten2.

Zu erledigende Schritte:

* Bestätigen Sie, dass es sich bei dem auszutauschenden Schalter um SW2 handelt.
* Trennen Sie die Kabel vom Schalter sw2.
* Schließen Sie die Kabel wieder an den Schalter NSW2 an.
* Überprüfen Sie alle Gerätekonfigurationen auf Switch nsw2.


.Schritte
. Wenn AutoSupport auf diesem Cluster aktiviert ist, unterdrücken Sie die automatische Fallerstellung durch Aufruf einer AutoSupport -Nachricht:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ ist die Dauer des Wartungsfensters in Stunden.

. Ändern Sie die Berechtigungsstufe auf „Erweitert“, indem Sie *y* eingeben, wenn Sie zur Fortsetzung aufgefordert werden:
+
`set -privilege advanced`

. Überprüfen Sie den Gesundheitszustand der Speicherknotenports, um die Verbindung zum Speicherswitch S1 zu bestätigen:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Prüfen Sie, ob der Speicherschalter sw1 verfügbar ist:
+
`network device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Führe die `net show interface` Führen Sie einen Befehl auf dem funktionierenden Switch aus, um zu bestätigen, dass Sie beide Knoten und alle Regale sehen können:
+
`net show interface`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Überprüfen Sie die Regalanschlüsse im Lagersystem:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. Entfernen Sie alle Kabel, die am Speicherschalter sw2 angeschlossen sind.
. Schließen Sie alle Kabel wieder an den Ersatzschalter NSW2 an.
. Überprüfen Sie erneut den Gesundheitszustand der Speicherknotenports:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Vergewissern Sie sich, dass beide Schalter verfügbar sind:
+
`net device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Überprüfen Sie die Regalanschlüsse im Lagersystem:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. Ändern Sie die Berechtigungsstufe wieder auf Administrator:
+
`set -privilege admin`

. Wenn Sie die automatische Fallerstellung unterdrückt haben, können Sie sie durch Aufruf einer AutoSupport Nachricht wieder aktivieren:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Wie geht es weiter?
Nachdem Sie Ihre Schalter ausgetauscht haben, können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
