---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 'Ersetzen eines fehlerhaften NVIDIA SN2100 Storage Switch in einem unterbrechungsfreien Verfahren \(NDU\).' 
---
= Ersetzen Sie einen NVIDIA SN2100 Storage-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen defekten NVIDIA SN2100 Storage Switch ersetzen. Hierbei handelt es sich um ein unterbrechungsfreies Verfahren.

.Bevor Sie beginnen
Stellen Sie vor der Installation der Cumulus-Software und der RCFs auf einem NVIDIA SN2100-Speicherschalter Folgendes sicher:

* Ihr System kann NVIDIA SN2100 Storage Switches unterstützen.
* Sie haben die entsprechenden RCFs heruntergeladen.


Der http://hwu.netapp.com["Hardware Universe"^] Ausführliche Informationen zu unterstützten Ports und deren Konfigurationen erhalten Sie im Detail.

Die vorhandene Netzwerkkonfiguration muss die folgenden Merkmale aufweisen:

* Führen Sie alle Schritte zur Fehlerbehebung durch, um zu bestätigen, dass Sie Ihren Switch ersetzen müssen.
* Stellen Sie sicher, dass auf beiden Switches eine Verwaltungskonnektivität besteht.
+

NOTE: Stellen Sie sicher, dass alle Fehlerbehebungsschritte durchgeführt wurden, um zu bestätigen, dass Ihr Switch ausgetauscht werden muss.



Der Ersatz-NVIDIA SN2100-Switch muss die folgenden Eigenschaften aufweisen:

* Die Management-Netzwerk-Konnektivität ist funktionsfähig.
* Sie können über die Konsole auf den Ersatzschalter zugreifen.
* Das entsprechende RCF- und Cumulus-Betriebssystemabbild wird auf den Switch geladen.
* Die anfängliche Anpassung des Schalters ist abgeschlossen.


.Zusammenfassung der Vorgehensweise
Dieses Verfahren ersetzt den zweiten NVIDIA SN2100 Storage Switch sw2 durch den neuen NVIDIA SN2100 Switch nsw2. Die beiden Knoten sind node1 und node2.

Schritte zur Fertigstellung:

* Vergewissern Sie sich, dass der zu ersetzende Schalter sw2 ist.
* Trennen Sie die Kabel vom Schalter sw2.
* Schließen Sie die Kabel wieder an den Schalter nsw2 an.
* Überprüfen Sie alle Gerätekonfigurationen am Switch nsw2.


.Schritte
. Wenn AutoSupport in diesem Cluster aktiviert ist, unterdrücken Sie die automatische Erstellung eines Falls durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_X_ ist die Dauer des Wartungsfensters in Stunden.

. Ändern Sie die Berechtigungsebene in Erweitert, und geben Sie *y* ein, wenn Sie dazu aufgefordert werden, fortzufahren:
+
`set -privilege advanced`

. Überprüfen Sie den Integritätsstatus der Speicherknotenports, um die Verbindung zum Speicherswitch S1 zu bestätigen:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Stellen Sie sicher, dass der Speicherschalter sw1 verfügbar ist:
+
`network device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Führen Sie die aus `net show interface` Mit dem Befehl auf dem Arbeitsschalter bestätigen Sie, dass Sie beide Nodes und alle Shelfs sehen können:
+
`net show interface`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Überprüfen Sie die Shelf-Ports im Storage-System:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. Entfernen Sie alle Kabel, die am Speicherschalter sw2 angeschlossen sind.
. Schließen Sie alle Kabel wieder an den Ersatzschalter nsw2 an.
. Überprüfen Sie den Integritätsstatus der Speicher-Node-Ports erneut:
+
`storage port show -port-type ENET`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Vergewissern Sie sich, dass beide Switches verfügbar sind:
+
`net device-discovery show -protocol lldp`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Überprüfen Sie die Shelf-Ports im Storage-System:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. Ändern Sie die Berechtigungsebene zurück in den Administrator:
+
`set -privilege admin`

. Wenn Sie die automatische Case-Erstellung unterdrückt haben, aktivieren Sie es erneut, indem Sie eine AutoSupport Meldung aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Was kommt als Nächstes?
Nachdem Sie Ihre Schalter ausgetauscht haben, können Sie link:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"]Die
