---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Überprüfen Sie bei Installation und Wartung von NVIDIA SN2100-Switches alle empfohlenen Dokumente. 
---
= Dokumentationsanforderungen für NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie bei Installation und Wartung von NVIDIA SN2100-Switches alle empfohlenen Dokumente.

In der folgenden Tabelle ist die Dokumentation für die NVIDIA SN2100-Switches aufgeführt.

[cols="1,2"]
|===
| Titel | Beschreibung 


 a| 
link:install_setup_sn2100_switches_overview.html["_NVIDIA SN2100 Switches einrichten und konfigurieren_"^]
 a| 
Hier wird beschrieben, wie Sie Ihre NVIDIA SN2100-Switches einrichten und konfigurieren, einschließlich der Installation von Cumulus Linux und entsprechenden RCFs.



 a| 
link:migrate_cisco_sn2100_cluster_switch.html["_Von einem Cisco Cluster-Switch zu einem NVIDIA SN2100 Cluster-Switch migrieren_"^]
 a| 
Eine Beschreibung der Migration von Umgebungen, in denen Cisco Cluster Switches verwendet werden, in Umgebungen, die NVIDIA SN2100 Cluster-Switches verwenden.



 a| 
link:migrate_cisco_sn2100_storage_switch.html["_Von einem Cisco Storage Switch zu einem NVIDIA Storage Switch migrieren_"^]
 a| 
Eine Beschreibung der Migration von Umgebungen, die Cisco Storage Switches in Umgebungen verwenden, die NVIDIA SN2100 Storage-Switches verwenden.



 a| 
link:migrate_2n_switched_sn2100_switches.html["_Migration zu einem Cluster mit zwei Nodes und NVIDIA SN2100 Cluster Switches_"^]
 a| 
Hier wird die Migration zu einer Switch-Umgebung mit zwei Nodes mit NVIDIA SN2100-Cluster-Switches beschrieben.



 a| 
link:replace_sn2100_switch_cluster.html["_Ersetzen Sie einen NVIDIA SN2100-Cluster-Switch_"^]
 a| 
Beschreibt das Verfahren zum Ersetzen eines defekten NVIDIA SN2100-Switch in einem Cluster und Herunterladen von Cumulus Linux und Referenzkonfigurationsdatei.



 a| 
link:replace_sn2100_switch_storage.html["_Einen NVIDIA SN2100-Storage-Switch ersetzen_"^]
 a| 
Beschreibt das Verfahren zum Austausch eines defekten NVIDIA SN2100-Speicherschalters und Herunterladen von Cumulus Linux und Referenzkonfigurationsdatei.

|===