---
permalink: switch-nvidia-sn2100-storage/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt die gesamte empfohlene Dokumentation lesen. 
---
= Dokumentationsanforderungen für NVIDIA SN2100-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Installation und Wartung des NVIDIA SN2100 Switches sollten Sie unbedingt die gesamte empfohlene Dokumentation lesen.

Die folgende Tabelle listet die für die NVIDIA SN2100 Switches verfügbare Dokumentation auf.

[cols="1,2"]
|===
| Titel | Beschreibung 


 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html["_Einrichten und Konfigurieren Ihrer NVIDIA SN2100-Switches_"^]
 a| 
Beschreibt, wie Sie Ihre NVIDIA SN2100 Switches einrichten und konfigurieren, einschließlich der Installation von Cumulus Linux und den entsprechenden RCFs.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html["_Migration von einem Cisco -Speicherswitch zu einem NVIDIA SN2100-Speicherswitch_"^]
 a| 
Beschreibt, wie Sie von Umgebungen, die Cisco -Speicher-Switches verwenden, zu Umgebungen migrieren, die NVIDIA SN2100-Speicher-Switches verwenden.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["_Migration zu einem Zwei-Knoten-Switch-Cluster mit NVIDIA SN2100 Cluster-Switches_"^]
 a| 
Beschreibt, wie man mit NVIDIA SN2100 Cluster-Switches auf eine Zwei-Knoten-Switch-Umgebung migriert.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html["NVIDIA SN2100 Speicherswitch austauschen_"^]
 a| 
Beschreibt das Vorgehen zum Austausch eines defekten NVIDIA SN2100 Speicherswitches und zum Herunterladen von Cumulus Linux und der zugehörigen Konfigurationsdatei.

|===