---
permalink: switch-nvidia-sn2100-storage/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for sn2100 switches' 
summary: Mit diesem Verfahren können Sie die entsprechende Konfigurationsdatei für die Zustandsüberwachung von NVIDIA SN2100 Speicherswitches im Cluster installieren. 
---
= Installieren Sie die Konfigurationsdatei für den Ethernet Switch Health Monitor.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie wie folgt vor, um die entsprechende Konfigurationsdatei für die Zustandsüberwachung von Ethernet-Switches in NVIDIA Cluster-Switches zu installieren.  Unterstützte Modelle sind:

* MSN2100-CB2FC
* MSN2100-CB2RC
* X190006-PE
* X190006-PI



NOTE: Dieses Installationsverfahren gilt für ONTAP 9.10.1 und höher.

.Bevor Sie beginnen
* Überprüfen Sie durch Ausführen des folgenden Befehls, ob Sie die Konfigurationsdatei herunterladen müssen. `system switch ethernet show` und prüfen, ob für Ihr Modell *ANDERE* angezeigt wird.
+
Falls Ihr Modell nach Anwendung der Konfigurationsdatei immer noch *ANDERE* anzeigt, wenden Sie sich bitte an den NetApp -Support.

* Stellen Sie sicher, dass der ONTAP -Cluster betriebsbereit ist.
* Aktivieren Sie SSH, um alle in CSHM verfügbaren Funktionen nutzen zu können.
* Räumen Sie die `/mroot/etc/cshm_nod/nod_sign/` Verzeichnis auf allen Knoten:
+
.. Geben Sie die NodeShell ein:
+
`system node run -node <name>`

.. Änderung zu erweiterten Berechtigungen:
+
`priv set advanced`

.. Listen Sie die Konfigurationsdateien im folgenden Verzeichnis auf: `/etc/cshm_nod/nod_sign` Verzeichnis.  Wenn das Verzeichnis existiert und Konfigurationsdateien enthält, werden die Dateinamen aufgelistet.
+
`ls /etc/cshm_nod/nod_sign`

.. Löschen Sie alle Konfigurationsdateien, die zu Ihren angeschlossenen Switch-Modellen gehören.
+
Wenn Sie sich nicht sicher sind, entfernen Sie alle Konfigurationsdateien für die oben aufgeführten unterstützten Modelle und laden Sie anschließend die neuesten Konfigurationsdateien für dieselben Modelle herunter und installieren Sie diese.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Vergewissern Sie sich, dass die gelöschten Konfigurationsdateien nicht mehr im Verzeichnis vorhanden sind:
+
`ls /etc/cshm_nod/nod_sign`





.Schritte
. Laden Sie die Konfigurations-ZIP-Datei für den Ethernet-Switch-Integritätsmonitor entsprechend der zugehörigen ONTAP Version herunter.  Diese Datei ist verfügbar unter https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA Ethernet-Switches"^] Seite.
+
.. Auf der Downloadseite der NVIDIA SN2100 Software wählen Sie *Nvidia CSHM-Datei* aus.
.. Auf der Seite „Vorsicht/Unbedingt lesen“ das Kontrollkästchen aktivieren, um zuzustimmen.
.. Auf der Seite „Endbenutzer-Lizenzvereinbarung“ das Kontrollkästchen aktivieren, um zuzustimmen, und auf *Akzeptieren & Fortfahren* klicken.
.. Auf der Seite „Nvidia CSHM File - Download“ wählen Sie die entsprechende Konfigurationsdatei aus.  Folgende Dateien sind verfügbar:




[role="tabbed-block"]
====
.ONTAP 9.15.1 und höher
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 bis 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]Laden Sie die entsprechende ZIP-Datei auf Ihren internen Webserver hoch.
. Die Einstellungen für den erweiterten Modus können Sie von einem der ONTAP -Systeme im Cluster aus aufrufen.
+
`set -privilege advanced`

. Führen Sie den Befehl „switch health monitor configure“ aus.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. Vergewissern Sie sich, dass die Befehlsausgabe für Ihre ONTAP Version mit folgendem Text endet:


[role="tabbed-block"]
====
.ONTAP 9.15.1 und höher
--
Die Zustandsüberwachung des Ethernet-Switches hat die Konfigurationsdatei installiert.

--
.ONTAP 9.11.1 bis 9.14.1
--
SHM hat die Konfigurationsdatei installiert.

--
.ONTAP 9.10.1
--
Das heruntergeladene CSHM-Paket wurde erfolgreich verarbeitet.

--
====
Im Fehlerfall wenden Sie sich bitte an den NetApp Support.

. [[step6]]Warten Sie bis zum Doppelten des Abfrageintervalls des Ethernet-Switch-Integritätsmonitors, das durch Ausführen von `system switch ethernet polling-interval show` , bevor der nächste Schritt ausgeführt wird.
. Führen Sie den Befehl aus `system switch ethernet configure-health-monitor show` Stellen Sie im ONTAP -System sicher, dass die Cluster-Switches erkannt werden, wobei das überwachte Feld auf *True* gesetzt ist und das Feld für die Seriennummer nicht *Unknown* anzeigt.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----


.Wie geht es weiter?
Nach der Installation der CSHM-Datei können Sielink:../switch-cshm/config-overview.html["Konfigurieren der Switch-Integritätsüberwachung"] Die
